if (GetLocale()=="koKR") then
	XPERL_TUTORIAL_TITLE1	= "미니맵 아이콘"
	XPERL_TUTORIAL_TITLE2	= "플레이어창"
	XPERL_TUTORIAL_TITLE3	= "대상창"
	XPERL_TUTORIAL_TITLE4	= "파티창"
	XPERL_TUTORIAL_TITLE5	= "파티 소환수창"
	XPERL_TUTORIAL_TITLE6	= "소환수창"
	XPERL_TUTORIAL_TITLE7	= "설정"
	XPERL_TUTORIAL_TITLE8	= "대상의 대상창"
	XPERL_TUTORIAL_TITLE9	= "대상의 대상의 대상창"
	XPERL_TUTORIAL_TITLE10	= "주시 대상창"
	XPERL_TUTORIAL_TITLE11	= "지원창"
	XPERL_TUTORIAL_TITLE12	= "메인탱커 목록"
	XPERL_TUTORIAL_TITLE13	= "아이템 검사"
	XPERL_TUTORIAL_TITLE14	= "시전 현황"
	XPERL_TUTORIAL_TITLE15	= "파티 대상"
	XPERL_TUTORIAL_TITLE16	= "공격대창"

	XPERL_TUTORIAL1		= "The minimap icon is your key to instant access of the "..XPerl_ShortProductName.." options. Alternatively you can always access the options window by using the |c00FFFF80/xperl|r command.\r\rWhen the options window is open, all "..XPerl_ShortProductName.." frames are unlocked and movable with the mouse."
	XPERL_TUTORIAL2		= "The Player frame is the representation of your character, including it's Portrait, Level, Name, Health and Mana, Combat State (sword icon), Resting State (ZZZ icon), PVP Rank, PVP State (your faction symbol).\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Player|r tab."
	XPERL_TUTORIAL3		= "The Target frame is the representation of your target, including much the same information as your Player Frame.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Target|r tab."
	XPERL_TUTORIAL4		= "The Party frames are the representation of your fellow party members, including much the same information as your Player Frame.\r\rIn the "..XPerl_ShortProductName.." Options you can configure these frames by selecting the |c00FFFF80Party|r tab."
	XPERL_TUTORIAL5		= "The Party Pet frames are the representation of your fellow party member's pets. Basic information is shown for these frames.\r\rIn the "..XPerl_ShortProductName.." Options you can configure these frames by selecting the |c00FFFF80Party|r tab."
	XPERL_TUTORIAL6		= "The Pet frame is the representation of your pet, including it's Portrait, Level, Name, Health and Mana and Combat State (sword icon).\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Player|r tab."
	XPERL_TUTORIAL7		= "The options window can configure any part of "..XPerl_ShortProductName..".\r\rThe top left corner shows alignment options for selected frames. Mousing over other frames (or selecting different tabs from the top) will change these options to reflect those frames.\r\rThe bottom left corner shows basic frame appearance options.\r\rThe tabs along the top contain all the options for the relevant frames."
	XPERL_TUTORIAL8		= "The Target's Target frame is the representation of your target's target (The target that your target has), including much the same information as your Target Frame.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Target|r tab and seeing options in the top-right corner."
	XPERL_TUTORIAL9		= "The Target's Target's Target frame is the representation of your target's target's target (The target that your target's target has), including much the same information as your Target Frame.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Target|r tab and seeing options in the top-right corner."
	XPERL_TUTORIAL10	= "The Focus frame is the representation of your focus, including much the same information as your Player Frame.\r\rTo change focus, see the WoW Key Bindings |c00FFFF80Targetting Functions|r section and look for |c00FFFF80Focus Target|r and |c00FFFF80Target Focus|r.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Focus|r tab."
	XPERL_TUTORIAL11	= "The Assists Frame will show you (on the left) all the raid members targetting you, or optionally only healers targetting you. And on the right will show all raid members who are assisting on your current target.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Helper|r tab and changing the |c00FFFF80Target Counters|r options."
	XPERL_TUTORIAL12	= "The MT List shows the currently defined Main Tanks. These tanks can be defined with CTRA, oRA2 or via the raid member drop down menus from "..XPerl_ShortProductName.."'s raid frames.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Helper|r tab and changing the |c00FFFF80Target Counters|r options."
	XPERL_TUTORIAL13	= "A complete replacement for the CTRA/oRA2 |c00FFFF80/raitem|r, |c00FFFF80/radur|r, |c00FFFF80/raresist|r and |c00FFFF80/rareg|r commands. You can drop items into the item list and never have to remember the names of items again.\r\rThe |c00FFFF80Query|r button will run an item check query for the ticked items, and perform durability, resist and reagent check at the same time, giving you the ability to check and review all the results conveniently.\r\rYou can also report these findings to any channel by using the dropdown selection and the reporting buttons."
	XPERL_TUTORIAL14	= "A raid casting monitor to show cast bars and mana status of all selected raid members. And shows their targets to the right.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Monitor|r tab."
	XPERL_TUTORIAL15	= "These are your party member's targets, showing name, in-combat and PVP flag. Optionally showing a health bar.\r\rIn the "..XPerl_ShortProductName.." Options you can configure these frames by selecting the |c00FFFF80Party|r tab."
	XPERL_TUTORIAL16	= "The Raid frames are the representation of your raid members, with Name, in-combat status, Health and Mana. Other status flags can show in the health bars, like AFK, Dead, Ghost, and res monitor things.\r\rIn the "..XPerl_ShortProductName.." Options you can configure this frame by selecting the |c00FFFF80Player|r tab.\r\rCheck out the raid alignment options for different alignment and growth options."
end
