if (GetLocale() == "esES") then

XPERL_TUTORIAL_TITLE1	= "Icono de minimapa"
XPERL_TUTORIAL_TITLE2	= "Marco de jugador"
XPERL_TUTORIAL_TITLE3	= "Marco de objetivo"
XPERL_TUTORIAL_TITLE4	= "Marco de grupo"
XPERL_TUTORIAL_TITLE5	= "Marco de mascotas de grupo"
XPERL_TUTORIAL_TITLE6	= "Marco de mascota"
XPERL_TUTORIAL_TITLE7	= "Opciones"
XPERL_TUTORIAL_TITLE8	= "Marco de objetivo de objetivo"
XPERL_TUTORIAL_TITLE9	= "Marco de objetivo de objetivo de objetivo"
XPERL_TUTORIAL_TITLE10	= "Marco de enfoque"
XPERL_TUTORIAL_TITLE11	= "Marco de asistencia"
XPERL_TUTORIAL_TITLE12	= "Lista de TP"
XPERL_TUTORIAL_TITLE13	= "Comprobación de objetos"
XPERL_TUTORIAL_TITLE14	= "Monitor de lanzamiento"
XPERL_TUTORIAL_TITLE15	= "Objetivos de grupo"
XPERL_TUTORIAL_TITLE16	= "Marco de banda"

XPERL_TUTORIAL1		= "El icono de minimapa es tu llave para acceder instantáneamente a las opciones de "..XPerl_ShortProductName..". Alternativamente, siempre puedes abrir la ventana de opciones usando el comando |c00FFFF80/xperl|r.\r\rCuando se abre la ventana de opciones, todos los marcos de "..XPerl_ShortProductName.." quedan desbloqueados y se pueden mover con el ratón."
XPERL_TUTORIAL2		= "El marco de jugador es la representación de tu personaje, incluyendo su retrato, nivel, nombre, salud y maná, estado de combate (icono de espadas), estado de descanso (icono ZZZ), Rango JcJ, Estado de JcJ (tu símbolo de facción).\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco seleccionando la pestaña de |c00FFFF80Jugador|r."
XPERL_TUTORIAL3		= "El marco de objetivo es la representación de tu objetivo, prácticamente la misma información que el marco de jugador.\r\r En las opciones de  "..XPerl_ShortProductName.." puedes configurar este marco seleccionando la pestaña |c00FFFF80Objetivo|r ."
XPERL_TUTORIAL4		= "El marco de grupo es la representación de tus compañeros de grupo, incluyendo la misma información que el marco de jugador.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80PGrupo|r ."
XPERL_TUTORIAL5		= "El marco de mascotas de grupo es la representación de las mascotas de tu grupo. Se muestra información básica en este marco.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Grupo|r ."
XPERL_TUTORIAL6		= "El marco de mascota es la representación de tu mascota, incluyendo su retrato, nivel, nombre, salud y maná, y estado de combate (icono de espadas).\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Jugador|r ."
PERL_TUTORIAL7		= "Desde la ventana de opciones puedes configurar cualquier parte de "..XPerl_ShortProductName..".\r\rLa esquina izquierda superior muestra opciones de alineamiento para los marcos seleccionados. Pasando el ratón sobre otros marcos (o seleccionando diferentes pestañas) cambiarán estas opciones para mostrar los marcos apropiados.\r\rLa parte inferior izquierda muestra la apariencia básica de los marcos.\r\rLas pestañas a lo largo contienen todas las opciones importantes para los marcos."
XPERL_TUTORIAL8		= "El marco de objetivo de objetivo es la representación del objetivo de tu objetivo (El objetivo que tiene tu objetivo), incluyendo prácticamente la misma información que el marco de objetivo.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Objetivo|r en las opciones de la esquina derecha superior."
XPERL_TUTORIAL9		= "El marco de objetivo de objetivo de objetivo (El objetivo que el objetivo de tu objetivo tiene), muestra la misma información que el marco de objetivo.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Objetivo|r en las opciones de la esquina derecha."
XPERL_TUTORIAL10	= "El marco de enfoque es la representación de tu enfoque, incluyendo prácticamente la misma información que el marco de jugador.\r\rPara cambiar elenfoque, mira los enlaces de teclas de WoW, en la sección |c00FFFF80Funciones de objetivo|r busca |c00FFFF80enfoque de objetivo|r.\r\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Enfoque|r ."
XPERL_TUTORIAL11	= "El marco de asistencia te mostrará (en la izquierda) todos los miembros de la banda que te tienen como objetivo, o opcionalmente, los sanadores que te tienen como objetivo. Y en la derecha todos los miembros de banda que tienen al mismo objetivo que tu.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Ayudante|r y cambiando las opciones de los |c00FFFF80Contadores de objetivos|r ."
XPERL_TUTORIAL12	= "La lista de TP muestra los Tanques Principales (MT) definidos actualmente. Estos tanques pueden definirse con CTRA, oRA2 o a través de los menús desplegables de los miembros de banda de "..XPerl_ShortProductName..".\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Ayudante|r y cambiando las opciones|c00FFFF80Contadores de objetivos|r ."
XPERL_TUTORIAL13	= "Un completo reemplazo para los comandos de CTRA/oRA2 |c00FFFF80/raitem|r, |c00FFFF80/radur|r, |c00FFFF80/raresist|r and |c00FFFF80/rareg|r . Puedes arrastrar objetos a la lista de objetos y no tendrás que preocuparte de nuevo de recordar los nombres.\r\rEl botón de |c00FFFF80Pregunta|r hará una comprobación para los objetos seleccionados, y además también para durabilidad de objetos, resistencias e ingredientes al mismo tiempo, dándote la habilidad de comprobar y revisar todos los resultados convenientmente.\r\rTambién puedes envíar estos resultados a cualquier canal usando el menú desplegable y los botones de reporte."
XPERL_TUTORIAL14	= "Un monitor de lanzamiento de hechizos de banda, y el estado de maná de todos los miembros de banda seleccionados. Y muestra sus objetivos a la derecha.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Monitor|r ."
XPERL_TUTORIAL15	= "Estos son los objetivos de los miembros de tu grupo, mostrando nombre, y banderas de estado en combate y JcJ. Opcionalmente, se puede mostrar la barra de salud.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco en la pestaña |c00FFFF80Grupo|r ."
XPERL_TUTORIAL16	= "El marco de banda es la representación de los miemrbos de tu banda, con Nombre, estado de combate, salud y maná. Otras banderas de estado pueden aparecer en el marco, como AUS, Muerto, Fantasma, y otras cosas relacionadas con el monitor de resurrección.\r\rEn las opciones de "..XPerl_ShortProductName.." puedes configurar este marco seleccionando la pestaña |c00FFFF80Banda|r .\r\rComprueba las opciones de alineamiento para ordenar los marcos según te convenga."

end