if (GetLocale()=="zhCN") then

	XPERL_TUTORIAL_TITLE1	= "小地图按钮"
	XPERL_TUTORIAL_TITLE2	= "玩家窗口"
	XPERL_TUTORIAL_TITLE3	= "目标窗口"
	XPERL_TUTORIAL_TITLE4	= "队友窗口"
	XPERL_TUTORIAL_TITLE5	= "队友宠物窗口"
	XPERL_TUTORIAL_TITLE6	= "宠物窗口"
	XPERL_TUTORIAL_TITLE7	= "功能设置"
	XPERL_TUTORIAL_TITLE8	= "目标的目标窗口"
	XPERL_TUTORIAL_TITLE9	= "目标的目标的目标窗口"
	XPERL_TUTORIAL_TITLE10	= "焦点窗口"
	XPERL_TUTORIAL_TITLE11	= "协助窗口"
	XPERL_TUTORIAL_TITLE12	= "坦克列表"
	XPERL_TUTORIAL_TITLE13	= "物品确认"
	XPERL_TUTORIAL_TITLE14	= "施法监视"
	XPERL_TUTORIAL_TITLE15	= "队友目标"
	XPERL_TUTORIAL_TITLE16	= "团队框架"

	XPERL_TUTORIAL1     = "点击小地图图标可开启 "..XPerl_ShortProductName.." 功能设置页面. 也可以输入 |c00FFFF80/xperl|r 命令开启设置窗口.\r\r当设置窗口开启时, 所有 "..XPerl_ShortProductName.." 框架皆为解锁状态,可使用鼠标拖动至任何位置."
	XPERL_TUTORIAL2     = "玩家框架是显示您个人信息的相关界面, 包含头像, 等级, 名称, 生命及法力, 战斗状态 (剑的图标), 休息状态 (ZZZ 图标), PVP 军衔, PVP 状态 (您的阵营标志).\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80玩家|r 显示方式."
	XPERL_TUTORIAL3     = "目标框架是显示您的目标的界面, 包括了和玩家框架一样的信息.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80目标|r 显示方式."
	XPERL_TUTORIAL4     = "队友框架是显示您的同队队员的界面, 包括了和玩家框架一样的信息.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80队员|r 显示方式."
	XPERL_TUTORIAL5     = "队友宠物框架是显示跟随您同队队员宠物的界面. 一些基本信息将会显示在这框架中.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80队员宠物|r 显示方式."
	XPERL_TUTORIAL6     = "宠物框架是显示您宠物的界面, 包含头像, 等级, 名称, 生命及法力, 战斗状态 (剑的图标).\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80宠物|r 显示方式."
	XPERL_TUTORIAL7     = "功能设置窗口可设置 "..XPerl_ShortProductName.." 头像相关功能."
	XPERL_TUTORIAL8     = "目标的目标框架是显示您目标的目标的界面 (您的目标所选的目标), 所包括的信息和您的目标框架一样.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80目标|r 显示方式."
	XPERL_TUTORIAL9     = "目标的目标的目标框架是显示您目标的目标的目标界面 (您的目标所选的目标的目标), 所包括的信息和您的目标框架一样.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80目标|r 显示方式."
	XPERL_TUTORIAL10    = "焦点框架是显示您焦点对象的界面, 包括了和玩家框架一样的信息.\r\r转移注意点, 看 WoW 按键设置 |c00FFFF80目标作用T|r 部分和寻找 |c00FFFF80焦点目标|r 和 |c00FFFF80目标焦点|r.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80焦点|r 显示方式."
	XPERL_TUTORIAL11    = "协助框架将显示(左侧)团队队员目标对象为你的列表, 或设置为治疗对象为你的列表. 右侧窗口则显示所有团队成员中跟你同样目标的名单列表.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80助手|r 显示方式及变更 |c00FFFF80目标计数|r 功能."
	XPERL_TUTORIAL12    = "MT名单将显示当前被选定的主坦克. 这些坦克可经由 CTRA, oRA2 或从 "..XPerl_ShortProductName.."'团队框架拖放数位人员到选单.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80助手|r 表单及变更 |c00FFFF80目标计数|r 功能."
	XPERL_TUTORIAL13    = "完整结合了 CTRA/oRA2 |c00FFFF80/raitem|r, |c00FFFF80/radur|r, |c00FFFF80/raresist|r 以及 |c00FFFF80/rareg|r 指令. 你可拖放任何物品至物品列表.\r\r点击 |c00FFFF80查询|r 按键将执行物品确认, 并执行耐久, 抗性和药剂检查, 让您方便的检查和回顾所有结果.\r\r您可以选择报告的按钮让这些检查结果向任一频道报告."
	XPERL_TUTORIAL14    = "团队施法监视可显示所有选择的团队成员施法进度条以及法力状态. 并且显示他们的目标在框架右边.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架所选择的 |c00FFFF80监视|r 显示方式."
	XPERL_TUTORIAL15    = "显示你目前队员的目标, 可显示出名称, 战斗中状态以及 PVP 状态. 可选择性显示生命状态.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置此框架的 |c00FFFF80队员|r 排列方式."
	XPERL_TUTORIAL16    = "团队框架为显示您目前团队成员的界面, 包含名称, 战斗中状态, 生命及法力. 其他状态也可显示在生命条处, 如 暂离, 死亡, 灵魂, 以及复活状态监视等.\r\r在 "..XPerl_ShortProductName.." 功能设置页你可以设置 此框架的|c00FFFF80玩家|r排列方式.\r\r."

end