if (GetLocale()=="zhTW") then

XPERL_TUTORIAL_TITLE1	= "小地圖 Icon"
XPERL_TUTORIAL_TITLE2	= "玩家框架"
XPERL_TUTORIAL_TITLE3	= "目標框架"
XPERL_TUTORIAL_TITLE4	= "隊友框架"
XPERL_TUTORIAL_TITLE5	= "隊友寵物框架"
XPERL_TUTORIAL_TITLE6	= "寵物框架"
XPERL_TUTORIAL_TITLE7	= "功能設置"
XPERL_TUTORIAL_TITLE8	= "目標的目標框架"
XPERL_TUTORIAL_TITLE9	= "目標的目標的目標框架"
XPERL_TUTORIAL_TITLE10	= "專注框架"
XPERL_TUTORIAL_TITLE11	= "協助框架"
XPERL_TUTORIAL_TITLE12	= "坦克列表"
XPERL_TUTORIAL_TITLE13	= "物品確認"
XPERL_TUTORIAL_TITLE14	= "施法監視"
XPERL_TUTORIAL_TITLE15	= "隊友目標"
XPERL_TUTORIAL_TITLE16	= "團隊框架"

XPERL_TUTORIAL1		= "點擊小地圖圖示(icon)可開啟 "..XPerl_ShortProductName.." 功能設置頁面. 也可以輸入 |c00FFFF80/xperl|r 指令開啟設定視窗.\r\r當設置視窗開啟時, 所有 "..XPerl_ShortProductName.." 框架皆為解鎖狀態可使用滑鼠拖動至任何位置."
XPERL_TUTORIAL2		= "玩家框架是顯示您個人資訊的相關介面, 包含頭像, 等級, 名稱, 生命及法力, 戰鬥狀態 (劍的圖像), 休息狀態 (ZZZ icon), PVP 軍銜, PVP 狀態 (您的陣營標誌).\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80玩家|r 顯示方式."
XPERL_TUTORIAL3		= "目標框架是顯示您的目標的介面, 包括了和玩家框架一樣的資訊.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80目標|r 顯示方式."
XPERL_TUTORIAL4		= "隊友框架是顯示您的同隊隊員的介面, 包括了和玩家框架一樣的資訊.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80隊員|r 顯示方式."
XPERL_TUTORIAL5		= "隊友寵物框架是顯示跟隨您同隊隊員寵物的介面. 一些基本資訊將會顯示在這框架中.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80隊員寵物|r 顯示方式."
XPERL_TUTORIAL6		= "寵物框架是顯示您寵物的介面, 包含頭像, 等級, 名稱, 生命及法力, 戰鬥狀態 (劍的圖像).\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80寵物|r 顯示方式."
XPERL_TUTORIAL7		= "功能設置視窗可設定 "..XPerl_ShortProductName.." 頭像相關功能."
XPERL_TUTORIAL8		= "目標的目標框架是顯示您目標的目標的介面 (您的目標所選的目標), 所包括的資訊和您的目標框架一樣.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80目標|r 顯示方式."
XPERL_TUTORIAL9		= "目標的目標的目標框架是顯示您目標的目標的目標介面 (您的目標所選的目標的目標), 所包括的資訊和您的目標框架一樣.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80目標|r 顯示方式."
XPERL_TUTORIAL10	= "專注框架是顯示您專注對象的介面, 包括了和玩家框架一樣的資訊.\r\r轉移注意點, 看 WoW 按鍵設定 |c00FFFF80目標作用T|r 部分和尋找 |c00FFFF80專注目標|r 和 |c00FFFF80目標鎖定|r.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80Focus|r 顯示方式."
XPERL_TUTORIAL11	= "協助框架將顯示(左側)團隊隊員目標對象為你的列表, 或設定為治療對象為你的列表. 右側視窗則顯示所有團隊成員中跟你同樣目標的名單列表.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80助手|r 顯示方式及變更 |c00FFFF80目標計數|r 功能."
XPERL_TUTORIAL12	= "MT 名單將顯示當前被選定的主坦克. 這些坦克可經由 CTRA, oRA2 或從 "..XPerl_ShortProductName.."'團隊框架拖放數位人員到選單.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80助手|r 表單及變更 |c00FFFF80目標計數|r 功能."
XPERL_TUTORIAL13	= "完整結合了 CTRA/oRA2 |c00FFFF80/raitem|r, |c00FFFF80/radur|r, |c00FFFF80/raresist|r 以及 |c00FFFF80/rareg|r 指令. 你可拖放任何物品至物件列表.\r\r點擊 |c00FFFF80Query|r 按鍵將執行物品確認, 並執行耐久, 抗性和藥劑檢查, 給您方便地檢查和回顧所有結果.\r\r您可以選擇回報的按鈕讓這些檢查結果向任一頻道報告."
XPERL_TUTORIAL14	= "團隊施法監視可顯示所有選擇的團隊成員施法進度條以及法力狀態. 並且顯示他們的目標在框架右邊.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架所選擇的 |c00FFFF80監視|r 顯示方式."
XPERL_TUTORIAL15	= "顯示你目前隊員的目標, 可顯示出名稱, 戰鬥中狀態以及 PVP 狀態. 可選擇性顯示生命力狀態.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定此框架的 |c00FFFF80隊員|r 排列方式."
XPERL_TUTORIAL16	= "團隊框架為顯示您目前團隊成員的介面, 包含名稱, 戰鬥中狀態, 生命力及法力. 其他狀態也可顯示在生命力條處, 如 暫離, 死亡, 靈魂, 以及復活狀態監視等.\r\r在 "..XPerl_ShortProductName.." 功能設置頁你可以設定 此框架的|c00FFFF80玩家|r排列方式.\r\r."
end