local L = LibStub("AceLocale-3.0"):NewLocale("Critline", "enUS", true)
if not L then return end


L["Add by name"] = true
L["Add target"] = true
L["Advanced options"] = true
L["Alphabetically"] = true
L["Amount color"] = true
L["Basic options"] = true
L["By crit record"] = true
L["By normal record"] = true
L["Cannot add players to mob filter."] = true
L["Chat output"] = true
L["Check to enable damage events to be recorded."] = true
L["Check to enable healing events to be recorded."] = true
L["Check to enable pet damage events to be recorded."] = true
L["Crit"] = true
L["Critical!"] = true
L["Critline splash frame unlocked"] = true
L["Delete mob"] = true
L["Detailed summary"] = true
L["Disable to ignore records where the target is an NPC."] = true
L["Disable to ignore records where the target is a player."] = true
L["Display previous record along with \"New record\" messages."] = true
L["Don't filter magic"] = true
L[" (DoT)"] = true
L["Drag to move"] = true
L["Edit tooltip format"] = true
L["Enable to ignore integrated aura filter."] = true
L["Enable to ignore integrated mob filter."] = true
L["Enable to include rather than exclude selected spells in the spell filter."] = true
L["Enable to let magical damage ignore the level adjustment."] = true
L["Enable to use scrolling combat text for \"New record\" messages instead of the default splash frame."] = true
L["Enter mob name:"] = true
L[" (HoT)"] = true
L["If level difference between you and the target is greater than this setting, records will not be registered."] = true
L["Ignore aura filter"] = true
L["Ignore mob filter"] = true
L["Invalid mob name."] = true
L["Invalid player name."] = true
L["Invert spell filter"] = true
L["Left-click to open options\nRight-click to hide button"] = true
L["Left-click to toggle summary frame\nRight-click to open options\nDrag to move"] = true
L["Level adjustment"] = true
L["Minimap button"] = true
L["Mob filter"] = true
L["Move splash screen"] = true
L["New %s record!"] = true
L["No records"] = true
L["Normal"] = true
L["No target selected."] = true
L["Plays a sound on a new record."] = true
L["Play sound"] = true
L["Prints new record notifications to the chat frame."] = true
L["Record damage"] = true
L["Record healing"] = true
L["Record pet damage"] = true
L["Record PvE"] = true
L["Record PvP"] = true
L["Reset all records for this tree"] = true
L["Right-click to lock"] = true
L["%s added to mob filter."] = true
L["Saves a screenshot on a new record."] = true
L["Saves your high normal and critical damage records and flashes a message if you break the record."] = true
L["Screenshot"] = true
L["Sets the number of seconds you wish to display the splash frame."] = true
L["Sets the scale of the splash frame."] = true
L["Sets the scale of the summary frame."] = true
L["Set the color for the amount text in the splash frame."] = true
L["Set the color for the spell text in the splash frame."] = true
L["Show button on minimap."] = true
L["Show damage"] = true
L["Show damage in summary frame."] = true
L["Show healing"] = true
L["Show healing in summary frame."] = true
L["Show old record"] = true
L["Show pet damage"] = true
L["Show pet damage in summary frame."] = true
L["Shows the new record on the middle of the screen."] = true
L["%s is already in mob filter."] = true
L["Sort summary spells:"] = true
L["Spell color"] = true
L["Spell filter"] = true
L["Splash frame"] = true
L["Splash frame scale"] = true
L["Splash frame timer"] = true
L["%s removed from mob filter."] = true
L["Summary frame scale"] = true
L["Suppress all records while mind controlled."] = true
L["Suppress mind control"] = true
L["Use combat text splash"] = true
L["Use detailed format in the Critline summary tooltip."] = true