-- AUTOMATICALLY GENERATED BY <_NPCScan.Tools/Tools/RoutesToPathData.lua>!
select( 2, ... ).PathData = {
	[ 475 ] = { -- Blade's Edge Mountains
		-- Hemathion
		[ 18692 ] = "J’¢nM] hO5¢O5¢ST´ÖL»ÚL»ÚHè¹WFRªáFRªáFý¦âJ’¢nJ’¢nO5¢L»ÚL»ÚFRªáJ’¢nIº€ëJûsOØoùOØoùQ°r3P¾|6RTÑUÉ…ŽU÷iU÷iQ‘ÿJŒ…ÉJŒ…ÉIº€ëOØoùP¾|6RTÑU÷iJŒ…ÉOØoùP¾|6P¾|6U÷iJŒ…É";
		-- Morcrush
		[ 18690 ] = "˜r7Âœô1–Ÿ3ZŸ3Z ò9lŸ=Æ›ÓA™™C½–A:–A:–>;˜r7Â˜r7ÂŸ3ZŸ=ÆŸ=Æ›ÓA–A:Ÿ=Æ–A:˜r7Â­BÃZ«¬£®OŸ4®OŸ4±-¢²¯Â¢²¯Â¢°Å®­BÃZ®OŸ4²¯Â¢­BÃZ ÿ‰ £ŒV£•‹\"µÖe?¶K¹¸ÁC¸ÁC½Š;~Áñ9 Ç>:7Ì\"E‡ÉáG€¸“MB¸Xf¶ÈiD²½k~«‚©¤ãŽŠ¤ãŽŠ ÿ‰£•‹\"Ç>:7ÉáG€Åã=w¤ãŽŠ£•‹\"¨è€°Áñ9 Ç>:7Åã=w²½k~¤ãŽŠ¨è€°Áñ9 Åã=wÂ=²½k~¨è€°± hyÁñ9 Â=¾ƒ>²¶ÈiD²½k~± hy¸ÁCÁñ9 ¾ƒ>²¶ÈiD± hyµÖe?¸ÁC¾ƒ>²º¬Eð¸“MB¶ÈiDµÖe?¸ÁCº¬Eð¸“MBµÖe?¸ÁC¸“MB";
		-- Speaker Mar'grom
		[ 18693 ] = "e¼‚ëi=zŒmàxïmàxïoÅ|o4‰­o4‰­lÓ‘nfÕ•zfÕ•zdê“e¼‚ëe¼‚ëmàxïo4‰­o4‰­fÕ•ze¼‚ë\\@v\r=‹’u@U’u@U—üKû˜1R ˜1R ”›YÎƒZƒZŒæW§RÑ4L²ŽÙI	\\@v\\@v’u@U˜1R ˜1R ƒZRÑ4L²\\@v˜1R ˜1R RÑ;P±˜1R ;P±4L²¢¢/—¥€,Ó¨¦/(¨¦/(¯@.­—F\
­—F\
«dF¦é?±¦é?±¢4¢¢/—¢¢/—¨¦/(­—F\
­—F\
¦é?±¢¢/—lÎiqhÁ°t`¿4t`¿4vé¿ËxïÄSxïÄSy…ÈÁxlËÌxlËÌmBÖÎjºÕöjºÕöj^ÒÐlÎilÎit`¿4xïÄSxïÄSxlËÌjºÕöxïÄSjºÕölÎi";
	};
	[ 486 ] = { -- Borean Tundra
		-- Fumblub Gearwind
		[ 32358 ] = "£t'L¨ *=±-2ÿ±-2ÿ¬:eª5F³9S{¯vOƒ®JÇ®JÇ¬:e±-2ÿ±-2ÿ»‘C¯½iGÕ¼ÆPÿ¾ZD¼V_;¼V_;µ2g®¤]¥¤]¥žUTS¸J­›CGy˜lGl–\
D¨–\
D¨—5?Ÿ&®Ÿ&®£t'L±-2ÿ±-2ÿª5F¥µ3M³9S{®JÇ±-2ÿ±-2ÿ½iGÕ¼ÆPÿ›CGy–\
D¨Ÿ&®Ÿ&®±-2ÿ¥µ3M³9S{±-2ÿ¼ÆPÿ¸J­›CGyŸ&®Ÿ&®¥µ3M¢¶6ã±äXÈ³9S{¼ÆPÿ¤]¥¸J­Ÿ&®Ÿ&®¢¶6ã¡ñ>(±äXÈ¼ÆPÿ¼V_;¤]¥Ÿ&®¡ñ>(®![d±äXÈ¼V_;¤]¥¡ñ>(¤LK6®![d¼V_;¤]¥¤]¥¤LK6§»U”§»U”®![d¤]¥";
		-- Icehorn
		[ 32361 ] = "Ìpz¦Î4r•ÐTobÓ¼sœÛwxlÚq~ÙÖ$|ÎË}ÌÌpz¦Ìpz¦ÐTobÓ¼sœÓ¼sœÚq~ÙÖ$|Ó¼sœÖ$|Ìpz¦Ò©LÔéM¥Ø0SœØ0SœÞUR–ã9R3ã9R3ìVN(ïSÝïSÝâ©YkÑ–XâÑ–XâËŸTñÏoMíÏoMíÒ©LØ0SœØ0Sœã9R3ïSÝÑ–XâÏoMíØ0SœØ0SœïSÝÑ–XâèXbäÜæcgÜÅ`ÜÅ`è*`èXbä";
		-- Old Crystalbark
		[ 32357 ] = "4Lq5SC¯9áC¢I™Q'N(K^Q-KXïEýV¡C{U?;U?;V;0Z#?¸Z#?¸\\\"Cˆ[‹L[‹LT`TRTUSIrW€>^7¡XÁ4Lq9áC¢8âJ™I™Q'Q-KU%OåXïEýU?;Z#?¸[‹LRTUSIrW€7¡XÁ4Lq8âJ™AoUðI™Q'U%OåW†M]XïEýZ#?¸7¡XÁ8âJ™;#S3W†M]Z#?¸[‹L7¡XÁ;#S3AoUðU%OåW†M][‹LIrW€7¡XÁAoUðU%Oå[‹LIrW€AoUðU%OåIrW€";
	};
	[ 488 ] = { -- Dragonblight
		-- Crazed Indu'le Survivor
		[ 32409 ] = "&+•ý&éI)†‹À,’ŽŠ3ä‰Q>B„É>B„É@.‡lD¼Ž¤D¼Ž¤K¦Ž\000U¡ŽBU¡ŽBW‘ K6¢@K6¢@H´¢ÊD{›PD{›PA½—ü@‘|2Ñ,J—´(Á˜r(Á˜r&+•ý)†‹À,’ŽŠ>B„ÉD¼Ž¤D¼Ž¤U¡ŽBK6¢@K6¢@D{›P@‘|(Á˜r)†‹À,’ŽŠD¼Ž¤K6¢@@‘|2Ñ(Á˜r,’ŽŠD¼Ž¤@‘|<íŽÙ<íŽÙ2Ñ,’ŽŠ,’ŽŠD¼Ž¤<íŽÙ%ŽwR%Ép¾(Õoª(Õoª+)yk) {/(Õoª) {/%ŽwR";
		-- Scarlet Highlord Daion
		[ 32417 ] = "³•7Üµ®2‚¸á9Á¾ANÄ¯F”ÃSHâÃSHâ¼/G”¶§C@¶§C@³•7Ü¸á9Á¸á9Á¾ANÃSHâ¸á9ÁÃSHâ¶§C@Ù=mÌØjŸÚô`|Úô`|Ý\\`\000â©f_â©f_ãmi¦àøn!àøn!Þ!ooÙ=mÌÙ=mÌÚô`|â©f_â©f_àøn!Ù=mÌ¶ü·R¶´­¿¸è­ß¹r»w»ÌÀGº’Áø²øÀA±@Æs¯|Å®¯|Å®±n½V´Ï¸Q¶ü·R¸è­ß¹r»w¹r»wº’Áø·¾²øÀA¯|Å®´Ï¸Q´Ï¸Q¶ü·R¹r»w¹r»w·¾µ\
½Oµ\
½O²øÀA´Ï¸Q¹r»wµ\
½O´Ï¸Q";
		-- Tukemuth
		[ 32400 ] = "™M}›íHšž;I­§QGªqLI¯vHÎ¯vHÎ´FHè¶âLí¶âLí·>TZ´ÜX®brG´w®µÂ|ÓµÂ|Ó²ø•Ö°ožƒ°ožƒ­„Ÿvª˜“¡@’n¡@šdžËž\ržËž\r”,™Í–¡‘[”ÉŽ¾–¡‘[”,™Í”,™Í‰™…‡”¨…‡”¨…sÒƒvµƒvµ•€[W™M}™M}ž;I­ oNÒ§QG¯vHÎ¶âLí¶âLí´ÜX¯ÿXâ®brGµÂ|Ó°ožƒ°ožƒª˜“©W‡*žËž\r–¡‘[™³’½”‡‰e”ÉŽ¾”,™Í”,™Í…‡”¨ƒvµƒvµ™M} oNÒ§QG¶âLí¯ÿXâ­i]Š®brG°ožƒ°ožƒ©W‡*§\
¡@’nžËž\r™³’½”‡‰e”,™Íƒvµƒvµ oNÒ£`Q°£`Q°§QG¯ÿXâ­i]Š°ožƒ§\
¡@’n™³’½œ‹‘‰–\
…+”‡‰eƒvµƒvµ£`Q°¯ÿXâ­i]Š§\
¢êŒV¢êŒV¡@’nœ‹‘‰˜Ôƒ¯–\
…+ƒvµƒvµ¯ÿXâ­i]Š¢êŒVœ‹‘‰ž\\—œC„¢˜Ôƒ¯ƒvµƒvµ­i]Š¢êŒV¢êŒVž\\—óˆ*œC„¢ƒvµ¢êŒV¢êŒVóˆ*œC„¢";
	};
	[ 141 ] = { -- Dustwallow Marsh
		-- Dart
		[ 14232 ] = "tÐ2u)xÇ%›xÇ%›{À$3}¥&Â}¥&Â~æ3T}O5Ï}O5Ïy6tÐ2tÐ2xÇ%›}¥&Â}¥&Â}O5ÏtÐ2";
	};
	[ 490 ] = { -- Grizzly Hills
		-- Arcturis
		[ 38453 ] = "Ni’MNBBQåBQåBQÊ’@Ni’M";
		-- Grocklar
		[ 32422 ] = "ÓuÁjW*f8*f8Ídz«f_!ër'yÛ(1€o(1€o'R\r%S’,%S’,¹“¼Æ‘aÓu*f8«f_!ër(1€o%S’,%S’,Æ‘ažòžòÓu«f_«f_!ër%S’,žò«f_%S’,Q·’³M\"Ê²×\"Ê²×)ü®71®B71®B8ö±:³¹û:³¹û9¼ž/¾¸*%9¶lQ·\"Ê²×\"Ê²×71®B:³¹û/¾¸*%9¶l\"Ê²×\"Ê²×:³¹û/¾¸*3¢Ä5SB<Ú‰À<Ú‰ÀB ˆ§D%‹)D%‹)DM–ÜBT™xBT™x5êšÚ3Ã–Ü3Ã–Ü3¢Ä<Ú‰À<Ú‰ÀD%‹)BT™x<Ú‰ÀBT™x3Ã–Ü";
		-- Seething Hate
		[ 32429 ] = "C,vfDq[H†r•H†r•I#vâDÐz’H†r•DÐz’C,vfW$zW[]{/[=|[=|Y	‚ˆU`[=|U`W$zWd9yºhz’i ¤i ¤fð„a£€Øa£€ØaN|úd9yºi ¤a£€Ød9yº";
		-- Syreian the Bonecarver
		[ 32438 ] = "œ„Wž.Rh¤¯Kû­ÅB¯ª=w±n=æ±n=æ²T?ù± D¯´M¿ºCR¾.Y¦¾.Y¦ÃZ³Åð_;Å_cñÆgÕÄ”l„Ä”l„¾Oqë¼¸pH¹îbþ³•]j±ÄZ)©™Vð¬¥\\q­waÿ­waÿ­kÚ«nO«nO§kî§dÃ¥µa |^Š[À[Àœ„W¤¯Kû­ÅB±n=æ± D¯¾.Y¦Åð_;Å_cñÅ_cñÄ”l„¼¸pH¹îbþ±ÄZ)°:R½©™Vð­waÿ«nO¥µa[À¤¯Kû¤¯Kû­ÅB± D¯´M¿¾.Y¦Å_cñÅ_cñ¼¸pH½\000j)©™Vð«nO§dÃ§dÃ¥µa¤¯Kû¤¯Kû± D¯°£Hâ´M¿Å_cñ½\000j)©ÚR©™Vð§dÃ¤¯Kû°£Hâ´M¿´M¿½\000j)¹îbþ©ÚR§dÃ¤¯Kû´M¿¹îbþ°:R½¬cP;©ÚR¤¯Kû´M¿°:R½¬cP;¤¯Kû´M¿¬cP;";
	};
	[ 465 ] = { -- Hellfire Peninsula
		-- Fulgorge
		[ 18678 ] = "; G9ü•f:Žp:Žp;ÀƒÃ>5y	>5y	B obGöj=KçcZN}YQ:YÎQ:YÎQ‚\\ôP‰d¯P‰d¯NÅi	Ko\\@‰}@ò¤É>—§Î>—§Î:e¦; G; G:Žp>5y	KçcZQ:YÎP‰d¯P‰d¯Ko\\Gs@i@‰}>—§Î>—§Î; G>5y	Göj=KçcZP‰d¯@i>—§Î>5y	>5y	Göj=P‰d¯AØƒF@i>5y	>5y	P‰d¯GsCÃyAØƒF>5y	>5y	GsCÃyH ²½F²ZFÜ©ŒFÜ©ŒJº¢¯P\000œ\"X1”¯ZÍ‰À]‡\
]‡\
aë€åi=Anc}órGz0sñ{Úsñ{ÚsnƒSqª†8qª†8j=‰™d›ˆe[6‘ÿ[)›ÆX ÑLú¨üH ²½FÜ©ŒFÜ©ŒP\000œ\"UÖ™]‡\
i=Anc}ónc}ósñ{Úqª†8[6‘ÿX ÑT9ŸìRG åLú¨üFÜ©Œ]‡\
nc}óqª†8]I‹ç[6‘ÿT9ŸìRG åFÜ©ŒUÖ™]‡\
qª†8d›ˆe]I‹çT9ŸìRG åRG åUÖ™X1”¯]‡\
d›ˆe]I‹ç]I‹çRG åX1”¯X1”¯]‡\
]I‹çf°hg¨ºhõ§Rhõ§Rkq¬k¥²Ým/¶1u?²&€¯å€¯åæ±ñ•é´L•é´L—­·*–‡¼‘–‡¼‘‘½c»¥qø¹l»‹gK¹gK¹f°hhõ§Rm/¶1€¯å•é´L•é´L–‡¼‘»¥vâ·âqø¹gK¹gK¹hõ§Rk¥²Ý•é´L»¥z’¸†gK¹k¥²Ým/¶1m/¶1•é´Lz’¸†vâ·âgK¹m/¶1m/¶1z’¸†vâ·â";
		-- Mekthorg the Wild
		[ 18677 ] = "rÊss©k‹tth1tth1vh>y³mpy³mp|Iuµz’{}(€4…~OŽùÅŽùÅŽ;‚nƒ‡´}I™*}\\p{xž\rk=´zj»hü·´hü·´ie³Fm/Ÿ¾m/Ÿ¾qN•v®–vxrsTu2rÊsrÊstth1y³mp}(€4ŽùÅƒ‡´}c”?}I™*{xž\roO¢ak=´zhü·´vxrrÊsy³mpzî~}(€4ƒ‡´}c”?{xž\rvÜœÙoO¢ahü·´m/Ÿ¾yŒƒ÷vxry³mpzî~ƒ‡´€ª€ª}c”?vÜœÙr&ž±oO¢am/Ÿ¾yŒƒ÷y³mpz’{€ªvÜœÙr&ž±r&ž±m/Ÿ¾v®–yX‹…yŒƒ÷z’{€ªr&ž±v®–yX‹…z’{zî~€ªv®–yX‹…zî~€ªyX‹…¬\"Çè¤LÀu¢ä½Ù¢ä½Ù£¯µR¥»²•¥»²•¯¾®U±Ñ¯.±Ñ¯.¶öµµ·¹J°½½®pÆy¬\"Çè¬\"Çè¢ä½Ù¥»²•¥»²•±Ñ¯.·¹J°½½¬\"Çè¥»²•¥»²•·¹J²Ýº¥»²•²Ýº°½½";
		-- Vorakem Doomspeaker
		[ 18679 ] = "ˆFã‰ÔCþÌG_¡©G†¨“Ct«‹FE«‹FE«ŸNO©xQ ©xQ  [TŽ“¶Sþ“¶SþŒúQG‡sKÆ‡sKÆˆFãÌG_–yI†¡©G†«‹FE«‹FE©xQ “¶Sþ“¶Sþ‡sKÆÌG_–yI†«‹FE“¶SþÌG_–yI†“¶Sþ²a{¹±[r·\
fµ·\
fµºÚ]í¼Ù[=¼Ù[=¿b[çÁub©Áub©Âk¹½¸qh½¸qhº]yõ´2}V´2}V²a{¹·\
fµ·\
fµ¼Ù[=Áub©Áub©½¸qh´2}V·\
fµÁub©´2}VµÈ˜†³¢‰D·r„Â·r„Â¼…Â¿H²¿H²¾!œÌ¼‹Ÿ'¼‹Ÿ'¹	µÈ˜†µÈ˜†·r„Â¿H²¿H²¼‹Ÿ'µÈ˜†b-PvcL’h_K~h_K~o—Mío¾VýjkSþjkXRhÇY†hÇY†ctVfb-Pvh_K~o¾VýjkSþjkSþhÇY†b-Pvh_K~jkSþb-Pv";
	};
	[ 491 ] = { -- Howling Fjord
		-- King Ping
		[ 32398 ] = "O!(ST“¯PA—PA—M/ŽžO!(FfŸFµ¤ãCa¦fCa¦f>¥S>I¢ÐCa¦f>I¢ÐFfŸMÌ½5N¿¯ìPì°Pì°P\r½¸MÌ½5QN½\000S,½RëÄRëÄQÃþQN½\000QåÏSaÉ¬W†ÉW†ÉWšÌjSˆÑW†ÉSˆÑQåÏ";
		-- Perobas the Bloodthirster
		[ 32377 ] = "€·‚u	ˆDˆD‹Ÿ/Š)\"TŠ)\"TˆK!ÿ‚ˆå‚ˆåªß€·€·ˆDŠ)\"TŠ)\"T‚ˆå€·—š3G˜Û.Ò¤2[¤2[›w9Œ™ :D¤2[™ :D—š3GªC.¿¬I'\
®Ë%F³&Ž¶§Ì¸>˜¸>˜¹À#·Á*è±{+W¬p0ªªC.¿ªC.¿®Ë%F³&Ž³&Ž¸>˜·Á*è±{+WªC.¿³&Ž³&Ž·Á*è±{+W";
		-- Vigdis the War Maiden
		[ 32386 ] = "¯·~¾®!u¨¯ØpÄµ€n—¹xe»¬b{½vemÀe?Â{hÕÂ{hÕÃãsÃ€ÀëßÁž½‘¡u½‘¡u¹³Ÿù¶®›<³g™=­¤–»­Ì“g´t„ð¯·~¾¯ØpÄµ€n—»¬b{½vem½vemÂ{hÕÃ€ÁˆõÀëß½‘¡u¶®›<³g™=­Ì“g´t„ð¯ØpÄµ€n—µ€n—½vemÃ€Áˆõ½‘¡u¶®›<¶®›<­Ì“g±:“t´H´t„ðµ€n—µ€n—Ã€ÁˆõÁˆõ¶®›<±:“t´Hµ€n—ÁˆõÁˆõ±:“t´H";
	};
	[ 492 ] = { -- Icecrown
		-- High Thane Jorfus
		[ 32501 ] = "­ßg´¬²b©­«]p­«]p°‰ZÇµ\
\\/»W¡½;Oi¿ËPo¿ËPo½Z^¶â_.¶â_.¶Èf´iõ´iõ°Aj­ßg´­ßg´­«]pµ\
\\/»W¡¿ËPo¶â_.¶â_.´iõ­ßg´­ßg´µ\
\\/»W¡»W¡¶â_.­ßg´|PáauLØûttÑÊttÑÊvéÈ­zûÅ_zûÅ_~ÊÀƒ&Ûƒ&Û€oá{|Páa|PáattÑÊzûÅ_zûÅ_ƒ&Û|PáaN›…PòœÌPN¡©WE¬àZQ©Q[~«²[²^Ù³_v·1_v·1]„·èZõ¶+SÃµsP–µãOƒ³ZPA¯M uN›…WE¬à[~«²X´®p[²_v·1Zõ¶+Zõ¶+SÃµsOƒ³ZPA¯N›…PN¡©WE¬àX´®p[²[²Zõ¶+Oƒ³ZPA¯PN¡©WE¬àWE¬à[²Oƒ³ZWE¬àOƒ³ZPA¯";
		-- Hildana Deathstealer
		[ 32495 ] = "JqÞHXu¨HRdðLçTIÛL¥JJF¡JJF¡MAªQÄB ]Ó?\r]p<j_:Ô_:Ô`ò<ç`@\000`@\000^(DŽUtIÁM}N‘P.S¶N.]O` RdtS9ieS9ieR&nìL²uIÎwöEê}ODÝ{ŸHXu¨JqÞNÒmVJºfRJqÞHRdð]B3]Ó?\r_:ÔLIJÇM}N‘N.]S9ieL²uIÎwöIÎwöDÝ{ŸHXu¨LŸb×JºfRHRdð]B3_:Ô`@\000S9ieIÎwöHXu¨LŸb×HRdðK)]„]B3`@\000UtIÁS9ieHXu¨NÒmVO¾hšLŸb×K)]„U¨FÜ]B3UtIÁS9ieNÒmVO¾hšO¾hšK)]„LçTQÄB U¨FÜUtIÁO` S9ieO¾hšQÄB UtIÁP±EêN.]O` O¾hšQÄB P±EêMóEÂN.]O¾hšLçTJJF¡QÄB MóEÂLIJÇN.]LçTJJF¡MóEÂLIJÇLçTJJF¡LIJÇ†\
ŽB†Š~ˆr‡Áˆr‡Á‹„ŽÒ„2’äŠû—ü‡§™‰Í–öÞš6—R™’ú™’ú—E ò“M¡£“M¡£“Ðžv–öp‰*Šô‡§²†\
ŽB†\
ŽBˆr‡ÁŽÒ„2’äŠû™‰Í–öÞ™’ú“M¡£–öp‹¬ˆ1‰*Šô†\
ŽB’äŠû–öÞ™’ú™’ú–öp—˜K‹¬ˆ1†\
ŽBŽÒ„2’äŠû™’ú—˜KŽUˆr‹¬ˆ1ŽÒ„2ŽÒ„2’äŠû—˜KŽÒ„2—˜KŽUˆr";
		-- Putridus the Ancient
		[ 32487 ] = "°ë³­ì¯ì­«©xv?•{P¬žwé®wé®rh•›r×ˆDr×ˆDwE{˜‚f®‚f®ŠkaÄ˜ºct§>s¼®—“²@¦f²@¦f³Ö©*´,°´,°°ë³­«©xv?•wé®r×ˆD§>s¼²@¦f´,°´,°­«©x®±§ev®‰Œv?•r×ˆD§>s¼´,°®±§ezv®‰Œr×ˆD§>s¼®±§e«\"•€ƒäkôzr×ˆD§>s¼«\"•€¤`y*ƒäkôr×ˆD‚f®˜ºct§>s¼¤`y*ŠxgÎƒäkô‚f®˜ºct¤`y*–ýh´–ýh´ŠxgÎ‚f®–ýh´‚f®˜ºct";
	};
	[ 477 ] = { -- Nagrand
		-- Bro'Gaz the Clanless
		[ 18684 ] = "Qå;‹UÖ9DWÁ>WÁ>XREêVsQVsQT,XMYH1`FzD›AAª„•A‹6>¸‹Æ>¸‹Æ>í„AÞ}ÅCTyE]žGÕWRJºQÿCÃQå;‹Qå;‹WÁ>VsQH1`D›AAª„•Aª„•>¸‹ÆAÞ}ÅRJºQå;‹VsQAª„•AÞ}ÅCTyNæPØRJºVsQH1`Aª„•CTyGÕWNæPØVsQH1`CTyGÕWGÕWVsQMYIõ\\ŸH1`GÕWMYIõ\\ŸGÕWnŽUm\"ˆ^t%‰Àt%‰Àt›ŒIs3ŽÅuY“¯{\"—­}5šç†¡‡Û·‡ö\r…Ü\r…Ü~ó‚Zƒ3ƒþ‡*ƒÝŒ6[Œ~„µ‰Ç‹’‰7•S‡ï›C…¨ŸÄ…¤z€|¦f€|¦f|ž¦y{ç by³œt¼˜ÁnŽUnŽUt%‰Às3ŽÅ†¡‡Û\r…Üƒ3ƒþƒ3ƒþ‡*ƒÝŒ~„µ‰Ç‹’‡ï›C…¨ŸÄ…¨ŸÄ€|¦f{ç bnŽUs3ŽÅuY“¯†¡‡Ûƒ3ƒþŒ~„µ…¨ŸÄ{ç by³œy³œnŽUuY“¯‡\
Þ†¡‡ÛŒ~„µy³œuY“¯}5šç‡\
ÞŒ~„µ‰Ç‹’…¨ŸÄy³œ}5šç…Ï•ö‡\
Þ‰Ç‹’…¨ŸÄ}5šçNš…Ï•ö‰Ç‹’…¨ŸÄNš…Ï•ö…¨ŸÄ”µ½Ù”•µ»–f³¼–f³¼šû¶²¼5£¼¾\\¦Y¼ª½VµÏ¸Ç²±n³¯¯Ñ³¯¯Ñ¶€±-¶®´ê¸0»ªáÄ”¦üÄã¦üÄã¤êË¥¡ÑÊà˜­Ë„š¬Ð˜™ÒF˜™ÒF•ŽÌ—yÀø—yÀø”µ½Ù–f³¼£¼¾\\ª½V«Æ¿ÑµÏ¸Ç³¯¯Ñ¶®´ê¦üÄã¡ÑÊà£%Ä˜­Ë„˜™ÒF—yÀø—yÀø–f³¼²¼5µÏ¸Ç¶®´ê¸0»¸0»¦üÄã£%ÄšÔ¾Ë˜­Ë„—yÀø«Æ¿ÑµÏ¸Ç¸0»šÔ¾Ë—yÀø²¼5«Æ¿Ñ¸0»£%Ä£%ÄšÔ¾Ë²¼5£¼¾\\«Æ¿Ñ£%Ä²¼5£¼¾\\£%Ä";
		-- Goretooth
		[ 17144 ] = "¿ØÂ¼ÁˆÀÄÆÎÍVÆÎÍVÅÈÓÃÒÁÃÊà¿ØÂ¼ÆÎÍVÆÎÍVÃÒÁÃÊàÅA[A<”÷<–È?±›/AØŸ;E‡Ÿ;E‡ ØR×ŸbTñŸbTñŸ\rX$[JòQ:ŒÓO¾‹ÆIy‹ÆIy‰kDÐŠCAÅA[”÷<–È?±–È?±Ÿ;E‡ŸbTñŸbTñ[J™7V¡™7V¡òQ:‹ÆIy‹ÆIyŠCAÅA[ÅA[–È?±ŸbTñŸbTñ™7V¡‹ÆIyŸbTñ‹ÆIyÅA[NwROHuYVétêVétêY³pb]\"r]\"r_pÑ`vrñ`vrñ`·xè^(|^(|_Ëƒ9\\V„÷\\V„÷W»‹NŒÓN\\ˆ7MB‚ˆO.{dO.{dNwRVétêVétê]\"r`vrñ^(|\\V„÷NŒÓNŒÓN\\ˆ7O.{dO.{dVétê`vrñ`vrñ^(|NŒÓ`vrñNŒÓO.{dg$bÊi=^«lçaåm²csh$r×j™r×j™t`oØtwörñz~tÐ}It9€kÚzxi³{gfwögfwöe¡ruhïirhïirj³lPhŒqNkûh_j³lPhïirh eµg$bÊlçaår×j™twörñz~rñz~t9€kÚzxgfwöhïirhŒqNkûh_hïirh eµh eµlçaåm²crñz~kÚzxgfwögfwöhŒqNi^uÉn;h*kûh_h eµrñz~gfwöi^uÉn;h*h eµm²crñz~i^uÉnvwüpÿjÍn;h*m²crñz~nvwür-sÉpÿjÍm²cr×j™r×j™rñz~r-sÉr×j™r-sÉpÿjÍ";
		-- Voidhunter Yar
		[ 18683 ] = "Zº¥z_¦^V«]aÿ®ù^V«]_¦c¨´eŽ¥?g_§€e«fã®¸gÕ²¯gÕ²¯jû²×k¶égé¶ygX»‘eÏÀbeÏÀbc3Ä¡`HÇ_`HÇ_aË6^—Ì}]ÅÇïY­ÇU”ÅSTÂP'ÄãNvÁÑR¾OQ[¸áR²,R²,N­æO—©ŸSg­—U‡ªX§X§W8 øYÛŸËZº¥z^V«]Z³«Úaÿ®ù_¦c¨´c¨´g_§€e«gÕ²¯k¶égé¶ygé¶yeÏÀb`HÇ_`HÇ_^—Ì}]ÅÇï]ÅÇïU”ÅSTÂSTÂNvÁÑR¾OR²,O—©ŸSg­—X§YÛŸËZº¥zZº¥zZ³«ÚW§¯\000c¯µ¡aÿ®ùc¨´c¨´e«gÕ²¯gÕ²¯gé¶y`HÇ_`HÇ_]ÅÇïSTÂSTÂR¾OR²,R²,Sg­—X§X§Zº¥zW§¯\000c¯µ¡c¨´gÕ²¯R²,X§W§¯\000b–»˜c¯µ¡gÕ²¯R²,W§¯\000U¡´b–»˜gÕ²¯`HÇ_STÂR²,U¡´_À'b–»˜`HÇ_STÂU¡´U¼º[‹À£_À'`HÇ_STÂU¼ºWÕ¾;WÕ¾;[‹À£`HÇ_WÕ¾;`HÇ_STÂ";
	};
	[ 479 ] = { -- Netherstorm
		-- Chief Engineer Lorthander
		[ 18697 ] = "@UlC¶`ªF^pF^pJ`‰KPctKPctJf?G>g†G>g†DÐnpBÊphBÊph@Ñoƒ@Ul@UlF^pKPctG>g†BÊph@UlKPctG>g†@Ult9Ñ&tFËÌv‡ÈÎv‡ÈÎ}«Ì‘±ÏH±ÏHËÕ_|6Û¿|6Û¿w´ÚŸt9Ñ&t9Ñ&v‡ÈÎ±ÏH±ÏH|6Û¿t9Ñ&•Y¬ú’ˆ G”\\”\\.ŸHŸ\\¤ÝŸ\\¤Ýí«q—š®ù—š®ù•Y¬ú”\\”\\Ÿ\\¤Ý—š®ù";
		-- Ever-Core the Punisher
		[ 18698 ] = "<k]:¦e>„cI¦jKdÉS3jÀS3jÀO.pØJ³uJ³uD¯u@Nr•@Nr•<k]>„cFRmI¦jS3jÀS3jÀJ³u@Nr•@Nr•>„c?ph FRmS3jÀ@Nr•@Nr•?ph B ldB ldFRm@Nr•;6¨:=£¢@!£SD¶¦>Iy£nK¦éK¦éJ)­ßGâ´gGâ´gJŒ·IïºûIïºû=«ÈÇ78Æ78Æ2GÀo0|·*0|·*2T§»4þ¦ö4þ¦ö7\
®\r6¡·è>p«P;6¨@!£SD¶¦>K¦éGâ´g78Æ0|·*4þ¦öAå¯i>p«P@!£S@!£SD¶¦>Gâ´g78Æ4þ¦ö6¡·èAå¯i@!£SGâ´g78Æ6¡·è9¼óB–µsAå¯iGâ´g78Æ9¼ó>V½ÒAë»<B–µsGâ´gIïºû78Æ>V½ÒAë»<Gâ´gIïºûIïºû>V½ÒAë»<—eU›˜ÛO¤šáM}¢nPß¦šOª¹QÊª¹QÊ¬ÌV°4ie°4ie¯ u÷¨*|à¨*|àž!~Ùž.s{špåž.s{ž!~Ùž!~Ù“3{boiboid2”m\\q—eU›šáM}žUP¨*|àž.s{¥%rë—âlÙšpåž!~Ùboi”m\\q—eU›—eU›žUP¢nPß°4ie¨*|à¥%rë—âlÙž!~Ùboi—eU›¢nPßª¹QÊ°4ie¥%rë©¦m¿—lgs—âlÙboi°4ie©¦m¿ªJe˜e`'—lgsboiª¹QÊ°4ieªJeœ/Y“˜e`'boiª¹QÊªJe§»Yîœ/Y“boi—eU›ª¹QÊ§»Yî¡‰VÕ¡‰VÕœ/Y“—eU›ª¹QÊ¡‰VÕ—eU›";
		-- Nuramoc
		[ 20932 ] = "T%NÙRøGüUã@oW”<]X52Zk0¤Zk0¤\\¿0¾_—6Ž_—6Ža A_BCÃ\\<Nß]íR–\\‘U¯\\‘U¯WYáU`WéU`WéT%NÙUã@oW”<]Zk0¤_—6Ž_—6Ž_BCÃ\\6D¶[6Gö\\<Nß\\‘U¯\\‘U¯U`WéUã@oUã@oW”<]_—6Ž_—6Ž\\6D¶[6Gö[6Gö\\‘U¯Uã@oUã@o_—6Ž[6Gö…zŽ‡“ŒŠŽË˜º’{§y’{­•ý­•ý°‚Ÿ°·¢{°·¢{ªd§¨	¥µ£ê¡:ˆœÓ†8šç†8šç…zŽŠŽË˜º’{­•ý°·¢{°·¢{¨	¥µ£ê¡:£ê¡:†8šçŠŽËŠŽË˜º’{°·¢{ŠŽË°·¢{£ê¡:;^Ì:ÔÈr<‹ÆšJxÊÚOÆ®eÁÃo.½ìmI´¼pv±–pv±–rˆ±:vÈº…vÈº…t÷Ç>s•É=nHÇyd•ÌZÔÍvN¸ÎËIÒt@4Ñ{@4Ñ{;^Ì<‹ÆšJxÊÚeÁÃlúÀòo.½ìpv±–vÈº…vÈº…s•É=nHÇynHÇyZÔÍvN¸ÎË@4Ñ{<‹ÆšCÊ˜lúÀòo.½ìvÈº…nHÇyN¸ÎË@4Ñ{@4Ñ{CÊ˜JxÊÚlúÀòvÈº…nHÇynHÇy@4Ñ{JxÊÚJxÊÚlúÀònHÇy";
	};
	[ 473 ] = { -- Shadowmoon Valley
		-- Ambassador Jerrikar
		[ 18695 ] = "F\
€ƒH yKPyKPyO;~Mæ“&Mæ“&Jû’ZIK‘IK‘F\
€ƒKPyKPyMæ“&IK‘pùPbqœK^uYAAuYAAwsAhyŒD›yŒD›wšQ½tgSatgSapùPbuYAAuYAAyŒD›tgSaŒ]\\ú‘W™0YÔ™0YÔ˜´_ì’f’fƒdþŒ_'Œ_'Œ]\\ú™0YÔ™0YÔ’fŒ_'y=¤‡{˜¤µ|~®ì|~®ìzî·âxe¸´xe¸´qø°4qÄ¬íqÄ¬íy=¤‡|~®ì|~®ìxe¸´qÄ¬í®B—Õ²–L¸üš^¸üš^ºd„ºÚ§ºÚ§¸õ¨º°u¥2°u¥2­I¡©¬¥¬¥®B—Õ¸üš^¸üš^ºÚ§°u¥2¸üš^°u¥2¬¥";
		-- Collidus the Warp-Watcher
		[ 18694 ] = "”¼;‹“Ã7l™x43™x43¢¢4n¬\"6f¬\"6f­58è®'H“®'H“¾ùHÀuJ	ÀuJ	ÁøV¨¿HW$™õ8K”¼;‹™x43ÀuJ	¿HW$½—LC¢38e™õ8K™x43®'H“ÀuJ	½—LCª’:r¢38e™x43®'H“½—LC«¹L¥ª’:r™x43¬\"6f¬\"6f®'H“«¹L¥¬\"6f«¹L¥ª’:r]Vjq_i³il˜il˜mŠqAuý‚£uý‚£w‰*uŠ³uŠ³o—†µl6}5a·u]«x1[‹u¡[‹u¡[…o¾]Vjq]Vjqil˜uý‚£uý‚£uŠ³l6}5a·u[‹u¡]Vjq]Vjquý‚£l6}5gÈxâa·u]Vjql6}5gÈxâ]Vjq–½‘ëÃˆŽ!¾ËŽ!¾ËŒ<¶‹à°‰‹à°‰Ž¾¯ì4µmO¦YŸv¢,ž«ª³­.µz¬¶y°¶y°«¥µ\
¢³g¢³gž}¯Ñí­iŽ!¾Ë‹à°‰4µmœPª=O¦Y¢,ž«¥8¬„ª³­.¶y°¶y°¢³gí­iŽ!¾Ë4µmØ»‘œPª=¢,ž« u¦®¥8¬„¶y°í­i–½Ž!¾ËØ»‘“¶º¦œPª= u¦®¢ª^¥8¬„í­i–½Ø»‘“¶º¦ u¦®¢ª^í­ií­i–½“¶º¦“¶º¦ u¦®í­i";
		-- Kraator
		[ 18696 ] = "e¼fÈj¬a o·cZo·cZoOnjmjme›i†e¼fÈo·cZjme¼fÈi³µRi†¬²m}¨Œm}¨Œqÿ§KrÐªWrÐªWoŠ·Îi³µRm}¨ŒrÐªWi³µR—lq œžru«yX«yX˜*€Ø–+H–+H•%y*—lq «yX–+H—lq prqv”„v”„x	 4w€(ew€(eq-%?pv”„w€(epL/m5O±kÚT•rMT•rMSñvEQbyQbyN‘v®LrGLrGL/m5T•rMT•rMQbyLrG";
	};
	[ 493 ] = { -- Sholazar Basin
		-- Aotona
		[ 32481 ] = "r{ˆl{À‰îy#“kÍ’þiœúd–>d–>c÷j’j’iÇƒFl€4l€4pr{ˆlr{ˆly#“p·p·kÍ’þd–>j’l€4r{ˆlr{ˆlp·d–>r{ˆld–>j’‡§‚©Š\000[°[°’°…¡øˆ“øˆ“ˆD‰­†¡†¡†¡†¡‡§‚©[°[°øˆ“†¡†¡:¢ä–+Ÿª•ã®ù•ã®ùŽË©*:¢ä„2²ˆŠî·‰#¾B‰#¾B„ãÁ¶‚&¼‰#¾B‚&¼„2²ˆu?´êsg¸0là¸ºlà¸ºl²ÀòiÛÃÖgK´ÂeŽ±Tfö­Šfö­ŠkªÚpÑ«<pÑ«<sñ®«u?´êlà¸ºiÛÃÖgK´ÂgK´Âfö­ŠpÑ«<pÑ«<u?´êlà¸ºlà¸ºgK´ÂpÑ«<";
		-- King Krush
		[ 32485 ] = "FL†Õ@.†È>c‚þ>c‚þ>ßzDÝtDÝtKçaÞP‰]„P‰]„Q£TZÚIZÚI_ùK=`O!XâUYT@hrP±qoKûwüOvz0P–}\"N\\€Oƒ’MNÒ¦8NÒ¦8Pù§ïRªôRªôOO±I>´I>´I´ÀòG_ÄG_ÄA°Áø>«¼Ì>«¼ÌA½®\\E¼©ÚFL†Õ>c‚þDÝtZÚI`O!XâUYXâUYP±qoMjsÝKûwüP–}\"N\\€NÒ¦8RªôI>´I>´G_Ä>«¼ÌFL†ÕDÝtP‰]„P‰]„ZÚIXâUYKûwüN\\€NÒ¦8NÒ¦8I>´>«¼ÌP‰]„XâUYMjsÝNÒ¦8>«¼ÌE¼©ÚFL†ÕP‰]„MjsÝKûwüNÒ¦8E¼©ÚFL†ÕMjsÝKûwüFL†ÕKûwüE¼©ÚtÃl<w$b©z’g“‚ëg…ãc,‰XdM‰XdMŠkŸˆ“w®ˆ“w®{J{dyõ{dyõvâr tÃl<tÃl<z’g“.iº.iº‚ëg‰XdM‰XdMˆ“w®{dyõ{dyõtÃl<.iº.iº‰XdM{dyõƒÈD„9ËÓ…Ñ‚jÒ@¤Ì„“›Èõ¢{Ëq¥‡ÆÁªkÆ_ªkÆ_¬CÈ	«˜Í¤«˜Í¤¥E×õŸßÚ’ŸßÚ’”÷ÚŸ‘Øx‹çØõ‡8ÛôƒtÖƒtÖnÍBƒÈDjÒ@“›Èõ–¡Ìó¢{ËqªkÆ_«˜Í¤«˜Í¤ŸßÚ’‘Øx‘Øx‹çØõƒtÖƒtÖƒÈD…Ñ‚jÒ@–¡ÌóOÎ}OÎ}¢{Ëq«˜Í¤«˜Í¤‘ØxƒtÖƒtÖ…Ñ‚ˆQÔFˆQÔFjÒ@OÎ}OÎ}«˜Í¤ƒtÖˆQÔFOÎ}ƒtÖ";
		-- Loque'nahak
		[ 32517 ] = "±‰³³Ö¯N¶§¯;¶§¯;¸è³¸è¸k¸è¸k¶Ü»à³É»¥³É»¥±£¸±‰³±‰³¶§¯;¸è¸k¸è¸k³É»¥±‰³ªk¿\r­ß¾.° Æ8° Æ8«’Í¤¦Ì¸¦Ì¸¥ãÉ#ªk¿\r° Æ8¦Ì¸ªk¿\r‚×è~HÓz~;Ð~;Ð‚uÉ…„LÒñ„LÒñ…8ÖÎ‚×è~;Ð„LÒñ‚×è‘A6S“Ã3n–Ï3n–Ï3n™	6€™	;’™	;’–â?v“M?b“M?b‘[;Ÿ‘A6S‘A6S–Ï3n™	;’™	;’“M?b‘A6SX§MVXÕJJ[˜Fð[˜Fð`\000R]úT¢[˜Fð]úT¢X§MVL¥£ÃOå¤ãR©ÀR©ÀPU¯åKÀ¯AKÀ¯AIÎ¬wL¥£ÃR©ÀKÀ¯AL¥£Ã3×²37_®\\9è°‚9è°‚9†¹05Éºd5Éºd2Þ¹û3×²39è°‚5Éºd3×²3";
	};
	[ 478 ] = { -- Terokkar Forest
		-- Crippler
		[ 18689 ] = "Vš¥¡C×¢½Gf‘hGf‘hNæƒ9Y“|wY“|wfézJs€As€A}BŒ\"‚ø›’‚ø›’ƒþ­¸ª¿Øª¿Øx†Ìžm/º~X“œÙVš¥¡Gf‘hGf‘hY“|ws€As€A‚ø›’ª¿Øª¿Øm/º~q ´2^•LX“œÙGf‘hª¿Øq ´2s3­5f“^•LGf‘hª¿Øs3­5sg¤f“Gf‘hs€As€Aª¿Øsg¤l]•Lf“s€As€Asg¤q&›s€Aq&›l]•L]¿¦Ü`\rŸ\retœpetœpjÍŸ!m¦´m¦´k\"®ìeÂ²eÂ²`¯b]¿¦Ü]¿¦Üetœpm¦´m¦´eÂ²]¿¦Ü";
		-- Doomsayer Jurim
		[ 18686 ] = "]VN‘\\)Gü^.G^.G_—Næ^BTÉ]aA_\000h´^\\nß^\\nß[çnž\\qhŒ\\qhŒZra‰[çT9]VN‘^.G^BTÉ]aA^\\nß\\qhŒ\\qhŒ[çT9]VN‘]VN‘^BTÉ]aA]aA\\qhŒ]VN‘b©>íb¶;¹fÈ<~y	A}c>Ò‚Ð=¸‡191Š03:’g/¤’g/¤’°2‚‹5÷‹5÷ˆ7;¬ƒS@ª}ÙB@yDE2m¿Emm¿EmhÎCgeµ?Ueµ?Ub©>ífÈ<~‡191’g/¤‹5÷ƒS@ª}ÙB@m¿Emeµ?UfÈ<~i @‰‚Ð=¸‡191‹5÷m¿Emeµ?Ui @‰‚Ð=¸‹5÷ƒS@ªm¿Emi @‰nVB@y	A‚Ð=¸ƒS@ªm¿EmnVB@y	Ay	AƒS@ªm¿Em‹ÀStŒ/PA”¨R—XVfžZ^¡ë_iª¬o.¶~´Ö€ë¤Yc{ ½bœ«]œ«]–+YQ“US“US‹ÀSt”¨Rª¬o.´Ö€ë¨Áq[¤Yc{œ«]“US“US”¨R—XVf¥Ö`·ª¬o.¨Áq[¤Yc{“US—XVf¥Ö`·¨Áq[¤Yc{¤Yc{—XVf¡ë_i¡ë_i¥Ö`·¤Yc{";
		-- Okrek
		[ 18685 ] = "K^k¬O±fRRˆlPRˆlPNŠuFLúoØRˆlPLúoØK^k¬|Ó-w}\"Þ~ù!ò~ù!ò„•)ï€ÿ4t€ÿ4t~Ò4|Ó-w~ù!ò€ÿ4t|Ó-w”t9—s7l›=à›=à›˜Fm’{=›=à’{=”t9¼žŒ/«‘-©*‘-©*’&«P‘±œ‘±œ”S¶\
‘½¤¼ž‘-©*‘±œ‘±œ‘½¤¼ž";
	};
	[ 11 ] = { -- The Barrens
		-- Takk the Leaper
		[ 5842 ] = "•€”`h—šU—šUœÙÝž¤Œž¤ŒŸ!œô'Yœô'Y›²&f›¹Ì˜Ç»•€—šUž¤Œœô'Y›¹Ì›¹Ì˜Ç»—šU—šUž¤Œ›¹Ì";
	};
	[ 495 ] = { -- The Storm Peaks
		-- Dirkee
		[ 32500 ] = "gšƒŽhr€‰i†€oi†€oj’…Ži0‰ b”¢d9–ïb-œôb-œô^\\™	]B”L]B”L^‘aª‹’fÈ†sgšƒŽi†€oi†€oi0‰ ezŠ#b Ab”¢b-œôb-œô]B”Laª‹’fÈ†si†€oezŠ#b Ab-œôaª‹’aª‹’fÈ†sezŠ#cÐŒ~b Aaª‹’ezŠ#cÐŒ~aª‹’ifh“c×móaumóauoicþj¦ij¦ilwmÌj6p\rj6p\rgÈjºififmóauj¦iifj¦ij6p\r«}}«vE«Útg«Útg­¤tŽ¯¤{q¯¤{q­ÅÅ¬5Å¬5Å«}}«Útg«Útg¯¤{q¬5Å";
		-- Skoll
		[ 35189 ] = "uz¤Ïw¥2w´§Rw´§Ru¨¨Ît¢§yw´§Rt¢§yuz¤Ïo¾Ÿ|q45s3ž¾s3ž¾r•¢To¾Ÿ|Jõƒ•J)€ÿKáÅKáÅLÆ‚:Jõƒ•LÆ¥SLÓ¢nP\r£¢P\r£¢Nì¥µLÆ¥SF\
‚FµÅH€‰H€‰GE‚×F\
‚";
		-- Time-lost Proto Drake
		[ 32491 ] = "S9[q[…S•b-Mcb-Mcn5GÁnOM<c¢R]XrU?_ßU?_ßRÑaoLcœG8m„HètIX}\\IX}\\MÙxèV\
qÄV\
qÄ]PiKa[fÂa[fÂd÷hygÁkxgÁkxiŒpNi­|\"}‘vµyow€jJw€jJwšdZy	`vwsMnOM<n5GÁn5GÁwyGÏ€ëJá€ëJá…µN5‡ÕR@‡ÕR@‡Vé†?ZQ{djWqƒ@zûƒ@zûƒ¼~¾‚½‚½‚½‚½~.‰	xhÕ—\
d9ž¤a:£%a:£%^ù¤É\\¦Õ\\¦Õ]í¨™_ª«ô_ª«ô`¾°ÿa–·7fö«Ÿh žUjõ™ jõ™ o4•»sZ”µsZ”µwy–özŒœc|²¢Ê€U¬C}\"®!kç ëjW¬Ci*³Fi*³Ffm¸Ác¼~5²½}\"®!€U¬C€U¬C‰±NGµðGµð~‘Èü}\"Ì]}\"Ì]xÇÓFuFÕYuFÕYetÖ1aÔaÔ^ìÏË^\\ÊÍ^\\ÊÍ[ÎOUzÐ4UzÐ4M¿ÎbN±ÉxI“ÆN±ÉxM¿ÎbM¿ÎbF8ÈDDMÂ¼DMÂ¼Cø»dG§­žJ…©ÇG¦Dg›<Dg›<D3ŽBGâŽ.^Ùn[’q½S,yÎIk„‡GâŽ.D3ŽBEŽuÜC¢nHCZf®CZf®DtaœFö^¸b-McnOM<c¢Rc¢RU?_ßLcœgÁkxi­|\"iÔ…F}‘vµw€jJy	`vOO}wsMn5GÁn5GÁ€ëJá‡ÕR@‡ÕR@†?ZQ|jca{djWƒ@zû‚½‚½‚½‚½xqÄÿhÕ—\
a:£%\\¦Õ\\¦Õ_ª«ôa–·7e¯±‚fö«Ÿjõ™ sZ”µzŒœc|²¢Ê|²¢Ê}\"®!yÇ¤kç ëi*³Fc¼{dÇè~5²½€U¬C€U¬CGµð}\"Ì]UzÐ4N±ÉxUË~I“ÆM¿ÎbDMÂ¼DMÂ¼G§­žJ…©ÇDg›<GâŽ.Güš³Ik„‡D3ŽBEã}àEŽuÜCZf®Fö^¸S9[qb-Mcc¢Rc¢RLcœH­d`|}‘vµy	`vOO}n5GÁ‡ÕR@‚½‚½qÄÿlP“SsZ”µ|²¢ÊyÇ¤kç ëc¼auÀÊ{dÇè€U¬C}\"Ì]^\\ÊÍUzÐ4UË~G´Á×I“ÆDMÂ¼J…©ÇDg›<Güš³N«~žIk„‡Eã}àEã}àEŽuÜFö^¸S9[qc¢RH­d`‚©QOO}‡ÕR@sZ”µyÇ¤vÂŠwXÎå{dÇè}\"Ì]^\\ÊÍUË~ZDÉŸG§»ôG´Á×DMÂ¼J…©ÇGüš³Iü¢:L^!S9[qH­d`ƒ÷T¨‚©Q‡ÕR@sZ”µvÂŠt÷šûs÷Ð×wXÎå}\"Ì]^\\ÊÍZDÉŸ]ÅLK¯‰G§»ôDMÂ¼J…©ÇIü¢:LŸ¥`Fö^¸L^!H­d`‚ÐX	ƒ÷T¨‡ÕR@sZ”µt÷šûršs÷Ð×}\"Ì]uFÕYaÔ^\\ÊÍ]ÅLK¯‰DMÂ¼J…©ÇJ…©ÇLŸ¥`Pb¥fFö^¸H­d`GgÎ‚ÐX	‡ÕR@|jcajõ™ sZ”µršeÖÐÿs÷Ð×uFÕYaÔ]ÅL]Ù»ôNóªîK¯‰J…©ÇJ…©ÇPb¥fVÈ¤Eã}àFö^¸GgÎy	`v‚ÐX	|jcajõ™ ršm«.eÖÐÿuFÕYaÔaÔ]Ù»ô]5³¼W+ªPNóªîJ…©ÇEã}àGgÎG8m„y	`v|jcazûfYjõ™ m«.kç ëcaÏHeÖÐÿaÔW+ªPJ…©ÇVÈ¤Eã}àG8m„IX}\\y	`vzûfY{djWe¯±‚jõ™ kç ëbÌÓcaÏHaÔY³«’W+ªPVÈ¤N«~žEã}àIX}\\|y	`v{djWe¯±‚kç ëauÀÊa:ÆïbÌÓaÔ[³®Y³«’VÈ¤S,yÎN«~žIX}\\|{djW‚½‚½dg´e¯±‚auÀÊa:ÆïaÔ]5³¼^ÙnS,yÎIX}\\4€N|‚½‚½a–·7dg´auÀÊauÀÊa:Æï]5³¼^ÙnIX}\\V\
qÄ|¹ƒñ4€N‚½‚½\\¦Õa–·7auÀÊauÀÊ]5³¼[³®aNl‘^ÙnV\
qÄv§Šç|¹ƒñ‚½‚½\\¦ÕauÀÊ[³®aNl‘V\
qÄa[fÂv§Šç‚½‚½lP“S\\¦Õ[³®VÈ¤cZm¥aNl‘a[fÂp|Œjv§ŠçlP“S\\¦ÕVÈ¤]àŸve›pNcZm¥a[fÂm5ŒCp|ŒjlP“ShÕ—\
\\¦Õ]àŸve›pNa[fÂgÁkxjº‰ m5ŒClP“ShÕ—\
]àŸva4œÓfrÞe›pNgÁkxiÔ…Fjº‰ lP“SlP“ShÕ—\
a4œÓfs—frÞgÁkxlP“Sa4œÓeŽ”`fs—gÁkxiÔ…FiÔ…FlP“SeŽ”`iÔ…FeŽ”`fs—";
		-- Vyragosa
		[ 32630 ] = "S©\\[ôT9bœNbœNn¤Hen¾MàdR½]pYU¯`ƒU¯`ƒS@bL~d@G§n(IXu%IÇ~\000IÇ~\000NIyŒVzrhVzrh]¿iîaÊgfaÊgfefih1lh1liûpòj|Æ~\000wXy…o¾wïjîwïjîx	dþyxawâM¸n¾Màn¤Hen¤HewéHr[K…[K…†$NÙˆDRäˆDRä‡†W†®Zõ{Ójûƒq·ƒ¯{Ÿƒ¯{Ÿ„,bƒ,ƒaƒ,ƒa~ž‰­xr4iD—­d¨ŸHaª£Éaª£É_i¥m\\„§y\\„§y^\\©=`¬˜`¬˜a-±£b·Ûgf¬CižùkdšCkdšCo¤–_sÉ•YsÉ•Ywé—šzû}\"£n€Ä¬æ}‘®ÅlV¡jÇ¬æi™³êi™³êfÜ¹dc¼¥~¤³`}‘®Å€Ä¬æ€Ä¬æø±ñ·¶”·¶”\000ÉŸ}‘Í\000}‘Í\000y7ÓêuµÕýuµÕýeãÖÕa‰Ôµa‰Ôµ_\\Ðo^ÌËq^ÌËq[‹ÎòUêÐ×UêÐ×N.ÏO!ÊJÆ§O!ÊN.ÏN.ÏF¨ÈèD¼Ã`D¼Ã`Dg¼H®BJõªkG€¦§DÖ›àDÖ›àD¢ŽæHRŽÒ_Hn¸\\raSœzqIÛ…+HRŽÒD¢ŽæEýv€DnìCÊgRCÊgRDãb@Gf_\\bœNn¾MàdR½dR½U¯`ƒL~d@h1lj|ÆjD…é~\000wXwïjîyxa¾P wâM¸n¤Hen¤He[K…ˆDRäˆDRä†®Zõ|Ùd{Ójûƒ¯{Ÿƒ,ƒaƒ,ƒaxr4r3‘£iD—­aª£É\\„§y\\„§y`¬˜b·Ûf²&gf¬CkdšCsÉ•Yzû}\"£n}\"£n}‘®Åz6¥%lV¡i™³êc¼¥{ÓÈŒ~¤³`€Ä¬æ€Ä¬æ·¶”}‘Í\000UêÐ×O!ÊUðÌ\"JÆ§N.ÏD¼Ã`D¼Ã`H®BJõªkDÖ›àHRŽÒHl›WIÛ…+D¢ŽæFR~ƒEýv€CÊgRGf_\\S©\\bœNdR½dR½L~d@Ie€\r|¹~\000wXyxa¾P n¤HeˆDRäƒ,ƒar3‘£l¿“÷sÉ•Y}\"£nz6¥%lV¡c¼¥aåÁn{ÓÈŒ€Ä¬æ}‘Í\000^ÌËqUêÐ×UðÌ\"H$Â{JÆ§D¼Ã`JõªkDÖ›àHl›WOAIÛ…+FR~ƒFR~ƒEýv€Gf_\\S©\\dR½IeƒR@¾P ˆDRäsÉ•Yz6¥%w1ž.wÈÏ‰{ÓÈŒ}‘Í\000^ÌËqUðÌ\"Z³ÊCH¼˜H$Â{D¼Ã`JõªkHl›WJk¢ÝLq^ÅS©\\Ie„gULƒR@ˆDRäsÉ•Yw1ž.uf›ŸtgÑ{wÈÏ‰}‘Í\000^ÌËqZ³ÊC]}ÅðKx°-H¼˜D¼Ã`JõªkJk¢ÝM¦Gf_\\Lq^ÅIeƒ@X­„gULˆDRäsÉ•Yuf›Ÿruš¦tgÑ{}‘Í\000uµÕýa‰Ôµ^ÌËq]}ÅðKx°-D¼Ã`JõªkJõªkM¦PÑ¦\
Gf_\\IeG†hrƒ@X­ˆDRä|ÙdkdšCsÉ•Yruš¦fEÑ£tgÑ{uµÕýa‰Ôµ]}Åð^I¼˜Ob«’Kx°-JõªkJõªkPÑ¦\
W8¥%FR~ƒGf_\\G†hryxaƒ@X­|ÙdkdšCruš¦nÒfEÑ£uµÕýa‰Ôµa‰Ôµ^I¼˜]¥´`WšªôOb«’JõªkFR~ƒG†hrG§n(yxa|Ùd{jfýkdšCnÒlV¡cÐÏìfEÑ£a‰ÔµWšªôJõªkW8¥%FR~ƒG§n(IÇ~\000yxa{jfý{Ójûf²&kdšClV¡buÍvcÐÏìa‰ÔµZ#¬5WšªôW8¥%OAFR~ƒIÇ~\000€\r|¹yxa{Ójûf²&lV¡aåÁnaªÇ“buÍva‰Ôµ\\\"®¸Z#¬5W8¥%SœzqOAIÇ~\000€\r|¹{Ójûƒ,ƒadÖ´Âf²&aåÁnaªÇ“a‰Ôµ]¥´`_Hn¸SœzqIÇ~\000¤€ò€\r|¹ƒ,ƒab·ÛdÖ´ÂaåÁnaåÁnaªÇ“]¥´`_Hn¸IÇ~\000Vzrh}(„•¤€òƒ,ƒa\\„§yb·ÛaåÁnaåÁn]¥´`\\\"®¸a½m5_Hn¸Vzrhw‹‹}(„•ƒ,ƒa\\„§yaåÁn\\\"®¸a½m5VzrhaÊgfw‹‹ƒ,ƒal¿“÷\\„§y\\\"®¸W8¥%cÊnHa½m5aÊgfpëw‹‹l¿“÷\\„§yW8¥%^O f\
pòcÊnHaÊgfm¥Œæpël¿“÷iD—­\\„§y^O f\
pòaÊgfh1lk)ŠCm¥Œæl¿“÷iD—­^O a£wfsf\
pòh1ljD…ék)ŠCl¿“÷l¿“÷iD—­a£wfãŽ;fsh1ll¿“÷a£weý•fãŽ;h1ljD…éjD…él¿“÷eý•jD…éeý•fãŽ;";
	};
	[ 201 ] = { -- Un'Goro Crater
		-- Ravasaur Matriarch
		[ 6581 ] = "›…¤”¢Ýšç©—s©—s¬p—X°G›…°G›…²3¢&²G©­²G©­¬„µf©õµm¢Ý´¨Ÿò¾!›CÀë›CÀë—Î¿¾–¹î–¹î–Â²,›…¤”›…¤”©—s°G›…°G›…²G©­©õµm¤Ï°¢Ý´¨›CÀë›CÀë–¹î›…¤”°G›…©õµm§_±¤Ï°›CÀë›…¤”›…¤”°G›…§_±§_±¤Ï°›…¤”";
	};
	[ 40 ] = { -- Wetlands
		-- Razormaw Matriarch
		[ 1140 ] = "«„M¬˜J)°|G®°|G®´?IµÖLôµÖLôµöOì³T÷³T÷²gXr°'X“¯;Tg¬Pb«„M«„M°|G®µÖLôµÖLô³T÷°'X“¯;Tg«„MµÖLôµÖLô°'X“¯;Tg";
	};
	[ 467 ] = { -- Zangarmarsh
		-- Bog Lurker
		[ 18682 ] = "g$¨üeÂ¥Èe‡ oe‡ oh1™Qlw”9{”€‰‘n†§”Ž†§”Ž‡_š¹„ý¥„ý¥ƒÐ­ž‚¯‰‚¯‰—«¹¤Öl£nkô©¦j¬«Cj¬«Cg$¨üe‡ olw”9{”†§”Ž†§”Ž„ý¥‚¯‰l£nj¬«Ce‡ o†§”Ž‚¯‰¤ÖmVIl£ne‡ o†§”Ž¤Ö~\rŸAp\r™õmVIe‡ o†§”Ž~\rŸAzÇ›p\r™õe‡ olw”9lw”9†§”ŽzÇ›lw”9zÇ›p\r™õÏÿÃZÏƒ¾OÑu¼æÑu¼æ×“ÃMÜÊ¦ÜÊ¦àÖ“àAÜ<àAÜ<ÝæêxØèî\\Øèî\\ÖìÖsâMÔ÷×KÏÿÃZÑu¼æÑu¼æÜÊ¦àAÜ<àAÜ<Øèî\\ÖsâMÖsâMÔ÷×KÑu¼æÑu¼æàAÜ<ÖsâM5µ=ó:74@ª2‚@ª2‚Gï4êJ=7´J=7´K^;K?ØK?ØHRGsDJîDJî<ŸMÌ8M8M: EÝ?EF:A£: EÝ8M8M4{EY5µ=ó@ª2‚J=7´K?ØK?ØDJî8M8M?EFAòB×:A£8M5µ=óK?Ø8MAòB×<˜;~:A£5µ=óK?ØAòB×CM<j<˜;~5µ=ó@ª2‚@ª2‚K?ØCM<j@¾:D<˜;~@ª2‚@ª2‚CM<j@¾:D";
		-- Coilfang Emissary
		[ 18681 ] = "AUy*=²ao>i]5>i]5A\\VDn_!Dn_!FLxE¼{¹E¼{¹CT|cAUy*AUy*>i]5Dn_!Dn_!E¼{¹AUy*—´[ûšJX†£{]„£{]„¦Rb3¨Qi7¨Qi7§7p¤9uÉ¤9uÉ Gtˆ j#æe™Wbñ—“`—“`—´[û£{]„£{]„¨Qi7¤9uÉæe—“`£{]„£{]„¤9uÉ j#£{]„ j#æe²,¸™¶Rµm¹º¶ö¹º¶öºÀ¼<¸™¾¸™¾³t¿'±{¼¥±{¼¥²,¸™¹º¶ö¹º¶ö¸™¾±{¼¥¾¤ÇX½pÅ®¿;Âœ¿;ÂœÁGÂ¯ÀøÇ*¿;ÂœÀøÇ*¾¤ÇX¡×¨k¡¡‚¢¢ž\\¢¢ž\\¤Ö ½¥`¦l¥`¦l¨è¬Ù©²Ý©²Ý¦»µÈÒ¶šÒ¶š›à³mŸÒ®¡×¨k¢¢ž\\¥`¦l¥`¦l©²ÝÒ¶šÒ¶šŸÒ®¡×¨k¡×¨k¥`¦lÒ¶š¹…Ö®¹ÀÐh»ÓÍì»ÓÍì¾HÓ½„×Q½„×Q»)Øû¹…Ö®»ÓÍì½„×Q¹…Ö®µsÇâ´¨Å®·ÂM·ÂM¹…Ãˆ¸ÆK·ÂM¸ÆKµsÇâ";
		-- Marticar
		[ 18680 ] = "‰û)z’Æu8+îW€,…Mæ.M<.M<0¤Q‰0!\\/0!\\/.—`b-`¾)m«,s3*	w1ž æŠÀŽ¤ÀŽ¤QŽž‰û‰ûÆu8#œj+îW€.M<0!\\/)m«*	w1%?vYž ÀŽ¤‰û‰û#œj(´_!(´_!+îW€0!\\/(ühÁ)m«%?vY!ƒyrž ‰û(´_!0!\\/-`¾(ühÁ%?vY!ƒyr!ƒyr‰û(´_!(´_!-`¾(ühÁ(´_!(ühÁ!ƒyr]\"]‘b[R–h$P\000s÷P|y^KÍùKùKHS¯’VY’VYUYrŒ˜Zr\000Uru\\qi7]cecndMf®a×hDa×hD]ÅbM]\"]‘]\"]‘h$P\000nÌQ–s÷P|ùK’VY’VYŒ˜Zr\000Uecna×hD]\"]‘]\"]‘nÌQ–s÷P|s÷P|’VY\000Ui7]cecn]\"]‘]\"]‘s÷P|\000U\000Ui7]c]\"]‘¶Ütã°'cF°h^æ°h^æ´ðY™»„[=»„[=½\\`|½\\d¢ÁÞo—ËI€·Îùˆ­Îùˆ­Î\\Œ6É|É|Ä9Œ‘¹û{‹¹û{‹¶Ütã°h^æ°h^æ»„[=½\\d¢ÁÞo—Îùˆ­É|É|¹û{‹°h^æ°h^æ½\\d¢ÁÞo—°h^æÁÞo—É|";
	};
	[ 496 ] = { -- Zul'Drak
		-- Gondria
		[ 33776 ] = "›í—ü ËŸ\r›¬¦ï ÿgü¤µm« -t2 -t2 i¦ ÿgü®ÒÁ °ÊÁ[®¸ÍI®¸ÍI¬pÌžªÍÉ®¸ÍIªÍÉ®ÒÁ Ã•«íË­„ÊŸ²½ÊŸ²½Èr¶yÅý·ÎÅý·ÎÄ+»jÂn¸õÂn¸õÂT­ßÃ•«íÃ•«íÊŸ²½Åý·ÎÅý·ÎÂn¸õÃ•«í´2yk´gƒn°}Š°}Š° yx´2yk";
		-- Griegen
		[ 32471 ] = ")Î²M,­Å4{­(:J± E¢±G”´%G”´%G»ºçB »B »B&È@;ÊŸ@;ÊŸ5ÝÎª1åËw1åËw1½ÈX4¼Å?<¸¦-I¹*^¶Ü*^¶Ü)Î²M4{­(:J± G”´%B »1åËw4¼Å?7yÇ_<¸¦*^¶Ü4{­(4{­(:J± B »@;ÊŸ1åËw7yÇ_><º’<¸¦4{­(@;ÊŸ7yÇ_<„ÄÉ><º’4{­(B »B »@;ÊŸ<„ÄÉB »<„ÄÉ><º’>ÒŽ(A‰‡lC×†šC×†šGüŒ„Gö‘?'›6>w¡©;Ô£{;Ô£{62¡£5t—5t—7€™k<6˜>?.’½>ÒŽ(C×†šC×†šGö‘DÖ’Ã?'›6;Ô£{5t—?.’½C×†šDÖ’ÃDÖ’Ã?'›65t—<6˜>?.’½DÖ’ÃDÖ’Ã5t—<6˜>!u”¢!N£$ê‹6$ê‹6'¡ŒÌ*’•»*’•»)e˜#°˜	#°˜	!u”¢$ê‹6$ê‹6*’•»#°˜	";
		-- Terror Spinner
		[ 32475 ] = "ƒŽVƒaQ-Ž!PŽ!PŽUÖƒŽV˜#bÞ˜r]¿™èY>™èY>Ÿ\rWÈ ½\\Ú ½\\ÚIeF›e›e˜#bÞ™èY>™èY> ½\\Ú›e²þ6·3øº˜6ãº˜6ã»ô;³¼@4¹ÚCÊ¹­PAµ»Q·µ»Q·³mO}´?I´?²œ;)²þ6²þ6º˜6ã¼@4¹ÚCÊµ»Q·´?I´?²þ6¼@4¼@4¹ÚCÊ´?I¼@4´?I´?Í¤Q:ÏƒOóÓðU÷ÓðU÷ÔZrÍób©Íób©Í._ËÍ¤Q:ÓðU÷Íób©Í¤Q:Ã¶cÊÈŒfÈ snÈ snÁÞs×ÁˆgÈ snÁˆgÃ¶cÊ¸Î¦´¹À¡ÊÂê¡ÑÂê¡ÑÃ¶¥8¿–¯b¿–¯b¼Æ¯ß¸Î¦´Âê¡Ñ¿–¯b¸Î¦´";
		-- Zul'drak Sentinel
		[ 32447 ] = "/ÅÒ¯1:ÐhIÏòIÏòIµ¡L’µ»L’µ»L‹ÛjHïÛcI×­0ÿØ0/ÅÖÈ/ÅÖÈ/ÅÒ¯IÏòL’µ»HïÛcI×­I×­/ÅÖÈIÏòIÏòL’µ»I×­a£‡âf»ÒhÇ€An—Š)sÃŒÌrÊ‘uw8ž\rzži|¢×|¢×{/ªJx«¿oB³`…2Õý‚:Ú/‚:Ú/g°–eªûeªûe’Ti—8lç”ýi—8e’Te’Ta½Œa£‡âa£‡âhÇ€Ai¦…i¦…n—Š)rÊ‘uw8ž\r|¢×x«¿oB³`‚:Ú/eªûeªûi—8i¥Llç”ýe’Ta£‡âa£‡âi¦…rÊ‘utˆšáw8ž\rx«¿eªûi¥LkÓ¬oƒ•ãlç”ýa£‡âa£‡ârÊ‘utˆšátˆšáx«¿uðªoB³`eªûkÓ¬oƒ•ãa£‡âtˆšáoB³`kÓ¬oH¬‘tê¡øoƒ•ãtˆšáuðªoB³`oH¬‘tê¡øtˆšáuðªuðªoH¬‘t%¤ðuðªt%¤ðtê¡ø";
	};
};
