--[[

************************************************************************

deDE.lua

deDE localization strings for Collectinator

File date: 2010-03-30T00:31:02Z 
Project version: v1.0.4

Please update:
http://www.wowace.com/projects/collectinator/localization/deDE/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "deDE", false)

if not L then return end

L["About"] = "Über"
L["Achievement"] = "Erfolg"
L["ACHIEVEMENT_DESC"] = "Sammelobjekte, die Erfolge sind, sollen im Scan einbezogen werden."
L["ACQUIRETOOLTIPPOSITION_DESC"] = "Ändert die Position des Tooltips, der Informationen über die Quelle enthält."
L["Acquisition"] = "Quelle"
L["Adolescent Whelp"] = "Halbwüchsiger Welpe"
L["Alamma"] = true
L["Aldraan"] = true
L["Alexander Calder"] = true
L["ALL_FILTERED"] = "Deine Filter verhindern, dass Einträge angezeigt werden. Bitte ändere Deine Filtereinstellungen und versuche es erneut."
L["ALT_CLICK"] = "Alt-Klick zum Hinzufügen/Entfernen dieses Eintrages zu/von Deiner Ignoreliste."
L["Alt-Collections"] = "Alt-Sammlungen"
L["Apothecary Hummel"] = "Apotheker Hummel"
L["Artifact"] = "Artefakt"
L["Artifact_DESC"] = "Sammlerstücke mit artefaktischer Qualität sollen in den Scan eingeschlossen werden."
L["Auto Scan Map"] = "Karte automatisch scannen"
L["AUTOSCANMAP_DESC"] = " AUTOSCANMAP_DESC"
L["Babagaya Shadowcleft"] = "Babagaya Schattenkluft"
L["Bana Wildmane"] = "Bana Wildmähne"
L["BC_WOW_DESC"] = "Gegenstände aus The Burning Crusade"
L["Belbi Quikswitch"] = "Belbi Blitzknips"
L["Binding"] = "Bindung"
L["Blix Fixwidget"] = "Blix Fixtand"
L["Bloodsail Deckhand"] = "Deckmatrose der Blutsegelbukaniere"
L["Bloodsail Elder Magus"] = "Hochmagus der Blutsegelbukaniere"
L["Bloodsail Mage"] = "Magier der Blutsegelbukaniere"
L["Bloodsail Raider"] = "Räuber der Blutsegelbukaniere"
L["Bloodsail Sea Dog"] = "Seebär der Blutsegelbukaniere"
L["Bloodsail Swabby"] = "Deckhelfer der Blutsegelbukaniere"
L["Bloodsail Swashbuckler"] = "Schwadroneur der Blutsegelbukaniere"
L["Bloodsail Warlock"] = "Hexenmeister der Blutsegelbukaniere"
L["Blue Dragonspawn"] = "Blaudrachenbrut"
L["Blue Scalebane"] = "Blaue Bannschuppe"
L["BOA_DESC"] = "Accountgebundene Gegenstände in den Scan mit einbeziehen."
L["BOAFilter"] = "Accountgebunden"
L["BOE_DESC"] = "Beim Anlegen gebundene Gegenstände in den Scan mit einbeziehen."
L["BOEFilter"] = "Beim Anlegen gebunden"
L["Bogflare Needler"] = "Sumpflichtschwärmer"
L["BOP_DESC"] = "Beim Aufheben gebundene Gegenstände in den Scan mit einbeziehen."
L["BOPFilter"] = "Beim Aufheben gebunden"
L["Bottom"] = "Unterer Rand"
L["Breanni"] = true
L["Briarthorn"] = "Wilddornrose"
L["Brunn Flamebeard"] = "Brunn Flammenbart"
L["Burning Crusade"] = true
L["Celoenus"] = true
L["Cielstrasza"] = true
L["CLEAR_DESC"] = "Setz das Suchfeld zurück."
L["Clear Exclusion List"] = "Leert die Ausschlussliste"
L["CLEAR_EXCLUSION_LIST_DESC"] = "Entfernt alle Einträge aus der Ausschlußliste."
L["Clear Waypoints"] = "Karteneinträge entfernen"
L["CLEAR_WAYPOINTS_DESC"] = true
L["Clockwork Assistant"] = "Aufziehgehilfe"
L["Cloned Ooze"] = "Geklonter Brühschlammer"
L["CLOSE_DESC"] = "Schließt das Collectinator-Fenster"
L["COLLECTIBLE_EXCLUDED"] = "Gegenstand ist auf der Ausschlussliste"
L["Collectinator_ALLEXCLUDED"] = "Deine Ausschlussliste verhindert, dass Einträge angezeigt werden. Bitte ändere Deine Ausschlussliste und versuche es erneut."
L["Collectinator_ALLKNOWN"] = "Du kennst alles, es bleibt nichts mehr übrig zu sammeln."
L["Collectinator Documentation"] = "Collectinator-Dokumentation"
L["Collectinator_SEARCHFILTERED"] = "Deine Suche hatte keine Ergebnisse."
L["COLLECTOR_ED_DESC"] = "Sammelobjekte, die über die \"Collectors' Edition\" erhalten werden können, sollen in den Scan einbezogen werden."
L["Collectors' Edition"] = " Collectors' Edition"
L["Common"] = "Verbreitet"
L["Common_DESC"] = "Sammlerstücke mit verbreiteter Qualität sollen in den Scan eingeschlossen werden."
L["Common Issues"] = "Häufige Probleme"
L["COMMON_ISSUES_DESC"] = [=[Bitte prüfe diese häufigsten Probleme, bevor du einen Fehlerbericht schreibst.
1) Reittier/Haustier wird nicht angezeigt! - Prüfe deine Filtereinstellungen, um sicherzustellen, dass der Eintrag nicht gefiltert wird.]=]
L["CONTRACTALL"] = "- Alle"
L["CONTRACTALL_DESC"] = "Minimiert alle Einträge."
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Korporal Arthur Flew"
L["CRAFT_DESC"] = "Sammelobjekte, die durch eigene Herstellung erhalten werden können, sollen in den Scan einbezogen werden."
L["Crafted"] = "Hergestellt"
L["Crimson Whelp"] = "Purpurroter Welpe"
L["CTRL_CLICK"] = "Strg-Klick zum Einfügen dieses Eintrages als Link in den Chat."
L["CTRL_SHIFT_CLICK"] = "Strg-Umschalt-Klick zum Hinzufügen des Gegenstandes auf die Karte."
L["Dalaran Shield Guard"] = "Schildwache von Dalaran"
L["Dalaran Spellscribe"] = "Zauberschreiber von Dalaran"
L["Dalaran Summoner"] = "Beschwörer von Dalaran"
L["Dalaran Theurgist"] = "Theurg von Dalaran"
L["Dama Wildmane"] = "Dama Wildmähne"
L["Dame Evniki Kapsalis"] = true
L["Darahir"] = true
L["Dart"] = "Pfeil"
L["DB_LOAD_ERROR"] = [=[Fehler: Datenbank konnte nicht korrekt geladen werden.
Bitte beende WoW und lösche die Collectinator-Datenbankdatei (Collectinator.lua) in:
\\World of Warcraft\\WTF\\Account\\<Account Name>>\\SavedVariables\\]=]
L["Dealer Rashaad"] = "Händler Rashaad"
L["Defias Pirate"] = "Pirat der Defias"
L["Demisette Cloyce"] = true
L["Derrick Brindlebeard"] = "Derrick Scheckenbart"
L["Deviate Guardian"] = "Deviatwächter"
L["Deviate Ravager"] = "Deviatverheerer"
L["Devouring Ooze"] = "Verschlingender Brühschlammer"
L["Dhugru Gorelust"] = "Dhugru Blutgier"
L["Display"] = "Anzeige"
L["DISPLAY_EXCLUSION_DESC"] = "Zeigt Einträge in der Ausschlussliste an."
L["Display Exclusions"] = "Ausschlüsse anzeigen"
L["Display Options"] = "Anzeige-Einstellungen"
L["DISPLAY_OPTIONS_DESC"] = "Einstellungen für die Anzeige ändern."
L["DOC_DESC"] = "Dokumentation für Collectinator"
L["Documentation"] = "Dokumentation"
L["Donni Anthania"] = true
L["Doru Thunderhorn"] = "Doru Donnerhorn"
L["Draconic Magelord"] = "Drachischer Magierlord"
L["Draconic Mageweaver"] = "Drachischer Magiewirker"
L["Drake Dealer Hurlunk"] = "Drachenhändler Hurlunk"
L["Dread Commander Thalanor"] = "Schreckenskommandant Thalanor"
L["Dreaming Whelp"] = "Träumender Welpe"
L["Driz Tumblequick"] = "Driz Purzelfix"
L["Durgan Thunderbeak"] = "Durgan Donnerschnabel"
L["Eliza Killian"] = true
L["Epic"] = "Episch"
L["Epic_DESC"] = "Sammlerstücke mit epischer Qualität sollen in den Scan eingeschlossen werden."
L["EVENT_DESC"] = "Sammelobjekte, die bei besonderen Veranstaltungen (BlizzCon, WWI, etc.) erhalten werden können, sollen in den Scan einbezogen werden."
L["EXCLUDECOUNT_DESC"] = "Schließe ausgeschlossene Einträge bei der Zählung der gesamten Einträge ein."
L["Exclusion Issues"] = "Ausschlussprobleme"
L["EXCLUSION_ISSUES_DESC"] = "Um einen Eintrag zur Ausschlußliste (ignorieren) hinzuzufügen, im Scan-Fenster Alt + Klick auf den entsprechenden Eintrag durchführen. Um diesen Eintrag wieder herzustellen, die Optionen öffnen und \"Zeige ausgeschlossene\" auf AN umschalten. Dies wird im nächsten Scan alle Einträge anzeigen, die du bisher ausgeschlossen hattest. Danach wieder Alt + Klick auf den Eintrag durchführen, um diesen von der Ausschlußliste zu entfernen."
L["EXPANDALL"] = "+ Alle"
L["EXPANDALL_DESC"] = "Maximiert alle Einträge."
L["Faction"] = "Fraktion"
L["FACTION_DESC"] = "Horde- und Allianz-Gegenstände in den Scan mit einbeziehen."
L["Fedryen Swiftspear"] = "Fedryen Flinkspeer"
L["Filter"] = true
L["FILTER_CLOSE_DESC"] = "Fensteroberfläche für Filteroptionen schließen."
L["FILTERCOUNT_DESC"] = "Gefilterte Elemente als nicht vorhanden behandeln. Die Wahl dieser Option ändert die Anzahl der bekannten und unbekannten Sammelobjekte."
L["FILTERING_BC_DESC"] = "Konfiguration für bestimmte Rufbelohnungs-Einträge aus \"Burning Crusade\", die in den Scan einbezogen werden sollen."
L["FILTERING_BINDING_DESC"] = "Konfiguration bestimmter Bindungstypen, die in den Scan einbezogen werden sollen."
L["FILTERING_GENERAL_DESC"] = "Konfiguration weiterer, mehr allgemeinerer Filter-Typen."
L["FILTERING_MISC_DESC"] = "Konfiguration für verschiedene Optionen, die auch in den Darstellungsoptionen vorhanden sind."
L["FILTERING_OBTAIN_DESC"] = "Konfiguration für bestimmte Erarbeitungsmethoden, welche die Einträge benötigen, sollen in den Scan einbezogen werden."
L["FILTERING_OLDWORLD_DESC"] = "Konfiguration für bestimmte Rufbelohnungs-Einträge aus der \"alten Welt\", die in den Scan einbezogen werden sollen."
L["FILTERING_RARITY_DESC"] = "Konfiguration im Bezug auf welche Seltenheitstypen in den Scan eingeschlossen werden sollen."
L["FILTERING_REP_DESC"] = "Konfiguration für bestimmte Rufbelohnungs-Einträge, die in den Scan einbezogen werden sollen."
L["FILTERING_WOTLK_DESC"] = "Konfiguration für bestimmte Rufbelohnungs-Einträge aus \"Wrath of the Lich King\", die in den Scan einbezogen werden sollen."
L["FILTERKNOWNCOUNT_DESC"] = "Bezieht gefilterte Gegenstände, die bekannt sind, in die Zählung ein, aber behandelt unbekannte gefilterte Gegenstände als nicht vorhanden."
L["FILTER_OPEN_DESC"] = "Öffnet die Filter-Einstellungen."
L["Filters"] = "Filter"
L["Flamesnorting Whelp"] = "Flammenschnaubender Welpe"
L["Flesh Hunter"] = "Fleischjäger"
L["Flik"] = true
L["Font Size"] = "Schriftgröße"
L["FONT_SIZE_DESC"] = "Ändert die Schriftgröße."
L["Forest Frog"] = "Urwaldfrosch"
L["Freka Bloodaxe"] = "Freka Blutaxt"
L["Gaelden Hammersmith"] = "Gaelden Hammerschmied"
L["Game Commands"] = "Spiel-Befehle"
L["GAME_COMMANDS_DESC"] = [=[Befehlszeile:
Collectinator wurde vor kurzem geändert, so dass zum Ändern von Parametern eine GUI verwendet wird. Geben Sie /collectinator ein, um die GUI zu öffnen. Erlaubte Befehle sind:
- TBD

Maus-Klicks:
Collectinator verhält sich unterschiedlich, je nachdem welche Modifikationstasten Sie beim Klicken benutzen.

Scan-Schaltfläche:
Dies ist die Funktionalität, die auftritt, wenn Sie die Scan-Schaltfläche anklicken.

- Normaler Klick
  Führt einen Scan der aktuellen Fertigkeit durch, und zeigt dabei die Sammelobjekte in einem neuen Fenster an.
- SHIFT + Klick
  Generiert eine Textablage der aktuellen Fertigkeit im CSV-Format.
- Alt + Klick
  Entfernt alle Karteneintragungen auf der Weltkarte und auf der Minikarte, die von Collectinator generiert worden sind.

Einträge:
Dies ist die Funktionalität, die auftritt, wenn Sie einen Eintrag anklicken.

- Normaler Klick
  Erweitert oder vermindert die Informationen zum Erwerb des Eintrags.
- SHIFT + Klick
  Generiert einen Gegenstands-Link des Gegenstandes, in den der Eintrag verwandelt wird, in die Standard-Chat-Box.
- Strg + Klick
  Generiert einen Zauber-Link für den Eintrag, den Sie angeklickt haben.
- Alt + Klick
  Fügt einen Eintrag aus der Ausschluss-Liste hinzu oder entfernt diesen.
- Strg + SHIFT + Klick
  Fügt der Weltkarte oder Minikarte die Methoden des Erwerbs eines bestimmten Eintrags hinzu.]=]
L["Gargantuan Ooze"] = "Riesengroßer Brühschlammer"
L["Geen"] = true
L["General"] = "Allgemein"
L["General Options"] = "Allgemeine Einstellungen"
L["Gimrizz Shadowcog"] = "Gimrizz Schattenrad"
L["Glutinous Ooze"] = "Klebriger Brühschlammer"
L["Gregor MacVince"] = true
L["Grella"] = true
L["Grol'dar"] = true
L["Grunda Bronzewing"] = "Grunda Bronzeflügel"
L["Grunnda Wolfheart"] = "Grunnda Wolfsherz"
L["Gundrak Raptor"] = "Raptor von Gundrak"
L["Halpa"] = true
L["Harb Clawhoof"] = "Harb Klauenhuf"
L["Hide Pop-Up"] = "Pop-Up verbergen"
L["HIDEPOPUP_DESC"] = "Verhindert die Anzeige von Pop-Ups, die den Grund weshalb das Scan-Fenster leer ist, mitteilen."
L["Hiren Loresong"] = "Hiren Lehrensang"
L["Include Excluded"] = "Ausgeschlossene Einträge einbeziehen"
L["Include Filtered"] = "Gefilterte Einträge einbeziehen"
L["Include Known Filtered"] = "Bekannte, gefilterte Gegenstände einbeziehen"
L["Instance"] = "Instanz"
L["INSTANCE_DESC"] = "Sammelobjekte, die in (5er-) Instanzen erhalten werden können, sollen in den Scan einbezogen werden."
L["Irisee"] = true
L["Item"] = "Gegenstand"
L["Jekyll Flandring"] = true
L["Jepetto Joybuzz"] = "Jepetto Spaßbrumm"
L["Jeremiah Payson"] = true
L["Jilanne"] = true
L["Kaal Soulreaper"] = "Kaal Seelentod"
L["Kartosh"] = true
L["Katie Hunter"] = "Katie Waidmann"
L["Knight Dameron"] = "Ritter Dameron"
L["Known"] = "Bekannt"
L["KNOWN_DESC"] = "Alle bereits bekannten Gegenstände in den Scan mit einbeziehen."
L["Landro Longshot"] = "Landro Fernblick"
L["Large Vile Slime"] = "Großer böser Brühschleimer"
L["Larkin Thunderbrew"] = "Larkin Donnerbräu"
L["Left"] = "Linker Rand"
L["Legendary"] = "Legendär"
L["Legendary_DESC"] = "Sammlerstücke mit legendärer Qualität sollen in den Scan eingeschlossen werden."
L["Lelanai"] = true
L["Lich King"] = true
L["Lieutenant Karter"] = "Leutnant Karter"
L["Lillehoff"] = true
L["Lil Timmy"] = "Klein Timmy"
L["Living Decay"] = "Lebender Verfall"
L["LK_WOW_DESC"] = "Gegenstände aus Wrath of the Lich King."
L["Location"] = "Ort"
L["Luther Pickman"] = "Luther Pickmann"
L["Magus Tirth"] = true
L["Main Filter Options"] = "Haupt-Filter-Einstellungen"
L["MAINFILTER_OPTIONS_DESC"] = "Erlaubt die Angabe wie verschiedene Filter verarbeitet werden."
L["Main Options"] = "Haupt-Optionen"
L["MAIN_OPTIONS_DESC"] = "Haupt-Konfigurations-Optionen"
L["Map Issues"] = "Karten-Einstellungen"
L["MAP_ISSUES_DESC"] = "Collectinator stützt sich auf TomTom, um Icons und Karteneintragungen auf der Weltkarte und auf der Minikarte hinzuzufügen. Diese Vermerke können angepaßt werden, indem das Collectinator-Konfigurations-Menü aufgerufen und zu den Darstellungs-Optionen gescrollt wird. Wenn TomTom nicht installiert ist, wird gar nichts hinzugefügt. Das automatische Hinzufügen von Icons ist standardmäßig deaktiviert."
L["Map Options"] = "Karten-Optionen"
L["MAP_OPTIONS_DESC"] = "Erlaubt dir, die Art und Weise wie Collectinator in der Weltkarte und Minikarte integriert wird, zu verändern."
L["Maximillian Crowe"] = "Maximillian Raab"
L["Mei Francis"] = true
L["Merideth Carlson"] = true
L["Midsummer Merchant"] = "Sonnenwendhändler"
L["Midsummer Supplier"] = "Sonnenwendversorger"
L["Milli Featherwhistle"] = "Milli Federpfiff"
L["Mini Map"] = "Minikarte"
L["MINIMAP_DESC"] = true
L["Mirket"] = true
L["Misc"] = "Sonstiges"
L["Miscellaneous"] = "Sonstiges"
L["MISSING_LIBRARY"] = "%s fehlt. Addon kann nicht ausgeführt werden."
L["Mob Drop"] = "Mob-Drop"
L["MOB_DROP_DESC"] = "Sammelobjekte, die Mob-Drops sind, sollen in den Scan einbezogen werden."
L["Mor'vek"] = true
L["Mouse"] = "Maus"
L["Mycah"] = true
L["Name"] = true
L["Narkk"] = true
L["Noblegarden Merchant"] = "Nobelgartenhändler"
L["Noblegarden Vendor"] = "Nobelgartenverkäufer"
L["NO_DISPLAY"] = "Keine Einträge können angezeigt werden. Falls du diese Mitteilung erhältst, schreibe bitte ein Ticket auf http://www.wowace.com/projects/collectinator/tickets und führe bitte an, welche Filter du angewendet hast, was in deiner Ausschlußliste steht, welche Art von Scan durchgeführt wurde, sowie die Anzahl der bekannten/unbekannten Einträge."
L["NoItemLink"] = "Für diesen Gegenstand gibt es keinen Link oder er war nicht in Deinem Cache."
L["NOTSCANNED"] = "Dieses Sammelobjekt wurde noch nicht gescant. Bitte öffne das Interface und klicke auf Scan. Beachte, dass das Scannen von Reittieren bzw. Fahrzeugen und Haustieren gleichzeitig durchgeführt wird."
L["NOT_YET_SCANNED"] = "Noch nicht gescant!"
L["Obtain"] = "Quelle"
L["Obtained From"] = "Quelle"
L["Off"] = "Aus"
L["Ogunaro Wolfrunner"] = "Ogunaro Wolfsläufer"
L["Ok"] = true
L["Old World"] = "Alte Welt"
L["ORIGINAL_WOW_DESC"] = "Gegenstände aus Classic World of Warcraft."
L["Other Realms"] = "Andere Server"
L["Pol Amberstill"] = "Pol Bernruh"
L["Poor"] = "Schlecht"
L["Poor_DESC"] = "Sammlerstücke mit minderer Qualität sollen in den Scan eingeschlossen werden."
L["\"Pretty Boy\" Duncan"] = "Schönling Duncan"
L["Primal Ooze"] = "Urzeitbrühschlammer"
L["Profile"] = "Profil"
L["Profile Options"] = "Profil-Einstellungen"
L["Provisioner Nasela"] = "Versorgerin Nasela"
L["PVP"] = true
L["PVP_DESC"] = "Gegestände aus dem PVP in den Scan miteinbeziehen."
L["Quest"] = true
L["QUEST_DESC"] = "Gegenstände aus Quests in den Scan mit einbeziehen."
L["Raid"] = "Schlachtzug"
L["RAID_DESC"] = "Gegenstände aus Schlachtzügen in den Scan mit einbeziehen."
L["Raider Bork"] = "Räuber Bork"
L["Rare"] = "Rar"
L["Rare_DESC"] = "Sammlerstücke mit rarer Qualität sollen in den Scan eingeschlossen werden."
L["Rarity"] = "Seltenheit"
L["Ravasaur Matriarch"] = "Ravasaurusmatriarchin"
L["Ray'ma"] = true
L["Razormaw Matriarch"] = "Scharfzahnmatriarchin"
L["Razzashi Raptor"] = "Razzashiraptor"
L["Red Whelp"] = "Roter Welpe"
L["Removed from Game"] = "Aus dem Spiel entfernt"
L["Reporting Bugs"] = "Fehler melden"
L["REPORTING_BUGS_DESC"] = [=[Wenn Sie einen Fehler melden, stellen Sie bitte sicher, dass Sie folgendes tun:
1) Laden Sie die neueste Version herunter, diese ist erhältlich bei http://www.wowace.com/projects/collectinator/files/
2) Stellen Sie sicher, dass noch keine Fehlermeldung zu Ihrem Problem eingereicht wurde. Dies können Sie überprüfen auf http://www.wowace.com/projects/collectinator/tickets/
3) Lesen Sie die Dokumentation über Fehlerberichterstattung auf http://www.wowace.com/projects/collectinator/pages/feedback-and-bug-reporting/
4) Wenn Ihr Problem nicht aufgeführt ist, und Sie die neueste Version benutzen, überprüfen Sie Ihre Addon Einstellungen. Überprüfen Sie die Filter, die Profile, etc.
5) Sie haben einen Fehler gefunden, den niemand zuvor gemeldet hat. Erstellen Sie ein neues Ticket auf http://www.wowace.com/projects/collectinator/tickets/ mit einer das Problem beschreibenden Überschrift. Stellen Sie sicher, dass Sie die Fehlermeldung, die Sie erhalten haben, einbeziehen (nur die Fehlermeldung; ich benötige nicht eine Liste der Addons, die Sie verwenden.), der aktuelle Eintrag, den Sie bearbeitet haben, sowie jedwede andere Information, von der Sie denken, dass sie helfen könnte.
Wenn Sie einen Fehlerbericht erstatten, schließen Sie NICHT alle ihre AddOns von Swatter mit ein. Dies macht es nur schwer zu lesen. Wenn Sie eine gute Modifikation zum Melden von Fehlern haben möchten, besorgen Sie sich BugSack. Veröffentlichen Sie keine Fehler oder fehlende Gegenstände bei den Kommentaren, oder senden Sie mir diese über eine PM. Veröffentlichen Sie diese als ein Ticket, welches ich leicht verfolgen und über das ich Sie leicht ansprechen kann.]=]
L["REP_TEXT_DESC"] = [=[Hier linksklicken, um alle Ruf-Filter zu wählen.
Hier rechtsklicken, um all Ruf-Filter abzuwählen.]=]
L["Reputation"] = "Ruf"
L["Reset All Filters"] = "Alle Filter zurücksetzen"
L["RESET_DESC"] = "Alle Filter auf Standardwerte zurücksetzen."
L["RESET_WINDOW_DESC"] = "Setzt das GUI auf die Standard-Position zurück."
L["Reset Window Position"] = "Fensterposition zurücksetzen"
L["Retired"] = "Entfallen"
L["Richard Kerwin"] = true
L["Right"] = "Rechter Rand"
L["Rillie Spindlenut"] = "Rillie Spindelnuss"
L["Rivern Frostwind"] = true
L["Rook Hawkfist"] = "Rook Falkenfaust"
L["Rotting Sludge"] = "Faulender Schlamm"
L["Rupert Boch"] = "Ruper Boch"
L["Sairuk"] = true
L["Samamba"] = true
L["Sandahl"] = true
L["Scalding Whelp"] = "Brühender Welpe"
L["Scan"] = true
L["SCAN_COMPANIONS_DESC"] = [=[Scant das aktuell geöffnete Begleiter-Fenster.
SHIFT + Klick, um eine Zeichenkette zu generieren, die auf "Warcraft Pets" hochgeladen werden kann, um deine Sammlung zu aktualisieren.
Alt + SHIFT + Klick, um eine Textablage all deiner Sammelobjekte zu generieren.
Alt + Klick, um alle eingetragenen Standorte auf der Minikarte und auf der Weltkarte zu entfernen.]=]
L["SEARCH_BOX_DESC"] = "Suchbegriff eingeben."
L["SEARCH_DESC"] = "Filter zu Einträgen, die Text enthalten, nach links."
L["Searing Whelp"] = "Sengender Welpe"
L["SEASONAL_DESC"] = "Sammelobjekte, die während eines Weltereignisses erhalten werden können, in den Scan mit einbeziehen."
L["SHIFT_CLICK"] = "SHIFT + Klick, um den herstellbaren Artikel über diesen Link des Sammelobjektes in den Chat einzufügen."
L["Shylenai"] = true
L["Sixx"] = true
L["Sort"] = "Sortierung"
L["Sorting"] = "Sortierung"
L["SORTING_DESC"] = "Die Art und Weise ändern, in der die dargestellten Sammelobjekte sortiert werden."
L["Sorting Options"] = "Sortierungs-Einstellungen"
L["SORTING_OPTIONS_DESC"] = "Erlaubt die Anpassung der Art und Weise, wie die dargestellten Sammelobjekte sortiert werden."
L["Special Event"] = "Besonderes Ereignis"
L["SPECIFIC_REP_DESC"] = "Fraktion %s einbeziehen."
L["SPELLTOOLTIPPOSITION_DESC"] = "Ändert die Position des Tooltips mit den Sammel-Informationen."
L["Sprite Darter"] = "Grimmlingflitzer"
L["Stone Guard Mukar"] = "Steingardist Mutaha"
L["Store"] = "Blizzard Store"
L["STORE_DESC"] = "Sammelobjekte, die beim \"Blizzard Store\" erhalten werden können, sollen in den Scan einbezogen werden."
L["Strahad Farsan"] = true
L["Tainted Ooze"] = "Besudelter Brühschlammer"
L["Takk the Leaper"] = "Takk der Springer"
L["Talionia"] = true
L["Tanaika"] = true
L["TCG"] = "WoW Trading Card Game"
L["TCG_DESC"] = "Sammelobjekte, die über das \"World of Warcraft Trading Card Game\" erhalten werden können, sollen in den Scan einbezogen werden."
L["Text Dump"] = "Textablage"
L["TEXT_DUMP_DESC"] = "Zeigt alle Sammelobjekte in einem durch Kommata getrennten Format an, welches kopiert und bei einem anderen Client eingefügt werden kann."
L["Thanthaldis Snowgleam"] = "Thanthaldis Schneeglanz"
L["The Ongar"] = "Der Ongar"
L["Thistleheart"] = "Distelherz"
L["Time-Lost Proto Drake"] = "Zeitverlorener Protodrache"
L["Tohfo Skyhoof"] = "Tohfo Himmelshuf"
L["Tooltip (Acquire) Position"] = "Tooltip-Position (erarbeiten)"
L["Tooltip (Collectible) Position"] = "Tooltip-Position (sammelbar)"
L["Tooltip Options"] = "Tooltip-Einstellungen"
L["TOOLTIP_OPTIONS_DESC"] = "Hier kann angegeben werden, wie sich die Tooltips verhalten sollen. Der Erarbeitungs-Tooltip listet die verschiedenen Informationen auf, wie ein bestimmtes Sammelobjekt erhalten werden kann, während der Zauber-Tooltip die Informationen zum Sammelobjekt selbst auflistet."
L["Tooltip Scale"] = "Tooltip-Skalierung"
L["TOOLTIP_SCALE_DESC"] = "Ändert die Skalierung des Tooltip. Erlaubte Werte zwischen 0.5 und 1.5 (Standardwert: 0.9)."
L["Top"] = "Oberer Rand"
L["Torallius the Pack Handler"] = "Torallius der Herdentreiber"
L["Trader Narasu"] = "Händler Narasu"
L["Trellis Morningsun"] = "Trellis Morgensonne"
L["UI_SCALE_DESC"] = "Ändert die Skalierung der UI. Reicht von 0,5 bis 1,5 (1 ist standard)"
L["Unavailable"] = "Nicht verfügbar"
L["Uncommon"] = "Selten"
L["Uncommon_DESC"] = "Sammlerstücke mit seltener Qualität sollen in den Scan eingeschlossen werden."
L["Unger Statforth"] = "Unger Stattfort"
L["Unhandled Collectible"] = "Unbehandeltes Sammelobjekt"
L["Unknown"] = "Unbekannt"
L["UNKNOWN_DESC"] = "Alle unbekannten Sammelobjekte in den Scan einbeziehen."
L["Unknown Zone"] = "Unbekannte Zone"
L["Ursula Deline"] = true
L["Using Filters"] = "Benutze Filter"
L["USING_FILTERS_DESC"] = [=[Filter können an- und ausgeschaltet werden. Es gibt zwei Filter-Typen: einer, welcher verhindert, dass ein bestimmtes Sammelobjekt angezeigt wird; und einer, welcher verhindert, dass eine bestimmte Art von Erwerbsinformation angezeigt wird.
Beim zuerst genannten Filter, entsprechen diese den Eigenschaften des Sammelobjekts (z.B. Bindung). Wenn Sie Collectinator so umschalten, dass beim Aufheben gebundene Sammelobjekte nicht angezeigt werden sollen, dann werden beim Scan auch keine Sammelobjekte angezeigt, die beim Aufheben gebunden sind. Die zweite Art von Filter befasst sich mit Informationen zum Erwerb. Wenn ein Sammelobjekt als Mob-Drop erhältlich ist, oder auch bei einem Händler erworben werden kann, und sie schalten den Filter so um, dass jene Sammelobjekte, die beim Händler zu beschaffen sind, nicht angezeigt werden, wird dennoch das Sammelobjekt beim Scan angezeigt werden; jedoch werden dann die Informationen zum Händler verborgen. Der Grund hierfür ist, dass es noch eine weitere Möglichkeit gibt, dieses Sammelobjekt zu bekommen (Mob-Drop), also sollte es weiterhin beim Scan aufscheinen.
Bitte beachten Sie, dass die Tooltips immer die Methoden der gegnerischen Fraktion, ein Sammelobjekt zu erhalten, verbergen. Dies wurde getan, um Platz im Tooltipp zu sparen, da sie recht groß werden können.]=]
L["Vasarin Redmorn"] = "Vasarin Morgenröte"
L["Vendor"] = "Händler"
L["VENDOR_DESC"] = "Sammelobjekte, die beim Händler gekauft werden können, sollen in den Scan einbezogen werden."
L["Veron Amberstill"] = "Veron Bernruh"
L["Version"] = true
L["View Exclusion List"] = "Ausschlussliste anzeigen"
L["VIEW_EXCLUSION_LIST_DESC"] = "Gibt eine Liste von allen Einträgen auf der Ausschlussliste aus."
L["Vile Ooze"] = "Übler Brühschlammer"
L["Vile Slime"] = "Böser Brühschleimer"
L["Winaestra"] = true
L["World Drop"] = "Welt-Drop"
L["WORLD_DROP_DESC"] = "Sammelobjekte, die Welt-Drops sind, sollen in den Scan einbezogen werden."
L["WORLDMAP_DESC"] = true
L["Xan'tish"] = true
L["Yarlyn Amberstill"] = "Yarlyn Bernruh"
L["Zachariah Post"] = true
L["Zanien"] = true
L["Zevrost"] = true
L["Zjolnir"] = true
