--[[

************************************************************************

esES.lua

esES localization strings for Collectinator

File date: 2010-04-04T16:38:43Z 
Project version: v1.0.4

Please update:
http://www.wowace.com/projects/collectinator/localization/esES/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "esES", false)

if not L then return end

