--[[

************************************************************************

frFR.lua

frFR localization strings for Collectinator

File date: 2010-04-04T16:38:43Z 
Project version: v1.0.4

Please update:
http://www.wowace.com/projects/collectinator/localization/frFR/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "frFR", false)

if not L then return end

L["About"] = "À propos"
L["Achievement"] = "Haut fait"
L["ACHIEVEMENT_DESC"] = "Les objets collectionnables qui sont des Hauts-Faits seront inclus dans l'analyse."
L["ACQUIRETOOLTIPPOSITION_DESC"] = "Change la position de la bulle d'aide contenant les informations d'acquisition."
L["Acquisition"] = true
L["Adolescent Whelp"] = "Jeune dragonnet"
L["Alamma"] = true
L["Aldraan"] = true
L["Alexander Calder"] = true
L["ALL_FILTERED"] = "Vos filtres vous empêchent d'afficher un quelconque résultat. Veuillez changer les réglages de vos filtres et réessayez."
L["ALT_CLICK"] = "Alt-click pour ajouter/retirer cette entrée de votre liste d'objets ignorés"
L["Alt-Collections"] = "Collection des Alts"
L["Apothecary Hummel"] = "Apothicaire Hummel"
L["Artifact"] = "Artefact"
L["Artifact_DESC"] = "Intègre ou non les objets de collection avec une qualité artefact dans l'analyse."
L["Auto Scan Map"] = "Analyser automatiquement la carte"
L["AUTOSCANMAP_DESC"] = true
L["Babagaya Shadowcleft"] = "Babagaya Ombrefourchu"
L["Bana Wildmane"] = "Bana Crin-sauvage"
L["BC_WOW_DESC"] = "Objets de collections disponibles avec Burning Crusade."
L["Belbi Quikswitch"] = "Belbi Coupecircuit"
L["Binding"] = "Lien"
L["Blix Fixwidget"] = "Blix Réparouage"
L["Bloodsail Deckhand"] = "Matelot de la Voile sanglante"
L["Bloodsail Elder Magus"] = "Ancien magus de la Voile sanglante"
L["Bloodsail Mage"] = "Mage de la Voile sanglante"
L["Bloodsail Raider"] = "Ecumeur de la Voile sanglante"
L["Bloodsail Sea Dog"] = "Loup de mer de la Voile sanglante"
L["Bloodsail Swabby"] = "Mousse de la Voile sanglante"
L["Bloodsail Swashbuckler"] = "Bretteur de la Voile sanglante"
L["Bloodsail Warlock"] = "Démoniste de la Voile sanglante"
L["Blue Dragonspawn"] = "Draconide bleu"
L["Blue Scalebane"] = "Plaiedécaille bleu"
L["BOA_DESC"] = "Intègre ou non les entrées qui sont des objets liés au compte dans l'analyse."
L["BOAFilter"] = "Lié au compte"
L["BOE_DESC"] = "Intègre ou non les entrées qui sont des objets liés quand équipés dans l'analyse."
L["BOEFilter"] = "Lié quand équipé"
L["Bogflare Needler"] = "Piqueur Tourbembrase"
L["BOP_DESC"] = "Intègre ou non les entrées qui sont des objets liés quand ramassés dans l'analyse."
L["BOPFilter"] = "Lié quand ramassé"
L["Bottom"] = "Bas"
L["Breanni"] = true
L["Briarthorn"] = "Eglantine"
L["Brunn Flamebeard"] = "Brunn Flammebarbe"
L["Burning Crusade"] = true
L["Celoenus"] = true
L["Cielstrasza"] = true
L["CLEAR_DESC"] = "Efface le contenu de la boîte de recherche."
L["Clear Exclusion List"] = "Effacer la liste des exclus"
L["CLEAR_EXCLUSION_LIST_DESC"] = "Enlève toutes les entrées de la liste des exclus."
L["Clear Waypoints"] = "Effacer les points"
L["CLEAR_WAYPOINTS_DESC"] = true
L["Clockwork Assistant"] = "Assistant mécanique"
L["Cloned Ooze"] = "Limon cloné"
L["CLOSE_DESC"] = "Ferme la fenêtre de Collectinator."
L["COLLECTIBLE_EXCLUDED"] = "L'objet de collection est dans la liste d'exclusions."
L["Collectinator_ALLEXCLUDED"] = "Vos exclusions empêchent actuellement quoique ce soit d'être affiché. Veuillez changer vos exclusions et essayez à nouveau."
L["Collectinator_ALLKNOWN"] = "Vous connaissez toutes les entrées, il n'y a plus rien que vous ne puissiez collectionner."
L["Collectinator Documentation"] = "Doc. de Collectinator"
L["Collectinator_SEARCHFILTERED"] = "Votre recherche n'a produit aucun résultat."
L["COLLECTOR_ED_DESC"] = "Intègre ou non les objets de collection provenant des éditions collector dans l'analyse."
L["Collectors' Edition"] = "Éditions collector"
L["Common"] = "Classique"
L["Common_DESC"] = "Intègre ou non les objets de collection avec une qualité classique dans l'analyse."
L["Common Issues"] = "Problèmes récurrents"
L["COMMON_ISSUES_DESC"] = [=[Jetez un coup d'oeil à ces problèmes récurrents avant d'effectuer un rapport de bogue.
1) Une monture/un familier bien spécifique ne s'affiche pas ! - Vérifiez vos paramètres de filtrage afin d'être sûr que l'entrée en question n'a pas été filtré.]=]
L["CONTRACTALL"] = "- Ts"
L["CONTRACTALL_DESC"] = "Minimise toutes les entrées listées ci-dessous."
L["Coreiel"] = true
L["Corporal Arthur Flew"] = "Caporal Arthur Flew"
L["CRAFT_DESC"] = "Intègre ou non les objets de collection qu'il faut fabriquer dans l'analyse."
L["Crafted"] = "Fabriqués"
L["Crimson Whelp"] = "Dragonnet cramoisi"
L["CTRL_CLICK"] = "Ctrl-Clic gauche pour ajouter le lien de cette entrée dans la fenêtre de discussion."
L["CTRL_SHIFT_CLICK"] = "Ctrl-Shift-Clic gauche pour ajouter l'objet sur la carte et la minicarte."
L["Dalaran Shield Guard"] = "Garde du bouclier de Dalaran"
L["Dalaran Spellscribe"] = "Copiste de Dalaran"
L["Dalaran Summoner"] = "Invocateur de Dalaran"
L["Dalaran Theurgist"] = "Théurge de Dalaran"
L["Dama Wildmane"] = "Dama Crin-sauvage"
L["Dame Evniki Kapsalis"] = true
L["Darahir"] = true
L["Dart"] = "Flèche"
L["DB_LOAD_ERROR"] = [=[Erreur : la base de données ne s'est pas correctement chargée.
Veuillez quitter WoW et supprimer la base de données de Collectinator (Collectinator.lua) qui se trouve dans :
\\World of Warcraft\\WTF\\Account\\<Nom du compte>\\SavedVariables\\]=]
L["Dealer Rashaad"] = "Camelot Rashaad"
L["Defias Pirate"] = "Pirate défias"
L["Demisette Cloyce"] = true
L["Derrick Brindlebeard"] = "Derrick Piquebarbe"
L["Deviate Guardian"] = "Gardien déviant"
L["Deviate Ravager"] = "Ravageur déviant"
L["Devouring Ooze"] = "Limon dévorant"
L["Dhugru Gorelust"] = "Dhugru Soif-de-carnage"
L["Display"] = "Affichage"
L["DISPLAY_EXCLUSION_DESC"] = "Affiche les entrées qui se trouvent dans la liste des exclus."
L["Display Exclusions"] = "Afficher les exclus"
L["Display Options"] = "Options d'affichage"
L["DISPLAY_OPTIONS_DESC"] = "Vous permet de personnaliser la façon dont le GUI se comporte."
L["DOC_DESC"] = "Documentation pour Collectinator"
L["Documentation"] = true
L["Donni Anthania"] = true
L["Doru Thunderhorn"] = "Doru Corne-tonnerre"
L["Draconic Magelord"] = "Seigneur-mage draconique"
L["Draconic Mageweaver"] = "Tisse-magie draconique"
L["Drake Dealer Hurlunk"] = "Camelot de drake Hurlunk"
L["Dread Commander Thalanor"] = "Commandant de l'effroi Thalanor"
L["Dreaming Whelp"] = "Dragonnet rêveur"
L["Driz Tumblequick"] = "Driz Voltevive"
L["Durgan Thunderbeak"] = "Durgan Tonnebec"
L["Eliza Killian"] = true
L["Epic"] = "Epique"
L["Epic_DESC"] = "Intègre ou non les objets de collection avec une qualité épique dans l'analyse."
L["EVENT_DESC"] = "Les objets collectionnables provenant d'événements spéciaux (WWI, BlizCon, etc.) seront inclus dans l'analyse."
L["EXCLUDECOUNT_DESC"] = "Intègre ou non les entrées exclues dans le compte total des entrées."
L["Exclusion Issues"] = "Problèmes d'exclusion"
L["EXCLUSION_ISSUES_DESC"] = "Pour ajouter une entrée dans la liste des exclus (autrement dit, des ignorés), faites tout simplement la combinaison Alt-clic gauche sur cette entrée dans la fenêtre d'analyse. Pour récupérer cette entrée, ouvrez les options et cochez la case \"Afficher les exclus\". Cela aura pour effet d'afficher toutes les entrées que vous avez exclus après votre prochaine analyse. Une fois que vous avez fait cela, faites à nouveau Alt-clic gauche sur l'entrée pour l'enlever de la liste des exclus."
L["EXPANDALL"] = "+ Ts"
L["EXPANDALL_DESC"] = "Étend toutes les entrées listées ci-dessous."
L["Faction"] = true
L["FACTION_DESC"] = "Intègre ou non les objets de collection des deux factions dans l'analyse."
L["Fedryen Swiftspear"] = "Fedryen Vivelance"
L["Filter"] = "Filtre"
L["FILTER_CLOSE_DESC"] = "Ferme le panneau d'options des filtres"
L["FILTERCOUNT_DESC"] = "Intègre ou non les entrées filtrées dans le compte total des entrées."
L["FILTERING_BC_DESC"] = "Configuration des récompenses de réputation de Burning Crusade à intégrer dans l'analyse."
L["FILTERING_BINDING_DESC"] = "Configuration des types de liens à intégrer dans l'analyse."
L["FILTERING_GENERAL_DESC"] = "Configuration de plusieurs autres types de filtres généraux."
L["FILTERING_MISC_DESC"] = "Configuration des options diverses qui sont également présentes dans les options d'affichage."
L["FILTERING_OBTAIN_DESC"] = "Configuration des méthodes d'obtention à intégrer dans l'analyse."
L["FILTERING_OLDWORLD_DESC"] = "Configuration des récompenses de réputation de l'ancien monde à intégrer dans l'analyse."
L["FILTERING_RARITY_DESC"] = "Configuration pour laquelle les types de qualités sont inclus dans l'analyse."
L["FILTERING_REP_DESC"] = "Configuration des récompenses de réputation à intégrer dans l'analyse."
L["FILTERING_WOTLK_DESC"] = "Configuration des récompenses de réputation de Wrath of the Lich King à intégrer dans l'analyse."
L["FILTERKNOWNCOUNT_DESC"] = "Intègre les objets filtrés connus dans le compte, mais traite les objets filtrés inconnus comme non-existants."
L["FILTER_OPEN_DESC"] = "Ouvre le panneau d'options des filtres"
L["Filters"] = "Filtres"
L["Flamesnorting Whelp"] = "Dragonnet crache-flammes"
L["Flesh Hunter"] = "Chasse-chair"
L["Flik"] = true
L["Font Size"] = "Taille des polices"
L["FONT_SIZE_DESC"] = "Change la taille des polices."
L["Forest Frog"] = "Grenouille forestière"
L["Freka Bloodaxe"] = "Freka Hache-sanglante"
L["Gaelden Hammersmith"] = "Gaelden Forgemartel"
L["Game Commands"] = "Commandes en jeu"
L["Gargantuan Ooze"] = "Limon gargantuesque"
L["Geen"] = true
L["General"] = "Général"
L["General Options"] = "Options générales"
L["Gimrizz Shadowcog"] = "Gimrizz Sombrouage"
L["Glutinous Ooze"] = "Limon gluant"
L["Gregor MacVince"] = true
L["Grella"] = true
L["Grol'dar"] = true
L["Grunda Bronzewing"] = "Grunda Aile-de-Bronze"
L["Grunnda Wolfheart"] = "Grunnda Coeur-de-loup"
L["Gundrak Raptor"] = "Raptor de Gundrak"
L["Halpa"] = true
L["Harb Clawhoof"] = "Harb Sabot-griffu"
L["Hide Pop-Up"] = "Cacher pop-ups"
L["HIDEPOPUP_DESC"] = "Empêche l'affichage des pop-ups indiquant pourquoi la fenêtre d'analyse est vide. Ces pop-ups seront toujours affichées la tout première fois après qu'une nouvelle version de l'addon a été installée."
L["Hiren Loresong"] = "Hiren Chanterite"
L["Include Excluded"] = "Intégrer les exclus"
L["Include Filtered"] = "Intégrer les filtrés"
L["Include Known Filtered"] = "Intégrer les connus filtrés"
L["Instance"] = true
L["INSTANCE_DESC"] = "Intègre ou non les objets de collections récupérables dans les instances à 5 dans l'analyse."
L["Irisee"] = true
L["Item"] = "Objet"
L["Jekyll Flandring"] = true
L["Jepetto Joybuzz"] = "Jepetto Mizanjoie"
L["Jeremiah Payson"] = true
L["Jilanne"] = true
L["Kaal Soulreaper"] = "Kaal Fauche-l'âme"
L["Kartosh"] = " Kartosh"
L["Katie Hunter"] = true
L["Knight Dameron"] = "Chevalier Dameron"
L["Known"] = "Connus"
L["KNOWN_DESC"] = "Intègre tous les objets de collection connus dans l'analyse."
L["Landro Longshot"] = "Landro Tirauloin"
L["Large Vile Slime"] = "Grande gelée maléfique"
L["Larkin Thunderbrew"] = "Larkin Tonnebière"
L["Left"] = "Gauche"
L["Legendary"] = "Légendaire"
L["Legendary_DESC"] = "Intègre ou non les objets de collection avec une qualité légendaire dans l'analyse."
L["Lelanai"] = true
L["Lich King"] = true
L["Lieutenant Karter"] = true
L["Lillehoff"] = true
L["Lil Timmy"] = "Jeune Timmy"
L["Living Decay"] = "Pourriture vivante"
L["LK_WOW_DESC"] = "Les objets de collection disponibles avec Wrath of the Lich King."
L["Location"] = "Emplacement"
L["Luther Pickman"] = true
L["Magus Tirth"] = true
L["Main Filter Options"] = "Options principales des filtres"
L["MAINFILTER_OPTIONS_DESC"] = "Vous permet de spécifier comment les différents filtres sont gérés."
L["Main Options"] = "Options principales"
L["MAIN_OPTIONS_DESC"] = "Options principales de configuration"
L["Map Issues"] = "Problèmes de carte"
L["MAP_ISSUES_DESC"] = "Collectionator se réfère à TomTom pour ajouter ses icônes et ses points de navigation à la carte du monde et à la minicarte. Vous pouvez personnaliser ces icônes/points en vous rendant dans le menu de configuration de Collectionator, partie options d'affichage. Si TomTom n'est pas installé, rien ne sera ajouté. L'ajout automatique d'icônes est désactivé par défaut."
L["Map Options"] = "Options de la carte"
L["MAP_OPTIONS_DESC"] = "Vous permet de changer la façon dont Collectinator s'intègre avec la carte du monde et la minicarte."
L["Maximillian Crowe"] = true
L["Mei Francis"] = true
L["Merideth Carlson"] = true
L["Midsummer Merchant"] = "Marchand du solstice"
L["Midsummer Supplier"] = "Fournisseur du solstice"
L["Milli Featherwhistle"] = "Milli Siffleplume"
L["Mini Map"] = "Minicarte"
L["MINIMAP_DESC"] = true
L["Mirket"] = true
L["Misc"] = "Divers"
L["Miscellaneous"] = "Divers"
L["MISSING_LIBRARY"] = "%s est manquant. L'addon ne peut se lancer."
L["Mob Drop"] = "Butin de monstre"
L["MOB_DROP_DESC"] = "Intègre ou non les objets de collection trouvés comme butin sur les montres dans l'analyse."
L["Mor'vek"] = true
L["Mouse"] = "Souris"
L["Mycah"] = true
L["Name"] = "Nom"
L["Narkk"] = true
L["Noblegarden Merchant"] = "Marchand du Jardin des nobles"
L["Noblegarden Vendor"] = "Vendeur du Jardin des nobles"
L["NO_DISPLAY"] = "Aucune entrée à afficher. Si vous obtenez ce message, veuillez envoyer un ticket à l'adresse http://www.wowace.com/projects/collectinator/tickets en indiquant les filtres que vous avez activés, le contenu de votre liste des exclus, le type d'analyse effectuée et le nombre d'entrées connues/inconnues."
L["NoItemLink"] = "Cet objet n'a pas de lien ou n'est pas encore de votre cache."
L["NOTSCANNED"] = "Les familiers/montures n'ont pas encore été scannées. SVP ouvrez l'interface et appuyez sur Analyser. L'analyse des familiers/montures sont faites en même temps."
L["NOT_YET_SCANNED"] = "Pas encore analysé !"
L["Obtain"] = "Obtention"
L["Obtained From"] = "Moyen(s) d'obtention"
L["Off"] = true
L["Ogunaro Wolfrunner"] = "Ogunaro Mène-loup"
L["Ok"] = true
L["Old World"] = "Ancien monde"
L["ORIGINAL_WOW_DESC"] = "Objets de collections disponibles avec le jeu original."
L["Other Realms"] = "Autres royaumes"
L["Pol Amberstill"] = "Pol Distillambre"
L["Poor"] = "Médiocre"
L["Poor_DESC"] = "Intègre ou non les objets de collection avec une qualité médiocre dans l'analyse."
L["\"Pretty Boy\" Duncan"] = "Duncan « le Beau garçon »"
L["Primal Ooze"] = "Limon primitif"
L["Profile"] = "Profil"
L["Profile Options"] = "Options du profil"
L["Provisioner Nasela"] = "Approvisionneur Nasela"
L["PVP"] = "JcJ"
L["PVP_DESC"] = "Intègre ou non les objets de collection obtenus en JcJ dans l'analyse."
L["Quest"] = "Quête"
L["QUEST_DESC"] = "Les objets collectionnables obtenus en récompenses de quêtes seront inclus dans l'analyse."
L["Raid"] = true
L["RAID_DESC"] = "Les objets collectionnables obtenus en raid (ex: Cœur de Magma, Caverne de Sanctuaire du Serpent, etc.) seront inclus dans l'analyse."
L["Raider Bork"] = "Ecumeur Bork"
L["Rare"] = true
L["Rare_DESC"] = "Intègre ou non les objets de collection avec une qualité rare dans l'analyse."
L["Rarity"] = "Qualité"
L["Ravasaur Matriarch"] = "Matriarche ravasaure"
L["Ray'ma"] = true
L["Razormaw Matriarch"] = "Matriarche tranchegueules"
L["Razzashi Raptor"] = "Raptor Razzashi"
L["Red Whelp"] = "Dragonnet rouge"
L["Removed from Game"] = "Enlevé du jeu"
L["Reporting Bugs"] = "Rapport de bugs"
L["REPORTING_BUGS_DESC"] = [=[Lors du signalement d'un bogue, veuillez effectuer les actions suivantes :
1) Téléchargez la dernière version, disponible sur http://www.wowace.com/projects/collectinator/files/
2) Assurez-vous qu'il n'y a pas déjà un signalement de bogue pour votre problème. Vous pouvez vérifier cela à l'adresse  http://www.wowace.com/projects/collectinator/tickets/
3) Lisez la documentation du signalement de bogue à l'adresse http://www.wowace.com/projects/collectinator/pages/feedback-and-bug-reporting/
4) Si votre problème n'est pas cité et que vous utilisez la dernière version, vérifiez les paramètres de votre addon : filtres, profils, etc.
5) Vous avez trouvé un bogue  que personne n'a signalé auparavant. Créez un nouveau ticket à l'adresse http://www.wowace.com/projects/collectinator/tickets/ avec comme sujet une courte description du problème. Dans le ticket, n'oubliez pas d'indiquer le message d'erreur que vous avez reçu (juste le message d'erreur, pas besoin de la liste des addons que vous utilisez), l'entrée sur laquelle vous étiez et tout autre information qui pourrait nous aider selon vous.
Lors du signalement d'un bogue, n'indiquez PAS tous les addons que vous avez. Cela rend juste le ticket plus difficile à lire. Si vous voulez un bon addon de signalement de bogue, téléchargez BugSack. Ne signalez pas les erreurs/objets manquants dans les commentaires, et ne me les envoyer pas par messagerie privée. Ouvrez un ticket, ce qui permet de le suivre et de le résoudre facilement.]=]
L["REP_TEXT_DESC"] = [=[Clic-gauche pour sélectionner tous les filtres de réputation.
Clic-droit pour dé-sélectionner tous les filtres de réputation.]=]
L["Reputation"] = "Réputation"
L["Reset All Filters"] = "Réinit. tous les filtres"
L["RESET_DESC"] = "Réinit.des filtres."
L["RESET_WINDOW_DESC"] = "Place l'UI à sa position d'origine"
L["Reset Window Position"] = "Réinit. la position de la fenêtre"
L["Retired"] = "Enlevés"
L["Richard Kerwin"] = true
L["Right"] = "Droite"
L["Rillie Spindlenut"] = "Rillie Fuseboulon"
L["Rivern Frostwind"] = "Rivern Givrevent"
L["Rook Hawkfist"] = "Freux Poing-faucon"
L["Rotting Sludge"] = "Vase pourrissante"
L["Rupert Boch"] = true
L["Sairuk"] = true
L["Samamba"] = true
L["Sandahl"] = true
L["Scalding Whelp"] = "Dragonnet flamboyant"
L["Scan"] = "Analyser"
L["SCAN_COMPANIONS_DESC"] = [=[Analyse la fenêtre actuellement ouverte.
Shift-clic gauche pour générer un string qui peut être envoyé à Warcraft Pets pour mettre à jour votre collection.
Alt-Shift-clic gauche pour générer un text dump des objets de collection que vous possédez.
Alt-clic gauche pour enlever tous les points de navigation de la minicarte et de la carte du monde.]=]
L["SEARCH_BOX_DESC"] = "Entrer le texte à trouver"
L["SEARCH_DESC"] = "Filtre toutes les entrées ne contenant pas le texte de gauche."
L["Searing Whelp"] = "Dragonnet incendiaire"
L["SEASONAL_DESC"] = "Les objets collectionnables obtenables lors d'événements mondiaux seront inclus dans l'analyse."
L["SHIFT_CLICK"] = "Shift-Clic pour ajouter l'article fabriqué par le lien d'objet de collection vers votre fenêtre de discussion."
L["Shylenai"] = true
L["Sixx"] = true
L["Sort"] = "Trier"
L["Sorting"] = "Tri"
L["SORTING_DESC"] = "Change la façon dont les objets de collection sont triés."
L["Sorting Options"] = "Options du tri"
L["SORTING_OPTIONS_DESC"] = "Vous permet de personnaliser la façon dont les objets de collection sont triés."
L["Special Event"] = "Évènements spéciaux"
L["SPECIFIC_REP_DESC"] = "Intègre ou non la faction %s."
L["SPELLTOOLTIPPOSITION_DESC"] = "Change la position de la bulle d'aide affichant les informations sur les objets collectionnables."
L["Sprite Darter"] = "Fée fléchetteuse"
L["Stone Guard Mukar"] = "Garde de pierre Mukar"
L["Store"] = "La boutique Blizzard"
L["STORE_DESC"] = "Intègre ou non les objets de collection provenant de la boutique Blizzard dans l'analyse."
L["Strahad Farsan"] = true
L["Tainted Ooze"] = "Limon corrompu"
L["Takk the Leaper"] = "Takk le Bondisseur"
L["Talionia"] = true
L["Tanaika"] = true
L["TCG"] = "WoW Trading Card Game"
L["TCG_DESC"] = "Intègre ou non les objets de collection provenant du jeu de cartes à collectionner World of Warcraft dans l'analyse."
L["Text Dump"] = true
L["TEXT_DUMP_DESC"] = "Affiche tous les objets de collection dans un format de valeurs séparées par une virgule qui  peut être copié et coller dans un autre client."
L["Thanthaldis Snowgleam"] = "Thanthaldis Luireneige"
L["The Ongar"] = "L'Ongar"
L["Thistleheart"] = "Coeurdechardon"
L["Time-Lost Proto Drake"] = "Proto-drake perdu dans le temps"
L["Tohfo Skyhoof"] = "Tohfo Sabot-du-ciel"
L["Tooltip (Acquire) Position"] = "Position de la bulle d'acquisition"
L["Tooltip (Collectible) Position"] = "Position de la bulle de l'objet"
L["Tooltip Options"] = "Options de la bulle d'aide"
L["TOOLTIP_OPTIONS_DESC"] = "Vous permet de définit la façon dont les bulles d'aide se comportent. La bulle d'aide d'acquisition affiche les différentes informations sur la façon d'obtenir l'objet de collection, tandis que la bulle d'aide du sort affiche les informations concernant l'objet de collection en lui-même."
L["Tooltip Scale"] = "Échelle de la bulle d'aide"
L["TOOLTIP_SCALE_DESC"] = "Change l'échelle de la bulle d'aide. De 0.5 à 1.5 (1 par défaut)"
L["Top"] = "Haut"
L["Torallius the Pack Handler"] = "Torallius le Pâtre"
L["Trader Narasu"] = "Marchand Nasaru"
L["Trellis Morningsun"] = "Trellis Solmatin"
L["UI_SCALE_DESC"] = "Change l'échelle de l'interface. Réglable de 0.5 à 1.5 (1 par défaut)"
L["Unavailable"] = "Indisponible"
L["Uncommon"] = "Bonne"
L["Uncommon_DESC"] = "Intègre ou non les objets de collection avec une qualité bonne dans l'analyse."
L["Unger Statforth"] = true
L["Unhandled Collectible"] = "Objet de collection non géré"
L["Unknown"] = "Inconnu"
L["UNKNOWN_DESC"] = "Inclure tous les objets collectionnables inconnus dans l'analyse."
L["Unknown Zone"] = "Zone inconnue"
L["Ursula Deline"] = true
L["Using Filters"] = "Utilisation des filtres"
L["USING_FILTERS_DESC"] = [=[Les filtres peuvent être activés/désactivés. Il y a deux types de filtres: le premier évite de montrer tous les compagnons, le second permet de choisir les catégories à ne pas afficher.
Avec le premiers type de filtres les propriétés des objets sont examinées (p.ex liés). Si vous choisissez de ne pas faite afficher les LqR, aucun objet LqR ne sera affiché. Le second type examine la base de données acquise en jeu. Si un compagnon est lootable par un mob, et vendu par un pnj, si vous choisissez de désactiver les vendeurs, seul les vendeurs seront désactivés mais le compagnon sera toujours affiché. La raison est qu'il existe une façon de looter le mob dans la base de données.
Veuillez noter que l'add-on cachera toujours la façon dont la faction adverse peux récupérer un compagnon, ceci pour que la taille de la bulle d'aide ne soit pas trop grande.]=]
L["Vasarin Redmorn"] = "Vasarin Rougematin"
L["Vendor"] = "Vendeur"
L["VENDOR_DESC"] = "Les objets collectionnables pouvant être achetés seront inclus dans l'analyse."
L["Veron Amberstill"] = "Veron Distillambre"
L["Version"] = true
L["View Exclusion List"] = "Voir liste des exclus"
L["VIEW_EXCLUSION_LIST_DESC"] = "Affiche une liste de toutes les entrées contenues dans la liste des exclus."
L["Vile Ooze"] = "Vil limon"
L["Vile Slime"] = "Gelée maléfique"
L["Winaestra"] = true
L["World Drop"] = "Butin mondial"
L["WORLD_DROP_DESC"] = "Les objets collectionnables (de butin mondial) seront inclus dans l'analyse."
L["WORLDMAP_DESC"] = true
L["Xan'tish"] = true
L["Yarlyn Amberstill"] = "Yarlyn Distillambre"
L["Zachariah Post"] = true
L["Zanien"] = true
L["Zevrost"] = true
L["Zjolnir"] = true
