--[[

************************************************************************

zhCN.lua

zhCN localization strings for Collectinator

File date: 2010-04-04T16:38:43Z 
Project version: v1.0.4

Please update:
http://www.wowace.com/projects/collectinator/localization/zhCN/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "zhCN", false)

if not L then return end

L["About"] = "关于"
L["Achievement"] = "成就"
L["ACHIEVEMENT_DESC"] = "扫描包含成就获取收藏品。"
L["ACQUIRETOOLTIPPOSITION_DESC"] = "更改包含获取信息提示的位置。"
L["Acquisition"] = "获得"
L["Adolescent Whelp"] = "翠绿幼龙"
L["Alamma"] = "奥拉玛"
L["Aldraan"] = "阿尔德兰"
L["Alexander Calder"] = "亚历山大·考德尔"
L["ALL_FILTERED"] = "过滤器目前阻止任何条目的显示。请更改过滤器设置，然后再试一次。"
L["ALT_CLICK"] = "Alt+点击添加/移除此项到忽略列表。"
L["Alt-Collections"] = "Alt+收集"
L["Apothecary Hummel"] = true -- Needs review
L["Artifact"] = "帐号绑定"
L["Artifact_DESC"] = "扫描包含帐号绑定品质收藏品。"
L["Auto Scan Map"] = "自动扫描地图"
L["AUTOSCANMAP_DESC"] = true -- Needs review
L["Babagaya Shadowcleft"] = "巴巴加亚·影隙"
L["Bana Wildmane"] = true -- Needs review
L["BC_WOW_DESC"] = "可在燃烧的远征获得。"
L["Belbi Quikswitch"] = "贝尔比"
L["Binding"] = "绑定"
L["Blix Fixwidget"] = "布利克斯·菲克维特"
L["Bloodsail Deckhand"] = "血帆桨手"
L["Bloodsail Elder Magus"] = "血帆大法师"
L["Bloodsail Mage"] = "血帆法师"
L["Bloodsail Raider"] = "血帆袭击者"
L["Bloodsail Sea Dog"] = "血帆水手"
L["Bloodsail Swabby"] = "血帆水兵"
L["Bloodsail Swashbuckler"] = "血帆流氓"
L["Bloodsail Warlock"] = "血帆术士"
L["Blue Dragonspawn"] = "蓝色龙人"
L["Blue Scalebane"] = "蓝色刃鳞龙人"
L["BOA_DESC"] = "扫描包含帐号绑定项物品。"
L["BOAFilter"] = "帐号绑定项"
L["BOE_DESC"] = "扫描包含装备绑定项物品。"
L["BOEFilter"] = "装备绑定项"
L["Bogflare Needler"] = "水光针刺者"
L["BOP_DESC"] = "扫描包含拾取绑定项物品。"
L["BOPFilter"] = "拾取绑定项"
L["Bottom"] = "按钮"
L["Breanni"] = "布琳妮"
L["Briarthorn"] = "布瑞尔索恩"
L["Brunn Flamebeard"] = "拉瑟尔·火须"
L["Burning Crusade"] = "燃烧的远征"
L["Celoenus"] = "塞罗努斯"
L["Cielstrasza"] = "希尔丝塔萨"
L["CLEAR_DESC"] = "清除扫描文本框。"
L["Clear Exclusion List"] = "清除排除列表"
L["CLEAR_EXCLUSION_LIST_DESC"] = "移除排除列表的所有项。"
L["Clear Waypoints"] = "清除路径点"
L["CLEAR_WAYPOINTS_DESC"] = true -- Needs review
L["Clockwork Assistant"] = "发条助手"
L["Cloned Ooze"] = "克隆软泥怪"
L["CLOSE_DESC"] = "关闭 Collectinator 窗口。"
L["COLLECTIBLE_EXCLUDED"] = "已排除收藏品列表"
L["Collectinator_ALLEXCLUDED"] = "排除目前阻止任何条目的显示。请更改排除设置，然后再试一次。"
L["Collectinator_ALLKNOWN"] = "你已经获得了所有项，这里没有什么你继续可收集的。"
L["Collectinator Documentation"] = "Collectinator 文档"
L["Collectinator_SEARCHFILTERED"] = "扫描没有结果。"
L["COLLECTOR_ED_DESC"] = "扫描包含典藏版获得收藏品。"
L["Collectors' Edition"] = "典藏版"
L["Common"] = "普通"
L["Common_DESC"] = "扫描包含普通品质收藏品。"
L["Common Issues"] = "常见问题"
L["COMMON_ISSUES_DESC"] = [=[在提交错误报告之前请参阅这些常见问题。
1) 坐骑/宠物不能被显示！ - 点选过滤去设置确认该项没有被过滤。]=]
L["CONTRACTALL"] = "-全部"
L["CONTRACTALL_DESC"] = "最小化全部列出项。"
L["Coreiel"] = "克蕾伊尔"
L["Corporal Arthur Flew"] = "下士亚瑟·弗卢"
L["CRAFT_DESC"] = "扫描包含制造获得收藏品。"
L["Crafted"] = "已制造"
L["Crimson Whelp"] = "深红雏龙"
L["CTRL_CLICK"] = "Ctrl+点击添加此项链接到聊天。"
L["CTRL_SHIFT_CLICK"] = "Ctrl+Shift+点击添加物品到地图和迷你地图。"
L["Dalaran Shield Guard"] = "达拉然持盾守卫"
L["Dalaran Spellscribe"] = "达拉然书记员"
L["Dalaran Summoner"] = "达拉然召唤师"
L["Dalaran Theurgist"] = "达拉然法师"
L["Dama Wildmane"] = "达玛·蛮鬃"
L["Dame Evniki Kapsalis"] = true -- Needs review
L["Darahir"] = "达拉希尔"
L["Dart"] = "达尔特"
L["DB_LOAD_ERROR"] = [=[错误：数据库未正确加载。
请退出魔兽世界并删除 Collectinator 数据库文件（Collectinator.lua）在：
\\World of Warcraft\\WTF\\Account\\<角色名称>>\\SavedVariables\\]=]
L["Dealer Rashaad"] = "商人拉沙德"
L["Defias Pirate"] = "迪菲亚海盗"
L["Demisette Cloyce"] = "德米赛特·克劳斯"
L["Derrick Brindlebeard"] = "德里克·斑须"
L["Deviate Guardian"] = "变异守护者"
L["Deviate Ravager"] = "变异破坏者"
L["Devouring Ooze"] = "吞噬淤泥怪"
L["Dhugru Gorelust"] = "杜格鲁·血怒"
L["Display"] = "显示"
L["DISPLAY_EXCLUSION_DESC"] = "显示排除列表项。"
L["Display Exclusions"] = "显示排除"
L["Display Options"] = "显示选项"
L["DISPLAY_OPTIONS_DESC"] = "允许自定义图形用户界面行为。"
L["DOC_DESC"] = "Collectinator 的文档"
L["Documentation"] = "文档"
L["Donni Anthania"] = "冬妮·安萨妮娅"
L["Doru Thunderhorn"] = "杜尔鲁·雷角"
L["Draconic Magelord"] = "龙人大法师"
L["Draconic Mageweaver"] = "龙人施法者"
L["Drake Dealer Hurlunk"] = "霍尔伦克"
L["Dread Commander Thalanor"] = "恐怖指挥官萨拉诺尔"
L["Dreaming Whelp"] = "睡梦雏龙"
L["Driz Tumblequick"] = "德利兹·塔波奎克"
L["Durgan Thunderbeak"] = true -- Needs review
L["Eliza Killian"] = "伊莉莎·基连"
L["Epic"] = "史诗"
L["Epic_DESC"] = "扫描包含史诗品质收藏品。"
L["EVENT_DESC"] = "扫描包含特殊事件（暴雪嘉年华，暴雪全球邀请赛等）获取收藏品。"
L["EXCLUDECOUNT_DESC"] = "包括总项目数的排除项。"
L["Exclusion Issues"] = "排除问题"
L["EXCLUSION_ISSUES_DESC"] = "如果想添加项到排除（忽略）列表，只需在扫描窗口 Alt+点击它。想让它回来，打开选项设置勾选“显示排除”。这将在下次扫描显示所有已排除项。在这之后，再次 Alt+点击此项从排除列表移除。"
L["EXPANDALL"] = "+全部"
L["EXPANDALL_DESC"] = "展开全部项列表。"
L["Faction"] = "阵营"
L["FACTION_DESC"] = "扫描包含联盟与部落双方阵营收藏品。"
L["Fedryen Swiftspear"] = "芬德雷·迅矛"
L["Filter"] = "过滤器"
L["FILTER_CLOSE_DESC"] = "关闭过滤器选项面板。"
L["FILTERCOUNT_DESC"] = "视为不存在的筛选项目。选择该选项将更改已知和未知的收藏品数量。"
L["FILTERING_BC_DESC"] = "配置扫描包含燃烧的远征声望奖励项。"
L["FILTERING_BINDING_DESC"] = "配置扫描包含绑定类型项。"
L["FILTERING_GENERAL_DESC"] = "配置多种过滤器类型。"
L["FILTERING_MISC_DESC"] = "配置扫描包含其它选项。"
L["FILTERING_OBTAIN_DESC"] = "配置扫描包含获取方式项。"
L["FILTERING_OLDWORLD_DESC"] = "配置扫描包含经典旧世声望奖励项。"
L["FILTERING_RARITY_DESC"] = "配置扫描包含的品质类型。"
L["FILTERING_REP_DESC"] = "配置扫描包含声望奖励项。"
L["FILTERING_WOTLK_DESC"] = "配置扫描包含巫妖王之怒声望奖励项。"
L["FILTERKNOWNCOUNT_DESC"] = "包含已知的项目的已过滤物品，但对未知的过滤物品设为不存在。"
L["FILTER_OPEN_DESC"] = "打开过滤器选项面板。"
L["Filters"] = "过滤器"
L["Flamesnorting Whelp"] = "喷火雏龙"
L["Flesh Hunter"] = "血肉猎手"
L["Flik"] = "弗里克"
L["Font Size"] = "字体大小"
L["FONT_SIZE_DESC"] = "更改字体大小。"
L["Forest Frog"] = "森林蛙"
L["Freka Bloodaxe"] = "弗蕾卡·血斧"
L["Gaelden Hammersmith"] = "盖尔丁"
L["Game Commands"] = "游戏命令"
L["GAME_COMMANDS_DESC"] = [=[命令行：
新的 Collectinator 现已使用用户图形界面更改参数。输入 /collectinator 打开图形用户界面。可用命令有：
- TBD

点击：
Collectinator 会有所不同，这取决于使用修改为何键点击。

扫描按钮：
当点击扫描按钮时产生的效果。

- 点击
  在新窗口当前商业技能进行扫描并显示收藏品。
- Shift+点击
  生成当前商业技能 CSV 格式文本转储。
- Alt+点击
  在世界地图和迷你地图移除所有 Collectinator 路径点。

项目：
当点击一项时产生的效果。

- 点击
  展开或收起该项获取信息。
- Shift+点击
  生成一个该项物品链接，可以输入到默认聊天窗口。
- Ctrl+点击
  生成一个点击该项的法术链接。
- Alt+点击
  从排除列表添加或移除一项。
- Ctrl-Shift Click
  Adds the specific entry acquire methods to the World Map and Mini-map.]=]
L["Gargantuan Ooze"] = "巨大的软泥怪"
L["Geen"] = "吉恩"
L["General"] = "常规"
L["General Options"] = "常规选项"
L["Gimrizz Shadowcog"] = "吉姆瑞兹·黑轮"
L["Glutinous Ooze"] = "粘稠的软泥怪"
L["Gregor MacVince"] = "格瑞戈·玛克温斯"
L["Grella"] = "格蕾拉"
L["Grol'dar"] = "格罗达尔"
L["Grunda Bronzewing"] = true -- Needs review
L["Grunnda Wolfheart"] = "格伦达·狼心"
L["Gundrak Raptor"] = "古达克迅猛龙"
L["Halpa"] = "哈尔帕"
L["Harb Clawhoof"] = "哈布·爪蹄"
L["Hide Pop-Up"] = "隐藏弹出提示"
L["HIDEPOPUP_DESC"] = "阻止弹出窗口通知为什么扫描显示窗口是空的。每次新版本添加后将会始终显示弹出窗口。"
L["Hiren Loresong"] = true -- Needs review
L["Include Excluded"] = "包含排除"
L["Include Filtered"] = "包含已过滤"
L["Include Known Filtered"] = "包含已知过滤"
L["Instance"] = "副本"
L["INSTANCE_DESC"] = "扫描包含副本（5人）获得收藏品。"
L["Irisee"] = "艾蕾希"
L["Item"] = "物品"
L["Jekyll Flandring"] = "耶克里·弗兰迪"
L["Jepetto Joybuzz"] = "耶比托·乔巴斯"
L["Jeremiah Payson"] = "杰雷米亚·派森"
L["Jilanne"] = "基尔兰"
L["Kaal Soulreaper"] = "卡尔·噬灵"
L["Kartosh"] = "卡托什"
L["Katie Hunter"] = "凯蒂·亨特"
L["Knight Dameron"] = true -- Needs review
L["Known"] = "已知"
L["KNOWN_DESC"] = "扫描包含全部已知收藏品。"
L["Landro Longshot"] = "兰德鲁·郎绍特"
L["Large Vile Slime"] = "可憎的大软泥怪"
L["Larkin Thunderbrew"] = "拉尔金·雷酒"
L["Left"] = "左侧"
L["Legendary"] = "传说"
L["Legendary_DESC"] = "扫描包含传说品质收藏品。"
L["Lelanai"] = "莱兰奈"
L["Lich King"] = "巫妖王之怒"
L["Lieutenant Karter"] = "卡特尔中尉"
L["Lillehoff"] = "李奥霍夫"
L["Lil Timmy"] = "利尔·迪米"
L["Living Decay"] = "腐朽软泥怪"
L["LK_WOW_DESC"] = "巫妖王之怒可用收藏品。"
L["Location"] = "位置"
L["Luther Pickman"] = "卢瑟·匹克曼"
L["Magus Tirth"] = "大法师提尔斯"
L["Main Filter Options"] = "主过滤器选项"
L["MAINFILTER_OPTIONS_DESC"] = "允许指定不同的过滤器是如何处理。"
L["Main Options"] = "主选项"
L["MAIN_OPTIONS_DESC"] = "主配置选项"
L["Map Issues"] = "地图问题"
L["MAP_ISSUES_DESC"] = "Collectinator 依靠 TomTom 类插件添加图标和路径点到世界地图和迷你地图。可以自定义这些通过 Collectinator 配置菜单和滚动显示这些选项。如果您没有 TomTom 类插件，将没有任何添加。自动加入的图标默认禁用。"
L["Map Options"] = "地图选项"
L["MAP_OPTIONS_DESC"] = "允许更改 Collectinator 嵌到世界地图和迷你地图之中。"
L["Maximillian Crowe"] = "玛克西米利安·克洛文"
L["Mei Francis"] = "梅尔·弗兰希斯"
L["Merideth Carlson"] = "梅丽德丝·卡尔森"
L["Midsummer Merchant"] = "仲夏商人"
L["Midsummer Supplier"] = "仲夏补给商"
L["Milli Featherwhistle"] = "米利·羽哨"
L["Mini Map"] = "迷你地图"
L["MINIMAP_DESC"] = true -- Needs review
L["Mirket"] = "米尔科特"
L["Misc"] = "其它"
L["Miscellaneous"] = "其它"
L["MISSING_LIBRARY"] = "%s缺失。插件不能运行。"
L["Mob Drop"] = "小怪掉落"
L["MOB_DROP_DESC"] = "扫描包含小怪掉落收藏品。"
L["Mor'vek"] = "莫维克"
L["Mouse"] = "鼠标"
L["Mycah"] = "麦卡"
L["Name"] = "名称"
L["Narkk"] = "纳尔克"
L["Noblegarden Merchant"] = "复活节商人"
L["Noblegarden Vendor"] = "复活节小贩"
L["NO_DISPLAY"] = "没有项目显示。如果您收到此消息，请提交一份 Ticket 到 http://www.wowace.com/projects/collectinator/tickets 说明使用了什么过滤器，什么东西在排除列表中，何种类型扫描完成以及已知/未知项的数目。"
L["NoItemLink"] = "此物品没有物品链接或它未在缓存中。"
L["NOTSCANNED"] = "尚未扫描此收藏拼。请打开这个的插件并扫描一下。注意，坐骑/宠物扫描是在同一时间完成。"
L["NOT_YET_SCANNED"] = "还未扫描！"
L["Obtain"] = "获得"
L["Obtained From"] = "从…获得"
L["Off"] = "关闭"
L["Ogunaro Wolfrunner"] = "奥古纳罗"
L["Ok"] = "确定"
L["Old World"] = "经典旧世"
L["ORIGINAL_WOW_DESC"] = "经典旧世可用收藏品。"
L["Other Realms"] = "其它服务器"
L["Pol Amberstill"] = "波尔·冻石"
L["Poor"] = "粗糙"
L["Poor_DESC"] = "扫描包含粗糙品质收藏品。"
L["\"Pretty Boy\" Duncan"] = "帅小伙子邓肯"
L["Primal Ooze"] = "原生软泥怪"
L["Profile"] = "配置文件"
L["Profile Options"] = "配置文件选项"
L["Provisioner Nasela"] = "补给官纳瑟拉"
L["PVP"] = "PvP"
L["PVP_DESC"] = "扫描包含 PvP 获得收藏品。"
L["Quest"] = "任务"
L["QUEST_DESC"] = "扫描包含任务奖励获得收藏品。"
L["Raid"] = "团队"
L["RAID_DESC"] = "扫描包含团队（例如：熔火之心，毒蛇神殿等。）获得收藏品。"
L["Raider Bork"] = "狼骑兵波尔克"
L["Rare"] = "精良"
L["Rare_DESC"] = "扫描包含精良品质收藏品。"
L["Rarity"] = "品质"
L["Ravasaur Matriarch"] = "暴掠龙女王"
L["Ray'ma"] = "莱玛"
L["Razormaw Matriarch"] = "刺喉雌龙"
L["Razzashi Raptor"] = "拉扎什迅猛龙"
L["Red Whelp"] = "红色雏龙"
L["Removed from Game"] = "游戏中已移除"
L["Reporting Bugs"] = "报告错误"
L["REPORTING_BUGS_DESC"] = [=[当报告错误，请确保执行下列操作：
1)下载最新版本，可从 http://www.wowace.com/projects/collectinator/files/ 获得。
2) 确保那里没有与所已提交问题相同的错误报告。可以检查这些在 http://www.wowace.com/projects/collectinator/tickets/
3) 读取错误报告文件资料 http://www.wowace.com/projects/collectinator/pages/feedback-and-bug-reporting/
4) 如果您的问题未列出，并且您使用的是最新版本验证您的插件设置。验证过滤器，等。
5) 你已经找到了，没有人曾报告过错误。创建一个新的 Ticket 在 http://www.wowace.com/projects/collectinator/tickets/ 的描述性标题这个问题。在 Ticket 上必包含的收到的错误信息（只是错误信息，我不需要的插件使用列表），你操作的项及任何其他信息，你认为可能有帮助。
当张贴错误报告时，请*不要*包含错误记录插件所提供的所有信息。这只会让人难以理解。如果希望提交一个好的错误报告，请使用 BugSack。请不要贴出错误或缺失物品，或者通过 PM 发送给我。以 Ticket 方式贴出可以轻松的处理和找到。”]=]
L["REP_TEXT_DESC"] = [=[点击这里选择全部声望过滤器。
右击这里取消全部声望过滤器。]=]
L["Reputation"] = "声望"
L["Reset All Filters"] = "重置所有过滤器"
L["RESET_DESC"] = "重置所有过滤器为默认值。"
L["RESET_WINDOW_DESC"] = "重置图形用户界面默认位置。"
L["Reset Window Position"] = "重置窗口位置"
L["Retired"] = "已移除"
L["Richard Kerwin"] = "理查德·科尔文"
L["Right"] = "右侧"
L["Rillie Spindlenut"] = "莉蕾·转轴"
L["Rivern Frostwind"] = "雷沃·霜翼"
L["Rook Hawkfist"] = "鲁克·鹰爪"
L["Rotting Sludge"] = "腐烂淤泥怪"
L["Rupert Boch"] = "鲁伯特·鲍什"
L["Sairuk"] = "塞鲁克"
L["Samamba"] = "萨玛巴"
L["Sandahl"] = "山达尔"
L["Scalding Whelp"] = "滚烫的雏龙"
L["Scan"] = "扫描"
L["SCAN_COMPANIONS_DESC"] = [=[扫描当前打开窗口。
Shift+点击生成收藏品文本转储。
Alt+点击在迷你地图和世界地图删除所有路径点。]=]
L["SEARCH_BOX_DESC"] = "输入文本查询。"
L["SEARCH_DESC"] = "在左侧包含过滤器项。"
L["Searing Whelp"] = "灼热雏龙"
L["SEASONAL_DESC"] = "扫描包含世界事件获得收藏品。"
L["SHIFT_CLICK"] = "Shift+点击添加制作的物品链接到聊天。"
L["Shylenai"] = "夏琳奈尔"
L["Sixx"] = "希克斯"
L["Sort"] = "排序"
L["Sorting"] = "排序中"
L["SORTING_DESC"] = "更改收藏品显示排序方式。"
L["Sorting Options"] = "排序选项"
L["SORTING_OPTIONS_DESC"] = "允许自定义收藏品显示排序方式。"
L["Special Event"] = "特殊事件"
L["SPECIFIC_REP_DESC"] = "包含%s阵营。"
L["SPELLTOOLTIPPOSITION_DESC"] = "更改收藏品信息提示位置。"
L["Sprite Darter"] = "小精龙"
L["Stone Guard Mukar"] = "石头守卫穆卡尔"
L["Store"] = "暴雪商店"
L["STORE_DESC"] = "扫描包含暴雪商店获得收藏品。"
L["Strahad Farsan"] = "斯坦哈德·法尔杉"
L["Tainted Ooze"] = "被污染的软泥怪"
L["Takk the Leaper"] = "“跳跃者”塔克"
L["Talionia"] = "塔莱尼娅"
L["Tanaika"] = "塔奈卡"
L["TCG"] = "集换卡"
L["TCG_DESC"] = "收集扫描包含魔兽世界集换卡获得收藏品。"
L["Text Dump"] = "文本转储"
L["TEXT_DUMP_DESC"] = "显示全部使用逗号分隔收藏品并可以复制和粘贴到其它地方。"
L["Thanthaldis Snowgleam"] = "塔萨迪斯·雪光"
L["The Ongar"] = "欧加尔"
L["Thistleheart"] = "瑟斯哈特"
L["Time-Lost Proto Drake"] = "迷失始祖幼龙"
L["Tohfo Skyhoof"] = true -- Needs review
L["Tooltip (Acquire) Position"] = "提示（获得）位置"
L["Tooltip (Collectible) Position"] = "提示（收藏品）位置"
L["Tooltip Options"] = "提示选项"
L["TOOLTIP_OPTIONS_DESC"] = "允许制定提示的行为。获取提示列出了如何获取收藏品的不同的信息，而法术提示列出了收藏品信息。"
L["Tooltip Scale"] = "提示缩放"
L["TOOLTIP_SCALE_DESC"] = "更改提示缩放。范围从.5到1.9（.9为默认）"
L["Top"] = "顶部"
L["Torallius the Pack Handler"] = "象群管理者妥拉留斯"
L["Trader Narasu"] = "商人纳拉苏"
L["Trellis Morningsun"] = "特雷利斯·晨日"
L["UI_SCALE_DESC"] = "更改用户界面缩放。范围从.5到1.5（1为默认）"
L["Unavailable"] = "不可用"
L["Uncommon"] = "优秀"
L["Uncommon_DESC"] = "扫描包含优秀品质收藏品。"
L["Unger Statforth"] = "安格尔·斯塔特弗斯"
L["Unhandled Collectible"] = "未得到收藏品"
L["Unknown"] = "未知"
L["UNKNOWN_DESC"] = "扫描包含全部未知收藏品。"
L["Unknown Zone"] = "未知区域"
L["Ursula Deline"] = "厄苏拉·德林"
L["Using Filters"] = "使用过滤器"
L["USING_FILTERS_DESC"] = [=[可以切换开启或关闭过滤器。有两种类型的过滤器：一种是将无法显示所有的收藏品了，另一种防止显示特定类型获取信息。
第一种类型的过滤器，这些匹配的收藏品（如：绑定）。如果您切换 Collectinator 不显示拾取绑定收藏品，扫描中拾取绑定收藏品将不显示。过滤器处理的第二类与获取信息。如果是小怪掉落收藏品，或从供应商提供的，并且切换为不显示供应商收藏品，收藏品会被显示但是供应商会被隐藏。原因是还有另一种方式来获得这种收藏品（小怪掉落），所以在扫描过程中仍然包含。
请注意，工具提示将始终隐藏对立阵营收藏。这样做是为了节省空间的提示，因为他们可以得到相当多的物品。]=]
L["Vasarin Redmorn"] = true -- Needs review
L["Vendor"] = "供应商"
L["VENDOR_DESC"] = "扫描包含从供应商购买的收藏品。"
L["Veron Amberstill"] = "维隆·冻石"
L["Version"] = "版本"
L["View Exclusion List"] = "查看排除列表"
L["VIEW_EXCLUSION_LIST_DESC"] = "列出排除列表全部项。"
L["Vile Ooze"] = "邪恶的软泥怪"
L["Vile Slime"] = "可憎的软泥怪"
L["Winaestra"] = "维奈丝特拉"
L["World Drop"] = "世界掉落"
L["WORLD_DROP_DESC"] = "扫描包含世界掉落收藏品。"
L["WORLDMAP_DESC"] = true -- Needs review
L["Xan'tish"] = "克萨迪斯"
L["Yarlyn Amberstill"] = "亚尔林·冻石"
L["Zachariah Post"] = "撒迦利亚·普斯特"
L["Zanien"] = "萨尼恩"
L["Zevrost"] = "泽弗洛斯特"
L["Zjolnir"] = "祖尼尔"
