--[[

************************************************************************

zhTW.lua

zhTW localization strings for Collectinator

File date: 2010-04-04T16:38:43Z 
Project version: v1.0.4

Please update:
http://www.wowace.com/projects/collectinator/localization/zhTW/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "zhTW", false)

if not L then return end

L["About"] = "關於"
L["Achievement"] = "成就"
L["ACHIEVEMENT_DESC"] = "掃描包含從成就中取得的收藏品。"
L["ACQUIRETOOLTIPPOSITION_DESC"] = "變更包含取得的提示訊息的位置。"
L["Acquisition"] = "取得"
L["Adolescent Whelp"] = "年輕的幼龍"
L["Alamma"] = "阿拉瑪"
L["Aldraan"] = "阿爾德蘭"
L["Alexander Calder"] = "亞歷山大·考德爾"
L["ALL_FILTERED"] = "你的篩選設定為不顯示任何物品，請更改你的篩選設定，然後再試一次。"
L["ALT_CLICK"] = "Alt+點擊新增/移除此項到你的忽略清單中。"
L["Alt-Collections"] = "Alt-蒐集"
L["Apothecary Hummel"] = "藥劑師赫梅爾"
L["Artifact"] = "帳號綁定"
L["Artifact_DESC"] = "掃描包含帳號綁定品質收藏品。"
L["Auto Scan Map"] = "自動掃描地圖"
L["AUTOSCANMAP_DESC"] = true
L["Babagaya Shadowcleft"] = "巴巴嘎亞暗影斬裂者"
L["Bana Wildmane"] = "巴那·蠻鬃"
L["BC_WOW_DESC"] = "可在燃燒的遠征中找到物品。"
L["Belbi Quikswitch"] = "貝爾碧·迅移"
L["Binding"] = "綁定"
L["Blix Fixwidget"] = "布力克斯·修械"
L["Bloodsail Deckhand"] = "血帆槳手"
L["Bloodsail Elder Magus"] = "血帆魔導師"
L["Bloodsail Mage"] = "血帆法師"
L["Bloodsail Raider"] = "血帆劫掠者"
L["Bloodsail Sea Dog"] = "血帆水手"
L["Bloodsail Swabby"] = "血帆水兵"
L["Bloodsail Swashbuckler"] = "血帆劍客"
L["Bloodsail Warlock"] = "血帆術士"
L["Blue Dragonspawn"] = "藍色龍裔"
L["Blue Scalebane"] = "藍色逆鱗龍人"
L["BOA_DESC"] = "掃瞄中包含帳號綁定的物品。"
L["BOAFilter"] = "帳號綁定的物品"
L["BOE_DESC"] = "掃描中包含裝備綁定的物品。"
L["BOEFilter"] = "裝備綁定的物品"
L["Bogflare Needler"] = "泥沼閃光釘刺者"
L["BOP_DESC"] = "掃描中包含拾取綁定的物品。"
L["BOPFilter"] = "拾取綁定的物品"
L["Bottom"] = "底部"
L["Breanni"] = "布芮妮"
L["Briarthorn"] = "布瑞爾索恩"
L["Brunn Flamebeard"] = "布朗恩·焰鬚"
L["Burning Crusade"] = "燃燒的遠征"
L["Celoenus"] = "塞隆娜絲"
L["Cielstrasza"] = "希爾史卓莎"
L["CLEAR_DESC"] = "清除搜尋文字框。"
L["Clear Exclusion List"] = "清除排除清單"
L["CLEAR_EXCLUSION_LIST_DESC"] = "從排除清單中移除所有物品。"
L["Clear Waypoints"] = "清除路徑點"
L["CLEAR_WAYPOINTS_DESC"] = true
L["Clockwork Assistant"] = "發條助手"
L["Cloned Ooze"] = "複製軟泥怪"
L["CLOSE_DESC"] = "關閉 Collectinator 視窗。"
L["COLLECTIBLE_EXCLUDED"] = "收藏品在排除清單中。"
L["Collectinator_ALLEXCLUDED"] = "你的排除設定為不顯示任何物品，請更改你的排除設定，然後再試一次。"
L["Collectinator_ALLKNOWN"] = "你已知了所有物品，已經沒有可蒐集的了。"
L["Collectinator Documentation"] = "Collectinator 使用說明"
L["Collectinator_SEARCHFILTERED"] = "您的搜尋沒有結果。"
L["COLLECTOR_ED_DESC"] = "掃描中包含從典藏版取得的收藏品。"
L["Collectors' Edition"] = "典藏版"
L["Common"] = "普通"
L["Common_DESC"] = "掃描包含普通品質收藏品。"
L["Common Issues"] = "常見問題"
L["COMMON_ISSUES_DESC"] = [=[回報bug之前請先參閱這些常見問題。
1) 無法顯示坐騎/寵物! - 查看你的篩選設定確認該物品沒有被篩選。]=]
L["CONTRACTALL"] = "- 全部"
L["CONTRACTALL_DESC"] = "最小化下列所有物品的清單。"
L["Coreiel"] = "寇瑞歐"
L["Corporal Arthur Flew"] = "亞瑟·弗路下士"
L["CRAFT_DESC"] = "掃描中包含從製造取得的收藏品。"
L["Crafted"] = "已製造"
L["Crimson Whelp"] = "赤紅幼龍"
L["CTRL_CLICK"] = "Ctrl+點擊新增此物品連結到你的聊天視窗中。"
L["CTRL_SHIFT_CLICK"] = "Ctrl+Shift+點擊新增物品到地圖及小地圖。"
L["Dalaran Shield Guard"] = "達拉然持盾守衛"
L["Dalaran Spellscribe"] = "達拉然書記員"
L["Dalaran Summoner"] = "達拉然召喚師"
L["Dalaran Theurgist"] = "達拉然巫者"
L["Dama Wildmane"] = "達瑪·野鬃"
L["Dame Evniki Kapsalis"] = "伊芙尼奇·卡莎莉絲夫人"
L["Darahir"] = "達拉喜爾"
L["Dart"] = "達爾特"
L["DB_LOAD_ERROR"] = [=[錯誤:沒有正確載入資料庫。
請離開魔獸世界並刪除Collectinator的資料庫檔案(Collectinator.lua)在:
\\World of Warcraft\\WTF\\Account\\<帳號>>\\SavedVariables\\]=]
L["Dealer Rashaad"] = "商人洛斯汗德"
L["Defias Pirate"] = "迪菲亞海賊"
L["Demisette Cloyce"] = "德米賽特·克勞斯"
L["Derrick Brindlebeard"] = "德瑞克·斑鬚"
L["Deviate Guardian"] = "變異守護者"
L["Deviate Ravager"] = "變異劫毀者"
L["Devouring Ooze"] = "吞噬軟泥怪"
L["Dhugru Gorelust"] = "杜格魯·血怒"
L["Display"] = "顯示"
L["DISPLAY_EXCLUSION_DESC"] = "顯示在排除清單中的物品。"
L["Display Exclusions"] = "顯示排除"
L["Display Options"] = "顯示選項"
L["DISPLAY_OPTIONS_DESC"] = "允許你自訂圖形介面的操作。"
L["DOC_DESC"] = "Collectinator的使用說明"
L["Documentation"] = "使用說明"
L["Donni Anthania"] = "冬妮·安薩妮婭"
L["Doru Thunderhorn"] = "杜魯·雷角"
L["Draconic Magelord"] = "龍人法師領主"
L["Draconic Mageweaver"] = "龍人施法者"
L["Drake Dealer Hurlunk"] = "龍之商人荷刃克"
L["Dread Commander Thalanor"] = "驚懼指揮官薩拉諾"
L["Dreaming Whelp"] = "睡夢中的幼龍"
L["Driz Tumblequick"] = "德瑞茲·迅跌"
L["Durgan Thunderbeak"] = "杜根·雷喙"
L["Eliza Killian"] = "伊莉莎·基里安"
L["Epic"] = "史詩"
L["Epic_DESC"] = "掃描包含史詩品質收藏品。"
L["EVENT_DESC"] = "掃描中包含特別事件(BlizzCon，WWI，等等)取得的收藏品。"
L["EXCLUDECOUNT_DESC"] = "包含總物品數量的已排除物品。"
L["Exclusion Issues"] = "排除問題"
L["EXCLUSION_ISSUES_DESC"] = "新增物品到排除(忽略)清單中，只要在掃描視窗上Alt+點擊它即可。若要還原，開啟選項設定並勾選\"顯示已排除\"。這將在你下次掃描時顯示已排除的物品。一但這樣做了，Alt+點擊該物品即可從排除清單中移除。"
L["EXPANDALL"] = "+ 全部"
L["EXPANDALL_DESC"] = "展開下列所有物品清單。"
L["Faction"] = "陣營"
L["FACTION_DESC"] = "掃描中包含聯盟及部落雙方陣營的收藏品。"
L["Fedryen Swiftspear"] = "費德萊恩·迅矛"
L["Filter"] = "篩選"
L["FILTER_CLOSE_DESC"] = "關閉篩選選項面板。"
L["FILTERCOUNT_DESC"] = "對於篩選到的物品如果不存在。選擇該選項將改變已知和未知數量的收藏品。"
L["FILTERING_BC_DESC"] = "配置掃描中包含燃燒的遠征聲望獎勵的物品。"
L["FILTERING_BINDING_DESC"] = "配置掃描中包含綁定類型的物品。"
L["FILTERING_GENERAL_DESC"] = "配置掃描中包含多種篩選類型的物品。"
L["FILTERING_MISC_DESC"] = "配置雜項的選項也顯示在選項中。"
L["FILTERING_OBTAIN_DESC"] = "配置掃描中包含取得方式的物品。"
L["FILTERING_OLDWORLD_DESC"] = "配置掃描中包含經典舊世聲望獎勵的物品。"
L["FILTERING_RARITY_DESC"] = "配置掃描包含的品質類型。"
L["FILTERING_REP_DESC"] = "配置掃描中包含聲望獎勵的物品。"
L["FILTERING_WOTLK_DESC"] = "配置掃描中包含巫妖王之怒聲望獎勵的物品。"
L["FILTERKNOWNCOUNT_DESC"] = "在計算中包含篩選過的已知物品，但忽略篩選過的未知物品。"
L["FILTER_OPEN_DESC"] = "開啟篩選選項面板。"
L["Filters"] = "篩選器"
L["Flamesnorting Whelp"] = "噴火幼龍"
L["Flesh Hunter"] = "血肉獵手"
L["Flik"] = "弗里克"
L["Font Size"] = "字型大小"
L["FONT_SIZE_DESC"] = "變更字型的大小。"
L["Forest Frog"] = "森林蛙"
L["Freka Bloodaxe"] = "弗雷卡·血斧"
L["Gaelden Hammersmith"] = "蓋爾丁·錘匠"
L["Game Commands"] = "遊戲命令"
L["GAME_COMMANDS_DESC"] = [=[命令列:
Collectinator已改使用圖形介面來設定。輸入 /collectinator 開啟圖形介面。可用的命令包含:
- TBD

點擊:
Collectinator將會有所不同，這取決於你修改使用的點擊按鍵。

掃描按鈕:
當你點擊掃描按鈕時才會有的功能。

- 點擊
  在當前專業技能進行掃描時於新視窗顯示收藏品。
- Shift+點擊
  在當前專業技能中產生CSV格式的文字。
- Alt+點擊
  移除在世界地圖及小地圖上所有由Collectinator產生的路徑點。

物品:
當你點擊一個物品時所產生的功能。

- 點擊
  展開或收起取得該物品的資訊。
- Shift+點擊
  產生一個物品連結並可輸入到預設的聊天視窗中。
- Ctrl+點擊
  為你點擊該物品產生一個法術連結。
- Alt+點擊
  從排除清單中新增或移除一個物品。
- Ctrl+Shift+點擊
  新增特定物品的取得方式到世界地圖及小地圖。]=]
L["Gargantuan Ooze"] = "巨大的軟泥怪"
L["Geen"] = "吉恩"
L["General"] = "一般"
L["General Options"] = "一般選項"
L["Gimrizz Shadowcog"] = "吉姆瑞茲·影輪"
L["Glutinous Ooze"] = "粘稠的軟泥怪"
L["Gregor MacVince"] = "格瑞戈·馬克凡斯"
L["Grella"] = "葛瑞拉"
L["Grol'dar"] = "格羅達爾"
L["Grunda Bronzewing"] = "關妲·青銅之翼"
L["Grunnda Wolfheart"] = "葛蘭達·狼心"
L["Gundrak Raptor"] = "剛德拉克迅猛龍"
L["Halpa"] = "哈爾帕"
L["Harb Clawhoof"] = "哈布·爪蹄"
L["Hide Pop-Up"] = "隱藏彈出視窗"
L["HIDEPOPUP_DESC"] = "停止彈出視窗通知你為何顯示掃描視窗中是空的。新版本新增了以後當你第一次使用時總是彈出視窗。"
L["Hiren Loresong"] = "希倫·識歌"
L["Include Excluded"] = "包含已排除"
L["Include Filtered"] = "包含已篩選"
L["Include Known Filtered"] = "包含已知的已篩選"
L["Instance"] = "副本"
L["INSTANCE_DESC"] = "掃描中包含從5人副本取得的收藏品。"
L["Irisee"] = "艾芮希"
L["Item"] = "裝備"
L["Jekyll Flandring"] = "耶克里·弗蘭迪"
L["Jepetto Joybuzz"] = "杰佩托·樂吱"
L["Jeremiah Payson"] = "傑雷米亞·派森"
L["Jilanne"] = "吉安妮"
L["Kaal Soulreaper"] = "卡爾·噬靈"
L["Kartosh"] = "卡托什"
L["Katie Hunter"] = "凱蒂·亨特"
L["Knight Dameron"] = "騎士達美隆"
L["Known"] = "已知"
L["KNOWN_DESC"] = "掃描中包含已知的收藏品。"
L["Landro Longshot"] = "藍卓·長射"
L["Large Vile Slime"] = "可憎的大泥漿怪"
L["Larkin Thunderbrew"] = "拉金·雷酒"
L["Left"] = "左"
L["Legendary"] = "傳說"
L["Legendary_DESC"] = "掃描包含帳傳說品質收藏品。"
L["Lelanai"] = "萊蘭奈"
L["Lich King"] = "巫妖王"
L["Lieutenant Karter"] = "卡特爾中尉"
L["Lillehoff"] = "立勒賀夫"
L["Lil Timmy"] = "利爾·迪米"
L["Living Decay"] = "腐朽軟泥怪"
L["LK_WOW_DESC"] = "可取得於巫妖王之怒的收藏品。"
L["Location"] = "位置"
L["Luther Pickman"] = "盧瑟·匹克曼"
L["Magus Tirth"] = "魔導師提爾斯"
L["Main Filter Options"] = "主要篩選選項"
L["MAINFILTER_OPTIONS_DESC"] = "允許你處理指定不同的篩選。"
L["Main Options"] = "主要選項"
L["MAIN_OPTIONS_DESC"] = "主要配置選項"
L["Map Issues"] = "地圖問題"
L["MAP_ISSUES_DESC"] = "Collectinator需要TomTom來新增圖示和路徑點到世界地圖及小地圖。你可以自訂這些Collectinator配置選單及滾動顯示選項。如果你沒有安裝TomTom則不會新增任何東西。自動新增圖示功能則預設為停用。"
L["Map Options"] = "地圖選項"
L["MAP_OPTIONS_DESC"] = "允許你變更如何整合Collectinator到世界地圖及小地圖。"
L["Maximillian Crowe"] = "瑪克西米利安·克洛文"
L["Mei Francis"] = "梅·法蘭西斯"
L["Merideth Carlson"] = "梅麗德絲·卡爾森"
L["Midsummer Merchant"] = "仲夏節慶商人"
L["Midsummer Supplier"] = "仲夏節慶供應商"
L["Milli Featherwhistle"] = "米利·羽哨"
L["Mini Map"] = "小地圖"
L["MINIMAP_DESC"] = true
L["Mirket"] = "米爾科特"
L["Misc"] = "雜項"
L["Miscellaneous"] = "雜項"
L["MISSING_LIBRARY"] = "缺少%s。插件無法運行。"
L["Mob Drop"] = "怪物掉落"
L["MOB_DROP_DESC"] = "掃描中包含怪物掉落的收藏品。"
L["Mor'vek"] = "莫維克"
L["Mouse"] = "滑鼠"
L["Mycah"] = "麥卡"
L["Name"] = "名稱"
L["Narkk"] = "納爾克"
L["Noblegarden Merchant"] = "貴族花園商人"
L["Noblegarden Vendor"] = "貴族花園商販"
L["NO_DISPLAY"] = "沒有顯示任何物品。如果你看到這個訊息請提交一份資料到http://www.wowace.com/projects/collectinator/tickets說明你使用了什麼篩選，在排除清單中有什麼，掃瞄完成的類型及已知/未知物品的數量。"
L["NoItemLink"] = "這個物品沒有連結或者不存在於你的暫存檔中。"
L["NOTSCANNED"] = "你還沒掃瞄這個收藏品，請打開插件介面，然後按一下掃瞄按鈕。注意掃描坐騎/寵物是同時完成的。"
L["NOT_YET_SCANNED"] = "還沒掃瞄!"
L["Obtain"] = "取得"
L["Obtained From"] = "取得從"
L["Off"] = "否"
L["Ogunaro Wolfrunner"] = "奧古納羅·狼行者"
L["Ok"] = "是"
L["Old World"] = "經典舊世"
L["ORIGINAL_WOW_DESC"] = "可取得於經典舊世的收藏品。"
L["Other Realms"] = "其他伺服器"
L["Pol Amberstill"] = "保爾·安伯斯堤爾"
L["Poor"] = "粗糙"
L["Poor_DESC"] = "掃描包含粗糙品質收藏品。"
L["\"Pretty Boy\" Duncan"] = "『漂亮男孩』鄧肯"
L["Primal Ooze"] = "原生軟泥怪"
L["Profile"] = "設定檔"
L["Profile Options"] = "設定檔選項"
L["Provisioner Nasela"] = "原生軟泥怪"
L["PVP"] = true
L["PVP_DESC"] = "掃描中包含從PVP取得的收藏品。"
L["Quest"] = "任務"
L["QUEST_DESC"] = "掃描中包含從任務取得的收藏品。"
L["Raid"] = "團隊"
L["RAID_DESC"] = "掃描中包含從團隊(如:熔火之心，毒蛇神殿，等等。)取得的收藏品。"
L["Raider Bork"] = "狼騎兵波爾克"
L["Rare"] = "精良"
L["Rare_DESC"] = "掃描包含精良品質收藏品。"
L["Rarity"] = "品質"
L["Ravasaur Matriarch"] = "暴掠龍族母"
L["Ray'ma"] = "雷瑪"
L["Razormaw Matriarch"] = "刺喉龍族母"
L["Razzashi Raptor"] = "拉札希迅猛龍"
L["Red Whelp"] = "紅色幼龍"
L["Removed from Game"] = "已從遊戲中移除"
L["Reporting Bugs"] = "回報Bugs"
L["REPORTING_BUGS_DESC"] = [=[當回報一個錯誤時，請確實做到以下幾點:
1) 從http://www.wowace.com/projects/collectinator/files/下載最新的版本。
2) 確認這個錯誤沒有被回報。你可以查看http://www.wowace.com/projects/collectinator/tickets/。
3) 閱讀錯誤報告文件。http://www.wowace.com/projects/collectinator/pages/feedback-and-bug-reporting/
4) 如果你的問題沒有列出，檢查你的設定以及你使用的是最新版本。檢查篩選選項，設定檔，等等。
5) 你發現了一個沒有人回報過的錯誤。到http://www.wowace.com/projects/collectinator/tickets/創一個新的標題和描述發生此問題的經過。在報告中一定要包含你所遇到的錯誤訊息(我不需要你所使用的插件列表，我只要錯誤訊息即可)，還有其他你認為有幫助的任何訊息。
當發帖回報錯誤時，請不要包含你所使用的所有插件。這只會讓人覺得難以閱讀。如果你想要一個優良的錯誤回報文章，請使用BugSack。請不要對錯誤/缺少的配方發表意見或者發送信件給我一整個下午。發送到ticket這樣我好處理及追蹤。]=]
L["REP_TEXT_DESC"] = [=[右鍵點擊來選擇所有聲望篩選。
左鍵點擊這來取消所有聲望篩選。]=]
L["Reputation"] = "聲望"
L["Reset All Filters"] = "重置所有篩選"
L["RESET_DESC"] = "重置所有篩選為預設值。"
L["RESET_WINDOW_DESC"] = "重置圖形介面到預設位置。"
L["Reset Window Position"] = "重置視窗位置"
L["Retired"] = "已撤除"
L["Richard Kerwin"] = "理查·科爾文"
L["Right"] = "右"
L["Rillie Spindlenut"] = "瑞里·軸螺"
L["Rivern Frostwind"] = "雷沃·霜風"
L["Rook Hawkfist"] = "茹克·鷹拳"
L["Rotting Sludge"] = "腐爛淤泥怪"
L["Rupert Boch"] = "魯伯特·鮑什"
L["Sairuk"] = "塞魯克"
L["Samamba"] = "沙瑪巴"
L["Sandahl"] = "山達爾"
L["Scalding Whelp"] = "滾燙幼龍"
L["Scan"] = "掃瞄"
L["SCAN_COMPANIONS_DESC"] = [=[掃描當前開啟的視窗。
Shift+點擊產生你擁有的收藏品的文字轉儲。
Alt+點擊在小地圖及世界地圖中移除所有路徑點。]=]
L["SEARCH_BOX_DESC"] = "輸入文字到搜尋中。"
L["SEARCH_DESC"] = "以左邊文字內容來篩選。"
L["Searing Whelp"] = "灼熱幼龍"
L["SEASONAL_DESC"] = "掃描中包含從世界事件取得的收藏品。"
L["SHIFT_CLICK"] = "Shift+點擊新增由製造造出的收藏品連結到你的聊天視窗中。"
L["Shylenai"] = "夏琳奈爾"
L["Sixx"] = "希克斯"
L["Sort"] = "排列"
L["Sorting"] = "排列中"
L["SORTING_DESC"] = "變更顯示收藏品的排列方式。"
L["Sorting Options"] = "排列選項"
L["SORTING_OPTIONS_DESC"] = "允許你自訂顯示收藏品的排列方式。"
L["Special Event"] = "特殊事件"
L["SPECIFIC_REP_DESC"] = "包含%s陣營。"
L["SPELLTOOLTIPPOSITION_DESC"] = "變更收藏品資訊的提示訊息位置。"
L["Sprite Darter"] = "小精龍"
L["Stone Guard Mukar"] = "石衛士慕卡"
L["Store"] = "Blizzard商店"
L["STORE_DESC"] = "掃描中包含從Blizzard商店取得的收藏品。"
L["Strahad Farsan"] = "斯坦哈德·法爾杉"
L["Tainted Ooze"] = "受污染的軟泥怪"
L["Takk the Leaper"] = "『跳躍者』塔克"
L["Talionia"] = "塔萊妮亞"
L["Tanaika"] = "塔奈卡"
L["TCG"] = "魔獸世界紙牌遊戲"
L["TCG_DESC"] = "掃描中包含從魔獸世界紙牌遊戲取得的收藏品。"
L["Text Dump"] = "文字轉儲"
L["TEXT_DUMP_DESC"] = "顯示所有以逗號分隔格式的收藏品，可以被複製並貼上到另一個客戶端。"
L["Thanthaldis Snowgleam"] = "塔薩迪斯·雪光"
L["The Ongar"] = "歐加爾"
L["Thistleheart"] = "瑟斯哈特"
L["Time-Lost Proto Drake"] = "時光流逝元龍"
L["Tohfo Skyhoof"] = "托弗·天蹄"
L["Tooltip (Acquire) Position"] = "提示訊息位置(取得)"
L["Tooltip (Collectible) Position"] = "提示訊息位置(收藏品)"
L["Tooltip Options"] = "提示訊息選項"
L["TOOLTIP_OPTIONS_DESC"] = "允許你自訂提示訊息。在取得提示訊息中列出取得收藏品的不同資訊，而法術提示訊息中則列出收藏品本身的資訊。"
L["Tooltip Scale"] = "提示訊息比例"
L["TOOLTIP_SCALE_DESC"] = "變更提示訊息的比例。範圍從.5到1.5(.9為預設值)"
L["Top"] = "頂部"
L["Torallius the Pack Handler"] = "『獸群管理者』托拉利斯"
L["Trader Narasu"] = "商人娜拉蘇"
L["Trellis Morningsun"] = "崔利斯·晨日"
L["UI_SCALE_DESC"] = "變更插件的比例。範圍從.5到1.5(1為預設值)"
L["Unavailable"] = "無法取得"
L["Uncommon"] = "優秀"
L["Uncommon_DESC"] = "掃描包含優秀品質收藏品。"
L["Unger Statforth"] = "安格爾·斯塔特弗斯"
L["Unhandled Collectible"] = "未取得的收藏品"
L["Unknown"] = "未知"
L["UNKNOWN_DESC"] = "掃描中包含所有未知的收藏品。"
L["Unknown Zone"] = "未知地區"
L["Ursula Deline"] = "厄蘇拉·德林"
L["Using Filters"] = "使用篩選"
L["USING_FILTERS_DESC"] = [=[可以切換開啟或關閉篩選。有兩種類型的篩選:一種是不顯示所有的收藏品，另一種是不顯示特殊類型的取得資訊。
第一種類型的篩選，這些符合的收藏品(如:綁定)。如果你設定Collectinator為不顯示拾取綁定的收藏品，則在掃描中就不會顯示拾取綁定的收藏品。第二種類型的篩選為取得資訊。如果收藏品可由怪物掉落或來自供應商並且設定不顯示供應商的收藏品，則收藏品會顯示但供應商資訊的則會隱藏。原因是還有另一種方式來取得收藏品(怪物掉落)，所以仍包含在掃描中。 
請注意提示訊息始終都會隱藏敵對陣營的取得方式，這樣做是為了避免提示訊息顯示太大。]=]
L["Vasarin Redmorn"] = "凡薩霖·紅晨"
L["Vendor"] = "供應商"
L["VENDOR_DESC"] = "掃描中包含從供應商購得的收藏品。"
L["Veron Amberstill"] = "維隆·凍石"
L["Version"] = "版本"
L["View Exclusion List"] = "查看排除清單"
L["VIEW_EXCLUSION_LIST_DESC"] = "列出排除清單中所有物品的清單。"
L["Vile Ooze"] = "邪惡的軟泥怪"
L["Vile Slime"] = "可憎的泥漿怪"
L["Winaestra"] = "烏恩絲"
L["World Drop"] = "世界掉落"
L["WORLD_DROP_DESC"] = "掃描中包含世界掉落的收藏品。"
L["WORLDMAP_DESC"] = true
L["Xan'tish"] = "克薩迪斯"
L["Yarlyn Amberstill"] = "亞爾林·凍石"
L["Zachariah Post"] = "撒迦利亞·普斯特"
L["Zanien"] = "賽尼安"
L["Zevrost"] = "澤弗洛斯特"
L["Zjolnir"] = "祖尼爾"
