local AceLocale = LibStub("AceLocale-3.0")
local L = AceLocale:GetLocale( "GearScore" )

GS_Tokens = {
--Teir 9 Tokens


--Teir 8 Tokens
	["45649"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
	["45647"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
	["45648"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 219 },
    ["45646"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45644"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45645"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 219 },
	["45637"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45635"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45636"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 219 },
	["45661"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45659"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45660"] = { ["ItemScore"] = 274, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 219 },
	["45652"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },
	["45650"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },
	["45651"] = { ["ItemScore"] = 365, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 219 },

--Teir 8.5 Tokens
	["45632"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45633"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45634"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 226 },
	["45643"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45641"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45642"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 226 },
	["45640"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45638"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45639"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 226 },
	["45658"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45656"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45657"] = { ["ItemScore"] = 289, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 226 },
	["45655"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },
	["45653"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },
	["45654"] = { ["ItemScore"] = 385, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 226 },

--Teir 7 Tokens
	["40618"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
	["40616"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
	["40617"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 200 },
   	["40615"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40613"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40614"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 200 },
	["40612"] = { ["ItemScore"] = 310 , ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40610"] = { ["ItemScore"] = 310 , ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40611"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 200 },
	["40624"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40622"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40623"] = { ["ItemScore"] = 233, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 200 },
	["40621"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },
	["40619"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },
	["40620"] = { ["ItemScore"] = 310, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 200 },

--Teir 7.5 Tokens
	["40633"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40631"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40632"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 1, ["ItemLevel"] = 213 },
	["40630"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40628"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40629"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Protector", ["ItemSlot"] = 10, ["ItemLevel"] = 213 },
	["40627"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40625"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40626"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 5, ["ItemLevel"] = 213 },
	["40639"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40637"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40638"] = { ["ItemScore"] = 261, ["ItemSubType"] = "Protector", ["ItemSlot"] = 3, ["ItemLevel"] = 213 },
	["40636"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Vanquisher", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },
	["40634"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Conqueror", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },
	["40635"] = { ["ItemScore"] = 348, ["ItemSubType"] = "Protector", ["ItemSlot"] = 7, ["ItemLevel"] = 213 },

}

GS_Factions = {
	["H"] = "Horde",
	["A"] = "Alliance",
	["Horde"] = "H",
	["Alliance"] = "A"
}

GS_Races = { 
	["HU"] = L["Human"],
	["DW"] = L["Dwarf"],
	["GN"] = L["Gnome"],
	["DR"] = L["Draenei"],
	["NE"] = L["NightElf"],
	["OR"] = L["Orc"],
	["TA"] = L["Tauren"],
	["TR"] = L["Troll"],
	["BE"] = L["BloodElf"],
	["UN"] = L["Undead"],
	["Human"] = "HU",
	["Dwarf"] = "DW",
	["Gnome"] = "GN",
	["Draenei"] = "DR",
	["NightElf"] = "NE",
	["Orc"] = "OR",
	["Tauren"] = "TA",
	["Troll"] = "TR",
	["BloodElf"] = "BE",
	["Scourge"] = "UN",
}

GS_Sexes = { [1] = "Neutral", [2] = "Male", [3] = "Female" }

GS_Classes = {
	["WA"] = L["Warrior"],
	["DK"] = L["Death Knight"],
	["PA"] = L["Paladin"],
	["SH"] = L["Shaman"],
	["HU"] = L["Hunter"],
	["DR"] = L["Druid"],
	["RO"] = L["Rogue"],
	["WK"] = L["Warlock"],
	["PR"] = L["Priest"],
	["MA"] = L["Mage"],
	["WARRIOR"] = "WA",
	["DEATHKNIGHT"] = "DK",
	["PALADIN"] = "PA",
	["SHAMAN"] = "SH",
	["HUNTER"] = "HU",
	["DRUID"] = "DR",
	["ROGUE"] = "RO",
	["WARLOCK"] = "WK",
	["PRIEST"] = "PR",
	["MAGE"] = "MA",
}

GS_EnglishClasses = {
	["WA"] = "WARRIOR",
	["DK"] = "DEATHKNIGHT",
	["PA"] = "PALADIN",
	["SH"] = "SHAMAN",
	["HU"] = "HUNTER",
	["DR"] = "DRUID",
	["RO"] = "ROGUE",
	["WK"] = "WARLOCK",
	["PR"] = "PRIEST",
	["MA"] = "MAGE",
}

GS_Texture = {
	[1] = GS_Slot1,
	[2] = GS_Slot2,
	[3] = GS_Slot3,
	[4] = GS_Slot4,
	[5] = GS_Slot5,
	[6] = GS_Slot6,
	[7] = GS_Slot7,
	[8] = GS_Slot8,
	[9] = GS_Slot9,
	[10] = GS_Slot10,
	[11] = GS_Slot11,
	[12] = GS_Slot12,
	[13] = GS_Slot13,
	[14] = GS_Slot14,
	[15] = GS_Slot15,
	[16] = GS_Slot16,
	[17] = GS_Slot17,
	[18] = GS_Slot18,
}


GS_ClassInfo = {
	["Warrior"]  = {
		["Name"] = "Warrior",
		["Key"] = "WA",
		["Red"] = 0.78,
		["Green"] = 0.61,
		["Blue"] = 0.43,
		["Equip"] = {
			["Plate"] = 1,
			["Shields"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Protector"] = 1,
		}
	},
	["Death Knight"] = {
		["Name"] = "Death Knight",
		["Key"] = "WA",
		["Red"] = 0.77,
		["Green"] = 0.12,
		["Blue"] = 0.23,
		["Equip"] = {
			["Plate"] = 1,
			["Sigils"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Vanquisher"] = 1,
		}
	},
	["Paladin"] = {
		["Name"] = "Paladin",
		["Key"] = "PA",
		["Red"] = 0.96,
		["Green"] = 0.55,
		["Blue"] = 0.73,
		["Equip"] = {
			["Plate"] = 1,
			["Librams"] = 1,
			["Shields"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
			["Two-Handed Swords"] = 1,
			["Conqueror"] = 1,
		}
	},
	["Druid"] = {
		["Name"] = "Druid",
		["Key"] = "DR",
		["Red"] = 1.00,
		["Green"] = 0.49,
		["Blue"] = 0.04,
		["Equip"] = {
			["Leather"] = 1,
			["Idols"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["Daggers"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Maces"] = 1,
            ["Vanquisher"] = 1,
		}
	},
	["Hunter"] = {
		["Name"] = "Hunter",
		["Key"] = "HU",
		["Red"] = 0.67,
		["Green"] = 0.83,
		["Blue"] = 0.45,
		["Equip"] = {
			["Mail"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Swords"] = 1,
			["Polearms"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Swords"] = 1,
            ["Protector"] = 1,
		}
	},
	["Mage"] = {
		["Name"] = "Mage",
		["Key"] = "MA",
		["Red"] = 0.41,
		["Green"] = 0.80,
		["Blue"] = 0.94,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Swords"] = 1,
			["Staves"] = 1,
            ["Vanquisher"] = 1,
		}
	},
	["Priest"] = {
		["Name"] = "Priest",
		["Key"] = "PR",
		["Red"] = 1.00,
		["Green"] = 1.00,
		["Blue"] = 1.00,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["Staves"] = 1,
            ["Conqueror"] = 1,
		}
	},
	["Rogue"] = {
		["Name"] = "Rogue",
		["Key"] = "RO",
		["Red"] = 1.00,
		["Green"] = 0.96,
		["Blue"] = 0.41,
		["Equip"] = {
			["Leather"] = 1,
			["Bows"] = 1,
			["Crossbows"] = 1,
			["Guns"] = 1,
			["Thrown"] = 1,
			["Daggers"] = 1,
			["Fist Weapons"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Maces"] = 1,
			["One-Handed Swords"] = 1,
            ["Vanquisher"] = 1,
		 }
	},
	["Shaman"] = {
		["Name"] = "Shaman",
		["Key"] = "SH",
		["Red"] = 0.14,
		["Green"] = 0.35,
		["Blue"] = 1.00,
		["Equip"] = {
			["Mail"] = 1,
			["Totems"] = 1,
			["Shields"] = 1,
			["Fist Weapons"] = 1,
			["One-Handed Axes"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Axes"] = 1,
			["One-Handed Maces"] = 1,
			["Staves"] = 1,
			["Two-Handed Axes"] = 1,
			["Two-Handed Maces"] = 1,
            ["Protector"] = 1,
		}
	},
	["Warlock"] = {
		["Name"] = "Warlock",
		["Key"] = "WK",
		["Red"] = 0.58,
		["Green"] = 0.51,
		["Blue"] = 0.79,
		["Equip"] = {
			["Cloth"] = 1,
			["Wands"] = 1,
			["Daggers"] = 1,
			["Miscellaneous"] = 1,
			["One-Handed Swords"] = 1,
			["Staves"] = 1,
            ["Conqueror"] = 1,
		}
	}
}

GS_ItemTypes = {
	["INVTYPE_RELIC"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false},
	["INVTYPE_TRINKET"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 33, ["Enchantable"] = false },
	["INVTYPE_2HWEAPON"] = { ["SlotMOD"] = 2.000, ["ItemSlot"] = 16, ["Enchantable"] = true },
	["INVTYPE_WEAPONMAINHAND"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 16, ["Enchantable"] = true },
	["INVTYPE_WEAPONOFFHAND"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = true },
	["INVTYPE_RANGED"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = true },
	["INVTYPE_THROWN"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false },
	["INVTYPE_RANGEDRIGHT"] = { ["SlotMOD"] = 0.3164, ["ItemSlot"] = 18, ["Enchantable"] = false },
	["INVTYPE_SHIELD"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = true },
	["INVTYPE_WEAPON"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 36, ["Enchantable"] = true },
	["INVTYPE_HOLDABLE"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 17, ["Enchantable"] = false },
	["INVTYPE_HEAD"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 1, ["Enchantable"] = true },
	["INVTYPE_NECK"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 2, ["Enchantable"] = false },
	["INVTYPE_SHOULDER"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 3, ["Enchantable"] = true },
	["INVTYPE_CHEST"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 5, ["Enchantable"] = true },
	["INVTYPE_ROBE"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 5, ["Enchantable"] = true },
	["INVTYPE_WAIST"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 6, ["Enchantable"] = false },
	["INVTYPE_LEGS"] = { ["SlotMOD"] = 1.0000, ["ItemSlot"] = 7, ["Enchantable"] = true },
	["INVTYPE_FEET"] = { ["SlotMOD"] = 0.75, ["ItemSlot"] = 8, ["Enchantable"] = true },
	["INVTYPE_WRIST"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 9, ["Enchantable"] = true },
	["INVTYPE_HAND"] = { ["SlotMOD"] = 0.7500, ["ItemSlot"] = 10, ["Enchantable"] = true },
	["INVTYPE_FINGER"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 31, ["Enchantable"] = false },
	["INVTYPE_CLOAK"] = { ["SlotMOD"] = 0.5625, ["ItemSlot"] = 15, ["Enchantable"] = true },
}

GS_DefaultSettings = {
	["KeepFaction"] = -1,
	["Player"] = 1,
	["Item"] = 1,
	["Show"] = 1,
	["Special"] = 1,
	["PVE"] = -1,
	["PVP"] = -1,
	["Communication"] = 1,
	["Compare"] = -1,
	["CHAT"] = -1,
	["Level"] = -1,
	["Average"] = -1,
	["Date2"] = 1,
	["ML"] = -1,
	["Slider"] = 10,
	["AutoPrune"] = 1,
	["ShowHelp"] = 1,
	["MinLevel"] = 80,
	["Detail"] = -1,
	["Restrict"] = 2, 
	["HNaxx"] = 3500,
	["Ulduar"] = 3850,
	["HUlduar"] = 4000,
	["Naxx"] = 3000,
	["HMaly"] = 3800,
	["Heroics"] = 2600,
	["Archavon"] = 2900,
	["Sarth"] = 2950,
	["HArchavon"] = 3350,
	["Malygos"] = 3400,
	["HSarth"] = 3450,
	["Emalon"] = 3650,
	["HEmalon"] = 3750,
	["HCrusade"] = 4500,
	["Crusade"] = 4100,
	["DatabaseAgeSlider"] = 30,
	["ShowSpecScores"] = {},
}

GS_TextureFiles = {
	[1] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Head.blp",
	[2] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Neck.blp",
	[3] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Shoulder.blp",
	[4] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[5] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[6] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Waist.blp",
	[7] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Legs.blp",
	[8] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Feet.blp",
	[9] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Wrists.blp",
	[10] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Hands.blp",
	[11] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-RFinger.blp",
	[12] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Finger.blp",
	[13] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket.blp",
	[14] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket.blp",
	[15] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest.blp",
	[16] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-MainHand.blp",
	[17] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-SecondaryHand.blp",
	[18] = "Interface\\PaperDoll\\UI-PaperDoll-Slot-Ranged.blp",
}

GS_Special = {
	["A"] = "Author of GearScore",
	["B"] = "Official Sponsor of GearScore",
	["C"] = "Official GearScore Guild",
	["D"] = "Official Nemesis of GearScore",
	["E"] = "Killing Machine",
	["F"] = "Petscore: 9001",
 	["Pauladin"] = { ["Realm"] = "Elune", ["Type"] = "B" },
 	
 	["Wolfric"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Coastar"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Alekzander"] = { ["Realm"] = "Agamaggan", ["Type"] = "B" },
 	["Decks"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
 	["Dram"] = { ["Realm"] = "Duskwood", ["Type"] = "B" },
 	["Moophasa"] = { ["Realm"] = "Silver Hand", ["Type"] = "B" },
 	["Spirts"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	--["Wizzardly"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	--["Cloroangel"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
 	["Aeonel"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Lollygimon"] = { ["Realm"] = "Caelestrasz", ["Type"] = "B" },  		
	["Midshipman"] = { ["Realm"] = "Fenris", ["Type"] = "B" },  		
	["Saruk"] = { ["Realm"] = "Mal'Ganis", ["Type"] = "B" },  		
	["Volstormbrew"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },  		
	["Shinnobe"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Spontaneous"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Nias"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },  		
	["Yaks"] = { ["Realm"] = "Balnazzar", ["Type"] = "B" },  		
	["Andresh"] = { ["Realm"] = "Uldaman", ["Type"] = "B" },  		
	["Atelyn"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" },  
	["UltraJames"] = { ["Realm"] = "Stormscale", ["Type"] = "B" }, 		
	--["Jubali"] = { ["Realm"] = "Frostmourne", ["Type"] = "B" }, 
	["Dalha"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" }, 
	["Delitahyral"] = { ["Realm"] = "Shandris", ["Type"] = "B" }, 
	["Deathhaeven"] = { ["Realm"] = "Eldre'thalas", ["Type"] = "B" }, 
	["Nareli"] = { ["Realm"] = "Detheroc", ["Type"] = "D" }, 
	["Dalha"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" }, 
	["Neisha"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" }, 
	["Tentontotem"] = { ["Realm"] = "Destromath", ["Type"] = "B" }, 
	["GryphonMD"] = { ["Realm"] = "Kargath", ["Type"] = "B" }, 
	["Judeondethus"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 	
	["Greatmelinko"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
	["Eshia"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" }, 
 	["Greatmelinko"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Hiivolt"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Tlor"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" }, 
 	["Arachna"] = { ["Realm"] = "Kel'Thuzad", ["Type"] = "B" },
 	["Belarr"] = { ["Realm"] = "Misha", ["Type"] = "B" }, 
 	["Zarniwhoop"] = { ["Realm"] = "Ysera", ["Type"] = "B" },  
 	["Faculty"] = { ["Realm"] = "Feathermoon", ["Type"] = "B" },  
 	["Round"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" }, 
 	["Berlioz"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" }, 
 	["Huzzan"] = { ["Realm"] = "Detheroc", ["Type"] = "B" }, 
 	["Lawlcat"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },  	
 	["Khyu"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },  	
 	["Tricksybell"] = { ["Realm"] = "Dentarg", ["Type"] = "B" },  	
 	["Quixotek"] = { ["Realm"] = "Kel'Thuzad", ["Type"] = "B" },  	
 	["Chetnik"] = { ["Realm"] = "Gurubashi", ["Type"] = "B" },  	
 	["Tekfour"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
 	["Tekfrost"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
 	["Adi"] = { ["Realm"] = "Elune", ["Type"] = "B" }, 
 	["Adibou"] = { ["Realm"] = "Elune", ["Type"] = "B" },  	 	
 	["Zinya"] = { ["Realm"] = "Azjol-Nerub", ["Type"] = "B" }, 
 	["Temmi"] = { ["Realm"] = "Dath'Remar", ["Type"] = "B" }, 
	["Tejal"] = { ["Realm"] = "Cairne", ["Type"] = "B" }, 
	["Doriecycline"] = { ["Realm"] = "Dreadmaul", ["Type"] = "B" }, 
	["Cayman"] = { ["Realm"] = "Shandris", ["Type"] = "B" }, 
 	["Verîx"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },
 	["Asulla"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },
	["Halcyana"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Midiga"] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },	
	 	
----------------------------
	["Midiga"] = { ["Realm"] = "IceCrown", ["Type"] = "B" },		 	
	["Drgoodhead "] = { ["Realm"] = "Stormreaver", ["Type"] = "B" },		 	
	["Squirrelly"] = { ["Realm"] = "Elune", ["Type"] = "B" },		 	
	["Atewheaties"] = { ["Realm"] = "Elune", ["Type"] = "B" },		 	
	["Shz"] = { ["Realm"] = "Gorefiend", ["Type"] = "B" },		 	
	["Zevilone"] = { ["Realm"] = "Llane", ["Type"] = "B" },		 	
	["Thorkeld"] = { ["Realm"] = "Shadow Council", ["Type"] = "B" },		 	
	["Vaxum"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Muru"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Moodle"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },		 	
	["Anzio"] = { ["Realm"] = "Bladefist", ["Type"] = "B" },		 	
	["Ggoddess"] = { ["Realm"] = "Madoran", ["Type"] = "B" },		 	
	["Rakkan"] = { ["Realm"] = "Lothar", ["Type"] = "B" },		 	
	["Taliaran"] = { ["Realm"] = "Grim Batol", ["Type"] = "B" },		 	
	["Dartagg"] = { ["Realm"] = "Crushridge", ["Type"] = "B" },		 	
	["Sethr"] = { ["Realm"] = "Crushridge", ["Type"] = "B" },		 	
	["Diosan"] = { ["Realm"] = "Scarlet Crusade", ["Type"] = "B" },		 	
	["Renth"] = { ["Realm"] = "Dragonblight", ["Type"] = "B" },		 	
	["Wherezwaldo"] = { ["Realm"] = "Magtheridon", ["Type"] = "B" },		 	
	["Mif"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },		 	
	["Lotorin"] = { ["Realm"] = "Thunderhorn", ["Type"] = "B" },		 	
	["Starrìe"] = { ["Realm"] = "Malfurion", ["Type"] = "B" },		 	
	["Jthome"] = { ["Realm"] = "Lightning's Blade", ["Type"] = "B" },		 	
	["Retmeat"] = { ["Realm"] = "Cairne", ["Type"] = "B" },		 	
	["Catzilla"] = { ["Realm"] = "Draenor", ["Type"] = "B" },		 	
	["Lonnie"] = { ["Realm"] = "Draenor", ["Type"] = "B" },		 	
	["Millantis"] = { ["Realm"] = "Archimonde", ["Type"] = "B" },		 	
	["Benzy"] = { ["Realm"] = "Alterac Mountains", ["Type"] = "B" },		 	
	["Deaddolly"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },		 	
	["Erd"] = { ["Realm"] = "Burning Legion", ["Type"] = "B" },		 	
	["Enigmà"] = { ["Realm"] = "Darksorrow", ["Type"] = "B" },		 	
	["Deaddolly"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },		 	
	["Dragonas"] = { ["Realm"] = "Lethon", ["Type"] = "B" },		 	
	["Salamando"] = { ["Realm"] = "Khadgar", ["Type"] = "B" },		 	
	["Alzinator"] = { ["Realm"] = "Shadowsong", ["Type"] = "B" },		 	
	["Junebee"] = { ["Realm"] = "Turalyon", ["Type"] = "B" },		 		
------------------------------	 	
-- 6/3/2010
	["Neysaa"] = { ["Realm"] = "Skywall", ["Type"] = "B" },			 	
	["Halcyana"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Kobekuro"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Kobeyama"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Sophiayuki"] = { ["Realm"] = "Detheroc", ["Type"] = "E" },
	["Praetori"] = { ["Realm"] = "Draenor", ["Type"] = "B" },
	["Strahdvonzar"] = { ["Realm"] = "Quel'Thalas", ["Type"] = "B" },
	["Rhakark"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" },
	["Jazzia"] = { ["Realm"] = "Earthen Ring", ["Type"] = "B" },
	["Diilemmaz"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Evilenigma"] = { ["Realm"] = "Darksorrow", ["Type"] = "B" },
	["Bittles"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Soilwork"] = { ["Realm"] = "Kirin Tor", ["Type"] = "B" },
	["Flayrot"] = { ["Realm"] = "Lothar", ["Type"] = "B" },
	["Direbear"] = { ["Realm"] = "Quel'Thalas", ["Type"] = "F" },
	["Vampiroth"] = { ["Realm"] = "Zul'jin", ["Type"] = "B" },
	["Tumtumm"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Winsticles"] = { ["Realm"] = "Frostmourne", ["Type"] = "B" },
	["Rekviem"] = { ["Realm"] = "Elune", ["Type"] = "B" },
	["Rîddîck"] = { ["Realm"] = "Madoran", ["Type"] = "B" },
	["Drakekitty"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Paladio"] = { ["Realm"] = "Area 52", ["Type"] = "B" },
	["Modellista"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
	["Cablitin"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Sneakycab"] = { ["Realm"] = "Proudmoore", ["Type"] = "B" },
	["Uselessllama"] = { ["Realm"] = "Spirestone", ["Type"] = "B" },
	["Penetråtion"] = { ["Realm"] = "Caelestrasz", ["Type"] = "B" },	 	
	
	["Funstar"] = { ["Realm"] = "Mal'Ganis", ["Type"] = "B" },
	["Omnimen"] = { ["Realm"] = "Agamaggen", ["Type"] = "B" },
	["Dotimusprime"] = { ["Realm"] = "Black DragonFlight", ["Type"] = "B" },
	["Sajuukkhar"] = { ["Realm"] = "Nordrassil", ["Type"] = "B" },
	["Noggienog"] = { ["Realm"] = "Windrunner", ["Type"] = "B" },
	["Stevelrwin"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Facerollftw"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Healsforhugs"] = { ["Realm"] = "Aggramar", ["Type"] = "B" },
	["Droodzz"] = { ["Realm"] = "Bruning Legion", ["Type"] = "B" },
	
	 	
------------------------------	 	 	
	["Arxkanite"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
	["Josephsmith"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
	["Choku"] = { ["Realm"] = "Magtheridon", ["Type"] = "B" },
	["Murmilude"] = { ["Realm"] = "Blade's Edge", ["Type"] = "B" },
	["Rangitor"] = { ["Realm"] = "Khaz'Goroth", ["Type"] = "B" },
	["Keightie"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
    	--["Kymax"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
    	["Zanier"] = { ["Realm"] = "Cairne", ["Type"] = "B" },    
    	--["Cuppycakes"] = { ["Realm"] = "Detheroc", ["Type"] = "A" },
    	--["Sausagefest"] = { ["Realm"] = "Detheroc", ["Type"] = "B" },
    	["Rogue Angels"] = { ["Realm"] = "Detheroc", ["Type"] = "C" },
}

GS_Rarity = {
	[0] = { Red = 0.55,	Green = 0.55, Blue = 0.55 },
	[1] = {	Red = 1.00,	Green = 1.00, Blue = 1.00 },
	[2] = {	Red = 0.12,	Green = 1.00, Blue = 0.00 },
	[3] = {	Red = 0.00,	Green = 0.50, Blue = 1.00 },
	[4] = {	Red = 0.69, Green = 0.28, Blue = 0.97 },
	[5] = { Red = 0.94,	Green = 0.09, Blue = 0.00 },
	[6] = {	Red = 1.00,	Green = 0.00, Blue = 0.00 },
	[7] = {	Red = 0.90,	Green = 0.80, Blue = 0.50 },
}

GS_Formula = {
	["A"] = {
		[4] = { ["A"] = 91.4500, ["B"] = 0.6500 },
		[3] = { ["A"] = 81.3750, ["B"] = 0.8125 },
		[2] = { ["A"] = 73.0000, ["B"] = 1.0000 }
	},
	["B"] = {
		[4] = { ["A"] = 26.0000, ["B"] = 1.2000 },
		[3] = { ["A"] = 0.7500, ["B"] = 1.8000 },
		[2] = { ["A"] = 8.0000, ["B"] = 2.0000 },
		[1] = { ["A"] = 0.0000, ["B"] = 2.2500 }
	}
}

GS_Quality = {
	[6000] = {
		["Red"] = { ["A"] = 0.94, ["B"] = 5000, ["C"] = 0.00006, ["D"] = 1 },
		["Green"] = { ["A"] = 0.47, ["B"] = 5000, ["C"] = 0.00047, ["D"] = -1 },
		["Blue"] = { ["A"] = 0, ["B"] = 0, ["C"] = 0, ["D"] = 0 },
		["Description"] = "Legendary"
	},
	[5000] = {
		["Red"] = { ["A"] = 0.69, ["B"] = 4000, ["C"] = 0.00025, ["D"] = 1 },
		["Green"] = { ["A"] = 0.28, ["B"] = 4000, ["C"] = 0.00019, ["D"] = 1 },
		["Blue"] = { ["A"] = 0.97, ["B"] = 4000, ["C"] = 0.00096, ["D"] = -1 },
		["Description"] = "Epic"
	},
	[4000] = {
		["Red"] = { ["A"] = 0.0, ["B"] = 3000, ["C"] = 0.00069, ["D"] = 1 },
		["Green"] = { ["A"] = 0.5, ["B"] = 3000, ["C"] = 0.00022, ["D"] = -1 },
		["Blue"] = { ["A"] = 1, ["B"] = 3000, ["C"] = 0.00003, ["D"] = -1 },
		["Description"] = "Superior"
	},
	[3000] = {
		["Red"] = { ["A"] = 0.12, ["B"] = 2000, ["C"] = 0.00012, ["D"] = -1 },
		["Green"] = { ["A"] = 1, ["B"] = 2000, ["C"] = 0.00050, ["D"] = -1 },
		["Blue"] = { ["A"] = 0, ["B"] = 2000, ["C"] = 0.001, ["D"] = 1 },
		["Description"] = "Uncommon"
	},
	[2000] = {
		["Red"] = { ["A"] = 1, ["B"] = 1000, ["C"] = 0.00088, ["D"] = -1 },
		["Green"] = { ["A"] = 1, ["B"] = 000, ["C"] = 0.00000, ["D"] = 0 },
		["Blue"] = { ["A"] = 1, ["B"] = 1000, ["C"] = 0.001, ["D"] = -1 },
		["Description"] = "Common"
	},
	[1000] = {
		["Red"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Green"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Blue"] = { ["A"] = 0.55, ["B"] = 0, ["C"] = 0.00045, ["D"] = 1 },
		["Description"] = "Trash"
	},
}



GS_CommandList = {
	[1] = "---GearScore Options List---",
   	[2] = "/gs <name> --> Shows you last reported score for player <name>.",
  	--[3] = "/gspam party, raid, or bg -> Reports scores of players in your group.",
	--[4] = "/gspam party <name> -> Whispers scores of players in your party to <name>.",
	[3] = "/gset player -> Toggles display of scores on players.",
	[4] = "/gset item -> Toggles display of scores for items.",
	--[7] = "/gset describe -> Toggles score descriptions for player's scores.",
	[5] = "/gset level -> Toggles iLevel information.",
	[6] = "/gset communicate -> Toggles Communication.",
    --[10] = "/gset average --> Shows Average ItemLevel in Tooltip.",
	[7] = "/gset reset --> Resets GearScore's Options back to Default.",
	--[12] = "/gset compare --> Toggles Display of Comparison info to Tooltip.",
	[8] = "/gset detail --> Toggles Display of Detailed Gear Items in Tooltip.",
	[9] = "/gset ml --> Toggles display of GearScore Masterloot comparison tooltip.",
	[10] = "/gset compare --> Toggles display of comparative info between you and your target's GearScore.",
	--[15] = "/gset prune --> Removes old and low level GearScores from your database.",
	[11] = "/gset purge --> Removes all entries from your database. Use with caution!",
	[12] = "/gset date --> Adds date & Time info to the tooltip",
	[13] = "/gset chat --> Adds GearScore information to Chat Frames.",
	[14] = "/gset transmit <name> --> Transmits your GearScore database to player <name>.",
	[15] = "/gsban <name> --> Toggles rather or not <name> is allowed to send you GearScore Data.",
  	[15] = "/gspam <group> -> Reports scores of players in your group. <group> can be 'party', 'raid', or 'group'",
	[16] = "/gspam <group> <targetchat> -> Whispers scores of players in your <group> to <targetchat> Eample: /gspam party guild",
}

GS_ShowSwitch = {[0] = 2,[1] = 3,[2] = 0,[3] = 1}
GS_ItemSwitch = {[0] = 3,[1] = 2,[2] = 1,[3] = 0}

GS_Zones = {
	["Elwynn Forest"] = "EWF",
	["Eversong Woods"] = "ESW",
	["Dun Morogh"] = "DMG",
	["Tirisfal Glades"] = "TFG",
	["Ghostlands"] = "GSL",
	["Loch Modan"] = "LMD",
	["Silverpine Forest"] = "SPF",
	["Westfall"] = "WSF",
	["Redridge Mountains"] = "RRM",
	["Duskwood"] = "DKW",
	["Hillsbrad Foothills"] = "HBF",
	["Wetlands"] = "WTL",
	["Alterac Mountains"] = "ATM",
	["Arathi Highlands"] = "AHL",
	["Stranglethorn Vale"] = "STV",
	["Badlands"] = "BDL",
	["Swamp of Sorrows"] = "SOS",
	["The Hinterlands"] = "THL",
	["Searing Gorge"] = "SRG",
	["The Blasted Lands"] = "TBL",
	["Burning Steppes"] = "BRS",
	["Western Plaguelands"] = "WPL",
	["Eastern Plaguelands"] = "EPL",
	["The Scarlet Enclave"] = "TSE",
	["Blackrock Mountain"] = "BRM",
	["Deadwind Pass"] = "DWP",
	["Isle of Quel'Danas"] = "IQD",
	["Azuremyst Isle"] = "AZI",
	["Durotar"] = "DRT",
	["Mulgore"] = "MLG",
	["Teldrassil"] = "TLD",
	["Bloodmyst Isle"] = "BMI",
	["Darkshore"] = "DKS",
	["The Barrens"] = "TBR",
	["Stonetalon Mountains"] = "STM",
	["Ashenvale"] = "ASV",
	["Thousand Needles"] = "TSN",
	["Desolace"] = "DSL",
	["Dustwallow Marsh"] = "DWM",
	["Feralas"] = "FRL",
	["Tanaris"] = "TNR",
	["Azshara"] = "AZS",
	["Felwood"] = "FLW",
	["Un'goro Crater"] = "UGC",
	["Winterspring"] = "WTS",
	["Silithus"] = "SLT",
	["Moonglade"] = "MGD",
    ["Hellfire Peninsula"] = "HFP",
    ["Zangarmarsh"] = "ZGM",
    ["Terokkar Forest"] = "TKF",
    ["Nagrand"] = "NGD",
    ["Blade's Edge Mountains"] = "BEM",
    ["Netherstorm"] = "NTS",
    ["Shadowmoon Valley"] = "SMV",
    ["Borean Tundra"] = "BRT",
    ["Howling Fjord"] = "HLF",
    ["Dragonblight"] = "DGB",
    ["Grizzly Hills"] = "GZH",
    ["Zul'Drak"] = "ZLD",
    ["Sholazar Basin"] = "SLB",
    ["Crystalsong Forest"] = "CSF",
    ["Storm Peaks"] = "STP",
    ["Icecrown"] = "ICN",
    ["Wintergrasp"] = "WTG",
    ["Hrothgar's Landing"] = "HTL",
    ["Orgrimmar"] = "ORG",
    ["Dalaran"] = "DAL",
    ["Ulduar"] = "ULD",
	["Auchenai Crypts"] = "ACC",
	["Sethekk Halls"] = "STH",
	["Caverns of Time"] = "COT",
	["Old Hillsbrad Foothills"] = "OHF",
	["City of Ironforge"] = "COI",
	["Unknown Location"] = "XXX",
	["Deadmines"] = "DDM",
	
--	["Shadowfang Keep"] = "SFK",
--	["Stockade"] = "STK",
--	["Gnomeregan"] = "GMR",
--	["Scarlet Monastery"] = "SCM",
--	["Temple of Atal'Hakkar"] = "TAH",
	
	
	["DDM"] = "Deadmines",
	["XXX"] = "Unknown Location",
	["COI"] = "City of Ironforge",
	["OHF"] = "Old Hillsbrad Foothills",
	["COT"] = "Caverns of Time",
	["STH"] = "Sethekk Halls",
	["ACC"] = "Auchenai Crypts",
	["ULD"] = "Ulduar",
	
    ["DAL"] = "Dalaran",
    ["EWF"] = "Elwynn Forest",
	["ESW"] = "Eversong Woods",
	["DMG"] = "Dun Morogh",
	["TFG"] = "Tirisfal Glades",
	["GSL"] = "Ghostlands",
	["LMD"] = "Loch Modan",
	["SPF"] = "Silverpine Forest",
	["WSF"] = "Westfall",
	["RRM"] = "Redridge Mountains",
	["SKW"] = "Duskwood",
	["HBF"] = "Hillsbrad Foothills",
	["WTL"] = "Wetlands",
	["ATM"] = "Alterac Mountains",
	["AHL"] = "Arathi Highlands",
	["STV"] = "Stranglethorn Vale",
	["BDL"] = "Badlands",
	["SOS"] = "Swamp of Sorrows",
	["THL"] = "The Hinterlands",
	["SRG"] = "Searing Gorge",
	["TBL"] = "The Blasted Lands",
	["BRS"] = "Burning Steppes",
	["WPL"] = "Western Plaguelands",
	["EPL"] = "Eastern Plaguelands",
	["TSE"] = "The Scarlet Enclave",
	["BRM"] = "Blackrock Mountain",
	["DWP"] = "Deadwind Pass",
	["IQD"] = "Isle of Quel'Danas",
	["AZI"] = "Azuremyst Isle",
	["DRT"] = "Durotar",
	["MLG"] = "Mulgore",
	["TLD"] = "Teldrassil",
	["BMI"] = "Bloodmyst Isle",
	["DKS"] = "Darkshore",
	["TBR"] = "The Barrens",
	["STM"] = "Stonetalon Mountains",
	["ASV"] = "Ashenvale",
	["TSN"] = "Thousand Needles",
	["DSL"] = "Desolace",
	["DWM"] = "Dustwallow Marsh",
	["FRL"] = "Feralas",
	["TNR"] = "Tanaris",
	["AZS"] = "Azshara",
	["FLW"] = "Felwood",
	["UGC"] = "Un'goro Crater",
	["WTS"] = "Winterspring",
	["SLT"] = "Silithus",
	["MGD"] = "Moonglade",
    ["HFP"] = "Hellfire Peninsula",
    ["ZGM"] = "Zangarmarsh",
    ["TKF"] = "Terokkar Forest",
    ["NGD"] = "Nagrand",
    ["BEM"] = "Blade's Edge Mountains",
    ["NTS"] = "Netherstorm",
    ["SMV"] = "Shadowmoon Valley",
    ["BRT"] = "Borean Tundra",
    ["HLF"] = "Howling Fjord",
    ["DGB"] = "Dragonblight",
    ["GZH"] = "Grizzly Hills",
    ["ZLD"] = "Zul'Drak",
    ["SLB"] = "Sholazar Basin",
    ["CSF"] = "Crystalsong Forest",
    ["STP"] = "Storm Peaks",
    ["ICN"] = "Icecrown",
    ["WTG"] = "Wintergrasp",
    ["HTL"] = "Hrothgar's Landing",
    ["ORG"] = "Orgrimmar"
}



GS_AchInfo = {
	["Dungeons"] = {
		[1242] = "Ingvar the Plunderer (|CFF00F000Utgarde Keep|r)",
	        [1231] = "Keristrasza (|CFF00F000The Nexus|r)",
  		[1232] = "Anub'arak (|CFF00F000Azjol-Nerub|r)",
  		[1233] = "Herald Volazj (|CFF00F000Ahn'kahet: The Old Kingdom|r)",
  		[1234] = "The Prophet Tharon'ja (|CFF00F000Drak'Tharon Keep|r)",
  		[1235] = "Cyanigosa (|CFF00F000The Violet Hold|r)",
	        [1236] = "Gal'darah (|CFF00F000Gundrak|r)",
        	[1237] = "Sjonnir the Ironshaper (|CFF00F000Halls of Stone|r)",
	        [1238] = "Loken (|CFF00F000Halls of Lightning|r)",
	        [1239] = "Ley-Guardian Eregos (|CFF00F000The Oculus|r)",
	        [1240] = "King Ymiron (|CFF00F000Utgarde Pinnacle|r)",
	        [1241] = "Mal'Ganis (|CFF00F000Caverns of Time: Stratholme|r)",
	        [4026] = "The Black Knight (|CFF00F000Trial of the Champion|r)",
		},
 	["Heroic Dungeons"] = {
		[1504] = "Ingvar the Plunderer (|CFF00F000Heroic Utgarde Keep|r)",
	        [1505] = "Keristrasza (|CFF00F000Heroic Nexus|r)",
	        [1506] = "Anub'arak (|CFF00F000Heroic Azjol-Nerub|r)",
	        [1507] = "Herald Volazj (|CFF00F000Heroic Ahn'kahet|r)",
	        [1508] = "The Prophet Tharon'ja (|CFF00F000Heroic Drak'Tharon Keep|r)",
	        [1509] = "Cyanigosa (|CFF00F000Heroic Violet Hold|r)",
	        [1510] = "Gal'darah (|CFF00F000Heroic Gundrak|r)",
		[1511] = "Sjonnir the Ironshaper (|CFF00F000Heroic Halls of Stone|r)",
		[1512] = "Loken (|CFF00F000Heroic Halls of Lightning|r)",
		[1513] = "Ley-Guardian Eregos (|CFF00F000Heroic Oculus|r)",
		[1514] = "King Ymiron (|CFF00F000Heroic Utgarde Pinnacle|r)",
		[1515] = "Mal'Ganis (|CFF00F000Caverns of Time: Stratholme|r)",
		[4027] = "The Black Knight (|CFF00F000Heroic Trial of the Champion|r)",
	},
	["Miscellaneous (10)"] = {
    	[1391] = "Malygos (|CFF00F000Eye of Eternity|r)",
		[1392] = "Sartharion (|CFF00F000Chamber of the Aspects|r)",
		[1753] = "Archavon the Stone Watcher (|CFF00F000Wintergrasp|r)",
		[2870] = "Emalon the Storm Watcher (|CFF00F000Wintergrasp|r)",
		[4074] = "Koralon the Flame Watcher (|CFF00F000Wintergrasp|r)",
		[4657] = "Toravon the Ice Watcher (|CFF00F000Wintergrasp|r",
		[4821] = "Halion (|CFF00F000Ruby Sanctum|r",
	},
	["Miscellaneous (25)"] = {
    	[1393] = "Sartharion (|CFF00F000Chamber of the Aspects|r)",
		[1394] = "Malygos (|CFF00F000Eye of Eternity|r)",
		[1754] = "Archavon the Stone Watcher (|CFF00F000Wintergrasp|r)",
		[3236] = "Emalon the Storm Watcher (|CFF00F000Wintergrasp|r)",
		[4075] = "Koralon the Flame Watcher (|CFF00F000Wintergrasp|r)",
		[4658] = "Toravon the Ice Watcher (|CFF00F000Wintergrasp|r",
		[4820] = "Halion (|CFF00F000Ruby Sanctum|r",
	},
	["Naxxramas (10)"] = {
		[1361] = "Anub'Rekhan",
		[1372] = "Gluth",
		[1366] = "Gothik the Harvester",
		[1362] = "Grand Widow Faerlina",
		[1371] = "Grobbulus",
		[1369] = "Heigan the Unclean",
		[1375] = "Four Horsemen",
		[1374] = "Instructor Razuvious",
		[1370] = "Loatheb",
		[1363] = "Maexxna",
		[1365] = "Noth the Plaguebringer",
		[1364] = "Patchwerk",
		[1373] = "Thaddius",
		[1376] = "Sapphiron",
		[1377] = "Kel'Thuzad",
	},
	["Naxxramas (25)"] = {
		[1368] = "Anub'Rekhan",
		[1378] = "Gluth",
		[1379] = "Gothik the Harvester",
		[1380] = "Grand Widow Faerlina",
		[1381] = "Grobbulus kills",
		[1382] = "Heigan the Unclean",
		[1383] = "Four Horsemen",
		[1384] = "Instructor Razuvious",
		[1385] = "Loatheb",
		[1386] = "Maexxna",
		[1387] = "Noth the Plaguebringer",
		[1367] = "Patchwerk",
		[1388] = "Thaddius",
		[1389] = "Sapphiron",
		[1390] = "Kel'Thuzad kills",

	},
	["Secrets of Ulduar (10)"] = {
		[2856] = "Flame Leviathan",
		[2857] = "Razorscale",
		[2858] = "Ignis the Furnace Master",
		[2859] = "XT-002 Deconstructor",
		[2860] = "Assembly of Iron",
		[2861] = "Kologarn",
		[2868] = "Auriaya",
		[2862] = "Hodir",
		[2863] = "Thorim",
		[2864] = "Freya",
		[2865] = "Mimiron",
		[2866] = "General Vezax",
		[2869] = "Yogg-Saron",
		[2867] = "Algalon the Observer",
	},
	["Secrets of Ulduar (25)"] = {
		[2872] = "Flame Leviathan",
		[2873] = "Razorscale",
		[2874] = "Ignis the Furnace Master",
		[2884] = "XT-002 Deconstructor",
		[2885] = "Assembly of Iron",
		[2875] = "Kologarn",
		[2882] = "Auriaya",
		[3256] = "Hodir",
		[3257] = "Thorim",
		[3258] = "Freya",
		[2879] = "Mimiron",
		[2880] = "General Vezax",
		[2883] = "Yogg-Saron",
		[2881] = "Algalon the Observer",
	},
	["Crusader (10)"] = {
		[4028] = "Beasts of Northrend",
		[4032] = "Lord Jaraxxus",
		[4036] = "Faction Champions",
		[4040] = "Val'kyr Twins",
		[4044] = "Anub'arak",
	},

	["Grand Crusader (10)"] = {
		[4030] = "Beasts of Northrend",
		[4033] = "Lord Jaraxxus",
		[4037] = "Faction Champions",
		[4041] = "Val'kyr Twins",
		[4045] = "Anub'arak",
	},
	["Crusader (25)"] = {
		[4031] = "Beasts of Northrend",
		[4034] = "Lord Jaraxxus",
		[4038] = "Faction Champions",
		[4042] = "Val'kyr Twins",
		[4046] = "Anub'arak",
	},
	["Grand Crusader (25)"] = {
		[4029] = "Beasts of Northrend",
		[4035] = "Lord Jaraxxus",
		[4039] = "Faction Champions",
		[4043] = "Val'kyr Twins",
		[4047] = "Anub'arak",
	},
	["Icecrown (10)"] = {
		[4639] = "Lord Morowgar",
		[4643] = "Lady Deathwhisper",
		[4644] = "Gunship Battles",
		[4645] = "Deathbringer",
		[4646] = "Festergut",
		[4647] = "Rotface",
		[4648] = "Blood Prince Council",
		[4649] = "Valithria",
		[4650] = "Professor Putricide",
		[4651] = "Blood Queen Lana'thel",
		[4652] = "Sindragosa",
		[4653] = "Lich King",
	},
	["Heroic Icecrown (10)"] = {
		[4640] = "Lord Morowgar",
		[4654] = "Lady Deathwhisper",
		[4659] = "Gunship Battles",
		[4662] = "Deathbringer",
		[4665] = "Festergut",
		[4668] = "Rotface",
		[4671] = "Blood Prince Council",
		[4674] = "Valithria",
		[4677] = "Professor Putricide",
		[4680] = "Blood Queen Lana'thel",
		[4684] = "Sindragosa",
		[4686] = "Lich King",
	},	
	["Icecrown (25)"] = {
		[4641] = "Lord Morowgar",
		[4655] = "Lady Deathwhisper",
		[4660] = "Gunship Battles",
		[4663] = "Deathbringer",
		[4666] = "Festergut",
		[4669] = "Rotface",
		[4672] = "Blood Prince Council",
		[4675] = "Valithria",
		[4678] = "Professor Putricide",
		[4681] = "Blood Queen Lana'thel",
		[4683] = "Sindragosa",
		[4687] = "Lich King",
	},
	["Heroic Icecrown (25)"] = {
		[4642] = "Lord Morowgar",
		[4656] = "Lady Deathwhisper",
		[4661] = "Gunship Battles",
		[4664] = "Deathbringer",
		[4667] = "Festergut",
		[4670] = "Rotface",
		[4673] = "Blood Prince Council",
		[4676] = "Valithria",
		[4679] = "Professor Putricide",
		[4682] = "Blood Queen Lana'thel",
		[4685] = "Sindragosa",
		[4688] = "Lich King",
	},	
--	["Ice Crown Citadel (10)"] = {
--	},	
}

GS_AchMax = {
	["Dungeons"] = 65,
	["Heroic Dungeons"] = 65,
	["Miscellaneous (10)"] = 35,
	["Miscellaneous (25)"] = 35,
	["Naxxramas (10)"] = 75,
	["Naxxramas (25)"] = 75,
	["Secrets of Ulduar (10)"] = 70,
	["Secrets of Ulduar (25)"] = 70,
	["Crusader (10)"] = 25,
	["Grand Crusader (10)"] = 25,
	["Crusader (25)"] = 25,
	["Grand Crusader (25)"] = 25,
	["Icecrown (10)"] = 60,
	["Icecrown (25)"] = 60,
	["Heroic Icecrown (10)"] = 60,
	["Heroic Icecrown (25)"] = 60,
}

GS_InstanceOrder = {
--	[1] = "Dungeons",
--	[2] = "Heroic Dungeons",
	[1] = "Miscellaneous (10)",
	[2] = "Miscellaneous (25)",
	[3] = "Naxxramas (10)",
	[4] = "Naxxramas (25)",
	[5] = "Secrets of Ulduar (10)",
	[6] = "Secrets of Ulduar (25)",
	[7] = "Crusader (10)",
	[8] = "Crusader (25)",
	[9] = "Grand Crusader (10)",
	[10] = "Grand Crusader (25)",
	[11] = "Icecrown (10)",
	[12] = "Icecrown (25)",
	[13] = "Heroic Icecrown (10)",
	[14] = "Heroic Icecrown (25)",				
}

GS_BackString = {
		[4045] = 108,
		[4046] = 109,
		[1237] = 15,
		[1380] = 43,
		[4047] = 110,
		[2873] = 76,
		[1365] = 35,
		[1508] = 10,
		[2875] = 80,
		[1366] = 27,
		[1382] = 45,
		[1507] = 8,
		[3258] = 84,
		[1373] = 37,
		[1362] = 28,
		[1240] = 21,
		[1383] = 46,
		[4043] = 106,
		[1239] = 19,
		[4041] = 104,
		[2879] = 85,
		[1510] = 14,
		[4039] = 102,
		[1241] = 23,
		[1384] = 47,
		[1234] = 9,
		[4037] = 100,
		[1367] = 51,
		[2881] = 88,
		[4035] = 98,
		[1513] = 20,
		[1369] = 30,
		[1512] = 18,
		[4033] = 96,
		[1506] = 6,
		[4029] = 94,
		[2883] = 87,
		[4031] = 93,
		[2874] = 77,
		[1370] = 33,
		[1386] = 49,
		[4028] = 91,
		[2884] = 78,
		[2870] = 89,
		[2885] = 79,
		[2880] = 86,
		[3257] = 83,
		[1371] = 29,
		[1387] = 50,
		[3256] = 82,
		[2882] = 81,
		[3236] = 90,
		[4030] = 92,
		[2872] = 75,
		[2596] = 39,
		[2856] = 61,
		[1515] = 24,
		[1385] = 48,
		[2866] = 72,
		[2857] = 62,
		[4032] = 95,
		[2864] = 70,
		[1377] = 39,
		[2858] = 63,
		[1389] = 53,
		[2862] = 68,
		[2868] = 67,
		[2859] = 64,
		[4034] = 97,
		[2860] = 65,
		[1231] = 3,
		[1374] = 32,
		[1390] = 54,
		[1505] = 4,
		[1509] = 12,
		[2861] = 66,
		[4036] = 99,
		[1381] = 44,
		[1232] = 5,
		[1375] = 31,
		[1391] = 57,
		[1754] = 60,
		[1753] = 59,
		[2863] = 69,
		[4038] = 101,
		[1238] = 17,
		[1233] = 7,
		[1376] = 38,
		[1392] = 55,
		[1242] = 1,
		[1372] = 26,
		[2865] = 71,
		[4040] = 103,
		[1514] = 22,
		[1361] = 25,
		[1504] = 2,
		[1393] = 56,
		[1364] = 36,
		[1388] = 52,
		[2867] = 74,
		[4042] = 105,
		[4074] = 111,
		[1235] = 11,
		[1378] = 41,
		[1394] = 58,
		[4075] = 112,
		[1511] = 16,
		[2869] = 73,
		[4044] = 107,
		[1368] = 40,
		[1236] = 13,
		[1379] = 42,
		[1363] = 34,
		[4026] = 113,
		[4027] = 114,
		
		[4639] = 115,
		[4640] = 116,
		[4641] = 117,
		[4642] = 118,
		[4643] = 119,
		[4654] = 120,
		[4655] = 121,
		[4656] = 122,
		[4644] = 123,
		[4659] = 124,
		[4660] = 125,
		[4661] = 126,
		[4645] = 127,
		[4662] = 128,
		[4663] = 129,
		[4664] = 130,
		[4646] = 131,
		[4665] = 132,
		[4666] = 133,
		[4667] = 134,
		[4647] = 135,
		[4668] = 136,
		[4669] = 137,
		[4670] = 138,
		[4648] = 139,
		[4671] = 140,
		[4672] = 141,
		[4673] = 142,
		[4649] = 143,
		[4674] = 144,
		[4675] = 145,
		[4676] = 146,
		[4650] = 147,
		[4677] = 148,
		[4678] = 149,
		[4679] = 150,
		[4651] = 151,
		[4680] = 152,
		[4681] = 153,
		[4682] = 154,
		[4652] = 155,
		[4684] = 156,
		[4683] = 157,
		[4685] = 158,
		[4653] = 159,
		[4686] = 160,
		[4687] = 161,
		[4688] = 162,
		[4657] = 163,
		[4658] = 164,
		[4821] = 165,
		[4822] = 166,
		[4820] = 167,
			
	
}