-- Russian (Русский)
-------------------
	function FIZ_InitRuFactionGains()
		if (FIZ_IsAlliance) then
			-- Darnassus
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Darnassus", 4, 8, "[55] Рассветница для Дарнаса", 75, {["Рассветница"]=10})
			FIZ_AddQuest("Darnassus", 4, 8, "[55] Рассветница для Крепости Оперенной Луны", 25, {["Рассветница"]=5})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Альянса"]=10})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Альянса"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Необычное яйцо", 10, {["Необыкновенное яйцо"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Хорошее яйцо", 10, {["Нормальное яйцо"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Обычное яйцо", 10, {["Обычное яйцо"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Плохое яйцо", 2, {["Испорченное яйцо"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Гроздь кристаллов", 19, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Ивус Лесной Властелин", 3, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Небо зовет – флот Ромеона", 3, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Небо зовет – флот Слидора", 3, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Небо зовет – флот Змейера", 3, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Пустые стойла", 2)
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Darnassus", 4, 8, "[60] Больше обломков брони", 3, {["Обломки брони"]=20})
			FIZ_AddItems("Darnassus", 4, 8, 250, {["Рекомендательный значок Дарнаса"]=1})
			-- Exodar
			FIZ_AddQuest("Exodar", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Альянса"]=10})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Альянса"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Гроздь кристаллов", 19, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Ивус Лесной Властелин", 3, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Небо зовет – флот Ромеона", 3, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Небо зовет – флот Слидора", 3, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Небо зовет – флот Змейера", 3, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Пустые стойла", 2)
			FIZ_AddQuest("Exodar", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Exodar", 4, 8, "[60] Больше обломков брони", 3, {["Обломки брони"]=20})
			FIZ_AddItems("Exodar", 4, 8, 250, {["Рекомендательный значок Экзодара"]=1})
			-- Gnomeregan Exiles
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Десять рекомендательных жетоновs", 150, {["Рекомендательный жетон Альянса"]=10})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Альянса"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Гроздь кристаллов", 19, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ивус Лесной Властелин", 3, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Небо зовет – флот Ромеона", 3, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Небо зовет – флот Слидора", 3, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Небо зовет – флот Змейера", 3, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Пустые стойла", 2)
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Больше обломков брони", 3, {["Обломки брони"]=20})
			FIZ_AddItems("Gnomeregan Exiles", 4, 8, 250, {["Рекомендательный значок Гномрегана"]=1})
			-- Stormwind
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Stormwind", 4, 8, "[40] Потерянные припасы", 25, {["Потерянные припасы"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Альянса"]=10})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Альянса"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Гроздь кристаллов", 19, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Ивус Лесной Властелин", 3, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Небо зовет – флот Ромеона", 3, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Небо зовет – флот Слидора", 3, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Небо зовет – флот Змейера", 3, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Пустые стойла", 2)
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Stormwind", 4, 8, "[60] Больше обломков брони", 3, {["Обломки брони"]=20})
			FIZ_AddItems("Stormwind", 4, 8, 250, {["Рекомендательный значок Штормграда"]=1})
			-- Ironforge
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Альянса"]=10})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Альянса"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Гроздь кристаллов", 19, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Ивус Лесной Властелин", 3, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Небо зовет – флот Ромеона", 3, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Небо зовет – флот Слидора", 3, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Небо зовет – флот Змейера", 3, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Пустые стойла", 2)
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Ironforge", 4, 8, "[60] Больше обломков брони", 3, {["Обломки брони"]=20})
			FIZ_AddItems("Ironforge", 4, 8, 250, {["Рекомендательный значок Стальгорна"]=1})
			-- Silverwing Sentinels
			FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Захват флага", 35, false)
			FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Победа на поле боя (3 захвата)", 105, false)
			-- Stormpike Guard
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Гроздь кристаллов", 5, {["Кристалл Бури"]=5})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ивус Лесной Властелин", 1, {["Кристалл Бури"]=1})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Небо зовет – флот Ромеона", 5, {["Жетон командира Северного Волка"]=1})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Небо зовет – флот Слидора", 1, {["Жетон солдата Северного Волка"]=1})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Небо зовет – флот Змейера", 2, {["Жетон лейтенанта Северного Волка"]=1})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Пустые стойла", 1)
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Упряжь ездовых баранов", 2, {["Шкура северного волка"]=1})
			FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Больше обломков брони", 1, {["Обломки брони"]=20})
			-- The League of Arathor
			FIZ_AddInstance("League of Arathor", 4, 8, "Собрано 160 ресурсов", 10, false)
			FIZ_AddInstance("League of Arathor", 4, 8, "Победа на поле боя (1600 ресурсов)", 100, false)
			-- Explorers' League
			FIZ_AddQuest("Explorers' League", 4, 8, "[71] Патрулирование Стальных Ворот", 250)
			FIZ_AddQuest("Explorers' League", 4, 8, "[80] Битва на вражеской территории", 62)
			FIZ_AddQuest("Explorers' League", 4, 8, "[80] Битва у Цитадели", 63)
			FIZ_AddQuest("Explorers' League", 4, 8, "[80] На равных с чемпионами", 62, {["Знак чемпиона"] = 4})
			FIZ_AddQuest("Explorers' League", 4, 8, "[78] Все слишком далеко зашло", 63)
			-- The Frostborn
			FIZ_AddQuest("The Frostborn", 4, 8, "[78] Все слишком далеко зашло", 250)
			FIZ_AddQuest("The Frostborn", 4, 8, "[80] Битва на вражеской территории", 62)
			FIZ_AddQuest("The Frostborn", 4, 8, "[80] Битва у Цитадели", 63)
			FIZ_AddQuest("The Frostborn", 4, 8, "[80] На равных с чемпионами", 62, {["Знак чемпиона"] = 4})
			-- The Silver Covenant
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Клинок, достойный чемпиона", 250, {["Меч Ясеневого озера"]=1})
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Клинок Зимы", 250, {["Клинок Зимы"]=1})
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Достойное оружие", 250, {["Меч Драк'Мара"]=1})
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Тренировка на поле боя", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Большая тренировка", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Теория и практика", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Великая битва", 250, {["Знак искателя славы"] = 3})
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] У вражеских врат", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Битва на вражеской территории", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Битва у Цитадели", 250)
			FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] На равных с чемпионами", 250, {["Знак чемпиона"] = 4})
			-- Valiance Expedition
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[71] Прорвать блокаду", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Атака с воздуха", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Атака пехоты", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Кровь избранных", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Царь горы", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Резня в Черноречье", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] На грани жизни и смерти", 250)
			FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Нападем, пока враг слаб!", 250)
			-- Alliance Vanguard
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Патрулирование Стальных Ворот", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[78] Все слишком далеко зашло", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Клинок, достойный чемпиона", 125, {["Меч Ясеневого озера"]=1})
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Клинок Зимы", 125, {["Клинок Зимы"]=1})
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Достойное оружие", 125, {["Меч Драк'Мара"]=1})
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Тренировка на поле боя", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Большая тренировка", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Теория и практика", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Великая битва", 125, {["Знак искателя славы"] = 3})
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] У вражеских врат", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Битва на вражеской территории", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Битва у Цитадели", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] На равных с чемпионами", 250, {["Знак чемпиона"] = 4})
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Прорвать блокаду", 38)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Атака с воздуха", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Атака пехоты", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Кровь избранных", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Царь горы", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Резня в Черноречье", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] На грани жизни и смерти", 125)
			FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Нападем, пока враг слаб!", 37)
		end
		if (FIZ_IsHorde) then
        	-- Darkspear Trolls
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Орды"]=10})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Орды"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Галлон крови", 19, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Локолар Владыка Льда", 2.5, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Небо зовет – флот Смуггла", 2.5, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Небо зовет – флот Мааши", 2.5, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Небо зовет – флот Маэстра", 2.5, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Пустые стойла", 2.5)
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Упряжь из бараньей кожи", 2.5, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Больше добычи!", 2.5, {["Обломки брони"]=20})
			FIZ_AddItems("Darkspear Trolls", 4, 8, 250, {["Рекомендательный значок Сен'джин"]=1})
			-- Orgrimmar
			FIZ_AddQuest("Orgrimmar", 4, 8, "[24] Пустой бочонок Чена", 75, {["Грозовая железа"]=5,["Слюнная железа Грозового змея"]=1, ["Печень кодо"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Орды"]=10})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Орды"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Галлон крови", 19, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Локолар Владыка Льдаd", 10, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Небо зовет – флот Смуггла", 10, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Небо зовет – флот Мааши", 10, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Небо зовет – флот Маэстра", 10, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Пустые стойла", 10)
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Упряжь из бараньей кожи", 10, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Больше добычи!", 10, {["Обломки брони"]=20})
			FIZ_AddItems("Orgrimmar", 4, 8, 250, {["Рекомендательный значок Оргриммара"]=1})
			-- Silvermoon City
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Орды"]=10})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Орды"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Галлон крови", 19, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Локолар Владыка Льда", 2.5, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Небо зовет – флот Смуггла", 2.5, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Небо зовет – флот Мааши", 2.5, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Небо зовет – флот Маэстра", 2.5, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Пустые стойла", 2.5)
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Упряжь из бараньей кожи", 2.5, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Больше добычи!", 2.5, {["Обломки брони"]=20})
			FIZ_AddItems("Silvermoon City", 4, 8, 250, {["Рекомендательный значок Луносвета"]=1})
			-- Thunder Bluff
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[55] Рассветница для Громового Утеса", 75, {["Рассветница"]=10})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Рекомендательный жетон Орды"]=10})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Один рекомендательный жетон", 5, {["Рекомендательный жетон Орды"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Необычное яйцо", 10, {["Необыкновенное яйцо"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Хорошее яйцо", 10, {["Нормальное яйцо"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Обычное яйцо", 10, {["Обычное яйцо"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Плохое яйцо", 2, {["Испорченное яйцо"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Галлон крови", 19, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Локолар Владыка Льда", 2.5, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Небо зовет – флот Смуггла", 2.5, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Небо зовет – флот Мааши", 2.5, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Небо зовет – флот Маэстра", 2.5, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Пустые стойла", 2.5)
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Упряжь из бараньей кожи", 2.5, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Больше добычи!", 2.5, {["Обломки брони"]=20})
			FIZ_AddItems("Thunder Bluff", 4, 8, 250, {["Рекомендательный значок Громового Утеса"]=1})
			-- Undercity
			FIZ_AddQuest("Undercity", 4, 8, "[60] Больше рунической ткани", 75, {["Руническая ткань"] = 20})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Десять рекомендательных жетонов", 150, {["Horde Commendation Signet"]=10})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Один рекомендательный жетон", 5, {["Horde Commendation Signet"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Галлон крови", 19, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Локолар Владыка Льда", 2.5, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Небо зовет – флот Смуггла", 2.5, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Небо зовет – флот Мааши", 2.5, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Небо зовет – флот Маэстра", 2.5, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Пустые стойла", 2.5)
			FIZ_AddQuest("Undercity", 4, 8, "[60] Упряжь из бараньей кожи", 2.5, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Undercity", 4, 8, "[60] Больше добычи!", 2.5, {["Обломки брони"]=20})
			FIZ_AddItems("Undercity", 4, 8, 250, {["Рекомендательный значок Подгорода"]=1})
			-- Frostwolf Clan
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Галлон крови", 5, {["Кровь солдата Грозовой Вершины"]=5})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Локолар Владыка Льда", 2.5, {["Кровь солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Небо зовет – флот Смуггла", 2.5, {["Плоть солдата Грозовой Вершины"]=1})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Небо зовет – флот Мааши", 2.5, {["Плоть лейтенанта Грозовой Вершины"]=1})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Небо зовет – флот Маэстра", 2.5, {["Плоть командира Грозовой Вершины"]=1})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Пустые стойла", 2.5)
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Упряжь из бараньей кожи", 2.5, {["Шкура альтеракского барана"]=1})
			FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Больше добычи!", 2.5, {["Обломки брони"]=20})
			-- The Defilers
			FIZ_AddInstance("The Defilers", 4, 8, "Собрано 160 ресурсов", 10, false)
			FIZ_AddInstance("The Defilers", 4, 8, "Победа на поле боя (1600 ресурсов)", 100, false)
			-- Warsong Outriders
			FIZ_AddInstance("Warsong Outriders", 4, 8, "Захват флага", 35, false)
			FIZ_AddInstance("Warsong Outriders", 4, 8, "Победа на поле боя (3 захвата)", 105, false)
			 	-- The Hand of Vengeance
		    	-- The Taunka
		    	-- The Sunreavers
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Клинок, достойный чемпиона", 250, {["Меч Ясеневого озера"]=1})
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Клинок Зимы", 250, {["Клинок Зимы"]=1})
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Достойное оружие", 250, {["Меч Драк'Мара"]=1})
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Тренировка на поле боя", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Большая тренировка", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Теория и практика", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Великая битва", 250, {["Знак искателя славы"]=3})
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] У вражеских врат", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Битва на вражеской территории", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Битва у Цитадели", 250)
			FIZ_AddQuest("The Sunreavers", 4, 8, "[80] На равных с чемпионами", 250, {["Знак чемпиона"]=4})
		    	-- Warsong Offensive
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Преследуй по пятам", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Текущий ремонт", 250, {["Рифленая шестеренка"]=4, ["Зубчатое колесо"]=3, ["Тугая пружина"]=2})
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] В военном лазарете", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Искрошить Альянс", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Воздушный десант", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Атака пехоты", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Кровь избранных", 250)
			FIZ_AddQuest("Warsong Offensive", 4, 8, "[80] Царь горы", 250)
			-- Horde Expedition
			FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 250)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Клинок, достойный чемпиона", 125, {["Меч Ясеневого озера"]=1})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Клинок Зимы", 125, {["Клинок Зимы"]=1})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Достойное оружие", 125, {["Меч Драк'Мара"]=1})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Тренировка на поле боя", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Большая тренировка", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Теория и практика", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Великая битва", 125, {["Знак искателя славы"]=3})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] У вражеских врат", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Битва на вражеской территории", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Битва у Цитадели", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] На равных с чемпионами", 125, {["Знак чемпиона"]=4})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Преследуй по пятам", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Текущий ремонт", 125, {["Рифленая шестеренка"]=4, ["Зубчатое колесо"]=3, ["Тугая пружина"]=2})
			FIZ_AddQuest("Horde Expedition", 4, 8, "[74] В военном лазарете", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Искрошить Альянс", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Воздушный десант", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Атака пехоты", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Кровь избранных", 125)
			FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Царь горы", 125)
		end
		-- Argent Dawn
		FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Камни приспешников плети", 50, {["Камень приспешника Плети"] = 20})
		FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Камни захватчиков Плети", 50, {["Камень захватчика Плети"] = 10})
		FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Камни осквернителей Плети", 50, {["Камень осквернителя Плети"] = 1})
		FIZ_AddQuest("Argent Dawn", 4, 8, "Использование Знака доблести Серебряного Рассвета", 100, {["Знак доблести Серебряного Рассвета"] = 1})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Обломки костей", 20, {["Обломки костей"] = 30})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Конечности и панцири некрорахнидов", 20, {["Конечности и панцири некрорахнидов"] = 30})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Средоточие стихий", 20, {["Средоточие Стихий"] = 30})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Лом черного железа", 20, {["Пластины из темного железа"] = 30})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Дикие ростки", 20, {["Дикий росток"] = 30})
		FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Крафтовые задания", 150)
		FIZ_AddQuest("Argent Dawn", 4, 8, "Квесты с котлами", 50)
		FIZ_AddMob("Argent Dawn", 4, 5, "Не элитники в Чумных землях", 10)
		FIZ_AddMob("Argent Dawn", 4, 6, "Элитники в Чумных землях", 10)
		FIZ_AddMob("Argent Dawn", 4, 6, "Лорды Котлов", 30)
		FIZ_AddMob("Argent Dawn", 4, 7, "Треш Стратхолма и Некроситета", 10)
		FIZ_AddMob("Argent Dawn", 4, 8, "Боссы Стратхолма и Некроситета", 50)
		FIZ_AddMob("Argent Dawn", 4, 8, "Барон Ривендер", 100, "Стратхолм")
		FIZ_AddMob("Argent Dawn", 4, 8, "Рас Ледяной Шепот (Некроситет)", 100)
		FIZ_AddInstance("Argent Dawn", 4, 8, "Стратхолм (45 минутный ран)", 850, false)
		FIZ_AddInstance("Argent Dawn", 4, 8, "Некроситет", 1200, false)
		-- Bloodsail Buccaneers
		FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Костоломы и Элитники Пиратской бухты", 25, "Пиратская бухта")
		FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Некоторые мобы Пиратской бухты", 5, "Пиратская бухта")
		FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Большинство мобов Пиратской бухты", 1, "Пиратская бухта")
		FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Джаззрик & Ригглфазз", 1, "Бесплодные земли")
		-- Darkmoon Faire --Ненавижу, блядь, просто ненавижу!
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Маленькие мохнатые лапки", 250, {["Маленькая мохнатая лапка"] = 5}, 500) --Лапки, бля, маленькие, бля...
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Разорванные шкуры", 250, {["Разорванная шкура медведя"] = 5}, 1100)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Мягкие, пушистые хвосты", 250, {["Мягкий пушистый хвост"] = 5}, 1700)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Радужные перья", 250, {["Радужное перо"] = 5}, 2500)
		FIZ_AddQuest("Darkmoon Faire", 4, 5, "Глаза злобных летучих мышей", 250, {["Глаз злобной летучей мыши"] = 10})
		FIZ_AddQuest("Darkmoon Faire", 4, 5, "Светящаяся кровь скорпида", 250, {["Светящаяся кровь скорпида"] = 10})
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Зернистое грузило", 250, {["Зернистое грузило"] = 10}, 500)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Тяжелый точильный камень", 250, {["Тяжелый шлифовальный камень"] = 7}, 1100)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Зеленые железные наручи", 250, {["Зеленые железные наручи"] = 3}, 1700)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Большая черная палица", 250, {["Большая черная палица"] = 1}, 2500)
		FIZ_AddQuest("Darkmoon Faire", 4, 5, "Ритуалы Силы", 250, {["Массивный шлифовальный камень"] = 8})
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Медный регулятор", 250, {["Медный регулятор"] = 5}, 500)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Трещащий бронзовый механизм", 250, {["Трещащий бронзовый механизм"] = 7}, 1100)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Зеленые петарды", 250, {["Зеленая петарда"] = 36}, 1700)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Автоматические ремонтные наборы", 250, {["Автоматический ремонтный набор"] = 6}, 2500)
		FIZ_AddQuest("Darkmoon Faire", 4, 5, "Ториевое устройство", 250, {["Ториевое устройство"] = 6})
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Тисненые кожаные сапоги", 250, {["Тисненые кожаные сапоги"] = 3}, 500)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Кожаные куртки", 250, {["Укрепленный кожаный доспех"] = 3}, 1100)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Гном-гигант!", 250, {["Варварская портупея"] = 3}, 1700)
		FIZ_AddQuest("Darkmoon Faire", 4, 4, "Мальчик-кроколиск и бородатый мурлок", 250, {["Поножи из черепашьего панциря"] = 1}, 2500)
		FIZ_AddQuest("Darkmoon Faire", 4, 5, "Накладки на доспехи", 250, {["Накладки из грубой кожи"] = 8})
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[10] Карты Новолуния: колода Разбойников", 25)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[25] Карты Новолуния: колода Мечей", 25)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[35] Карты Новолуния: колода Магов", 25)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[45] Карты Новолуния: колода Демонов", 25)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Звери", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Элементали", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Порталы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Воины", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Мстители", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Ураганы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Молитвы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Карты Новолуния: Безумцы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Колода карт Новолуния: Нежить", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Колода карт Новолуния: Призмы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Колода карт Новолуния: Аристократы", 350)
		FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Колода карт Новолуния: Хаос", 350)
		-- Gelkis Clan Centaur
		FIZ_AddMob("Gelkis Clan Centaur", 1, 8, "Кентавры клана Маграм", 20)
		-- Magram Clan Centaur
		FIZ_AddMob("Magram Clan Centaur", 1, 8, "Кентавры клана Гелкис", 20)
		-- Keepers of Time
		FIZ_AddInstance("Keepers of Time", 4, 8, "Старые предгорья Хилсбрада", 900, false)
		FIZ_AddInstance("Keepers of Time", 4, 8, "Старые предгорья Хилсбрада", 900, true)
		FIZ_AddInstance("Keepers of Time", 4, 8, "Черные топи", 1110, false)
		FIZ_AddInstance("Keepers of Time", 4, 8, "Черные топи", 1725, true)
		-- Ravenholdt
		FIZ_AddQuest("Ravenholdt", 4, 4, "[24] Эмблемы Синдиката", 250, {["Эмблема Синдиката"] = 1})
		FIZ_AddQuest("Ravenholdt", 4, 8, "[50] Принести лари", 75, {["Тяжелый ларь"] = 5})
		FIZ_AddMob("Ravenholdt", 4, 6, "Все члены синдиката", 5)
		-- Shen'dralar
		FIZ_AddQuest("Shen'dralar", 4, 8, "[54] Манускрипт Средоточия", 500, {["Манускрипт средоточия"] = 1, ["Нетронутый черный алмаз"] = 1, ["Большой сверкающий осколок"] = 4, ["Шкура тени"] = 2})
		FIZ_AddQuest("Shen'dralar", 4, 8, "[54] Манускрипт Скорости", 500, {["анускрипт скорости"] = 1, ["Нетронутый черный алмаз"] = 1, ["Большой сверкающий осколок"] = 2, ["Кровь героев"] = 2})
		FIZ_AddQuest("Shen'dralar", 4, 8, "[54] Манускрипт Защиты", 500, {["Манускрипт защиты"] = 1, ["Нетронутый черный алмаз"] = 1, ["Большой сверкающий осколок"] = 2, ["Истлевшая шовная нить поганища"] = 1})
		FIZ_AddQuest("Shen'dralar", 4, 8, "Классовые книги в Забытом городе", 500)
		-- Syndicate --Есть версия, что нельзя в принципе прокачать репу с синдикатом до превозношения
		FIZ_AddMob("Syndicate", 1, 8, "Мирокос Тихоступ", 5, "Альтеракские горы")
		FIZ_AddMob("Syndicate", 1, 8, "Винстон Вульф", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Лорд Джорах Черный Ворон", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Фахрад", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Зан Кругореззик", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Клякс Громодрев", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Симона Кантрелл", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Господин Канг", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Карло Аврелий", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Убийца из поместья Черного Ворона", 1)
		FIZ_AddMob("Syndicate", 1, 8, "Стражник поместья Черного Ворона", 1)
		-- Thorium Brotherhood -- Братство тория, мать его
		FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Пополнение запасов огненного плавня - королевская кровь", 25, {["Чешуя пламезавра"]=2, ["Уголь"]=1, ["Королевская кровь"]= 4}, FIZ_LIMIT_TYPE_HERB)
		FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Пополнение запасов огненного плавня - железо", 25, {["Чешуя пламезавра"]=2, ["Уголь"]=1, ["Железный слиток"] = 4}, FIZ_LIMIT_TYPE_MINE)
		FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Пополнение запасов огненного плавня - толстая кожа", 25, {["Чешуя пламезавра"]=2, ["Уголь"]=1, ["Толстая кожа"] = 10}, FIZ_LIMIT_TYPE_SKIN)
		FIZ_AddQuest("Thorium Brotherhood", 5, 5, "[45] Завоевать еще большую благосклонность", 25, {["Окалина черного железа"] = 100})
		FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Покровительство братства, черное железо", 75, {["Руда черного железа"] = 10})
		FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Покровительство братства, сердцевинная кожа", 350, {["Кожа Недр"] = 2})
		FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Покровительство братства, кровь горы", 500, {["Кровь Горы"] = 1})
		FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Покровительство братства, огненное ядро", 500, {["Огненное ядро"] = 1})
		FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Покровительство братства, ядро лавы", 500, {["Ядро лавы"] = 1})
		-- Древобрюхи, чтоб они все попередохли
		FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Перья для Нафиэна", 300, {["Перо из головного убора Мертвого Леса"] = 5})
		FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Перья для Гразла", 300, {["Перо из головного убора Мертвого Леса"] = 5})
		FIZ_AddQuest("Timbermaw Hold", 2, 8, "[56] Бусы для Сальфы", 300, {["Бусы духов Зимней Спячки"] = 5})
		FIZ_AddMob("Timbermaw Hold", 2, 6, "Мститель, Дозорный, Садовник, Землепроходец, Шаман м Воин из племени Мертвого Леса", 20, "Оскверненный лес")
		FIZ_AddMob("Timbermaw Hold", 2, 6, "Гонец, Дозорный, Шаман, Землепроходец, Тотемист, и Ведмедь из племени Зимней Спячки", 20, "Зимние Ключи")
		FIZ_AddMob("Timbermaw Hold", 2, 8, "Вождь Кровавая Утроба", 60, "Оскверненный лес")
		FIZ_AddMob("Timbermaw Hold", 2, 8, "Властитель Рор", 60, "Оскверненный лес")
		FIZ_AddMob("Timbermaw Hold", 2, 8, "Лапа Ярости (Редкий)", 50, "Оскверненный лес")
		FIZ_AddMob("Timbermaw Hold", 2, 8, "Гриззл Снежная Лапа (Редкий)", 50)
		FIZ_AddMob("Timbermaw Hold", 2, 8, "Верховный вождь племени Зимней Спячки", 50)
		-- Wintersaber Trainers
		FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Накормить ледопардов", 250)
		FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Вторжение племени Зимней Спячки", 250)
		FIZ_AddQuest("Wintersaber Trainers", 6, 8, "[60] Истребление великанов", 350)
		-- Ashtongue Deathsworn
		FIZ_AddInstance("Ashtongue Deathsworn", 4, 8, "Черный храм", 8000)
		-- Brood of Nozdormu
		FIZ_AddQuest("Brood of Nozdormu", 1, 4, "[60] Рука праведника", 500, {["Обломок силитидского панциря"]=200})
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Анубисат-защитник", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Анубисат-часовой", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Обсидиановый искоренитель", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Киражский плеточник", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Векнисский ядохвост", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Векнисский солдат", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Векнисский острожал", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Векнисский воин", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 4, "Векнисская оса", 100, "Ан'Кираж")
		FIZ_AddMob("Brood of Nozdormu", 1, 8, "Большинство боссов", 50, "Руины Ан'Киража")
		FIZ_AddMob("Brood of Nozdormu", 1, 8, "Оссириан Неуязвимый", 100, "Руины Ан'Киража")
		FIZ_AddMob("Brood of Nozdormu", 1, 8, "Императоры", 200, "Руины Ан'Киража")
		FIZ_AddMob("Brood of Nozdormu", 1, 8, "К'Тун", 2500, "Ан'Киража")
		FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Знаки различия киражского владыки", 500)		-- item
		FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Древний киражский артефакт", 1000)	-- item
		-- Cenarion Circle
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Рутинное задание", 150)
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Талисманы Бездны", 150, {["Талисман Бездны"] = 3})
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Перстни Бездны", 500, {["Перстень Бездны"] = 3})
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Скипетры Бездны", 700, {["Скипетр Бездны"] = 3})
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Тайные послания", 500, {["Зашифрованный Сумеречный текст"] = 10})
		FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Верность Кругу Кенария", 1000)
		FIZ_AddInstance("Cenarion Circle", 4, 8, "Руины Ан'Киража", 1200) -- counting only bosses
		FIZ_AddInstance("Cenarion Circle", 4, 8, "Ан'Кираж", nil) -- no data for full run or bosses
		FIZ_AddMob("Cenarion Circle", 4, 6, "Пламехват из культа Сумеречного Молота", 10)	-- only 0.2 @ 70
		FIZ_AddMob("Cenarion Circle", 4, 8, "Владыка Эверан из культа Сумеречного Молота", 10)	-- only 1 @ 70
		FIZ_AddMob("Cenarion Circle", 4, 8, "Храмовник <Совет Бездны>", 10)
		FIZ_AddMob("Cenarion Circle", 4, 8, "Герцог <Совет Бездны>", 50)
		FIZ_AddMob("Cenarion Circle", 4, 8, "Лорд <Верховный совет Бездны>", 100)
		-- Hydraxian Waterlords
		FIZ_AddMob("Hydraxian Waterlords", 4, 5, "Пустынный грохотун, Вихрь пыли", 5, "Силитус")
		FIZ_AddMob("Hydraxian Waterlords", 4, 5, "Большой обсидиановый элементаль", 5, "Пылающие степи")
		FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Лорд Опалитель", 15, "Глубины Черной горы")
		FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Ураганий (Редкий)", 25, "Силитус")
		FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Пиростраж Углевзор", 50, "Пик Черной горы")
		FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Треш Огненных Недр", 20, "Огненные Недра")
		FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Разрушитель из недр и Лавовые паки", 40, "Огненные Недра")
		FIZ_AddInstance("Hydraxian Waterlords", 4, 7, "Огненные Недра (все боссы)",1050, false)
		FIZ_AddInstance("Hydraxian Waterlords", 8, 8, "Огненные Недра (Golemagg и Рагнарос)",350, false)
		-- The Scale of the Sands
		FIZ_AddQuest("The Scale of the Sands", 4, 4, "[70] Сосуды Вечности", 3000, {["Неполный фиал Вайш"]=1, ["Неполный фиал Келя"]=1})
		FIZ_AddInstance("The Scale of the Sands", 5, 8, "Вершина Хиджала полная зачистка", 6000)
		FIZ_AddMob("The Scale of the Sands", 4, 8, "Треш Хиджала", 12, "Вершина Хиджала")
		FIZ_AddMob("The Scale of the Sands", 4, 8, "Ледяной змей", 60, "Вершина Хиджала")
		FIZ_AddMob("The Scale of the Sands", 4, 8, "Боссы Хиджала", 375, "Вершина Хиджала")
		FIZ_AddMob("The Scale of the Sands", 4, 8, "Архимонд", 1500, "Вершина Хиджала")
		-- The Violet Eye
		FIZ_AddInstance("The Violet Eye", 4, 8, "Полная зачистка Каражана", 6000, false)
		FIZ_AddMob("The Violet Eye", 4, 8, "Боссы Каражана", 250, "Каражан")
		FIZ_AddMob("The Violet Eye", 4, 8, "Треш Каражана", 15, "Каражан")
		-- Zandalar Tribe
		FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Монеты племен: Зулиан, Раззаши и Хаккари", 25, {["Зулианская монета"]=1, ["Монета Раззаши"]=1, ["Монета Хаккари"]=1})
		FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Монеты племен: Песчаная Буря, Дробители Черепов и Кровавый Скальп", 25, {["Монета Песчаной Бури"]=1, ["Монета клана Дробителей Черепов"]=1, ["Монета Кровавого Скальпа"]=1})
		FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Монеты племен: Гурубаши, Порочная Ветвь и Сухокожие", 25, {["Монета Гурубаши"]=1, ["Монета Порочной Ветви"]=1, ["Монета клана Сухокожих"]=1})
		FIZ_AddQuest("Zandalar Tribe", 6, 8, "[60] Защита Джунглей", 500)
		FIZ_AddQuest("Zandalar Tribe", 4, 8, "Драгоценности для Занзы", 75)
		FIZ_AddQuest("Zandalar Tribe", 4, 8, "Почетный знак Зандалара", 50)
		FIZ_AddInstance("Zandalar Tribe", 4, 8, "Зул'Гуруб", 2750)
		-- Booty Bay
		FIZ_AddMob("Booty Bay", 4, 8, "Андре Огнебородый", 5, "Танарис, 73.4 47.1")
		FIZ_AddMob("Booty Bay", 4, 8, "Рабочий, Флибустьер, Пират, Сорвиголова Южных морей", 2.5, "Танарис")
		FIZ_AddMob("Booty Bay", 1, 8, "Калиф Жало Скорпида", 10, "Танарис")
		FIZ_AddMob("Booty Bay", 1, 8, "Убийца, Бандит, Разбойник, Беззаконник, Вор из шайки Скитальцев Пустыни", 2.5, "Танарис")
		FIZ_AddMob("Booty Bay", 4, 8, "Барон Дольноберег", 5, "Степи")
		FIZ_AddMob("Booty Bay", 4, 8, "Грабитель, Канонир, Головорез, Капер Южных морей", 2.5, "Степи")
		FIZ_AddMob("Booty Bay", 4, 7, "Штейгер Коззл", 5, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 1, 7, "Штейгер, Геолог, Дровосек, Механик, Шахтер Торговой Компании", 5, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 1, 7, "Крошшер, Горнорабочий, Геодезист, Ремонтник, Начальник работ Торговой Компании", 5, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 4, 7, "Командир флота Фираллон, Капитан Штиллец, Капитан Кильватель", 25, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 4, 7, "Гарр Просоленное Копыто, Многоглаз, Брут", 25, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 4, 7, "'Красавчик' Дункан", 25, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 4, 6, "Матрос, Старший волхв, Маг, Налетчик из шайки Кровавого Паруса", 5, "Тернистая долина")
		FIZ_AddMob("Booty Bay", 4, 6, "Морской волк, Юнга, Сорвиголова, Чернокнижник из шайки Кровавого Паруса", 5, "Тернистая долина")
		FIZ_AddQuest("Booty Bay", 1, 8, "Новая энергия для уменьшения", 25, {["Ядро элементаля воды"] = 6})
		FIZ_AddQuest("Booty Bay", 1, 8, "Еще раз ослабим великанов", 25, {["Миниатюрный великан"] = 10})
		FIZ_AddQuest("Booty Bay", 1, 8, "[60] Освободите Нотта!", 350, {["Ключ от оков Гордока"] = 1})
		FIZ_AddQuest("Booty Bay", 1, 8, "[60] Броня огров Гордока", 75, {["Рулон рунической ткани"]=4, ["Грубая кожа"]=8, ["Руническая нить"]=2, ["Огрская дубильная кислота"]=1})
		FIZ_AddQuest("Booty Bay", 4, 8, "[44] Награда за воду", 5, {["Бурдюк с водой Скитальцев Пустыни"] = 5})
		-- Gadgetzan
		FIZ_AddMob("Gadgetzan", 4, 7, "Андре Огнебородый", 25, "Танарис, 73.4 47.1")
		FIZ_AddMob("Gadgetzan", 4, 7, "Рабочий, Флибустьер, Пират, Сорвиголова Южных морей", 5, "Танарис")
		FIZ_AddMob("Gadgetzan", 1, 6, "Калиф Жало Скорпида", 20, "Танарис")
		FIZ_AddMob("Gadgetzan", 1, 6, "Убийца, Бандит, Разбойник, Беззаконник, Вор из шайки Скитальцев Пустыни", 5, "Танарис")
		FIZ_AddMob("Gadgetzan", 4, 8, "Барон Дольноберег", 5, "Степи")
		FIZ_AddMob("Gadgetzan", 4, 8, "Грабитель, Канонир, Головорез, Капер Южных морей", 2.5, "Степи")
		FIZ_AddMob("Gadgetzan", 4, 8, "Штейгер Коззл", 2.5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 1, 8, "Штейгер, Геолог, Дровосек, Механик, Шахтер Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 1, 8, "Крошшер, Горнорабочий, Геодезист, Ремонтник, Начальник работ Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 4, 8, "Командир флота Фираллон, Капитан Штиллец, Капитан Кильватель", 5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 4, 8, "Гарр Просоленное Копыто, Многоглаз, Брут", 5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 4, 8, "'Красавчик' Дункан", 5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 4, 8, "Матрос, Старший волхв, Маг, Налетчик из шайки Кровавого Паруса", 2.5, "Тернистая долина")
		FIZ_AddMob("Gadgetzan", 4, 8, "Морской волк, Юнга, Сорвиголова, Чернокнижник из шайки Кровавого Паруса", 2.5, "Тернистая долина")
		FIZ_AddQuest("Gadgetzan", 1, 8, "Новая энергия для уменьшения", 25, {["Ядро элементаля воды"] = 6})
		FIZ_AddQuest("Gadgetzan", 1, 8, "Еще раз ослабим великанов", 25, {["Миниатюрный великан"] = 10})
		FIZ_AddQuest("Gadgetzan", 1, 8, "[60] Освободите Нотта!", 350, {["Ключ от оков Гордока"] = 1})
		FIZ_AddQuest("Gadgetzan", 1, 8, "[60] Броня огров Гордока", 75, {["Рулон рунической ткани"]=4, ["Грубая кожа"]=8, ["Руническая нить"]=2, ["Огрская дубильная кислота"]=1})
		FIZ_AddQuest("Gadgetzan", 4, 8, "[44] Награда за воду", 10, {["Бурдюк с водой Скитальцев Пустыни"] = 5})
		-- Ratchet
		FIZ_AddMob("Ratchet", 4, 8, "Андре Огнебородый", 5, "Танарис, 73.4 47.1")
		FIZ_AddMob("Ratchet", 4, 8, "Рабочий, Флибустьер, Пират, Сорвиголова Южных морей", 2.5, "Танарис")
		FIZ_AddMob("Ratchet", 1, 8, "Калиф Жало Скорпида", 10, "Танарис")
		FIZ_AddMob("Ratchet", 1, 8, "Убийца, Бандит, Разбойник, Беззаконник, Вор из шайки Скитальцев Пустыни", 2.5, "Танарис")
		FIZ_AddMob("Ratchet", 4, 6, "Барон Дольноберег", 25, "Степи")
		FIZ_AddMob("Ratchet", 4, 6, "Грабитель, Канонир, Головорез, Капер Южных морей", 5, "Степи")
		FIZ_AddMob("Ratchet", 4, 8, "Штейгер Коззл", 2.5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 1, 8, "Штейгер, Геолог, Дровосек, Механик, Шахтер Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 1, 8, "Крошшер, Горнорабочий, Геодезист, Ремонтник, Начальник работ Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 4, 8, "Командир флота Фираллон, Капитан Штиллец, Капитан Кильватель", 5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 4, 8, "Гарр Просоленное Копыто, Многоглаз, Брут", 5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 4, 8, "'Красавчик' Дункан", 5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 4, 8, "Матрос, Старший волхв, Маг, Налетчик из шайки Кровавого Паруса", 2.5, "Тернистая долина")
		FIZ_AddMob("Ratchet", 4, 8, "Морской волк, Юнга, Сорвиголова, Чернокнижник из шайки Кровавого Паруса", 2.5, "Тернистая долина")
		FIZ_AddQuest("Ratchet", 1, 8, "Новая энергия для уменьшения", 25, {["Ядро элементаля воды"] = 6})
		FIZ_AddQuest("Ratchet", 1, 8, "Еще раз ослабим великанов", 25, {["Миниатюрный великан"] = 10})
		FIZ_AddQuest("Ratchet", 1, 8, "[60] Освободите Нотта!", 350, {["Ключ от оков Гордока"] = 1})
		FIZ_AddQuest("Ratchet", 1, 8, "[60] Броня огров Гордока", 75, {["Рулон рунической ткани"]=4, ["Грубая кожа"]=8, ["Руническая нить"]=2, ["Огрская дубильная кислота"]=1})
		FIZ_AddQuest("Ratchet", 4, 8, "[44] Награда за воду", 5, {["Бурдюк с водой Скитальцев Пустыни"] = 5})
		-- Everlook --Круговзор
		FIZ_AddMob("Everlook", 4, 8, "Андре Огнебородый", 5, "Танарис, 73.4 47.1")
		FIZ_AddMob("Everlook", 4, 8, "Рабочий, Флибустьер, Пират, Сорвиголова Южных морей", 2.5, "Танарис")
		FIZ_AddMob("Everlook", 1, 8, "Калиф Жало Скорпида", 10, "Танарис")
		FIZ_AddMob("Everlook", 1, 8, "Убийца, Бандит, Разбойник, Беззаконник, Вор из шайки Скитальцев Пустыни", 2.5, "Танарис")
		FIZ_AddMob("Everlook", 4, 8, "Барон Дольноберег", 5, "Степи")
		FIZ_AddMob("Everlook", 4, 8, "Грабитель, Канонир, Головорез, Капер Южных морей", 2.5, "Степи")
		FIZ_AddMob("Everlook", 4, 8, "Штейгер Коззл", 2.5, "Тернистая долина")
		FIZ_AddMob("Everlook", 1, 8, "Штейгер, Геолог, Дровосек, Механик, Шахтер Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Everlook", 1, 8, "Крошшер, Горнорабочий, Геодезист, Ремонтник, Начальник работ Торговой Компании", 2.5, "Тернистая долина")
		FIZ_AddMob("Everlook", 4, 8, "Командир флота Фираллон, Капитан Штиллец, Капитан Кильватель", 5, "Тернистая долина")
		FIZ_AddMob("Everlook", 4, 8, "Гарр Просоленное Копыто, Многоглаз, Брут", 5, "Тернистая долина")
		FIZ_AddMob("Everlook", 4, 8, "'Красавчик' Дункан", 5, "Тернистая долина")
		FIZ_AddMob("Everlook", 4, 8, "Матрос, Старший волхв, Маг, Налетчик из шайки Кровавого Паруса", 2.5, "Теµµµµµрнистая долина")
		FIZ_AddMob("Everlook", 4, 8, "Морской волк, Юнга, Сорвиголова, Чернокнижник из шайки Кровавого Паруса", 2.5, "Тернистая долина")
		FIZ_AddQuest("Everlook", 1, 8, "Новая энергия для уменьшения", 25, {["Ядро элементаля воды"] = 6})
		FIZ_AddQuest("Everlook", 1, 8, "Еще раз ослабим великанов", 25, {["Миниатюрный великан"] = 10})
		FIZ_AddQuest("Everlook", 1, 8, "[60] Освободите Нотта!", 350, {["Ключ от оков Гордока"] = 1})
		FIZ_AddQuest("Everlook", 1, 8, "[60] Броня огров Гордока", 75, {["Рулон рунической ткани"]=4, ["Грубая кожа"]=8, ["Руническая нить"]=2, ["Огрская дубильная кислота"]=1})
		FIZ_AddQuest("Everlook", 4, 8, "[44] Награда за воду", 5, {["Бурдюк с водой Скитальцев Пустыни"] = 5})
		-- Cenarion Expedition
		FIZ_AddInstance("Cenarion Expedition", 4, 5, "Узилище", 650, false)
		FIZ_AddInstance("Cenarion Expedition", 6, 8, "Узилище", 650, true)	-- Trash 5, Bosses 70, no info on full clear
		FIZ_AddInstance("Cenarion Expedition", 4, 5, "Нижетопь", 1000, false)
		FIZ_AddInstance("Cenarion Expedition", 6, 8, "Нижетопь", 1000, true)	-- Trash 7, Bosses 70, no info on full clear
		FIZ_AddInstance("Cenarion Expedition", 4, 8, "Паровое подземелье", 1662, false)
		FIZ_AddInstance("Cenarion Expedition", 4, 8, "Паровое подземелье", 2319, true)
		FIZ_AddQuest("Cenarion Expedition", 4, 5, "[63] Растения Зангартопи", 250, {["Неопознанные части растений"] = 10})
		FIZ_AddQuest("Cenarion Expedition", 4, 6, "[63] Неизвестный науке вид", 500, {["Неизвестный науке вид"] = 1})
		FIZ_AddQuest("Cenarion Expedition", 4, 8, "[67] Готовься к войне", 75, {["Оружие Змеиного Зуба"] = 1})
		FIZ_AddQuest("Cenarion Expedition", 4, 8, "[72] Коллекция ушей", 150, {["Ухо прихвостня Эрнестуэя"] = 15})
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Надзиратель паровой помпы", 1, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Крехтский раб", 2.5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Чернорабочий из племени Отребья", 2.5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Надзиратель из клана Кровавой Чешуи", 5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Волногон из клана Кровавой Чешуи", 5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Колдунья из клана Темного Гребня", 5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Поработитель из клана Темного Гребня", 5, "Зангартопь")
		FIZ_AddMob("Cenarion Expedition", 4, 4, "Жутеклешень", 7, "Зангартопь")
		-- Honor Hold
		FIZ_AddInstance("Honor Hold", 4, 5, "Бастионы Адского Пламени", 600, false)
		FIZ_AddInstance("Honor Hold", 6, 8, "Бастионы Адского Пламени", 2000, true)
		FIZ_AddInstance("Honor Hold", 4, 5, "Кузня Крови", 750, false)
		FIZ_AddInstance("Honor Hold", 6, 8, "Кузня Крови", 2700, true)
		FIZ_AddInstance("Honor Hold", 4, 8, "Разрушенные залы", 1600, false)
		FIZ_AddInstance("Honor Hold", 4, 8, "Разрушенные залы", 2900, true)
		FIZ_AddQuest("Honor Hold", 4, 7, "[60] Штурмовые укрепления", 150)
		FIZ_AddMob("Honor Hold", 4, 4, "Любые из клана Изувеченной Длани", 5, "Полуостров Адского Пламени")
		-- Kurenai --Альянс противный
		FIZ_AddQuest("Kurenai", 4, 8, "[67] Лютые враги", 500, {["Обсидиановые боевые бусы"] = 10})
		FIZ_AddQuest("Kurenai", 4, 8, "[70] Защита Халаа", 500)
		FIZ_AddMob("Kurenai", 4, 8, "Сокрушитель и Мистик из клана Тяжелого Кулака", 10, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Служитель, Сектант и Чароплет бастиона Вечной Скорби", 10, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Маг и Воин из клана Тяжелого Кулака", 10, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Падальщик из племени Темной Крови", 2, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Громила, Разлагатель и Налетчик из племени Темной Крови", 10, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Разоритель и Шаман из клана Боевого Молота", 10, "Награнд")
		FIZ_AddMob("Kurenai", 4, 8, "Громила и Чернокнижник из клана Боевого Молота", 10, "Награнд")
		-- The Mag'har --Орда
		FIZ_AddQuest("The Mag'har", 4, 8, "[67] Покажи свою силу", 500, {["Обсидиановые боевые бусы"] = 10})
		FIZ_AddQuest("The Mag'har", 4, 8, "[70] Враги старые и враги новые", 500)
		FIZ_AddMob("The Mag'har", 4, 8, "Сокрушитель и Мистик из клана Тяжелого Кулака", 10, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Служитель, Сектант и Чароплет бастиона Вечной Скорби", 10, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Маг и Воин из клана Тяжелого Кулака", 10, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Падальщик из племени Темной Крови", 2, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Громила, Разлагатель и Налетчик из племени Темной Крови", 10, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Разоритель и Шаман из клана Боевого Молота", 10, "Награнд")
		FIZ_AddMob("The Mag'har", 4, 8, "Громила и Чернокнижник из клана Боевого Молота", 10, "Награнд")
		-- Ogri'la
		FIZ_AddQuest("Ogri'la", 4, 8, "[70] Излучение реликвии", 350)
		FIZ_AddQuest("Ogri'la", 4, 8, "[70] Нам нужно больше летучих скатов!", 350)
		FIZ_AddQuest("Ogri'la", 4, 8, "[70] Еще разок задать им жару!", 500)
		FIZ_AddQuest("Ogri'la", 6, 8, "[70] Демонов – долой!", 350)
		-- Netherwing
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Собрать их все!", 250, {["Яйцо дракона из стаи Крыльев Пустоты"]=1})
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Пыльца хаотического пыльника", 250, {["Пыльца пустопраха"]=40}, FIZ_LIMIT_TYPE_HERB)
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Хаотитовая Руда", 250, {["Хаотитовая руда"]=40}, FIZ_LIMIT_TYPE_MINE)
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Шкуры живодеров-пустокопов", 250, {["Шкура живодера-пустокопа"]=40}, FIZ_LIMIT_TYPE_SKIN)
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Медленная смерть", 250)
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Недружелюбные небеса", 250, {["Реликвия стаи Крыльев Пустоты"]=10})
		FIZ_AddQuest("Netherwing", 4, 8, "[70] Кристаллы Крыльев Пустоты", 250, {["Кристалл стаи Крыльев Пустоты"]=30})
		FIZ_AddQuest("Netherwing", 5, 8, "[70] Драконы – это не самое страшное", 350)
		FIZ_AddQuest("Netherwing", 5, 8, "[70] Собрать по кусочкам...", 350, {["Груз Копей Пустоты"]=15})
		FIZ_AddQuest("Netherwing", 5, 8, "[70] Ботиранг: Лекарство для нерадивых работников", 350)
		FIZ_AddQuest("Netherwing", 6, 8, "[70] Разрушение Сумеречного Портала", 500)
		FIZ_AddQuest("Netherwing", 7, 8, "[70+] Самая Опасная Ловушка", 500)
		-- Sporeggar
		FIZ_AddMob("Sporeggar", 3, 6, "Болотники, Болотоходы", 15)
		FIZ_AddMob("Sporeggar", 3, 7, "Болотный скрытень", 15)
		FIZ_AddQuest("Sporeggar", 3, 4, "[63] Проблемы спорлингов", 750, {["Мешочек зрелых спор"] = 10})
		FIZ_AddQuest("Sporeggar", 3, 5, "[64] Природные враги", 750, {["Усик болотника"] = 6})
		FIZ_AddQuest("Sporeggar", 3, 5, "[64] Еще усиков!", 750, {["Усик болотника"] = 6})	-- according to wowwiki only till 4, but in game it works till at least 5
		FIZ_AddQuest("Sporeggar", 4, 4, "[64] Грибы-огнешляпки", 750, {["Огнешляпка"] = 10})
		FIZ_AddQuest("Sporeggar", 5, 8, "[64] Раз уж мы по-прежнему друзья...", 750)
		FIZ_AddQuest("Sporeggar", 4, 8, "[64] Новые прорастающие споры", 750, {["Прорастающие споры"] = 6})
		FIZ_AddQuest("Sporeggar", 5, 8, "[65] Принеси мне еще одну клумбу!", 750, {["Кровавый гибискус"] = 5})
		-- Consortium
		FIZ_AddInstance("The Consortium", 4, 5, "Гробницы Маны", 1200, false)
		FIZ_AddInstance("The Consortium", 6, 8, "Гробницы Маны", 2400, true)
		FIZ_AddQuest("The Consortium", 4, 4, "[66] Украсть у вора", 250, {["Осколок кристалла Ошу'гуна"] = 10})
		FIZ_AddQuest("The Consortium", 4, 4, "[66] Кость на вес золота", 250, {["Пара бивней"] = 3})
		FIZ_AddQuest("The Consortium", 5, 8, "[67] Обсидиановое боевое ожерелье", 250, {["Обсидиановые боевые бусы"] = 10})
		FIZ_AddQuest("The Consortium", 5, 8, "[68] Еще одна группа духов Астрала", 250, {["Знак отличия братства Заксис"] = 10})
		FIZ_AddQuest("The Consortium", 6, 8, "[70] Каталог бирок пленников Эфириума", 250, {["Идентификационная табличка пленника Эфириума"] = 1})
		FIZ_AddQuest("The Consortium", 7, 8, "[70] Тысяча миров", 500, {["Ключ от тюрьмы братства Эфириум"] = 5})
		-- Thrallmar
		FIZ_AddInstance("Thrallmar", 4, 5, "Бастионы Адского Пламени", 600, false)
		FIZ_AddInstance("Thrallmar", 7, 8, "Бастионы Адского Пламени", 2000, true)
		FIZ_AddInstance("Thrallmar", 4, 5, "Кузня Крови", 750, false)
		FIZ_AddInstance("Thrallmar", 7, 8, "Кузня Крови", 2700, true)
		FIZ_AddInstance("Thrallmar", 4, 8, "Разрушенные залы", 1600, false)
		FIZ_AddQuest("Thrallmar", 4, 7, "[60] Штурмовые укрепления", 150)
		-- Lower City
		FIZ_AddInstance("Lower City", 4, 5, "Аукенайские гробницы", 750, false)
		FIZ_AddInstance("Lower City", 6, 8, "Аукенайские гробницы", 750, true)
		FIZ_AddInstance("Lower City", 4, 8, "Сетеккские залы", 1080, false)
		FIZ_AddInstance("Lower City", 4, 8, "Сетеккские залы", 1250, true)
		FIZ_AddInstance("Lower City", 4, 8, "Темный лабиринт", 2000, false)
		FIZ_AddInstance("Lower City", 4, 8, "Темный лабиринт", 2700, true)
		FIZ_AddQuest("Lower City", 4, 5, "[65] Затруднительное положение изгнанника", 250, {["Перо араккоа"] = 30})
		-- Sha'tari Skyguard
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Мир Теней", 150, {["Теневая пыль"] = 6})
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Огонь над Скеттисом", 350)
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Побег из Скеттиса", 150)
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Нам нужно больше летучих скатов!", 350)
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Еще разок задать им жару!", 500)
		FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Кровные враги", 350, {["Когти Аккарая"]=1, ["Хребет Каррога"]=1, ["Когти Геззарак"]=1, ["Чешуя Ваккиза"]=1})
		FIZ_AddMob("Sha'tari Skyguard", 4, 6, "Калири Скеттиса", 2.5, "Лес Тероккар, Скеттис")
		FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Затерянныe во времени, Чудовищная калири, прочие в Скеттисе", 10, "Лес Тероккар, Скеттис")
		FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Гневень Клятвы Когтя", 30, "Лес Тероккар, Скеттис")
		FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Темный Крикун Аккарай, Каррог, Геззарак Охотница, Ваккиз Ветрояр", 100, "Лес Тероккар, Скеттис (Вызываются для квеста Кровные враги)")
		FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Терокк", 500, "Лес Тероккар, Скеттис (Вызываемый)")
		-- The Aldor
		FIZ_AddQuest("The Aldor", 1, 3, "[64] Нехватка припасов", 250, {["Ядовитая железа Смертеплета"] = 8})
		FIZ_AddQuest("The Aldor", 4, 5, "[70] Больше знаков Кил'джедена", 250, {["Знак Кил'джедена"] = 10})
		FIZ_AddQuest("The Aldor", 4, 5, "[70] Знак Кил'джедена", 25, {["Знак Кил'джедена"] = 1})
		FIZ_AddQuest("The Aldor", 5, 8, "[70] Больше знаков Саргераса", 250, {["Знак Саргераса"] = 10})
		FIZ_AddQuest("The Aldor", 5, 8, "[70] Знак Саргераса", 25, {["Знак Саргераса"] = 1})
		FIZ_AddQuest("The Aldor", 5, 8, "[64] Очищающий Свет", 350, {["Латные перчатки Скверны"] = 1})
		-- The Scryers
		FIZ_AddQuest("The Scryers", 1, 3, "[64] Видения Ворен'таля", 250, {["Глаз гладкоспинного василиска"] = 8})
		FIZ_AddQuest("The Scryers", 4, 5, "[70] Больше перстней Огнекрылов", 250, {["Перстень Огнекрылов"] = 10})
		FIZ_AddQuest("The Scryers", 4, 5, "[70] Перстень Огнекрылов", 25, {["Перстень Огнекрылов"] = 1})
		FIZ_AddQuest("The Scryers", 5, 8, "[70] Больше перстней Ярости Солнца", 250, {["Перстень Ярости Солнца"] = 10})
		FIZ_AddQuest("The Scryers", 5, 8, "[70] Перстень Ярости Солнца", 25, {["Перстень Ярости Солнца"] = 1})
		FIZ_AddQuest("The Scryers", 5, 8, "[64] Преобразование силы", 350, {["Чародейский фолиант"] = 1})
		-- The Sha'tar
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Больше знаков Кил'джедена", 125, {["Знак Кил'джедена"] = 10})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Знак Кил'джедена", 12.5, {["Знак Кил'джедена"] = 1})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Больше знаков Саргераса", 125, {["Знак Саргераса"] = 10})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Знак Саргераса", 12.5, {["Знак Саргераса"] = 1})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Больше перстней Огнекрылов", 125, {["Перстень Огнекрылов"] = 10})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Перстень Огнекрылов", 12.5, {["Перстень Огнекрылов"] = 1})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Больше перстней Ярости Солнца", 125, {["Перстень Ярости Солнца"] = 10})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Перстень Ярости Солнца", 12.5, {["Перстень Ярости Солнца"] = 1})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Нехватка припасов", 125, {["Ядовитая железа Смертеплета"] = 8})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Видения Ворен'таля", 125, {["Глаз гладкоспинного василиска"] = 8})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Очищающий Свет", 175, {["Латные перчатки Скверны"] = 1})
		FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Преобразование силы", 175, {["Чародейский фолиант"] = 1})
		FIZ_AddInstance("The Sha'tar", 4, 8, "Механар", 1620, false)
		FIZ_AddInstance("The Sha'tar", 4, 8, "Механар", 3000, true)
		FIZ_AddInstance("The Sha'tar", 4, 8, "Ботаника", 2000, false)
		FIZ_AddInstance("The Sha'tar", 4, 8, "Ботаника", 3000, true)
		FIZ_AddInstance("The Sha'tar", 4, 8, "Аркатрац", 1800, false)
		FIZ_AddInstance("The Sha'tar", 4, 8, "Аркатрац", 3000, true)
		-- Shattered Sun Offensive
		-- general
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Обретение преимущества", 250, {["Пыль Пустоты"] = 8}, FIZ_LIMIT_TYPE_GATHER)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Военные планы Ярости Солнца", 250, {["Планы атаки Ярости Солнца"] = 1})
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Мультифазовый подход", 150)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Кровь за кровь", 250)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Взрыв врат", 250)
		-- Phase 1 (till Sun's Reach Sanctum)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Хаотичное поведение", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Охрана святилища", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
		-- Phase 2 (Sun's Reach Sanctum to Sun's Reach Armory)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Сражение за оружейную Солнечного Предела", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Отвлекающий маневр на Тропе Мертвых", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Подпитка для силового поля", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Дальнейшая перенастройка", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Перехват контейнеров с маной", 250, {["Контрабандный контейнер с маной"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 1) -- Phase 2 to 2b
		-- Phase 2B (after Sunwell)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Поддержка портала Солнечного Колодца", 250, {["Контрабандный контейнер с маной"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Знай свою силовую линию!", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
		-- Phase 3 (Armory to Harbor)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Перехватить подкрепление", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Захват гавани", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Битва должна продолжаться!", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Воздушные атаки должны продолжаться!", 150, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Подготовка к работе", 150, {["Железная руда Черноспинов"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 1) -- Phase 3 to 3b
		-- Phase 3b (after Anvil/Forge)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Оружие Ата'мала", 350, {["Очищенный металл Ата'мала"] = 5}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Продолжаем...", 250, {["Железная руда Черноспинов"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
		-- Phase 4 (Harbor to town)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Смотри в корень", 350, {["Корень острого шипа"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 1) -- Phase 4 to 4c
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Зачистить залив Зеленожабрых!", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Загнать врага в угол", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Клинки Рассвета должны быть сокрушены!", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Никто не забыт...", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 1) -- Phase 4 to 4b
		FIZ_AddQuest("Shattered Sun Offensive", 8, 8, "[70] Великодушный благодетель", 500, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
		-- Phase 4b (after Monument)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Щедрое пожертвование", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 2) -- Phase 4b onwards
		-- Phase 4c (after Your Roots)
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] И опять – смотри в корень", 350, {["Корень острого шипа"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards
		FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Взаимовыгодный бизнес", 250, {["Кровяника"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards

		-- Argent Crusade
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Рабы саронитовых шахт", 250)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Тролльский дозор", 350)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Поздравляем!", 500)
		FIZ_AddItems("Argent Crusade", 4, 8, 250, {["Рекомендательный значок Серебряного Авангарда"] = 1})
		FIZ_AddInstance("Argent Crusade", 4, 8, "Зачистка (Накидка)", 800, false)
		FIZ_AddInstance("Argent Crusade", 4, 8, "Зачистка (Накидка)", 2000, true)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] На равных с чемпионами", 250, {["Знак чемпиона"]=4})
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Атака с воздуха", 250)
		-- Frenzyheart Tribe
		FIZ_AddQuest("Frenzyheart Tribe", 1, 5, "[77] Защитник племени Бешеного Сердца", 51000)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Буйство Картака", 700)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Орудия войны", 700)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Тайная сила племени Бешеного Сердца", 700)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Шлем героя", 500)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] И снова цыплята!", 500)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Реджек: первая кровь", 500)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Сила Бури", 500)
		FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Сила озаренной крови", 500)
		-- The Kalu'ak
		FIZ_AddQuest("The Kalu'ak", 4, 8, "[68] Подготовка к самому худшему", 500)
		FIZ_AddQuest("The Kalu'ak", 4, 8, "[71] Планы на будущее", 500)
		FIZ_AddQuest("The Kalu'ak", 4, 8, "[69] Путь к его сердцу...", 500)
		-- Kirin Tor
		FIZ_AddQuest("Kirin Tor", 4, 8, "Ежедневные кулинарные квесты", 195)
		FIZ_AddQuest("Kirin Tor", 4, 8, "Ежедневные рыболовные квесты", 325)
		FIZ_AddQuest("Kirin Tor", 4, 8, "Ежедневные ювелирные квесты", 32, nil, FIZ_LIMIT_TYPE_JEWEL)
		FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Предсказания Времиара: Дейли нормал", 75)
		FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Доказательство смерти: Дейли героик", 75)
		FIZ_AddItems("Kirin Tor", 4, 8, 250, {["Рекомендательный значок Кирин-Тора"] = 1})
		FIZ_AddInstance("Kirin Tor", 4, 8, "Зачистка (Накидка)", 800, false)
		FIZ_AddInstance("Kirin Tor", 4, 8, "Зачистка (Накидка)", 2000, true)
		-- Knights of the Ebon Blade
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Из праха восстаньте!", 250)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Сбор информации", 250, {["Донесения разведки Алого Натиска"]=5})
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Наша метка", 250)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Закрытое воздушное пространство", 250)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Злоб любит огонь!", 250)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Пристрели их", 250)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Гадание по костям", 10, {["Кости врайкула"] = 15})
		FIZ_AddItems("Knights of the Ebon Blade", 4, 8, 250, {["Рекомендательный значок Черного Клинка"] = 1})
		FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Зачистка (Накидка)", 800, false)
		FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Зачистка (Накидка)", 2000, true)
		-- The Oracles
		FIZ_AddQuest("The Oracles", 1, 5, "[77] Длань Оракулов", 23239)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Власть над кристаллами", 700)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Воля Титанов", 700)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Могущество Великих", 700)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Умиротворение Великого камня дождя", 500, {["Драгоценные блестяшки"]=6})
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Песнь Очищения", 500)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Песнь Плодородия", 500)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Песнь Размышления", 500)
		FIZ_AddQuest("The Oracles", 6, 8, "[77] Песнь Ветра и Воды", 500)
		-- The Sons of Hodir
		FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Подношение Ходиру", 250, {["Реликвия Ульдуара"] = 10})
		FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Больше Вечного льда!", 350, {["Осколок Вечного льда"] = 1})
		FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Полировка шлема", 250, {["Вязкое масло"] = 5})
		FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Жар и холод", 250, {["Кусок застывшего железа"] = 5})
		FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Звуки рога Ходира", 250)
		FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Контрразведчик", 350)
		FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Бросая копье Ходира", 500)
		FIZ_AddQuest("The Sons of Hodir", 7, 8, "[80] Муки Арнгрима", 350)
		-- The Wyrmrest Accord
		FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[71] Охота на драконов", 250)
		FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[74] Защита храма Драконьего Покоя", 250)
		FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[80] Асы, ввысь!", 250)
		FIZ_AddItems("The Wyrmrest Accord", 4, 8, 250, {["Рекомендательный значок Храма Драконьего Поко"] = 1})
		FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Зачистка (Накидка)", 800, false)
		FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Зачистка (Накидка)", 2000, true)
		-- Ashen Verdict
		-- todo: add details
	end
	