-- Deutsch (German)
-------------------
function FIZ_InitDeFactionGains()
	if (FIZ_IsAlliance) then
		-- Darnassus
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Darnassus", 4, 8, "[55] Morgenkorn nach Darnassus", 75, {["Morgenkorn"]=10})
		FIZ_AddQuest("Darnassus", 4, 8, "[55] Morgenkorn f\195\188r die Mondfederfeste", 25, {["Morgenkorn"]=5})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Allianz"]=10})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Allianz"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ein au\195\159ergew\195\182hnliches Ei", 10, {["Au\195\159ergew\195\182hnliches Ei"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ein gutes Ei", 10, {["Gutes Ei"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ein gew\195\182hnliches Ei", 10, {["Gew\195\182hnliches Ei"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ein schlechtes Ei", 10, {["Schlechtes Ei"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Darnassus", 4, 8, 250, {["Belobigungsabzeichen von Darnassus"]=1})
		-- Exodar
		FIZ_AddQuest("Exodar", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Allianz"]=10})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Allianz"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Exodar", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Exodar", 4, 8, 250, {["Belobigungsabzeichen der Exodar"]=1})
		-- Gnomeregan Exiles
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Allianz"]=10})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Allianz"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Gnomeregan Exiles", 4, 8, 250, {["Belobigungsabzeichen von Gnomeregan"]=1})
		-- Stormwind
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Stormwind", 4, 8, "[40] The Lost Supplies", 25, {["Lost Supplies"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Allianz"]=10})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Allianz"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Stormwind", 4, 8, 250, {["Belobigungsabzeichen von Sturmwind"]=1})
		-- Ironforge
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Allianz"]=10})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Allianz"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Ironforge", 4, 8, 250, {["Belobigungsabzeichen von Eisenschmiede"]=1})
		-- Silverwing Sentinels
		FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Kriegshymnenschlucht Schlachtfeld Fahne gekapert", 35, false)
		FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Kriegshymnenschlucht Schlachtfeld Sieg (3 Fahnen)", 105, false)
		-- Stormpike Guard
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Haufenweise Kristalle", 18.75, {["Sturmkristall"]=5})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ivus der Waldf\195\188rst", 2.5, {["Sturmkristall"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ruf der L\195\188fte - Ichmans Luftflotte", 2.5, {["Medaille des Kommandanten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ruf der L\195\188fte - Slidores Luftflotte", 2.5, {["Medaille des Soldaten der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ruf der L\195\188fte - Vipores Luftflotte", 2.5, {["Medaille des Leutnants der Frostw\195\182lfe"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Widderzaumzeug", 2.5, {["Frostwolfbalg"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Mehr R\195\188stungsfetzen", 2.5, {["R\195\188stungsfetzen"]=20})
		-- The League of Arathor
		FIZ_AddInstance("The League of Arathor", 4, 8, "Arathibecken 160 Resourcen gesammelt", 10, false)
		FIZ_AddInstance("The League of Arathor", 4, 8, "Arathibecken Sieg (1600 Resourcen)", 100, false)

		-- Explorers' League
	    	FIZ_AddQuest("Explorers' League", 4, 8, "[71] Patrouille am Stählernen Tor", 250)
		-- spillover from Frostborn
		FIZ_AddQuest("Explorers' League", 4, 8, "[78] Zu weit getrieben", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Bedrohung von Oben", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Schlacht vor der Zitadelle", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Unter Champions", 62)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("Explorers' League", 4, 8, "[71] Durchbrecht die Blockade", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Luftangriff", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Bodenangriff", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] König der Berge", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Gemetzel am Schwarzwasser", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Leben oder Tod", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Tritt rein, solang' sie am Boden liegen", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Explorers' League", 4, 8, "Ruf aus Instanzen", 400, false)
		FIZ_AddInstance("Explorers' League", 4, 8, "Ruf aus Instanzen", 800, true)

		-- The Frostborn
		FIZ_AddQuest("The Frostborn", 4, 8, "[78] Zu weit getrieben", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("The Frostborn", 4, 8, "[71] Patrouille am Stählernen Tor", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Bedrohung von Oben", 63)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Schlacht vor der Zitadelle", 63)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Unter Champions", 62)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("The Frostborn", 4, 8, "[71] Durchbrecht die Blockade", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Luftangriff", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Bodenangriff", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] König der Berge", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Gemetzel am Schwarzwasser", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Leben oder Tod", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Tritt rein, solang' sie am Boden liegen", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("The Frostborn", 4, 8, "Ruf aus Instanzen", 400, false)
		FIZ_AddInstance("The Frostborn", 4, 8, "Ruf aus Instanzen", 800, true)

		-- The Silver Covenant
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Auf Winters Schneide", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Eine würdige Waffe", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Feldübung", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Reitgrundlagen", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Feldübungen eines Recken", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Der große Arenakampf", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Bedrohung von Oben", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Die Schlacht zum Gegner tragen", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Schlacht vor der Zitadelle", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Unter Champions", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[71] Patrouille am Stählernen Tor", 62.5)
		-- spillover from Frostborn
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[78] Zu weit getrieben", 62.5)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[71] Durchbrecht die Blockade", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Luftangriff", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Bodenangriff", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] König der Berge", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Gemetzel am Schwarzwasser", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Leben oder Tod", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Tritt rein, solang' sie am Boden liegen", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("The Silver Covenant", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("The Silver Covenant", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- Valiance Expedition
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[71] Durchbrecht die Blockade", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Luftangriff", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Bodenangriff", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Blut der Auserwählten", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] König der Berge", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Gemetzel am Schwarzwasser", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Leben oder Tod", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Tritt rein, solang' sie am Boden liegen", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[71] Patrouille am Stählernen Tor", 62.5)
		-- spillover from Frostborn
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[78] Zu weit getrieben", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Bedrohung von Oben", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Schlacht vor der Zitadelle", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Unter Champions", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Valiance Expedition", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Valiance Expedition", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- Alliance Vanguard
		-- spillover from Explorer's League
	    	FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Patrouille am Stählernen Tor", 125)
		-- spillover from Frostborn
	    	FIZ_AddQuest("Alliance Vanguard", 4, 8, "[78] Zu weit getrieben", 125)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Auf Winters Schneide", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Eine würdige Waffe", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Feldübung", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Reitgrundlagen", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Feldübungen eines Recken", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Der große Arenakampf", 125)
		-- tournament spillover
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Bedrohung von Oben", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Die Schlacht zum Gegner tragen", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Schlacht vor der Zitadelle", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Unter Champions", 125)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Durchbrecht die Blockade", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Luftangriff", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Bodenangriff", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Blut der Auserwählten", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] König der Berge", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Gemetzel am Schwarzwasser", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Leben oder Tod", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Tritt rein, solang' sie am Boden liegen", 125)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)
	end
	if (FIZ_IsHorde) then
		-- Darkspear Trolls
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Horde"]=10})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Horde"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Eine Gallone Blut", 18.75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Lokholar der Eislord", 2.5, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 2.5, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 2.5, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 2.5, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Widderledernes Zaumzeug", 2.5, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Mehr Beute!", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Darkspear Trolls", 4, 8, 250, {["Belobigungsabzeichen von Sen'jin"]=1})
		-- Orgrimmar
		FIZ_AddQuest("Orgrimmar", 4, 8, "[24] Chens leeres F\195\164sschen", 75, {["Blitzschlagdr\195\188se"]=5,["Donnerfalkenspeicheldr\195\188se"]=1, ["Kodoleber"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Horde"]=10})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Horde"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Eine Gallone Blut", 75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Lokholar der Eislord", 10, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 10, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 10, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 10, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Verwaiste St\195\164lle", 10)
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Widderledernes Zaumzeug", 10, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Mehr Beute!", 10, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Orgrimmar", 4, 8, 250, {["Belobigungsabzeichen von Orgrimmar"]=1})
		-- Silvermoon City
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Horde"]=10})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Horde"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Eine Gallone Blut", 18.75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Lokholar der Eislord", 2.5, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 2.5, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 2.5, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 2.5, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Widderledernes Zaumzeug", 2.5, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Mehr Beute!", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Silvermoon City", 4, 8, 250, {["Belobigungsabzeichen von Silbermond"]=1})
		-- Thunder Bluff
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[55] Morrowgrain to Thunder Bluff", 75, {["Morrowgrain"]=10})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Horde"]=10})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Horde"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ein au\195\159ergew\195\182hnliches Ei", 10, {["Au\195\159ergew\195\182hnliches Ei"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ein gutes Ei", 10, {["Gutes Ei"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ein gew\195\182hnliches Ei", 10, {["Gew\195\182hnliches Ei"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ein schlechtes Ei", 10, {["Schlechtes Ei"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Eine Gallone Blut", 18.75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Lokholar der Eislord", 2.5, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 2.5, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 2.5, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 2.5, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Widderledernes Zaumzeug", 2.5, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Mehr Beute!", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Thunder Bluff", 4, 8, 250, {["Belobigungsabzeichen von Donnerfels"]=1})
		-- Undercity
		FIZ_AddQuest("Undercity", 4, 8, "[60] Noch mehr Runenstoff", 75, {["Runenstoff"] = 20})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Zehn Belobigungsabzeichen", 150, {["Belobigungsabzeichen der Horde"]=10})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ein Belobigungsabzeichen", 5, {["Belobigungsabzeichen der Horde"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Eine Gallone Blut", 18.75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Lokholar der Eislord", 2.5, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 2.5, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 2.5, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 2.5, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Undercity", 4, 8, "[60] Widderledernes Zaumzeug", 2.5, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Mehr Beute!", 2.5, {["R\195\188stungsfetzen"]=20})
		FIZ_AddItems("Undercity", 4, 8, 250, {["Belobigungsabzeichen von Unterstadt"]=1})
		-- Frostwolf Clan
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Eine Gallone Blut", 18.75, {["Blut eines Soldaten der Sturmlanzen"]=5})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Lokholar der Eislord", 2.5, {["Blut eines Soldaten der Sturmlanzen"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Ruf der L\195\188fte - Guses Luftflotte", 2.5, {["Fleisch eines Sturmlanzensoldaten"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Ruf der L\195\188fte - Jeztors Luftflotte", 2.5, {["Fleisch eines Sturmlanzenleutnants"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Ruf der L\195\188fte - Mulvericks Luftflotte", 2.5, {["Fleisch eines Sturmlanzenkommandanten"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Verwaiste St\195\164lle", 2.5)
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Widderledernes Zaumzeug", 2.5, {["Alteracwidderbalg"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Mehr Beute!", 2.5, {["R\195\188stungsfetzen"]=20})
		-- The Defilers
		FIZ_AddInstance("The Defilers", 4, 8, "Arathibecken 160 Resourcen gesammelt", 10, false)
		FIZ_AddInstance("The Defilers", 4, 8, "Arathibecken Sieg (1600 Resourcen)", 100, false)
		-- Warsong Outriders
		FIZ_AddInstance("Warsong Outriders", 4, 8, "Kriegshymnenschlucht Schlachtfeld Fahne gekapert", 35, false)
		FIZ_AddInstance("Warsong Outriders", 4, 8, "Kriegshymnenschlucht Schlachtfeld Sieg (3 Fahnen)", 105, false)

		-- The Hand of Vengeance
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keilerei in Schwarzwasser", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Bedrohung von Oben", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Schlacht vor der Zitadelle", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Unter Champions", 62.5)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Haltet sie auf Trab", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Reparaturen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Überfordert!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Schreddert die Allianz", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Luftangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Bodenangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] König der Berge", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- The Taunka
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keilerei in Schwarzwasser", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Bedrohung von Oben", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Schlacht vor der Zitadelle", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Unter Champions", 62.5)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Haltet sie auf Trab", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Reparaturen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Überfordert!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Schreddert die Allianz", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Luftangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Bodenangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] König der Berge", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- The Sunreavers
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Auf Winters Schneide", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Eine würdige Waffe", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Feldübung", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Reitgrundlagen", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Feldübungen eines Recken", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Der große Arenakampf", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Bedrohung von Oben", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Die Schlacht zum Gegner tragen", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Schlacht vor der Zitadelle", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Unter Champions", 250)
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keilerei in Schwarzwasser", 125)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Haltet sie auf Trab", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Reparaturen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Überfordert!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Schreddert die Allianz", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Luftangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Bodenangriff", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blut der Auserwählten", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] König der Berge", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- Warsong Offensive
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Haltet sie auf Trab", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Reparaturen", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Überfordert!", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Schreddert die Allianz", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Luftangriff", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Bodenangriff", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Blut der Auserwählten", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[80] König der Berge", 250)
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keilerei in Schwarzwasser", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Auf Winters Schneide", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine würdige Waffe", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübung", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Reitgrundlagen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübungen eines Recken", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Der große Arenakampf", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Bedrohung von Oben", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Die Schlacht zum Gegner tragen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Schlacht vor der Zitadelle", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Unter Champions", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)

		-- Horde Expedition
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keilerei in Schwarzwasser", 250)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine Klinge, einem Helden angemessen", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Auf Winters Schneide", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Eine würdige Waffe", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübung", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Reitgrundlagen", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Feldübungen eines Recken", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Der große Arenakampf", 125)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Bedrohung von Oben", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Die Schlacht zum Gegner tragen", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Schlacht vor der Zitadelle", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Unter Champions", 125)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Haltet sie auf Trab", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Reparaturen", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Überfordert!", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Schreddert die Allianz", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Luftangriff", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Bodenangriff", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blut der Auserwählten", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] König der Berge", 125)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "�bertragsruf aus Instanzen", 800, true)
	end
	-- Argent Dawn
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Gei\195\159elsteine des Dieners", 50, {["Gei\195\159elstein des Dieners"] = 20})
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Gei\195\159elsteine des Eindringlings", 50, {["Gei\195\159elstein des Eindringlings"] = 10})
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Gei\195\159elsteine des Verderbers", 50, {["Gei\195\159elstein des Verderbers"] = 1})
	FIZ_AddQuest("Argent Dawn", 4, 8, "Ehrenmarke benutzen", 100, {["Ehrenmarke der Argentumd\195\164mmerung"] = 1})

	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Knochenfragmente", 20, {["Knochenfragmente"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Teile einer Gruftbestie", 20, {["Teile einer Gruftbestie"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Kern der Elemente", 20, {["Kern der Elemente"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Dunkeleisenfragmente", 20, {["Dunkeleisenfragmente"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Wildwedel", 20, {["Wildwedel"] = 30})
    	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Handwerksverfügung", 150)

	FIZ_AddQuest("Argent Dawn", 4, 8, "Kessel-Quests", 50)
	FIZ_AddMob("Argent Dawn", 4, 5, "Non-Eliten in den Pestl\195\164ndern", 10)
	FIZ_AddMob("Argent Dawn", 4, 6, "Eliten & Schattenmagier in den Pestl\195\164ndern", 10)
	FIZ_AddMob("Argent Dawn", 4, 6, "Kessellorde", 30)
	FIZ_AddMob("Argent Dawn", 4, 7, "Stratholme & Scholomance Trash", 10)
	FIZ_AddMob("Argent Dawn", 4, 8, "Stratholme & Scholomance Bosse", 50)
	FIZ_AddMob("Argent Dawn", 4, 8, "Baron Totenschwur (Stratholme)", 100)
	FIZ_AddMob("Argent Dawn", 4, 8, "Ras Frostraunen (Scholomance)", 100)
	FIZ_AddInstance("Argent Dawn", 4, 8, "Straholme 45 Minuten Run", 850, false)
	FIZ_AddInstance("Argent Dawn", 4, 8, "Scholomance", 1200, false)
	-- Bloodsail Buccaneers
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Haudrauf von Beutebucht & Eliten", 25, "Beutebucht")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Einge Mobs in Beutebucht", 5, "Beutebucht")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Die meisten Mobs in Beutebucht", 1, "Beutebucht")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Die meisten Mobs in Faldirs Bucht", 5, "Arathi Highlands, Faldirs Bucht")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Jazzrik & Riggelfuzz", 1, "\195\150dland")
	-- Darkmoon Faire
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Kleine pelzige Tatzen", 250, {["Kleine pelzige Tatze"] = 5}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Zerrissene B\195\164renpelze", 250, {["Zerrissener B\195\164renpelz"] = 5}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Weiche buschige Schw\195\164nze", 250, {["Weicher buschiger Schwanz"] = 5}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Farbenpr\195\164chtige Federb\195\188sche", 250, {["Farbenpr\195\164chtiger Federbusch"] = 5}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "B\195\182se Fledermausaugen", 250, {["B\195\182ses Fledermausauge"] = 10})
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Leuchtendes Skorpidblut", 250, {["Leuchtendes Skorpidblut"] = 10})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Grober Gewichtsstein", 250, {["Grober Gewichtsstein"] = 10}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Schwerer Schleifstein", 250, {["Schwerer Schleifstein"] = 7}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Gr\195\188ne Eisenarmschienen", 250, {["Gr\195\188ne Eisenarmschienen"] = 3}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Gro\195\159er schwarzer Streitkolben", 250, {["Gro\195\159er schwarzer Streitkolben"] = 1}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Verdichteter Schleifsteine", 250, {["Verdichteter Schleifstein"] = 8})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Kupfermodulator", 250, {["Kupfermodulator"] = 5}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Surrendes bronzenes Dingsda", 250, {["Surrendes bronzenes Dingsda"] = 7}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Gr\195\188nes Feuerwerk", 250, {["Gr\195\188nes Feuerwerk"] = 36}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Mechanische Repariersets", 250, {["Mechanisches Reparierset"] = 6}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Thoriumapparat", 250, {["Thoriumapparat"] = 6})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Gepr\195\164gte Lederstiefel", 250, {["Gepr\195\164gte Lederstiefel"] = 3}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Gekr\195\164ftigte Lederr\195\188stung", 250, {["Gekr\195\164ftigte Lederr\195\188stung"] = 3}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Barbarischer Harnisch", 250, {["Barbarischer Harnisch"] = 3}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Schildkr\195\182tenschuppengamaschen", 250, {["Schildkr\195\182tenschuppengamaschen"] = 1}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Unverw\195\188stliches R\195\188stungsset", 250, {["Unverw\195\188stliches R\195\188stungsset"] = 8})
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[10] Schurkenkartenset", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[25] Schwertkartenset", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[35] Magierkartenset", 25)
    	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[45] Dämonenkartenset", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Bestienkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Elementarkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Portalkartenset des Dunkelmond-Jahrmarkts", 350)
    	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Kriegsfürstenkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Furienkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Sturmkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Segenskartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Deliriumkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Untodeskartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Prismenkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Adligenkartenset des Dunkelmond-Jahrmarkts", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Chaoskartenset des Dunkelmond-Jahrmarkts", 350)
	-- Gelkis Clan Centaur
	FIZ_AddMob("Gelkis Clan Centaur", 1, 8, "Magramklan Zentauren", 20)
	-- Magram Clan Centaur
	FIZ_AddMob("Magram Clan Centaur", 1, 8, "Gelkisklan Zentauren", 20)
	-- Keepers of Time
	FIZ_AddInstance("Keepers of Time", 4, 8, "Das alte H\195\188gelland (HdZ1)", 900, false)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Das alte H\195\188gelland (HdZ1)", 900, true)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Schwarzer Morast (HdZ2)", 1110, false)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Schwarzer Morast (HdZ2)", 1725, true)
	-- Ravenholdt
	FIZ_AddQuest("Ravenholdt", 4, 4, "[24] Syndikatsembleme", 250, {["Emblem des Syndikats"] = 1})
	FIZ_AddQuest("Ravenholdt", 4, 8, "[50] Plunderkisten ben\195\182tigt", 75, {["Schwere Plunderkiste"] = 5})
	FIZ_AddMob("Ravenholdt", 4, 6, "Alle Syndikat-Mitglieder (nicht grau)", 5)
	FIZ_AddMob("Ravenholdt", 4, 6, "Alle Syndikat-Mitglieder (grau)", 1)
	-- Shen'dralar
	FIZ_AddQuest("Shen'dralar", 4, 8, "Buchb\195\164nde in D\195\188sterbruch", 500)
	FIZ_AddQuest("Shen'dralar", 4, 8, "Klassenb\195\188cher in D\195\188sterbruch", 500)
	-- Syndicate
	FIZ_AddMob("Syndicate", 1, 8, "Myrokos Leisetritt", 5)
	FIZ_AddMob("Syndicate", 1, 8, "Winstone Wolf", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Lord Jorach Rabenholdt", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Fahrad", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Zan Messerritzel", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Smudge Donnerholz", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Simone Cantrell", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Meister Kang", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Carlo Aurelius", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Rabenholdtauftragsm\195\182rder", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Rabenholdtwache", 1)
	-- Thorium Brotherhood
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Nachschub an feurigem Fluxus: K\195\182nigsblut", 25, {["Incendosaurierschuppe"]=2, ["Kohle"]=1, ["K\195\182nigsblut"]= 2}, FIZ_LIMIT_TYPE_HERB)
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Nachschub an feurigem Fluxus: Eisen", 25, {["Incendosaurierschuppe"]=2, ["Kohle"]=1, ["Eisenbarren"] = 2}, FIZ_LIMIT_TYPE_MINE)
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Nachschub an feurigem Fluxus: Schweres Leder", 25, {["Incendosaurierschuppe"]=2, ["Kohle"]=1, ["Schweres Leder"] = 2}, FIZ_LIMIT_TYPE_SKIN)
	FIZ_AddQuest("Thorium Brotherhood", 5, 5, "[45] Erlangte Anerkennung", 25, {["Dunkeleisenr\195\188ckst\195\164nde"] = 4})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Gunst der Bruderschaft, Dunkeleisenerz", 75, {["Dunkeleisenerz"] = 10})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Gunst der Bruderschaft, Kernleder", 350, {["Kernleder"] = 2})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Gunst der Bruderschaft, Blut des Berges", 500, {["Blut des Berges"] = 1})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Gunst der Bruderschaft, Feuerkern", 500, {["Feuerkern"] = 1})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Gunst der Bruderschaft, Lavakern", 500, {["Lavakern"] = 1})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Federn f\195\188r Nafien", 300, {["Kopfputzfeder der Totenwaldfelle"] = 5})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Federn f\195\188r Grazle", 300, {["Kopfputzfeder der Totenwaldfelle"] = 5})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[56] Perlen f\195\188r Salfa", 300, {["Geisterperlen der Winterfelle"] = 5})
	FIZ_AddMob("Timbermaw Hold", 2, 6, "R\195\164cher, H\195\182hlenbeh\195\188ter, Schamane, G\195\164rtner, Pfadfinder & Krieger der Totenwaldfelle", 20)
	FIZ_AddMob("Timbermaw Hold", 2, 6, "L\195\164ufer, H\195\182hlenbeh\195\188ter, Schamane, Totemiker, Pfadfinder & Ursa der Winterfelle", 20)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "H\195\164uptling Blutmagen", 60)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Oberanf\195\188hrer Ror", 60)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Wutpranke (Rar)", 50)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Grizzel Schneepfote (Rar)", 50)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Oberh\195\164uptling der Winterfelle", 50)
	-- Wintersaber Trainers
	FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Frosts\195\164blerverpflegung", 250)
	FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Eindringlinge der Winterfelle", 250)
	FIZ_AddQuest("Wintersaber Trainers", 6, 8, "[60] Tobende Riesen", 350)
	-- Ashtongue Deathsworn
	FIZ_AddInstance("Ashtongue Deathsworn", 4, 8, "Schwarzer Tempel", 8000)
	-- Brood of Nozdormu
	FIZ_AddQuest("Brood of Nozdormu", 1, 4, "[60] Die Hand der Gerechtigkeit", 500)
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Verteidiger des Anubisath", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "W\195\164chter des Anubisath", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Obsidianvernichter", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Wutstachel der Qiraji", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Schwarmkriecher der Vekniss", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Soldat der Vekniss", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Peitscher der Vekniss", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Krieger der Vekniss", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Wespe der Vekniss", 100, "Tempel von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Die meisten Bosse", 50, "Ruinen von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Ossirian", 100, "Ruinen von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Zwillingskaiser", 200, "Ruinen von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Cthun", 2500, "Ruinen von Ahn'Qiraj")
	FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Insignien des Qirajilords", 500)		-- item
	FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Uraltes Qirajiartefakt", 1000)	-- item
	-- Cenarion Circle
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Felddienst", 150)
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssische Wappen", 150, {["Abyssisches Wappen"] = 3})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssische Siegel", 500, {["Abyssisches Siegel"] = 3})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssische Szepter", 300, {["Abyssisches Szepter"] = 1})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Geheime Nachrichten", 500, {["Verschl\195\188sselter Schattenhammertext"] = 10})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Treue zum Zirkel des Cenarius", 1000)
	FIZ_AddInstance("Cenarion Circle", 4, 8, "Ruinen von Ahn'Qiraj", 1200) -- counting only bosses
	FIZ_AddInstance("Cenarion Circle", 4, 8, "Tempel von Ahn'Qiraj", nil) -- no data for full run or bosses
	FIZ_AddMob("Cenarion Circle", 4, 5, "Schattenhammerkultist", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 6, "Flammenh\195\164scher des Schattenhammerklans", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 6, "Bewahrer des Schattenhammers", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 8, "Lord des Schattenhammers Everun", 10)	-- only 1 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssischer Templer", 10)
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssischer F\195\188rst", 50)
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssischer Lord", 100)
	-- Hydraxian Waterlords
	FIZ_AddMob("Hydraxian Waterlords", 4, 5, "W\195\188stenrumpler, Staubst\195\188rmer", 5, "Silithus")
	FIZ_AddMob("Hydraxian Waterlords", 4, 5, "Gro\195\159er Obsidianelementar", 5, "Brennende Steppe")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Lord Incendius", 15, "Schwarzfelstiefen (BRT)")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Hurrikanus (Rar)", 25, "Silithus")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Feuerwache Glutseher", 50, "UBRS")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Geschmolzener Kern Trash", 20, "MC")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Geschmolzener Zerst\195\182rer & Lava Pack", 40, "MC")
	FIZ_AddInstance("Hydraxian Waterlords", 4, 7, "Molten Core (All Bosse)",1050, false)
	FIZ_AddInstance("Hydraxian Waterlords", 8, 8, "Molten Core (Golemagg & Ragnaros)",350, false)
	-- The Scale of the Sands
	FIZ_AddQuest("The Scale of the Sands", 4, 4, "[70] Die Phiolen der Ewigkeit", 3000)
	FIZ_AddInstance("The Scale of the Sands", 5, 8, " Schlacht von Mount Hyjal full clear", 6000)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Trash mobs", 12)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Frostwyrm", 60)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Bosse", 375)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Archimonde", 1500)
	-- The Violet Eye
	FIZ_AddInstance("The Violet Eye", 4, 8, "Karazan full clear", 6000, false)
	FIZ_AddMob("The Violet Eye", 4, 8, "Karazan Bosse", 250, "Karazan")
	FIZ_AddMob("The Violet Eye", 4, 8, "Karazan Trash", 15, "Karazan")
	-- Zandalar Tribe
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] M\195\188nzen der Razzashi, Hakkari und zulianische M\195\188nzen", 25)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] M\195\188nzen der Sandw\195\188ter, Sch\195\164delspalter und Blutskalpe", 25)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] M\195\188nzen der Gurubashi, Blutfratzen und Bleichborken", 25)
	FIZ_AddQuest("Zandalar Tribe", 6, 8, "[60] Der Greuelw\195\164chter", 500)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "Ein Schmuckst\195\188ck zerst\195\182ren", 75)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "Zandalarianische Ehrenm\195\188nze", 50)
	FIZ_AddInstance("Zandalar Tribe", 4, 8, "Zul'Gurub", 2750)
	-- Booty Bay
	FIZ_AddMob("Booty Bay", 1, 8, "Andre Feuerbart", 5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "S\195\188dmeerfreibeuter Dockarbeiter, Freibeuter, Pirat, Schwadroneur", 2.5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Kalif Skorpidstich", 10, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "W\195\188stenl\195\164ufer Auftragsm\195\182rder, Bandit, Schurke, Gesetzloser, Dieb", 2.5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Baron K\195\188stenschipper", 5, "Brachland")
	FIZ_AddMob("Booty Bay", 1, 8, "S\195\188dmeerfreibeuter Brigant, Kanonier, Halsabschneider, Kaperer", 2.5, "Brachland")
	FIZ_AddMob("Booty Bay", 1, 7, "Gro\195\159knecht Cozzle", 5, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 7, "Venture Co. Gro\195\159knecht, Geologe, Holzf\195\164ller, Mechaniker, Minenarbeiter", 5, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 7, "Venture Co. Schredder, Akkordminenarbeiter, Feldmesser, T\195\188ftler, Arbeitsleiter", 5, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 7, "Flottenmeister Firallon, Kapit\195\164n Stillwasser, K\195\164pt'n Kielhohl", 25, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 7, "Garr Salzhoof, Stahlauge, Brutus", 25, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 7, "Sch\195\182nling Duncan", 25, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 6, "Blutsegelbukaniere Deckmatrose, Hochmagus, Magier, R\195\164uber", 5, "Schligendorntal")
	FIZ_AddMob("Booty Bay", 1, 6, "Blutsegelbukaniere Seeb\195\164r, Deckhelfer, Schwadroneur, Hexenmeister", 5, "Schligendorntal")
	FIZ_AddQuest("Booty Bay", 1, 8, "Neuer Treibstoff f\195\188rs Schrumpfen", 25, {["Wasserelementarkerne"] = 6})
	FIZ_AddQuest("Booty Bay", 1, 8, "Und wieder unter den geschrumpften Riesen", 25, {["Schrumpf\195\188berreste"] = 10})
	FIZ_AddQuest("Booty Bay", 1, 8, "[60] Befreit Knot!", 350, {["Gordokfesselschl\195\188ssel"] = 1})
    	FIZ_AddQuest("Booty Bay", 1, 8, "[60] Ogeranzug der Gordok", 75, {["Runenstoffballen"]=4, ["Unverwüstliches Leder"]=8, ["Runenfaden"]=2, ["Ogergerbemittel"]=1})
	FIZ_AddQuest("Booty Bay", 1, 8, "[44] Wasserbeutelkopfgeld", 5, {["Wasserbeutel eines W\195\188stenl\195\164ufers"] = 5})
	FIZ_AddQuest("Booty Bay", 1, 3, "[30] Verrat am Blutsegel", 500, {["Seidenstoff"] = 40, ["Roter Farbstoff"]=4})
	-- Gadgetzan
	FIZ_AddMob("Gadgetzan", 1, 7, "Andre Feuerbart", 25, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 7, "S\195\188dmeerfreibeuter Dockarbeiter, Freibeuter, Pirat, Schwadroneur", 5, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 6, "Kalif Skorpidstich", 20, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 6, "W\195\188stenl\195\164ufer Auftragsm\195\182rder, Bandit, Schurke, Gesetzloser, Dieb", 5, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 8, "Baron K\195\188stenschipper", 5, "Brachland")
	FIZ_AddMob("Gadgetzan", 1, 8, "S\195\188dmeerfreibeuter Brigant, Kanonier, Halsabschneider, Kaperer", 2.5, "Brachland")
	FIZ_AddMob("Gadgetzan", 1, 8, "Gro\195\159knecht Cozzle", 2.5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Venture Co. Gro\195\159knecht, Geologe, Holzf\195\164ller, Mechaniker, Minenarbeiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Venture Co. Schredder, Akkordminenarbeiter, Feldmesser, T\195\188ftler, Arbeitsleiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Flottenmeister Firallon, Kapit\195\164n Stillwasser, K\195\164pt'n Kielhohl", 5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Garr Salzhoof, Stahlauge, Brutus", 5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Sch\195\182nling Duncan", 5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Blutsegelbukaniere Deckmatrose, Hochmagus, Magier, R\195\164uber", 2.5, "Schligendorntal")
	FIZ_AddMob("Gadgetzan", 1, 8, "Blutsegelbukaniere Seeb\195\164r, Deckhelfer, Schwadroneur, Hexenmeister", 2.5, "Schligendorntal")
	FIZ_AddQuest("Gadgetzan", 1, 8, "Neuer Treibstoff f\195\188rs Schrumpfen", 25, {["Wasserelementarkerne"] = 6})
	FIZ_AddQuest("Gadgetzan", 1, 8, "Und wieder unter den geschrumpften Riesen", 25, {["Schrumpf\195\188berreste"] = 10})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[60] Befreit Knot!", 350, {["Gordokfesselschl\195\188ssel"] = 1})
    	FIZ_AddQuest("Gadgetzan", 1, 8, "[60] Ogeranzug der Gordok", 75, {["Runenstoffballen"]=4, ["Unverwüstliches Leder"]=8, ["Runenfaden"]=2, ["Ogergerbemittel"]=1})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[44] Wasserbeutelkopfgeld", 10, {["Wasserbeutel eines W\195\188stenl\195\164ufers"] = 5})
	FIZ_AddQuest("Gadgetzan", 1, 3, "[15] Krieg zur See", 500, {["Magiestoff"] = 40, ["Starker Fluxus"]=4})
	-- Ratchet
	FIZ_AddMob("Ratchet", 1, 8, "Andre Feuerbart", 5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "S\195\188dmeerfreibeuter Dockarbeiter, Freibeuter, Pirat, Schwadroneur", 2.5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "Kalif Skorpidstich", 10, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "W\195\188stenl\195\164ufer Auftragsm\195\182rder, Bandit, Schurke, Gesetzloser, Dieb", 2.5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 6, "Baron K\195\188stenschipper", 25, "Brachland")
	FIZ_AddMob("Ratchet", 1, 6, "S\195\188dmeerfreibeuter Brigant, Kanonier, Halsabschneider, Kaperer", 5, "Brachland")
	FIZ_AddMob("Ratchet", 1, 8, "Gro\195\159knecht Cozzle", 2.5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Venture Co. Gro\195\159knecht, Geologe, Holzf\195\164ller, Mechaniker, Minenarbeiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Venture Co. Schredder, Akkordminenarbeiter, Feldmesser, T\195\188ftler, Arbeitsleiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Flottenmeister Firallon, Kapit\195\164n Stillwasser, K\195\164pt'n Kielhohl", 5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Garr Salzhoof, Stahlauge, Brutus", 5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Sch\195\182nling Duncan", 5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Blutsegelbukaniere Deckmatrose, Hochmagus, Magier, R\195\164uber", 2.5, "Schligendorntal")
	FIZ_AddMob("Ratchet", 1, 8, "Blutsegelbukaniere Seeb\195\164r, Deckhelfer, Schwadroneur, Hexenmeister", 2.5, "Schligendorntal")
	FIZ_AddQuest("Ratchet", 1, 8, "Neuer Treibstoff f\195\188rs Schrumpfen", 25, {["Wasserelementarkerne"] = 6})
	FIZ_AddQuest("Ratchet", 1, 8, "Und wieder unter den geschrumpften Riesen", 25, {["Schrumpf\195\188berreste"] = 10})
	FIZ_AddQuest("Ratchet", 1, 8, "[60] Befreit Knot!", 350, {["Gordokfesselschl\195\188ssel"] = 1})
    	FIZ_AddQuest("Ratchet", 1, 8, "[60] Ogeranzug der Gordok", 75, {["Runenstoffballen"]=4, ["Unverwüstliches Leder"]=8, ["Runenfaden"]=2, ["Ogergerbemittel"]=1})
	FIZ_AddQuest("Ratchet", 1, 8, "[44] Wasserbeutelkopfgeld", 5, {["Wasserbeutel eines W\195\188stenl\195\164ufers"] = 5})
	FIZ_AddQuest("Ratchet", 1, 3, "[15] Heilen alter Wunden", 500, {["Leinenstoff"] = 40, ["Leere Phiole"]=4})
	-- Everlook
	FIZ_AddMob("Everlook", 1, 8, "Andre Feuerbart", 5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "S\195\188dmeerfreibeuter Dockarbeiter, Freibeuter, Pirat, Schwadroneur", 2.5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Kalif Skorpidstich", 10, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "W\195\188stenl\195\164ufer Auftragsm\195\182rder, Bandit, Schurke, Gesetzloser, Dieb", 2.5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Baron K\195\188stenschipper", 5, "Brachland")
	FIZ_AddMob("Everlook", 1, 8, "S\195\188dmeerfreibeuter Brigant, Kanonier, Halsabschneider, Kaperer", 2.5, "Brachland")
	FIZ_AddMob("Everlook", 1, 8, "Gro\195\159knecht Cozzle", 2.5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Venture Co. Gro\195\159knecht, Geologe, Holzf\195\164ller, Mechaniker, Minenarbeiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Venture Co. Schredder, Akkordminenarbeiter, Feldmesser, T\195\188ftler, Arbeitsleiter", 2.5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Flottenmeister Firallon, Kapit\195\164n Stillwasser, K\195\164pt'n Kielhohl", 5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Garr Salzhoof, Stahlauge, Brutus", 5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Sch\195\182nling Duncan", 5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Blutsegelbukaniere Deckmatrose, Hochmagus, Magier, R\195\164uber", 2.5, "Schligendorntal")
	FIZ_AddMob("Everlook", 1, 8, "Blutsegelbukaniere Seeb\195\164r, Deckhelfer, Schwadroneur, Hexenmeister", 2.5, "Schligendorntal")
	FIZ_AddQuest("Everlook", 1, 8, "Neuer Treibstoff f\195\188rs Schrumpfen", 25, {["Wasserelementarkerne"] = 6})
	FIZ_AddQuest("Everlook", 1, 8, "Und wieder unter den geschrumpften Riesen", 25, {["Schrumpf\195\188berreste"] = 10})
	FIZ_AddQuest("Everlook", 1, 8, "[60] Befreit Knot!", 350, {["Gordokfesselschl\195\188ssel"] = 1})
    	FIZ_AddQuest("Everlook", 1, 8, "[60] Ogeranzug der Gordok", 75, {["Runenstoffballen"]=4, ["Unverwüstliches Leder"]=8, ["Runenfaden"]=2, ["Ogergerbemittel"]=1})
	FIZ_AddQuest("Everlook", 1, 8, "[44] Wasserbeutelkopfgeld", 5, {["Wasserbeutel eines W\195\188stenl\195\164ufers"] = 5})
	FIZ_AddQuest("Everlook", 1, 3, "[40] Wiedergutmachung", 500, {["Runenstoff"] = 40, ["Kohle"]=4})
	-- Cenarion Expedition
	FIZ_AddInstance("Cenarion Expedition", 4, 5, "Sklavenunterk\195\188nfte", 650, false)
	FIZ_AddInstance("Cenarion Expedition", 6, 8, "Sklavenunterk\195\188nfte", 650, true)	-- Trash 5, Bosses 70, no info on full clear
	FIZ_AddInstance("Cenarion Expedition", 4, 5, "Tiefensumpf", 1000, false)
	FIZ_AddInstance("Cenarion Expedition", 6, 8, "Tiefensumpf", 1000, true)	-- Trash 7, Bosses 70, no info on full clear
	FIZ_AddInstance("Cenarion Expedition", 4, 8, "Dampfkammer", 1662, false)
	FIZ_AddInstance("Cenarion Expedition", 4, 8, "Dampfkammer", 2319, true)
	FIZ_AddQuest("Cenarion Expedition", 4, 5, "[63] Pflanzen der Zangarmarschen", 250, {["Unbekannte Pflanzenteile"] = 10})
	FIZ_AddQuest("Cenarion Expedition", 4, 6, "[63] Nicht katalogisierte Gattung", 500, {["Nicht katalogisierte Gattung"] = 1})
	FIZ_AddQuest("Cenarion Expedition", 4, 8, "[67] Kriegsvorbereitungen", 75, {["Waffen des Echsenkessels"] = 1})
	FIZ_AddQuest("Cenarion Expedition", 4, 8, "[72] Spitzt die Ohren", 150, {["Ohr von Nesingwarys Lakai"] = 15})
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Dampfpumpenvorarbeiter", 1, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Sklave der Gramlinge", 2.5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Zwangsarbeiter des Lumpenpacks", 2.5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Aufseher der Blutschuppen", 5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Wellenruferin der Blutschuppen", 5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Zauberhexerin der Dunkelk\195\164mme", 5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Sklavenh\195\164ndler der Dunkelk\195\164mme", 5, "Zangarmarschen")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Terrorklaue", 7, "Zangarmarschen")
	-- Honor Hold
	FIZ_AddInstance("Honor Hold", 4, 5, "Bollwerk", 600, false)
	FIZ_AddInstance("Honor Hold", 6, 8, "Bollwerk", 2000, true)
	FIZ_AddInstance("Honor Hold", 4, 5, "Blutkessel", 750, false)
	FIZ_AddInstance("Honor Hold", 6, 8, "Blutkessel", 2700, true)
	FIZ_AddInstance("Honor Hold", 4, 8, "Zerschmetterte Hallen", 1600, false)
	FIZ_AddInstance("Honor Hold", 4, 8, "Zerschmetterte Hallen", 2900, true)
	FIZ_AddQuest("Honor Hold", 4, 7, "[60] H\195\182llenfeuerbefestigungen", 150)
	FIZ_AddMob("Honor Hold", 4, 4, "Mobs der Zerschmetterten Hand", 5, "H\195\182llenfeuerhalbinsel")
	-- Kurenai
	FIZ_AddQuest("Kurenai", 4, 8, "[67] Grimmige Feinde", 500, {["Obsidiankriegsperlen"] = 10})
	FIZ_AddQuest("Kurenai", 4, 8, "[70] Zur Verteidigung von Halaa", 500)
	FIZ_AddMob("Kurenai", 4, 8, "Zermalmer & Mystiker der Felsf\195\164uste", 10, "Nagrand, Ruinen der Brennenden Klinge")
	FIZ_AddMob("Kurenai", 4, 8, "Todesh\195\182riger, Kultisten und Zauberbinder von Kil'sorge", 10, "Nagrand, Burg Kil'Sorge")
	FIZ_AddMob("Kurenai", 4, 8, "Magier und Krieger der Felsf\195\164uste", 10, "Nagrand, Nord- und S\195\188dwindschlucht")
	FIZ_AddMob("Kurenai", 4, 8, "Strauchdieb der Finsterblut", 2, "Nagrand, Sunspring Post")
	FIZ_AddMob("Kurenai", 4, 8, "Schl\195\164ger, L\195\164uterer & R\195\164uber der Finsterblut", 10, "Nagrand, Sonnenwindposten")
	FIZ_AddMob("Kurenai", 4, 8, "H\195\164scher & Schamane der Totschl\195\164ger", 10, "Nagrand, Ruinen des Lachenden Sch\195\164dels")
	FIZ_AddMob("Kurenai", 4, 8, "Schl\195\164ger & Hexenmeister der Totschl\195\164ger", 10, "Nagrand, H\195\188gel der Totschl\195\164ger")
	-- The Mag'har
	FIZ_AddQuest("The Mag'har", 4, 8, "[67] St\195\164rke beweisen", 500, {["Obsidiankriegsperlen"] = 10})
	FIZ_AddQuest("The Mag'har", 4, 8, "[70] Feinde - alte und neue", 500)
	FIZ_AddMob("The Mag'har", 4, 8, "Zermalmer & Mystiker der Felsf\195\164uste", 10, "Nagrand, Ruinen der Brennenden Klinge")
	FIZ_AddMob("The Mag'har", 4, 8, "Todesh\195\182riger, Kultisten und Zauberbinder von Kil'sorge", 10, "Nagrand, Burg Kil'Sorge")
	FIZ_AddMob("The Mag'har", 4, 8, "Magier und Krieger der Felsf\195\164uste", 10, "Nagrand, Nord- und S\195\188dwindschlucht")
	FIZ_AddMob("The Mag'har", 4, 8, "Strauchdieb der Finsterblut", 2, "Nagrand, Sunspring Post")
	FIZ_AddMob("The Mag'har", 4, 8, "Schl\195\164ger, L\195\164uterer & R\195\164uber der Finsterblut", 10, "Nagrand, Sonnenwindposten")
	FIZ_AddMob("The Mag'har", 4, 8, "H\195\164scher & Schamane der Totschl\195\164ger", 10, "Nagrand, Ruinen des Lachenden Sch\195\164dels")
	FIZ_AddMob("The Mag'har", 4, 8, "Schl\195\164ger & Hexenmeister der Totschl\195\164ger", 10, "Nagrand, H\195\188gel der Totschl\195\164ger")
	-- Ogri'la
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] Die Strahlung des Relikts", 350)
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] B\195\164ndigt noch mehr \195\132therrochen!", 350)
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] Und wieder ein Bombenangriff!", 500)
	FIZ_AddQuest("Ogri'la", 6, 8, "[70] Bannt mehr D\195\164monen", 350)
	-- Netherwing
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Immer her mit den Eiern", 250, {["Ei der Netherschwingen"]=1})
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Netherstaubpollen", 250, {["Netherstaubpollen"]=40}, FIZ_LIMIT_TYPE_HERB)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Netheriterz", 250, {["Netheriterz"]=40}, FIZ_LIMIT_TYPE_MINE)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Balg eines Netherminenschinders", 250, {["Balg eines Netherminenschinders"]=40}, FIZ_LIMIT_TYPE_SKIN)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Ein langsamer Tod", 250)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Ein Schatten am Horizont", 250, {["Relikt der Netherschwingen"]=10})
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Kristalle der Netherschwingen", 250, {["Kristall der Netherschwingen"]=30})
	FIZ_AddQuest("Netherwing", 5, 8, "[70] Drachen sind unsere geringste Sorge", 350)
	FIZ_AddQuest("Netherwing", 5, 8, "[70] Die Dinge in den Griff bekommen...", 350, {["Fracht der Netherminen"]=15})
	FIZ_AddQuest("Netherwing", 5, 8, "[70] Der Schuhmerang: Das Mittel gegen den wertlosen Peon", 350)
	FIZ_AddQuest("Netherwing", 6, 8, "[70] Schw\195\164cht das Portal des Zwielichts", 500)
	FIZ_AddQuest("Netherwing", 7, 8, "[70+] Die t\195\182dlichste Falle aller Zeiten", 500)
	-- Sporeggar
	FIZ_AddMob("Sporeggar", 3, 6, "Sumpflord, Sumpfriese", 15)
	FIZ_AddMob("Sporeggar", 3, 7, "Marschenlauerer", 15)
	FIZ_AddQuest("Sporeggar", 3, 4, "[63] Die Misere der Sporlinge", 750, {["Reifer Sporenbeutel"] = 10})
	FIZ_AddQuest("Sporeggar", 3, 5, "[64] Nat\195\188rliche Feinde", 750, {["Sumpflordranke"] = 6})
	FIZ_AddQuest("Sporeggar", 3, 5, "[64] Mehr Ranken!", 750, {["Sumpflordranke"] = 6})	-- according to wowwiki only till 4, but in game it works till at least 5
	FIZ_AddQuest("Sporeggar", 4, 4, "[64] Gl\195\188hkappenpilze", 750, {["Gl\195\188hkappe"] = 10})
	FIZ_AddQuest("Sporeggar", 5, 8, "[64] Jetzt, da wir immer noch Freunde sind...", 750)
	FIZ_AddQuest("Sporeggar", 4, 8, "[64] Noch mehr fruchtbare Sporen", 750, {["Fruchtbare Sporen"] = 6})
	FIZ_AddQuest("Sporeggar", 5, 8, "[65] Bringt mir ein Geb\195\188sch!", 750, {["Bluthibiskus"] = 5})
	-- Consortium
	FIZ_AddInstance("The Consortium", 4, 5, "Managruft", 1200, false)
	FIZ_AddInstance("The Consortium", 6, 8, "Managruft", 2400, true)
	FIZ_AddQuest("The Consortium", 4, 4, "[66] Von Dieben stehlen", 250, {["Kristallfragment von Oshu'gun"] = 10})
	FIZ_AddQuest("The Consortium", 4, 4, "[66] Ein ganzer Kopf voll Elfenbein", 250, {["Paar Elfenbeinsto\195\159z\195\164hne"] = 3})
	FIZ_AddQuest("The Consortium", 5, 8, "[67] Obsidiankriegsperlen", 250, {["Obsidiankriegsperlen"] = 10})
	FIZ_AddQuest("The Consortium", 5, 8, "[68] Ein H\195\188gel voll Astraler", 250, {[" Insignie der Zaxxis"] = 10})
	FIZ_AddQuest("The Consortium", 6, 8, "[70] Geheimnisse des Astraleums", 250, {["Identifikationsmarke eines Gefangenen des Astraleums"] = 1})
	FIZ_AddQuest("The Consortium", 7, 8, "[70] Tausend Welten", 500, {["Gef\195\164ngnisschl\195\188ssel des Astraleums"] = 5})
	FIZ_AddQuest("The Consortium", 4, 8, "Scherbenwelt-Dungeon-Tagesquest (normal)", 250)
	FIZ_AddQuest("The Consortium", 4, 8, "Scherbenwelt-Dungeon-Tagesquest (heroisch)", 350)
	-- Thrallmar
	FIZ_AddInstance("Thrallmar", 4, 5, "Bollwerk", 600, false)
	FIZ_AddInstance("Thrallmar", 6, 8, "Bollwerk", 2000, true)
	FIZ_AddInstance("Thrallmar", 4, 5, "Blutkessel", 750, false)
	FIZ_AddInstance("Thrallmar", 6, 8, "Blutkessel", 2700, true)
	FIZ_AddInstance("Thrallmar", 4, 8, "Zerschmetterte Hallen", 1600, false)
	FIZ_AddInstance("Thrallmar", 4, 8, "Zerschmetterte Hallen", 2900, true)
	FIZ_AddQuest("Thrallmar", 4, 7, "[60] H\195\182llenfeuerbefestigungen", 150)
	-- Lower City
	FIZ_AddInstance("Lower City", 4, 5, "Auchenaikrypta", 750, false)
	FIZ_AddInstance("Lower City", 6, 8, "Auchenaikrypta", 750, true)
	FIZ_AddInstance("Lower City", 4, 8, "Sethekhallen", 1080, false)
	FIZ_AddInstance("Lower City", 4, 8, "Sethekhallen", 1250, true)
	FIZ_AddInstance("Lower City", 4, 8, "Schattenlabyrinth", 2000, false)
	FIZ_AddInstance("Lower City", 4, 8, "Schattenlabyrinth", 2700, true)
	FIZ_AddQuest("Lower City", 4, 5, "[65] Die Pflicht eines Ausgesto\195\159enen", 250, {["Arakkoafeder"] = 30})
	-- Sha'tari Skyguard
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Schattenwelt", 150, {["Schattenstaub"] = 6})
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Feuer \195\188ber Skettis", 350)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Flucht aus Skettis", 150)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] B\195\164ndigt noch mehr \195\132therrochen!", 350)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Und wieder ein Bombenangriff!", 500)
	FIZ_AddMob("Sha'tari Skyguard", 4, 6, "Kaliri von Skettis", 2.5, "W\195\164lder von Terokkar")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Krallenpriester, Zeitverlorene, Monstr\195\182ser Kaliri", 10, "W\195\164lder von Terokkar, Skettis")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Waldw\195\188ter der Krallenanbeter", 30, "W\195\164lder von Terokkar")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Akkarai, Karrog, Gezzarak, Vakkiz", 100, "W\195\164lder von Terokkar (Beschworen f\195\188r Feindesblut)")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Terokk", 500, "W\195\164lder von Terokkar (Beschworen)")
	-- The Aldor
	FIZ_AddQuest("The Aldor", 1, 3, "[64] Schwindende Vorr\195\164te", 250, {["Schreckensgiftbeutel"] = 8})
	FIZ_AddQuest("The Aldor", 4, 5, "[70] Mehr Male von Kil'jaeden", 250, {["Mal von Kil'jaeden"] = 10})
	FIZ_AddQuest("The Aldor", 4, 5, "[70] Einzelne Male von Kil'jaeden", 25, {["Mal von Kil'jaeden"] = 1})
	FIZ_AddQuest("The Aldor", 5, 8, "[70] Mehr Male des Sargeras", 250, {["Mal des Sargeras"] = 10})
	FIZ_AddQuest("The Aldor", 5, 8, "[70] Einzelne Male des Sageras", 25, {["Mal des Sargeras"] = 1})
	FIZ_AddQuest("The Aldor", 5, 8, "[64] Ein reinigendes Licht", 350, {["Teuflische Waffen"] = 1})
	-- The Scryers
	FIZ_AddQuest("The Scryers", 1, 3, "[64] Voren'thals Visionen", 250, {["Auge eines Dunstschuppenbasilisken"] = 8})
	FIZ_AddQuest("The Scryers", 4, 5, "[70] Mehr Siegel der Feuerschwingen", 250, {["Siegel der Feuerschwingen"] = 10})
	FIZ_AddQuest("The Scryers", 4, 5, "[70] Einzelne Siegel der Feuerschwingen", 25, {["Siegel der Feuerschwingen"] = 1})
	FIZ_AddQuest("The Scryers", 5, 8, "[70] Mehr Siegel des Sonnenzorns", 250, {["Siegel des Sonnenzorns"] = 10})
	FIZ_AddQuest("The Scryers", 5, 8, "[70] Einzelne Siegel des Sonnenzorns", 25, {["Siegel des Sonnenzorns"] = 1})
	FIZ_AddQuest("The Scryers", 5, 8, "[64] B\195\188ndelung der Macht", 350, {["Arkaner Foliant"] = 1})
	-- The Sha'tar
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Mehr Male von Kil'jaeden", 125, {["Mal von Kil'jaeden"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Einzelne Male von Kil'jaeden", 12.5, {["Mal von Kil'jaeden"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Mehr Male des Sargeras", 125, {["Mal des Sargeras"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Einzelne Male des Sageras", 12.5, {["Mal des Sargeras"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Mehr Siegel der Feuerschwingen", 125, {["Siegel der Feuerschwingen"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Einzelne Siegel der Feuerschwingen", 12.5, {["Siegel der Feuerschwingen"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Mehr Siegel des Sonnenzorns", 125, {["Siegel des Sonnenzorns"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Einzelne Siegel des Sonnenzorns", 12.5, {["Siegel des Sonnenzorns"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Schwindende Vorr\195\164te", 125, {["Schreckensgiftbeutel"] = 8})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Voren'thals Visionen", 125, {["Auge eines Dunstschuppenbasilisken"] = 8})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Ein reinigendes Licht", 175, {["Teuflische Waffen"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] B\195\188ndelung der Macht", 175, {["Arkaner Foliant"] = 1})
	FIZ_AddInstance("The Sha'tar", 4, 8, "Mechanaar", 1620, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Mechanaar", 3000, true)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Botanikum", 2000, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Botanikum", 3000, true)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Arkatraz", 1800, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Arkatraz", 3000, true)
	-- Shattered Sun Offensive
	-- general
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Einen Vorteil gewinnen", 250, {["Netherr\195\188ckst\195\164nde"] = 8}, FIZ_LIMIT_TYPE_GATHER)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Angriffspl\195\164ne der Sonnenzorn", 250, {["Angriffspl\195\164ne der Sonnenzorn"] = 1})
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die Multiphasen-Vermessung", 150)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Blut f\195\188r Blut", 250)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Vernichtet den Durchgang", 250)
	-- Phase 1 (till Sun's Reach Sanctum)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Unberechenbares Verhalten", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die Barrieren des Sanktums", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
	-- Phase 2 (Sun's Reach Sanctum to Sun's Reach Armory)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die Schlacht um die Waffenkammer der Sonnenweiten", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Ablenkungsman\195\182ver an der Todesschneise", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Fahrt die Barrieren hoch!", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Weitere Konvertierungen", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Manazellen abfangen", 250, {["Eingeschmuggelte Manazelle"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 1) -- Phase 2 to 2b
	-- Phase 2B (after Sunwell)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Das Sonnenbrunnenportal aufrechterhalten", 250, {["Eingeschmuggelte Manazelle"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Kenne deine Leylinien", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
	-- Phase 3 (Armory to Harbor)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Haltet die Verst\195\164rkung auf", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Den Hafen einnehmen", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die Schlacht muss weitergehen", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die Luftangriffe m\195\188ssen weitergehen", 150, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Vorbereitungen", 150, {["Eisenerz der Dunkelflossen"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 1) -- Phase 3 to 3b
	-- Phase 3b (after Anvil/Forge)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Waffen von Ata'mal", 350, {["Gereinigtes Metall von Ata'mal"] = 5}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] H\195\182rt jetzt nicht auf!", 250, {["Eisenerz der Dunkelflossen"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
	-- Phase 4 (Harbor to town)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Die eigenen Wurzeln entdecken", 350, {["Messerdornwurzel"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 1) -- Phase 4 to 4c
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Disrupt the Greengill Coast", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Den Feind vom Leibe halten", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Vernichtet die D\195\164mmerklingen", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Eine milde Gabe", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 1) -- Phase 4 to 4b
	FIZ_AddQuest("Shattered Sun Offensive", 8, 8, "[70] Ein gro\195\159m\195\188tiger Spender", 500, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	-- Phase 4b (after Monument)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Eure weitere Unterst\195\188tzung", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 2) -- Phase 4b onwards
	-- Phase 4c (after Your Roots)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Eure Wurzeln wiederentdecken", 350, {["Messerdornwurzel"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Gesch\195\164ft ge\195\182ffnet", 250, {["Blutbeere"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards
	-- Argent Crusade
	FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Vom Saronit abhängig", 250)
	FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Trollpatrouille", 350)
	FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Herzlichen Glückwunsch!", 500)
	FIZ_AddItems("Argent Crusade", 4, 8, 250, {["	Belobigungsabzeichen des Argentumkreuzzugs"] = 1})
	FIZ_AddInstance("Argent Crusade", 4, 8, "Championing (Wappenrock)", 800, false)
	FIZ_AddInstance("Argent Crusade", 4, 8, "Championing (Wappenrock)", 2000, true)
	if not FIZ_IsDeathKnight then
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Bedrohung von oben", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Die Schlacht zum Gegner tragen", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Schlacht vor der Zitadelle", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Unter Champions", 325)
	end
	-- Frenzyheart Tribe
	FIZ_AddQuest("Frenzyheart Tribe", 1, 5, "[77] Champion der Wildherzen", 51000)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Kartaks Wut", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Instrument des Krieges", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Geheime Kraft der Wildherzen", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Des Helden Helm", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Hühnerparty!", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Rejek: Erstes Blut", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Kraft des Sturms", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Des Herzbluts Stärke", 500)
	-- The Kalu'ak
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] Auf das Schlimmste gefasst sein", 500)
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] Zukunftsplanungen", 500)
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] Der Weg zu seinem Herzen...", 500)
	-- Kirin Tor
	FIZ_AddQuest("Kirin Tor", 4, 8, "Dalaran Koch-Tagesquest", 195)
	FIZ_AddQuest("Kirin Tor", 4, 8, "Dalaran Angel-Tagesquest", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Durchnässtes Rezept", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Versiegelte Giftphiole", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "Juwelenschleifen Tagesquest", 32, nil, FIZ_LIMIT_TYPE_JEWEL)
	FIZ_AddItems("Kirin Tor", 4, 8, 520, {["Belobigungsabzeichen der Kirin Tor"] = 1})
	FIZ_AddInstance("Kirin Tor", 4, 8, "Championing (Wappenrock)", 800, false)
	FIZ_AddInstance("Kirin Tor", 4, 8, "Championing (Wappenrock)", 2000, true)
	-- Knights of the Ebon Blade
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Erhebt euch von den Toten!", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Informationsbeschaffung", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Setzt ein Zeichen", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Flugsperrzone", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Ekel mag Feuer!!", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Schießt sie ab!", 250)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] In den Knochen lesen", 10, {["Vrykulknochen"] = 15})
	FIZ_AddItems("Knights of the Ebon Blade", 4, 8, 520, {["Belobigungsabzeichen der Schwarzen Klinge"] = 1})
	FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Championing (Wappenrock)", 800, false)
	FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Championing (Wappenrock)", 2000, true)
	if FIZ_IsDeathKnight then
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Bedrohung von oben", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Die Schlacht zum Gegner tragen", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Schlacht vor der Zitadelle", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Unter Champions", 325)
	end
	-- The Oracles
	FIZ_AddQuest("The Oracles", 1, 5, "[77] Hand der Orakel", 23239)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Beherrschen der Kristalle", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Wille der Titanen", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Macht der Großen", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Besänftigung des großen Regensteins", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Ein reinigendes Lied", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Lied der Fruchtbarkeit", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Lied der Besinnung", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Lied von Wind und Wasser", 500)
	-- The Sons of Hodir
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Hodirs Tribut", 650, {["Relikt von Ulduar"] = 10})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Vergesst das Immerfrosteis nicht!", 455, {["Immerfrostsplitter"] = 1})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Den Helm polieren", 455, {["Viskoses Öl"] = 5})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Heiß und kalt", 455, {["Gefrorener Eisenschrott"] = 5})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Hodirs Horn blasen", 455)
	FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Jagd auf Spione", 455)
	FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Hodirs Speer werfen", 650)
	FIZ_AddQuest("The Sons of Hodir", 7, 8, "[80] Arngrim füttern", 455)
	FIZ_AddItems("The Sons of Hodir", 4, 8, 520, {["Belobigungsabzeichen der Söhne von Hodir"] = 1})
	-- The Wyrmrest Accord
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[71] Drachenjagd", 325)
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[74] Verteidigt den Wyrmruhtempel", 325)
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[80] Schlacht in den Wolken!", 325)
	FIZ_AddItems("The Wyrmrest Accord", 4, 8, 520, {["Belobigungsabzeichen des Wyrmruhpakts"] = 1})
	FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Championing (Wappenrock)", 800, false)
	FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Championing (Wappenrock)", 2000, true)
	-- The Ashen Verdict
	FIZ_AddInstance("The Ashen Verdict", 4, 8, "Eiskronenzitadelle 10 (full clear)", 2070, false)
end
