function FIZ_InitEnFactionGains()
	if (FIZ_IsAlliance) then
		-- Darnassus
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Darnassus", 4, 8, "[55] Morrowgrain to Darnassus", 75, {["Morrowgrain"]=10})
		FIZ_AddQuest("Darnassus", 4, 8, "[55] Morrowgrain to Feathermoon Stronghold", 25, {["Morrowgrain"]=5})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ten Commendation Signets", 150, {["Alliance Commendation Signet"]=10})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] One Commendation Signet", 5, {["Alliance Commendation Signet"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] An Extraordinary Egg", 10, {["Extraordinary Egg"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] A Fine Egg", 10, {["Fine Egg"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] An Ordinary Egg", 10, {["Ordinary Egg"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] A Bad Egg", 10, {["Bad Egg"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Crystal Cluster", 18.75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ivus The Forest Lord", 2.5, {["Storm Crystal"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Call of Air: Ichman's Fleet", 2.5, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Call of Air: Slidore's Fleet", 2.5, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Call of Air: Vipore's Fleet", 2.5, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Darnassus", 4, 8, "[60] Ram Riding Harnesses", 2.5, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Darnassus", 4, 8, "[60] More Armor Scraps", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Darnassus", 4, 8, 250, {["Darnassus Commendation Badge"]=1})
		-- Exodar
		FIZ_AddQuest("Exodar", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ten Commendation Signets", 150, {["Alliance Commendation Signet"]=10})
		FIZ_AddQuest("Exodar", 4, 8, "[60] One Commendation Signet", 5, {["Alliance Commendation Signet"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Crystal Cluster", 18.75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ivus The Forest Lord", 2.5, {["Storm Crystal"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Call of Air: Ichman's Fleet", 2.5, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Call of Air: Slidore's Fleet", 2.5, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Call of Air: Vipore's Fleet", 2.5, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Exodar", 4, 8, "[60] Ram Riding Harnesses", 2.5, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Exodar", 4, 8, "[60] More Armor Scraps", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Exodar", 4, 8, 250, {["Exodar Commendation Badge"]=1})
		-- Gnomeregan Exiles
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ten Commendation Signets", 150, {["Alliance Commendation Signet"]=10})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] One Commendation Signet", 5, {["Alliance Commendation Signet"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Crystal Cluster", 18.75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ivus The Forest Lord", 2.5, {["Storm Crystal"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Call of Air: Ichman's Fleet", 2.5, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Call of Air: Slidore's Fleet", 2.5, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Call of Air: Vipore's Fleet", 2.5, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] Ram Riding Harnesses", 2.5, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Gnomeregan Exiles", 4, 8, "[60] More Armor Scraps", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Gnomeregan Exiles", 4, 8, 250, {["Gnomeregan Commendation Badge"]=1})
		-- Stormwind
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Stormwind", 4, 8, "[40] The Lost Supplies", 25, {["Lost Supplies"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ten Commendation Signets", 150, {["Alliance Commendation Signet"]=10})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] One Commendation Signet", 5, {["Alliance Commendation Signet"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Crystal Cluster", 18.75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ivus The Forest Lord", 2.5, {["Storm Crystal"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Call of Air: Ichman's Fleet", 2.5, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Call of Air: Slidore's Fleet", 2.5, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Call of Air: Vipore's Fleet", 2.5, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Stormwind", 4, 8, "[60] Ram Riding Harnesses", 2.5, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Stormwind", 4, 8, "[60] More Armor Scraps", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Stormwind", 4, 8, 250, {["Stormwind Commendation Badge"]=1})
		-- Ironforge
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ten Commendation Signets", 150, {["Alliance Commendation Signet"]=10})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] One Commendation Signet", 5, {["Alliance Commendation Signet"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Crystal Cluster", 75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ivus The Forest Lord", 10, {["Storm Crystal"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Call of Air: Vipore's Fleet", 10, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Call of Air: Slidore's Fleet", 10, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Call of Air: Ichman's Fleet", 10, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Empty Stables", 10)
		FIZ_AddQuest("Ironforge", 4, 8, "[60] Ram Riding Harnesses", 10, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Ironforge", 4, 8, "[60] More Armor Scraps", 10, {["Armor Scraps"]=20})
		FIZ_AddItems("Ironforge", 4, 8, 250, {["Ironforge Commendation Badge"]=1})
		-- Silverwing Sentinels
		FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Warsong BG Flag Capture", 35, false)
		FIZ_AddInstance("Silverwing Sentinels", 4, 8, "Warsong BG Win (3 Capturese)", 105, false)
		-- Stormpike Guard
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Crystal Cluster", 18.75, {["Storm Crystal"]=5})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ivus The Forest Lord", 2.5, {["Storm Crystal"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Call of Air: Ichman's Fleet", 2.5, {["Frostwolf Commander's Medal"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Call of Air: Slidore's Fleet", 2.5, {["Frostwolf Soldier's Medal"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Call of Air: Vipore's Fleet", 2.5, {["Frostwolf Lieutenant's Medal"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] Ram Riding Harnesses", 2.5, {["Frostwolf Hide"]=1})
		FIZ_AddQuest("Stormpike Guard", 4, 8, "[60] More Armor Scraps", 2.5, {["Armor Scraps"]=20})
		-- The League of Arathor
		FIZ_AddInstance("The League of Arathor", 4, 8, "Arathi Basin collect 160 Resources", 10, false)
		FIZ_AddInstance("The League of Arathor", 4, 8, "Arathi Basin Win (1600 Resources)", 100, false)

		-- Explorers' League
		FIZ_AddQuest("Explorers' League", 4, 8, "[71] Steel Gate Patrol", 250)
		-- spillover from Frostborn
		FIZ_AddQuest("Explorers' League", 4, 8, "[78] Pushed Too Far", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Learning The Reins ", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Among the Champions", 62.5)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("Explorers' League", 4, 8, "[71] Break the Blockade", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Assault by Air", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Assault by Ground", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] Blood of the Chosen", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[80] King of the Mountain", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Blackriver Skirmish", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Life or Death", 62.5)
		FIZ_AddQuest("Explorers' League", 4, 8, "[73] Kick'em While They're Down", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Explorers' League", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Explorers' League", 4, 8, "Spillover rep from dungeons", 800, true)

		-- The Frostborn
		FIZ_AddQuest("The Frostborn", 4, 8, "[78] Pushed Too Far", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("The Frostborn", 4, 8, "[71] Steel Gate Patrol", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Learning The Reins ", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Among the Champions", 62.5)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("The Frostborn", 4, 8, "[71] Break the Blockade", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Assault by Air", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Assault by Ground", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] Blood of the Chosen", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[80] King of the Mountain", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Blackriver Skirmish", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Life or Death", 62.5)
		FIZ_AddQuest("The Frostborn", 4, 8, "[73] Kick'em While They're Down", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("The Frostborn", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("The Frostborn", 4, 8, "Spillover rep from dungeons", 800, true)

		-- The Silver Covenant
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] A Blade Fit For A Champion", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] The Edge Of Winter", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] A Worthy Weapon", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Training In The Field", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Learning The Reins ", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] A Valiant's Field Training", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] The Grand Melee", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Threat From Above", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Taking Battle To The Enemy", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Battle Before The Citadel", 250)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Among the Champions", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[71] Steel Gate Patrol", 62.5)
		-- spillover from Frostborn
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[78] Pushed Too Far", 62.5)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[71] Break the Blockade", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Assault by Air", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Assault by Ground", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] Blood of the Chosen", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[80] King of the Mountain", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Blackriver Skirmish", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Life or Death", 62.5)
		FIZ_AddQuest("The Silver Covenant", 4, 8, "[73] Kick'em While They're Down", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("The Silver Covenant", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("The Silver Covenant", 4, 8, "Spillover rep from dungeons", 800, true)

		-- Valiance Expedition
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[71] Break the Blockade", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Assault by Air", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Assault by Ground", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Blood of the Chosen", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] King of the Mountain", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Blackriver Skirmish", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Life or Death", 250)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[73] Kick'em While They're Down", 250)
		-- spillover from Explorer's League
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[71] Steel Gate Patrol", 62.5)
		-- spillover from Frostborn
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[78] Pushed Too Far", 62.5)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Learning The Reins ", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("Valiance Expedition", 4, 8, "[80] Among the Champions", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Valiance Expedition", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Valiance Expedition", 4, 8, "Spillover rep from dungeons", 800, true)

		-- Alliance Vanguard
		-- spillover from Explorer's League
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Steel Gate Patrol", 125)
		-- spillover from Frostborn
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[78] Pushed Too Far", 125)
		-- spillover from Silver Covenant
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] A Blade Fit For A Champion", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] The Edge Of Winter", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] A Worthy Weapon", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Training In The Field", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Learning The Reins ", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] A Valiant's Field Training", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] The Grand Melee", 125)
		-- tournament spillover
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Threat From Above", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Taking Battle To The Enemy", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Battle Before The Citadel", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Among the Champions", 125)
		-- spillover from Valiance Expedition
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[71] Break the Blockade", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Assault by Air", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Assault by Ground", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] Blood of the Chosen", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[80] King of the Mountain", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Blackriver Skirmish", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Life or Death", 125)
		FIZ_AddQuest("Alliance Vanguard", 4, 8, "[73] Kick'em While They're Down", 125)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)
	end
	if (FIZ_IsHorde) then
	-- Darkspear Trolls
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ten Commendation Signets", 150, {["Horde Commendation Signet"]=10})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] One Commendation Signet", 5, {["Horde Commendation Signet"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] A Gallon of Blood", 18.75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Lokholar the Ice Lord", 2.5, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Call of Air: Guse's Fleet", 2.5, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Call of Air: Jeztor's Fleet", 2.5, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Call of Air: Mulverick's Fleet", 2.5, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] Ram Hide Harnesses", 2.5, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Darkspear Trolls", 4, 8, "[60] More Booty!", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Darkspear Trolls", 4, 8, 250, {["Sen'jin Commendation Badge"]=1})
		-- Orgrimmar
		FIZ_AddQuest("Orgrimmar", 4, 8, "[24] Chen's Empty Keg", 75, {["Lightning Gland"]=5,["Thunderhawk Saliva Gland"]=1, ["Kodo Liver"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ten Commendation Signets", 150, {["Horde Commendation Signet"]=10})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] One Commendation Signet", 5, {["Horde Commendation Signet"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] A Gallon of Blood", 75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Lokholar the Ice Lord", 10, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Call of Air: Guse's Fleet", 10, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Call of Air: Jeztor's Fleet", 10, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Call of Air: Mulverick's Fleet", 10, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Empty Stables", 10)
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] Ram Hide Harnesses", 10, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Orgrimmar", 4, 8, "[60] More Booty!", 10, {["Armor Scraps"]=20})
		FIZ_AddItems("Orgrimmar", 4, 8, 250, {["Orgrimmar Commendation Badge"]=1})
		-- Silvermoon City
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ten Commendation Signets", 150, {["Horde Commendation Signet"]=10})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] One Commendation Signet", 5, {["Horde Commendation Signet"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] A Gallon of Blood", 18.75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Lokholar the Ice Lord", 2.5, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Call of Air: Guse's Fleet", 2.5, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Call of Air: Jeztor's Fleet", 2.5, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Call of Air: Mulverick's Fleet", 2.5, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] Ram Hide Harnesses", 2.5, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Silvermoon City", 4, 8, "[60] More Booty!", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Silvermoon City", 4, 8, 250, {["Silvermoon Commendation Badge"]=1})
		-- Thunder Bluff
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[55] Morrowgrain to Thunder Bluff", 75, {["Morrowgrain"]=10})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ten Commendation Signets", 150, {["Horde Commendation Signet"]=10})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] One Commendation Signet", 5, {["Horde Commendation Signet"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] An Extraordinary Egg", 10, {["Extraordinary Egg"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] A Fine Egg", 10, {["Fine Egg"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] An Ordinary Egg", 10, {["Ordinary Egg"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] A Bad Egg", 10, {["Bad Egg"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] A Gallon of Blood", 18.75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Lokholar the Ice Lord", 2.5, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Call of Air: Guse's Fleet", 2.5, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Call of Air: Jeztor's Fleet", 2.5, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Call of Air: Mulverick's Fleet", 2.5, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] Ram Hide Harnesses", 2.5, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Thunder Bluff", 4, 8, "[60] More Booty!", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Thunder Bluff", 4, 8, 250, {["Thunder Bluff Commendation Badge"]=1})
		-- Undercity
		FIZ_AddQuest("Undercity", 4, 8, "[60] Additional Runecloth", 75, {["Runecloth"] = 20})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ten Commendation Signets", 150, {["Horde Commendation Signet"]=10})
		FIZ_AddQuest("Undercity", 4, 8, "[60] One Commendation Signet", 5, {["Horde Commendation Signet"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] A Gallon of Blood", 18.75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Lokholar the Ice Lord", 2.5, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Call of Air: Guse's Fleet", 2.5, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Call of Air: Jeztor's Fleet", 2.5, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Call of Air: Mulverick's Fleet", 2.5, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Undercity", 4, 8, "[60] Ram Hide Harnesses", 2.5, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Undercity", 4, 8, "[60] More Booty!", 2.5, {["Armor Scraps"]=20})
		FIZ_AddItems("Undercity", 4, 8, 250, {["Undercity Commendation Badge"]=1})
		-- Frostwolf Clan
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] A Gallon of Blood", 18.75, {["Stormpike Soldier's Blood"]=5})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Lokholar the Ice Lord", 2.5, {["Stormpike Soldier's Blood"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Call of Air: Guse's Fleet", 2.5, {["Stormpike Soldier Flesh"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Call of Air: Jeztor's Fleet", 2.5, {["Stormpike Lieutenant Flesh"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Call of Air: Mulverick's Fleet", 2.5, {["Stormpike Commander Flesh"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Empty Stables", 2.5)
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] Ram Hide Harnesses", 2.5, {["Alterac Ram Hide"]=1})
		FIZ_AddQuest("Frostwolf Clan", 4, 8, "[60] More Booty!", 2.5, {["Armor Scraps"]=20})
		-- The Defilers
		FIZ_AddInstance("The Defilers", 4, 8, "Arathi Basin collect 160 Resources", 10, false)
		FIZ_AddInstance("The Defilers", 4, 8, "Arathi Basin Win (1600 Resources)", 100, false)
		-- Warsong Outriders
		FIZ_AddInstance("Warsong Outriders", 4, 8, "Warsong BG Flag Capture", 35, false)
		FIZ_AddInstance("Warsong Outriders", 4, 8, "Warsong BG Win (3 Capturese)", 105, false)

	 	-- The Hand of Vengeance
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Learning The Reins", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Among the Champions", 62.5)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keep 'Em on Their Heels", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Making Repairs", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Overwhelmed!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Shred the Alliance", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Air", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Ground", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blood of the Chosen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] King of the Mountain", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)

	    	-- The Taunka
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Learning The Reins", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Among the Champions", 62.5)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keep 'Em on Their Heels", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Making Repairs", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Overwhelmed!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Shred the Alliance", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Air", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Ground", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blood of the Chosen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] King of the Mountain", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)

	    	-- The Sunreavers
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] A Blade Fit For A Champion", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] The Edge Of Winter", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] A Worthy Weapon", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Training In The Field", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Learning The Reins", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] A Valiant's Field Training", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] The Grand Melee", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Threat From Above", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Taking Battle To The Enemy", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Battle Before The Citadel", 250)
		FIZ_AddQuest("The Sunreavers", 4, 8, "[80] Among the Champions", 250)
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 125)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keep 'Em on Their Heels", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Making Repairs", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Overwhelmed!", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Shred the Alliance", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Air", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Ground", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blood of the Chosen", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] King of the Mountain", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)

	    	-- Warsong Offensive
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Keep 'Em on Their Heels", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Making Repairs", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Overwhelmed!", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[74] Shred the Alliance", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Assault by Air", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Assault by Ground", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[77] Blood of the Chosen", 250)
		FIZ_AddQuest("Warsong Offensive", 4, 8, "[80] King of the Mountain", 250)
		-- horde expedition spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 125)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Blade Fit For A Champion", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Edge Of Winter", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Worthy Weapon", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Training In The Field", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Learning The Reins", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Valiant's Field Training", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Grand Melee", 62.5)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Threat From Above", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Taking Battle To The Enemy", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Battle Before The Citadel", 62.5)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Among the Champions", 62.5)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)

		-- Horde Expedition
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Blackriver Brawl", 250)
		-- sunreaver spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Blade Fit For A Champion", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Edge Of Winter", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Worthy Weapon", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Training In The Field", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Learning The Reins", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] A Valiant's Field Training", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] The Grand Melee", 125)
		-- tournament spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Threat From Above", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Taking Battle To The Enemy", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Battle Before The Citadel", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] Among the Champions", 125)
		-- warsong offensive spillover
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Keep 'Em on Their Heels", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Making Repairs", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Overwhelmed!", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[74] Shred the Alliance", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Air", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Assault by Ground", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[77] Blood of the Chosen", 125)
		FIZ_AddQuest("Horde Expedition", 4, 8, "[80] King of the Mountain", 125)
		-- dungeon spillover
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 400, false)
		FIZ_AddInstance("Alliance Vanguard", 4, 8, "Spillover rep from dungeons", 800, true)
	end
	-- Argent Dawn
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Minion's Scourgestone", 50, {["Minion's Scourgestone"] = 20})
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Invader's Scourgestones", 50, {["Invader's Scourgestone"] = 10})
	FIZ_AddQuest("Argent Dawn", 4, 8, "[55] Corruptor's Scourgestone", 50, {["Corruptor's Scourgestone"] = 1})
	FIZ_AddQuest("Argent Dawn", 4, 8, "Using Valor Token", 100, {["Argent Dawn Valor Token"] = 1})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Bone Fragments", 20, {["Bone Fragments"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Crypt Fiend Parts", 20, {["Crypt Fiend Parts"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Core of Elements", 20, {["Core of Elements"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Dark Iron Scraps", 20, {["Dark Iron Scraps"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Savage Fronds", 20, {["Savage Fronds"] = 30})
	FIZ_AddQuest("Argent Dawn", 5, 8, "[60] Craftsman's Writs", 150)
	FIZ_AddQuest("Argent Dawn", 4, 8, "Cauldron Quests", 50)
	FIZ_AddMob("Argent Dawn", 4, 5, "Non-Elites in Plaguelands", 10)
	FIZ_AddMob("Argent Dawn", 4, 6, "Elites & Shadowmages in Plaguelands", 10)
	FIZ_AddMob("Argent Dawn", 4, 6, "Cauldron Lords", 30)
	FIZ_AddMob("Argent Dawn", 4, 7, "Stratholme & Scholomance Trash", 10)
	FIZ_AddMob("Argent Dawn", 4, 8, "Stratholme & Scholomance Bosses", 50)
	FIZ_AddMob("Argent Dawn", 4, 8, "Baron Rivendare (Stratholme)", 100)
	FIZ_AddMob("Argent Dawn", 4, 8, "Ras Frostwhisper (Scholomance)", 100)
	FIZ_AddInstance("Argent Dawn", 4, 8, "Straholme 45 Minute Run", 850, false)
	FIZ_AddInstance("Argent Dawn", 4, 8, "Scholomance", 1200, false)
	-- Bloodsail Buccaneers
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Booty Bay Bruiser & Elite", 25, "Booty Bay")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Some Booty Bay mobs", 5, "Booty Bay")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Most Booty Bay mobs", 1, "Booty Bay")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Most Faldir's Cove mobs", 5, "Arathi Highlands, Faldir's Cove")
	FIZ_AddMob("Bloodsail Buccaneers", 1, 8, "Jazzrik & Rigglefuzz", 1, "Badlands")
	-- Darkmoon Faire
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Small Furry Paws", 250, {["Small Furry Paw"] = 5}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Torn Bear Pelts", 250, {["Torn Bear Pelt"] = 5}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Soft Bushy Tails", 250, {["Soft Bushy Tail"] = 5}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Vibrant Plumes", 250, {["Vibrant Plume"] = 5}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Evil Bat Eyes", 250, {["Evil Bat Eye"] = 10})
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Glowing Scorpid Blood", 250, {["Glowing Scorpid Blood"] = 10})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Coarse Weightstones", 250, {["Coarse Weightstone"] = 10}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Heavy Grinding Stone", 250, {["Heavy Grinding Stone"] = 7}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Green Iron Bracers", 250, {["Green Iron Bracers"] = 3}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Big Black Mace", 250, {["Big Black Mace"] = 1}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Dense Grinding Stone", 250, {["Dense Grinding Stone"] = 8})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Copper Modulator", 250, {["Copper Modulator"] = 5}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Whirring Bronze Gizmo", 250, {["Whirring Bronze Gizmo"] = 7}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Green Firework", 250, {["Green Firework"] = 36}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Mechanical Repair Kits", 250, {["Mechanical Repair Kit"] = 6}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Thorium Widget", 250, {["Thorium Widget"] = 6})
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Embossed Leather Boots", 250, {["Embossed Leather Boots"] = 3}, 500)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Toughened Leather Armor", 250, {["Toughened Leather Armor"] = 3}, 1100)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Barbaric Harness", 250, {["Barbaric Harness"] = 3}, 1700)
	FIZ_AddQuest("Darkmoon Faire", 4, 4, "Turtle Scale Leggings", 250, {["Turtle Scale Leggings"] = 1}, 2500)
	FIZ_AddQuest("Darkmoon Faire", 4, 5, "Rugged Armor Kit", 250, {["Rugged Armor Kit"] = 8})
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[10] Rogues Deck", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[25] Swords Deck", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[35] Mages Deck", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[45] Demons Deck", 25)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Beasts Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Elementals Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Portals Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Warlords Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Furies Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Storms Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Blessings Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[70] Darkmoon Lunacy Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Darkmoon Undeath Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Darkmoon Prisms Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Darkmoon Nobles Deck", 350)
	FIZ_AddQuest("Darkmoon Faire", 4, 8, "[80] Darkmoon Chaos Deck", 350)
	-- Gelkis Clan Centaur
	FIZ_AddMob("Gelkis Clan Centaur", 1, 8, "Magram Clan Centaurs", 20)
	-- Magram Clan Centaur
	FIZ_AddMob("Magram Clan Centaur", 1, 8, "Gelkis Clan Centaurs", 20)
	-- Keepers of Time
	FIZ_AddInstance("Keepers of Time", 4, 8, "Old Hillsbarad (CoT1)", 900, false)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Old Hillsbarad (CoT1)", 900, true)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Black Morass (CoT2)", 1110, false)
	FIZ_AddInstance("Keepers of Time", 4, 8, "Black Morass (CoT2)", 1725, true)
	-- Ravenholdt
	FIZ_AddQuest("Ravenholdt", 4, 4, "[24] Syndicate Emblems", 250, {["Syndicate Emblem"] = 1})
	FIZ_AddQuest("Ravenholdt", 4, 8, "[50] Junkboxes Needed", 75, {["Heavy Junkbox"] = 5})
	FIZ_AddMob("Ravenholdt", 4, 6, "All Syndicate members", 5)
	-- Shen'dralar
	FIZ_AddQuest("Shen'dralar", 4, 8, "Librams in Dire Maul", 500)
	FIZ_AddQuest("Shen'dralar", 4, 8, "Class Books in Dire Maul", 500)
	-- Syndicate
	FIZ_AddMob("Syndicate", 1, 8, "Myrokos Silentform", 5)
	FIZ_AddMob("Syndicate", 1, 8, "Winstone Wolfe", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Lord Jorach Ravenholdt", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Fahrad", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Zan Shivsproket", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Smudge Thunderwood", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Simone Cantrell", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Master Kang", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Carlo Aurelius", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Ravenholdt Assassin", 1)
	FIZ_AddMob("Syndicate", 1, 8, "Ravenholdt Guard", 1)
	-- Thorium Brotherhood
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Restoring Fiery Flux via Kingsblood", 25, {["Incendosaur Scales"]=2, ["Coal"]=1, ["Kingsblood"]= 2}, FIZ_LIMIT_TYPE_HERB)
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Restoring Fiery Flux via Iron", 25, {["Incendosaur Scales"]=2, ["Coal"]=1, ["Iron Bar"] = 2}, FIZ_LIMIT_TYPE_MINE)
	FIZ_AddQuest("Thorium Brotherhood", 4, 4, "[45] Restoring Fiery Flux via ", 25, {["Incendosaur Scales"]=2, ["Coal"]=1, ["Heavy Leather"] = 2}, FIZ_LIMIT_TYPE_SKIN)
	FIZ_AddQuest("Thorium Brotherhood", 5, 5, "[45] Gaining Acceptance", 25, {["Dark Iron Residue"] = 4})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Favor Amongst the Brotherhood, Dark Iron Ore", 75, {["Dark Iron Ore"] = 10})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Favor Amongst the Brotherhood, Core Leather", 350, {["Core Leather"] = 2})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Favor Amongst the Brotherhood, Blood of the Mountain", 500, {["Blood of the Mountain"] = 1})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Favor Amongst the Brotherhood, Fiery Core", 500, {["Fiery Core"] = 1})
	FIZ_AddQuest("Thorium Brotherhood", 6, 8, "[60] Favor Amongst the Brotherhood, Lava Core", 500, {["Lava Core"] = 1})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Feathers for Nafien", 300, {["Deadwood Headdress Feather"] = 5})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[55] Feathers for Grazle", 300, {["Deadwood Headdress Feather"] = 5})
	FIZ_AddQuest("Timbermaw Hold", 2, 8, "[56] Beads for Salfa", 300, {["Winterfall Spirit Beads"] = 5})
	FIZ_AddMob("Timbermaw Hold", 2, 6, "Deadwood Avenger, Den Watcher, Shaman, Gardener, Pathfinder & Warrior", 20)
	FIZ_AddMob("Timbermaw Hold", 2, 6, "Winterfell Runner, Den Watcher, Shaman, Pathfinder, Totemic, & Ursa", 20)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Chieftain Bloodmaw", 60)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Overlord Ror", 60)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Ragepaw (Rare)", 50)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "Grizzle Snowpaw (Rare)", 50)
	FIZ_AddMob("Timbermaw Hold", 2, 8, "High Chief Winterfall", 50)
	-- Wintersaber Trainers
	FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Frostsaber Provisions", 250)
	FIZ_AddQuest("Wintersaber Trainers", 4, 8, "[60] Winterfall Intrusion", 250)
	FIZ_AddQuest("Wintersaber Trainers", 6, 8, "[60] Rampaging Giants", 350)
	-- Ashtongue Deathsworn
	FIZ_AddInstance("Ashtongue Deathsworn", 4, 8, "Black Temple full clear", 8000)
	-- Brood of Nozdormu
	FIZ_AddQuest("Brood of Nozdormu", 1, 4, "[60] The Hand of the Righteous", 500)
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Anubisath Defender", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Anubisath Sentinel", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Obsidian Eradicator", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Qiraj Lasher", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Vekniss Hive Crawler", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Vekniss Soldier", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Vekniss Stinger", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Vekniss Warrior", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 4, "Vekniss Wasp", 100, "Temple of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Most Bosses", 50, "Ruins of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Ossirian", 100, "Ruins of Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Twin Emperors", 200, "Ruinen von Ahn'Qiraj")
	FIZ_AddMob("Brood of Nozdormu", 1, 8, "Cthun", 2500, "Ruinen von Ahn'Qiraj")
	FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Qiraji Lord's Insignia", 500)		-- item
	FIZ_AddQuest("Brood of Nozdormu", 1, 8, "Ancient Qiraji Artifact", 1000)	-- item
	-- Cenarion Circle
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Field Duty", 150)
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssal Crests", 150, {["Abyssal Crest"] = 3})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssal Signets", 500, {["Abyssal Signet"] = 3})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Abyssal Scepters", 300, {["Abyssal Scepter"] = 1})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Secret Communication", 500, {["Encrypted Twilight Text"] = 10})
	FIZ_AddQuest("Cenarion Circle", 4, 8, "[60] Allegiance to Cenarion Circle", 1000)
	FIZ_AddInstance("Cenarion Circle", 4, 8, "Ruins of Ahn'Qiraj", 1200) -- counting only bosses
	FIZ_AddInstance("Cenarion Circle", 4, 8, "Temple of Ahn'Qiraj", nil) -- no data for full run or bosses
	FIZ_AddMob("Cenarion Circle", 4, 5, "Twilight Cultist", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 6, "Twilight Flamereaver", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 6, "Twilight Keeper", 10)	-- only 0.2 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 8, "Twilight Lord Everun", 10)	-- only 1 @ 70
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssal Templar", 10)
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssal Duke", 50)
	FIZ_AddMob("Cenarion Circle", 4, 8, "Abyssal Lord", 100)
	-- Hydraxian Waterlords
	FIZ_AddMob("Hydraxian Waterlords", 4, 5, "Desert Rumbler, Dust Stormer", 5, "Silithus")
	FIZ_AddMob("Hydraxian Waterlords", 4, 5, "Greater Obsidian Elemental", 5, "Burning Steppes")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Lord Incendius", 15, "BRD")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Huricanian (Rare)", 25, "Silithus")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Pyroguard Emberseer", 50, "UBRS")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Molten Core Trash", 20, "MC")
	FIZ_AddMob("Hydraxian Waterlords", 4, 6, "Molten Destroyer & Lava Pack", 40, "MC")
	FIZ_AddInstance("Hydraxian Waterlords", 4, 7, "Molten Core (all bosses)",1050, false)
	FIZ_AddInstance("Hydraxian Waterlords", 8, 8, "Molten Core (Golemagg & Ragnaros)",350, false)
	-- The Scale of the Sands
	FIZ_AddQuest("The Scale of the Sands", 4, 4, "[70] The Vials of Eternity", 3000)
	FIZ_AddInstance("The Scale of the Sands", 5, 8, "Battle for Mount Hyal full clear", 6000)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Trash mobs", 12)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Frost Wyrm", 60)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Bosses", 375)
	FIZ_AddMob("The Scale of the Sands", 4, 8, "Archimonde", 1500)
	-- The Violet Eye
	FIZ_AddInstance("The Violet Eye", 4, 8, "Karazan full clear", 6000, false)
	FIZ_AddMob("The Violet Eye", 4, 8, "Karazan bosses", 250, "Karazan")
	FIZ_AddMob("The Violet Eye", 4, 8, "Karazan trash", 15, "Karazan")
	-- Zandalar Tribe
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Zulian, Razzashi, and Hakkari Coins", 25)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Sandfury, Skullsplitter, and Bloodscalp Coins", 25)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "[60] Gurubashi, Vilebranch, and Witherbark Coins", 25)
	FIZ_AddQuest("Zandalar Tribe", 6, 8, "[60] The Savage Guard", 500)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "Destroy a Bijou", 75)
	FIZ_AddQuest("Zandalar Tribe", 4, 8, "Zandalar Honor Token", 50)
	FIZ_AddInstance("Zandalar Tribe", 4, 8, "Zul'Gurub", 2750)
	-- Booty Bay
	FIZ_AddMob("Booty Bay", 1, 8, "Andre Firebeard", 5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Southsea Dock Worker, Freebooter, Pirate, Swashbuckler", 2.5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Caliph Scorpidsting", 10, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Wastewander Assassin, Bandit, Rogue, Scofflaw, Thief", 2.5, "Tanaris")
	FIZ_AddMob("Booty Bay", 1, 8, "Baron Longshore", 5, "The Barrens")
	FIZ_AddMob("Booty Bay", 1, 8, "Southsea Brigand, Cannoneer, Cutthroat, Privateer", 2.5, "The Barrens")
	FIZ_AddMob("Booty Bay", 1, 7, "Foreman Cozzle", 5, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 7, "Venture Co. Foreman, Geologist, Lumberjack, Mechanic, Miner", 5, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 7, "Venture Co. Shredder, Strip Miner, Surveyor, Tinkerer, Workboss", 5, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 7, "Fleet Master Firallon, Captain Stillwater, Captain Keelhaul", 25, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 7, "Garr Salthoof, Ironpatch, Brutus", 25, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 7, "'Pretty Boy' Duncan", 25, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 6, "Bloodsail Deckhand, Elder Magus, Mage, Raider", 5, "Stranglethorn Vale")
	FIZ_AddMob("Booty Bay", 1, 6, "Bloodsail Sea Dog, Swabby, Swashbuckler, Warlock", 5, "Stranglethorn Vale")
	FIZ_AddQuest("Booty Bay", 1, 8, "[55] Refuel for the Zapping", 25, {["Water Elemental Core"] = 6})
	FIZ_AddQuest("Booty Bay", 1, 8, "[55] Again With the Zapped Giants", 25, {["Miniaturization Residue"] = 10})
	FIZ_AddQuest("Booty Bay", 1, 8, "[60] Free Knot!", 350, {["Gordok Shackle Key"] = 1})
	FIZ_AddQuest("Booty Bay", 1, 8, "[60] The Gordok Ogre Suit", 75, {["Bolt of Runecloth"]=4, ["Rugged Leather"]=8, ["Rune Thread"]=2, ["Ogre Tannin"]=1})
	FIZ_AddQuest("Booty Bay", 1, 8, "[44] Water Pouch Bounty", 5, {["Wastewander Water Pouch"] = 5})
	FIZ_AddQuest("Booty Bay", 1, 3, "[30] Traitor to the Bloodsail", 500, {["Silk Cloth"] = 40, ["Red Dye"]=4})
	-- Gadgetzan
	FIZ_AddMob("Gadgetzan", 1, 7, "Andre Firebeard", 25, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 7, "Southsea Dock Worker, Freebooter, Pirate, Swashbuckler", 5, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 6, "Caliph Scorpidsting", 20, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 6, "Wastewander Assassin, Bandit, Rogue, Scofflaw, Thief", 5, "Tanaris")
	FIZ_AddMob("Gadgetzan", 1, 8, "Baron Longshore", 5, "The Barrens")
	FIZ_AddMob("Gadgetzan", 1, 8, "Southsea Brigand, Cannoneer, Cutthroat, Privateer", 2.5, "The Barrens")
	FIZ_AddMob("Gadgetzan", 1, 8, "Foreman Cozzle", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Venture Co. Foreman, Geologist, Lumberjack, Mechanic, Miner", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Venture Co. Shredder, Strip Miner, Surveyor, Tinkerer, Workboss", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Fleet Master Firallon, Captain Stillwater, Captain Keelhaul", 5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Garr Salthoof, Ironpatch, Brutus", 5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "'Pretty Boy' Duncan", 5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Bloodsail Deckhand, Elder Magus, Mage, Raider", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Gadgetzan", 1, 8, "Bloodsail Sea Dog, Swabby, Swashbuckler, Warlock", 2.5, "Stranglethorn Vale")
	FIZ_AddQuest("Gadgetzan", 1, 8, "[55] Refuel for the Zapping", 25, {["Water Elemental Core"] = 6})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[55] Again With the Zapped Giants", 25, {["Miniaturization Residue"] = 10})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[60] Free Knot!", 350, {["Gordok Shackle Key"] = 1})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[60] The Gordok Ogre Suit", 75, {["Bolt of Runecloth"]=4, ["Rugged Leather"]=8, ["Rune Thread"]=2, ["Ogre Tannin"]=1})
	FIZ_AddQuest("Gadgetzan", 1, 8, "[44] Water Pouch Bounty", 10, {["Wastewander Water Pouch"] = 5})
	FIZ_AddQuest("Gadgetzan", 1, 3, "[15] War at sea", 500, {["Mageweave Cloth"] = 40, ["Strong Flux"]=4})
	-- Ratchet
	FIZ_AddMob("Ratchet", 1, 8, "Andre Firebeard", 5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "Southsea Dock Worker, Freebooter, Pirate, Swashbuckler", 2.5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "Caliph Scorpidsting", 10, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 8, "Wastewander Assassin, Bandit, Rogue, Scofflaw, Thief", 2.5, "Tanaris")
	FIZ_AddMob("Ratchet", 1, 6, "Baron Longshore", 25, "The Barrens")
	FIZ_AddMob("Ratchet", 1, 6, "Southsea Brigand, Cannoneer, Cutthroat, Privateer", 5, "The Barrens")
	FIZ_AddMob("Ratchet", 1, 8, "Foreman Cozzle", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Venture Co. Foreman, Geologist, Lumberjack, Mechanic, Miner", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Venture Co. Shredder, Strip Miner, Surveyor, Tinkerer, Workboss", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Fleet Master Firallon, Captain Stillwater, Captain Keelhaul", 5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Garr Salthoof, Ironpatch, Brutus", 5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "'Pretty Boy' Duncan", 5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Bloodsail Deckhand, Elder Magus, Mage, Raider", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Ratchet", 1, 8, "Bloodsail Sea Dog, Swabby, Swashbuckler, Warlock", 2.5, "Stranglethorn Vale")
	FIZ_AddQuest("Ratchet", 1, 8, "[55] Refuel for the Zapping", 25, {["Water Elemental Core"] = 6})
	FIZ_AddQuest("Ratchet", 1, 8, "[55] Again With the Zapped Giants", 25, {["Miniaturization Residue"] = 10})
	FIZ_AddQuest("Ratchet", 1, 8, "[60] Free Knot!", 350, {["Gordok Shackle Key"] = 1})
	FIZ_AddQuest("Ratchet", 1, 8, "[60] The Gordok Ogre Suit", 75, {["Bolt of Runecloth"]=4, ["Rugged Leather"]=8, ["Rune Thread"]=2, ["Ogre Tannin"]=1})
	FIZ_AddQuest("Ratchet", 1, 8, "[44] Water Pouch Bounty", 5, {["Wastewander Water Pouch"] = 5})
	FIZ_AddQuest("Ratchet", 1, 3, "[15] Mending Old Wounds", 500, {["Linen Cloth"] = 40, ["Empty Vial"]=4})
	-- Everlook
	FIZ_AddMob("Everlook", 1, 8, "Andre Firebeard", 5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Southsea Dock Worker, Freebooter, Pirate, Swashbuckler", 2.5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Caliph Scorpidsting", 10, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Wastewander Assassin, Bandit, Rogue, Scofflaw, Thief", 2.5, "Tanaris")
	FIZ_AddMob("Everlook", 1, 8, "Baron Longshore", 5, "The Barrens")
	FIZ_AddMob("Everlook", 1, 8, "Southsea Brigand, Cannoneer, Cutthroat, Privateer", 2.5, "The Barrens")
	FIZ_AddMob("Everlook", 1, 8, "Foreman Cozzle", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Venture Co. Foreman, Geologist, Lumberjack, Mechanic, Miner", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Venture Co. Shredder, Strip Miner, Surveyor, Tinkerer, Workboss", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Fleet Master Firallon, Captain Stillwater, Captain Keelhaul", 5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Garr Salthoof, Ironpatch, Brutus", 5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "'Pretty Boy' Duncan", 5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Bloodsail Deckhand, Elder Magus, Mage, Raider", 2.5, "Stranglethorn Vale")
	FIZ_AddMob("Everlook", 1, 8, "Bloodsail Sea Dog, Swabby, Swashbuckler, Warlock", 2.5, "Stranglethorn Vale")
	FIZ_AddQuest("Everlook", 1, 8, "[55] Refuel for the Zapping", 25, {["Water Elemental Core"] = 6})
	FIZ_AddQuest("Everlook", 1, 8, "[55] Again With the Zapped Giants", 25, {["Miniaturization Residue"] = 10})
	FIZ_AddQuest("Everlook", 1, 8, "[60] Free Knot!", 350, {["Gordok Shackle Key"] = 1})
	FIZ_AddQuest("Everlook", 1, 8, "[60] The Gordok Ogre Suit", 75, {["Bolt of Runecloth"]=4, ["Rugged Leather"]=8, ["Rune Thread"]=2, ["Ogre Tannin"]=1})
	FIZ_AddQuest("Everlook", 1, 8, "[44] Water Pouch Bounty", 5, {["Wastewander Water Pouch"] = 5})
	FIZ_AddQuest("Everlook", 1, 3, "[40] Making Amends", 500, {["Runecloth"] = 40, ["Coal"]=4})
	-- Cenarion Expedition
	FIZ_AddInstance("Cenarion Expedition", 4, 5, "Slave Pens", 650, false)
	FIZ_AddInstance("Cenarion Expedition", 6, 8, "Slave Pens", 650, true)	-- Trash 5, Bosses 70, no info on full clear
	FIZ_AddInstance("Cenarion Expedition", 4, 5, "Underbog", 1000, false)
	FIZ_AddInstance("Cenarion Expedition", 6, 8, "Underbog", 1000, true)	-- Trash 7, Bosses 70, no info on full clear
	FIZ_AddInstance("Cenarion Expedition", 4, 8, "Steamvault", 1662, false)
	FIZ_AddInstance("Cenarion Expedition", 4, 8, "Steamvault", 2319, true)
	FIZ_AddQuest("Cenarion Expedition", 4, 5, "[63] Plants of Zangarmarsh", 250, {["Unidentified Plant Parts"] = 10})
	FIZ_AddQuest("Cenarion Expedition", 4, 6, "[63] Uncatalogued Species", 500, {["Uncatalogued Species"] = 1})
	FIZ_AddQuest("Cenarion Expedition", 4, 8, "[67] Preparing for War", 75, {["Coilfang Armaments"] = 1})
	FIZ_AddQuest("Cenarion Expedition", 4, 8, "[72] Can't Get Ear-nough...", 150, {["Nesingwary Lackey Ear"] = 15})
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Steam Pump Overseer", 1, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Wrekt Slave", 2.5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Dreghood Drudge", 2.5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Bloodscale Overseer", 5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Bloodscale Wavecaller", 5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Darkcrest Sorceress", 5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Darkcrest Slaver", 5, "Zangarmarsh")
	FIZ_AddMob("Cenarion Expedition", 4, 4, "Terrorclaw", 7, "Zangarmarsh")
	-- Honor Hold
	FIZ_AddInstance("Honor Hold", 4, 5, "Hellfire Ramparts", 600, false)
	FIZ_AddInstance("Honor Hold", 6, 8, "Hellfire Ramparts", 2000, true)
	FIZ_AddInstance("Honor Hold", 4, 5, "Blood Furnace", 750, false)
	FIZ_AddInstance("Honor Hold", 6, 8, "Blood Furnace", 2700, true)
	FIZ_AddInstance("Honor Hold", 4, 8, "Shattered Halls", 1600, false)
	FIZ_AddInstance("Honor Hold", 4, 8, "Shattered Halls", 2900, true)
	FIZ_AddQuest("Honor Hold", 4, 7, "[60] Hellfire Fortifications", 150)
	FIZ_AddMob("Honor Hold", 4, 4, "Shattered Hands", 5, "Hellfire Peninsula")
	-- Kurenai
	FIZ_AddQuest("Kurenai", 4, 8, "[67] Fierce Enemies", 500, {["Obsidian Warbeads"] = 10})
	FIZ_AddQuest("Kurenai", 4, 8, "[70] In Defense of Halaa", 500)
	FIZ_AddMob("Kurenai", 4, 8, "Boulderfist Crusher & Mystic", 10, "Nagrand, Burning Blade Ruins")
	FIZ_AddMob("Kurenai", 4, 8, "Kil'sorrow Deathsworn, Cultist & Spellbinder", 10, "Nagrand, Kil'sorrow Fortress")
	FIZ_AddMob("Kurenai", 4, 8, "Boulderfist Mage & Warrior", 10, "Nagrand, North & Southwind Clefts")
	FIZ_AddMob("Kurenai", 4, 8, "Murkblood Scavenger", 2, "Nagrand, Sunspring Post")
	FIZ_AddMob("Kurenai", 4, 8, "Murkblood Brute, Putrifier & Raider", 10, "Nagrand, Sunspring Post")
	FIZ_AddMob("Kurenai", 4, 8, "Warmaul Reaver & Shaman", 10, "Nagrand, Laughing Skull Ruins")
	FIZ_AddMob("Kurenai", 4, 8, "Warmaul Brute & Warlock", 10, "Nagrand, Warmaul Hill")
	-- The Mag'har
	FIZ_AddQuest("The Mag'har", 4, 8, "[67] Proving Your Strength", 500, {["Obsidian Warbeads"] = 10})
	FIZ_AddQuest("The Mag'har", 4, 8, "[70] Enemies, Old and New", 500)
	FIZ_AddMob("The Mag'har", 4, 8, "Boulderfist Crusher & Mystic", 10, "Nagrand, Burning Blade Ruins")
	FIZ_AddMob("The Mag'har", 4, 8, "Kil'sorrow Deathsworn, Cultist & Spellbinder", 10, "Nagrand, Kil'sorrow Fortress")
	FIZ_AddMob("The Mag'har", 4, 8, "Boulderfist Mage & Warrior", 10, "Nagrand, North & Southwind Clefts")
	FIZ_AddMob("The Mag'har", 4, 8, "Murkblood Scavenger", 2, "Nagrand, Sunspring Post")
	FIZ_AddMob("The Mag'har", 4, 8, "Murkblood Brute, Putrifier & Raider", 10, "Nagrand, Sunspring Post")
	FIZ_AddMob("The Mag'har", 4, 8, "Warmaul Reaver & Shaman", 10, "Nagrand, Laughing Skull Ruins")
	FIZ_AddMob("The Mag'har", 4, 8, "Warmaul Brute & Warlock", 10, "Nagrand, Warmaul Hill")
	-- Ogri'la
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] The Relic's Emanation", 350)
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] Wrangle More Aether Rays!", 350)
	FIZ_AddQuest("Ogri'la", 4, 8, "[70] Bomb Them Again!", 500)
	FIZ_AddQuest("Ogri'la", 6, 8, "[70] Banish More Demons", 350)
	-- Netherwing
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Accepting All Eggs", 250, {["Netherwing Egg"]=1})
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Netherdust Pollen", 250, {["Netherdust Pollen"]=40}, FIZ_LIMIT_TYPE_HERB)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Nethercite Ore", 250, {["Nethercite Ore"]=40}, FIZ_LIMIT_TYPE_MINE)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Nethermine Flayer Hide", 250, {["Nethermine Flayer Hide"]=40}, FIZ_LIMIT_TYPE_SKIN)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] A Slow Death", 250)
	FIZ_AddQuest("Netherwing", 4, 8, "[70] The Not-So-Friendly Skies...", 250, {["Netherwing Relic"]=10})
	FIZ_AddQuest("Netherwing", 4, 8, "[70] Netherwing Crystals", 250, {["Netherwing Crystal"]=30})
	FIZ_AddQuest("Netherwing", 5, 8, "[70] Dragons are the Least of our Problems", 350)
	FIZ_AddQuest("Netherwing", 5, 8, "[70] Picking up the Pieces....", 350, {["Nethermine Cargo"]=15})
	FIZ_AddQuest("Netherwing", 5, 8, "[70] The Booterang: A Cure for the Common Worthless Peon", 350)
	FIZ_AddQuest("Netherwing", 6, 8, "[70] Disrupting the Twilight Portal", 500)
	FIZ_AddQuest("Netherwing", 7, 8, "[70+] The Deadliest Trap Ever Laid", 500)
	-- Sporeggar
	FIZ_AddMob("Sporeggar", 3, 6, "Bog Lords, Bog Giants", 15)
	FIZ_AddMob("Sporeggar", 3, 7, "Marsh Lurker", 15)
	FIZ_AddQuest("Sporeggar", 3, 4, "[63] The Sporeling's Plight", 750, {["Mature Spore Sac"] = 10})
	FIZ_AddQuest("Sporeggar", 3, 5, "[64] Natural Enemies", 750, {["Bog Lord Tendril"] = 6})
	FIZ_AddQuest("Sporeggar", 3, 5, "[64] More Tendrils", 750, {["Bog Lord Tendril"] = 6})	-- according to wowwiki only till 4, but in game it works till at least 5
	FIZ_AddQuest("Sporeggar", 4, 4, "[64] Glowcap Mushrooms", 750, {["Glowcap"] = 10})
	FIZ_AddQuest("Sporeggar", 5, 8, "[64] Now that we're still Friends...", 750)
	FIZ_AddQuest("Sporeggar", 4, 8, "[64] More Fertile Spores", 750, {["Fertile Spores"] = 6})
	FIZ_AddQuest("Sporeggar", 5, 8, "[65] Bring me a Shrubbery!", 750, {["Sanguine Hibiscus"] = 5})
	-- Consortium
	FIZ_AddInstance("The Consortium", 4, 5, "Mana Tombs", 1200, false)
	FIZ_AddInstance("The Consortium", 6, 8, "Mana Tombs", 2400, true)
	FIZ_AddQuest("The Consortium", 4, 4, "[66] Stealing from Thieves", 250, {["Oshu'gun Crystal Fragment"] = 10})
	FIZ_AddQuest("The Consortium", 4, 4, "[66] A Head Full of Ivory", 250, {["Pair of Ivory Tusks"] = 3})
	FIZ_AddQuest("The Consortium", 5, 8, "[67] Obsidian Warbeads", 250, {["Obsidian Warbeads"] = 10})
	FIZ_AddQuest("The Consortium", 5, 8, "[68] A Heap of Ethereals", 250, {["Zaxxis Insigna"] = 10})
	FIZ_AddQuest("The Consortium", 6, 8, "[70] Etherum Secrets", 250, {["Etherum Priosoner I.D. Tag"] = 1})
	FIZ_AddQuest("The Consortium", 7, 8, "[70] A Thousand Worlds", 500, {["Etherum Prison Key"] = 5})
	FIZ_AddQuest("The Consortium", 4, 8, "Outland daily dungeon quest (normal)", 250)
	FIZ_AddQuest("The Consortium", 4, 8, "Outland daily dungeon quest (heroic)", 350)
	-- Thrallmar
	FIZ_AddInstance("Thrallmar", 4, 5, "Hellfire Ramparts", 600, false)
	FIZ_AddInstance("Thrallmar", 7, 8, "Hellfire Ramparts", 2000, true)
	FIZ_AddInstance("Thrallmar", 4, 5, "Blood Furnace", 750, false)
	FIZ_AddInstance("Thrallmar", 7, 8, "Blood Furnace", 2700, true)
	FIZ_AddInstance("Thrallmar", 4, 8, "Shattered Halls", 1600, false)
	FIZ_AddInstance("Thrallmar", 4, 8, "Shattered Halls", 2900, true)
	FIZ_AddQuest("Thrallmar", 4, 7, "[60] Hellfire Fortifications", 150)
	-- Lower City
	FIZ_AddInstance("Lower City", 4, 5, "Auchenai Crypts", 750, false)
	FIZ_AddInstance("Lower City", 6, 8, "Auchenai Crypts", 750, true)
	FIZ_AddInstance("Lower City", 4, 8, "Sethekk Halls", 1080, false)
	FIZ_AddInstance("Lower City", 4, 8, "Sethekk Halls", 1250, true)
	FIZ_AddInstance("Lower City", 4, 8, "Shadow Labyrinth", 2000, false)
	FIZ_AddInstance("Lower City", 4, 8, "Shadow Labyrinth", 2700, true)
	FIZ_AddQuest("Lower City", 4, 5, "[65] The Outcast's Plight", 250, {["Arakkoa Feather"] = 30})
	-- Sha'tari Skyguard
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] World of Shadows", 150, {["Shadow Dust"] = 6})
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Fires over Skettis", 350)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Escape from Skettis", 150)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Wrangle More Aether Rays!", 350)
	FIZ_AddQuest("Sha'tari Skyguard", 4, 8, "[70] Bomb Them Again!", 500)
	FIZ_AddMob("Sha'tari Skyguard", 4, 6, "Skettis Kaliri", 2.5, "Terokkar Forest, Skettis")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Skettis, Talonpriests, Time-Lost Skettis, Monstrous Kaliri", 10, "Terokkar Forest, Skettis")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Talonsworn Forest-Rager", 30, "Terokkar Forest, Skettis")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Akkarai, Karrog, Gezzarak, Vakkiz", 100, "Terokkar Forest, Skettis (Summoned for Adversarial Blood)")
	FIZ_AddMob("Sha'tari Skyguard", 4, 8, "Terokk", 500, "Terokkar Forest, Skettis (Summoned)")
	-- The Aldor
	FIZ_AddQuest("The Aldor", 1, 3, "[64] Strained Supplies", 250, {["Dreadfang Venom Sac"] = 8})
	FIZ_AddQuest("The Aldor", 4, 5, "[70] More Marks of Kil'jaeden", 250, {["Mark of Kil'jaeden"] = 10})
	FIZ_AddQuest("The Aldor", 4, 5, "[70] Single Marks of Kil'jaeden", 25, {["Mark of Kil'jaeden"] = 1})
	FIZ_AddQuest("The Aldor", 5, 8, "[70] More Marks of Sargeras", 250, {["Mark of Sargeras"] = 10})
	FIZ_AddQuest("The Aldor", 5, 8, "[70] Single Mark of Sargeras", 25, {["Mark of Sargeras"] = 1})
	FIZ_AddQuest("The Aldor", 5, 8, "[64] A Cleansing Light", 350, {["Fel Armament"] = 1})
	-- The Scryers
	FIZ_AddQuest("The Scryers", 1, 3, "[64] Voren'thal's Visions", 250, {["Dampscale Basilisk Eye"] = 8})
	FIZ_AddQuest("The Scryers", 4, 5, "[70] More Firewing Signets", 250, {["Firewing Signet"] = 10})
	FIZ_AddQuest("The Scryers", 4, 5, "[70] Single Firewing Signets", 25, {["Firewing Signet"] = 1})
	FIZ_AddQuest("The Scryers", 5, 8, "[70] More Sunfury Signets", 250, {["Sunfury Signet"] = 10})
	FIZ_AddQuest("The Scryers", 5, 8, "[70] Single Sunfury Signets", 25, {["Sunfury Signet"] = 1})
	FIZ_AddQuest("The Scryers", 5, 8, "[64] Synthesis of Power", 350, {["Arcane Tome"] = 1})
	-- The Sha'tar
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] More Marks of Kil'jaeden", 125, {["Mark of Kil'jaeden"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Single Marks of Kil'jaeden", 12.5, {["Mark of Kil'jaeden"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] More Marks of Sargeras", 125, {["Mark of Sargeras"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Single Marks of Sargeras", 12.5, {["Mark of Sargeras"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] More Firewing Signets", 125, {["Firewing Signet"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Single Firewing Signets", 12.5, {["Firewing Signet"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] More Sunfury Signets", 125, {["Sunfury Signet"] = 10})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[70] Single Sunfury Signets", 12.5, {["Sunfury Signet"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Strained Supplies", 125, {["Dreadfang Venom Sac"] = 8})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Voren'thal's Visions", 125, {["Dampscale Basilisk Eye"] = 8})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] A Cleansing Light", 175, {["Fel Armament"] = 1})
	FIZ_AddQuest("The Sha'tar", 4, 5, "[64] Synthesis of Power", 175, {["Arcane Tome"] = 1})
	FIZ_AddInstance("The Sha'tar", 4, 8, "Mechanaar", 1620, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Mechanaar", 3000, true)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Botanica", 2000, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Botanica", 3000, true)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Arcatraz", 1800, false)
	FIZ_AddInstance("The Sha'tar", 4, 8, "Arcatraz", 3000, true)
	-- Shattered Sun Offensive
	-- general
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Gaining the Advantage", 250, {["Nether Residue"] = 8}, FIZ_LIMIT_TYPE_GATHER)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Sunfury Attack Plans", 250, {["Sunfury Attack Plans"] = 1})
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] The Multiphase Survey", 150)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Blood for Blood", 250)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Blast the Gateway", 250)
	-- Phase 1 (till Sun's Reach Sanctum)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Erratic Behavior", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] The Sanctum Wards", 150, nil, FIZ_LIMIT_TYPE_SSO, 1, 1) -- Phase 1 only
	-- Phase 2 (Sun's Reach Sanctum to Sun's Reach Armory)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] The Battle for the Sun's Reach Armory", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Distraction at the Dead Scar", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 2) -- Phase 2 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Arm the Wards!", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Further Conversions", 150, nil, FIZ_LIMIT_TYPE_SSO, 2, 5) -- Phase 2 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Intercepting the Mana Cells", 250, {["Smuggled Mana Cell"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 1) -- Phase 2 to 2b
	-- Phase 2B (after Sunwell)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Maintaining the Sunwell Portal", 250, {["Smuggled Mana Cell"] = 10}, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Know Your Ley Lines", 250, nil, FIZ_LIMIT_TYPE_SSO, 2, 5, 2) -- Phase 2B onwards
	-- Phase 3 (Armory to Harbor)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Intercept the Reinforcements", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Taking the Harbor", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 3) -- Phase 3 only
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] The Battle Must Go On", 250, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] The Air Strikes Must Continue", 150, nil, FIZ_LIMIT_TYPE_SSO, 3, 5) -- Phase 3 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Making Ready", 150, {["Darkspine Iron Ore"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 1) -- Phase 3 to 3b
	-- Phase 3b (after Anvil/Forge)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Ata'mal Armaments", 350, {["Cleansed Ata'mal Metal"] = 5}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Don't Stop Now....", 250, {["Darkspine Iron Ore"] = 3}, FIZ_LIMIT_TYPE_SSO, 3, 5, nil, 2) -- Phase 3b onwards
	-- Phase 4 (Harbor to town)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Discovering Your Roots", 350, {["Razorthorn Root"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 1) -- Phase 4 to 4c
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Disrupt the Greengill Coast", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Keeping the Enemy at Bay", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Crush the Dawnblade", 250, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] A Charitable Donation", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 1) -- Phase 4 to 4b
	FIZ_AddQuest("Shattered Sun Offensive", 8, 8, "[70] A Magnanimous Benefactor", 500, nil, FIZ_LIMIT_TYPE_SSO, 4, 5) -- Phase 4 onwards
	-- Phase 4b (after Monument)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Your Continued Support", 150, nil, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, 2) -- Phase 4b onwards
	-- Phase 4c (after Your Roots)
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Rediscovering Your Roots", 350, {["Razorthorn Root"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards
	FIZ_AddQuest("Shattered Sun Offensive", 4, 8, "[70] Open For Business", 250, {["Bloodberry"] = 5}, FIZ_LIMIT_TYPE_SSO, 4, 5, nil, nil, nil, 2) -- Phase 4c onwards
    	-- championing: The Argent Crusade, The Wyrmrest Accord, The Kirin Tor, Knights of the Ebon Blade,
    	-- 15 per trash, 30 per boss
    	-- Occolus normal: 480
    	-- Azjol heroic: 1360
    	-- Drak'Tharon heroic: 2000

	-- daily dungeon (normal) 75 for quest, 250 for reward
	-- daily dungeon (heroic) ?

	-- Argent Crusade
	FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Slaves to Saronite", 325)
	FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Troll Patrol", 455)
	FIZ_AddQuest("Argent Crusade", 4, 8, "[76] Congratulations!", 650)
	FIZ_AddItems("Argent Crusade", 4, 8, 520, {["Argent Crusade Commendation Badge"] = 1})
	FIZ_AddInstance("Argent Crusade", 4, 8, "Championing (Tabard)", 800, false)
	FIZ_AddInstance("Argent Crusade", 4, 8, "Championing (Tabard)", 2000, true)
	if not FIZ_IsDeathKnight then
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Among the Champions", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Threat From Above", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Taking Battle To The Enemy", 325)
		FIZ_AddQuest("Argent Crusade", 4, 8, "[80] Battle Before The Citadel", 325)
	end
	-- Frenzyheart Tribe
	FIZ_AddQuest("Frenzyheart Tribe", 1, 5, "[77] Frenzyheart Champion", 51000)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Kartak's Rampage", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Tools of War", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Secret Strength of the Frenzyheart", 700)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] A Hero's Headgear", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Chicken Party!", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Rejek: First Blood", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] Strength of the Tempest", 500)
	FIZ_AddQuest("Frenzyheart Tribe", 6, 8, "[77] The Heartblood's Strength", 500)
	-- The Kalu'ak
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] Preparing for the Worst", 500)
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] Planning for the Future", 500)
	FIZ_AddQuest("The Kalu'ak", 4, 8, "[70] The Way to His Heart...", 500)
	-- Kirin Tor
	FIZ_AddQuest("Kirin Tor", 4, 8, "Dalaran cooking daily quests", 195)
	FIZ_AddQuest("Kirin Tor", 4, 8, "Dalaran fishing daily quests", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Waterlogged Recipe", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "[80] Sealed Vial of Poison", 325)
	FIZ_AddQuest("Kirin Tor", 4, 8, "Jewelcrafting daily quests", 32, nil, FIZ_LIMIT_TYPE_JEWEL)
	FIZ_AddItems("Kirin Tor", 4, 8, 520, {["Kirin Tor Commendation Badge"] = 1})
	FIZ_AddInstance("Kirin Tor", 4, 8, "Championing (Tabard)", 800, false)
	FIZ_AddInstance("Kirin Tor", 4, 8, "Championing (Tabard)", 2000, true)
	-- Knights of the Ebon Blade
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] From Their Corpses, Rise!", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Intelligence Gathering", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Leave Our Mark", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] No Fly Zone", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Vile Like Fire!", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Shoot 'Em Up", 325)
	FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Reading the Bones", 10, {["Vrykul Bones"] = 15})
	FIZ_AddItems("Knights of the Ebon Blade", 4, 8, 520, {["Ebon Blade Commendation Badge"] = 1})
	FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Championing (Tabard)", 800, false)
	FIZ_AddInstance("Knights of the Ebon Blade", 4, 8, "Championing (Tabard)", 2000, true)
	if FIZ_IsDeathKnight then
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Threat From Above", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Taking Battle To The Enemy", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Battle Before The Citadel", 325)
		FIZ_AddQuest("Knights of the Ebon Blade", 4, 8, "[80] Among the Champions", 325)
	end
	-- The Oracles
	FIZ_AddQuest("The Oracles", 1, 5, "[77] Hand of the Oracles", 23239)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Mastery of the Crystals", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Will of the Titans", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Power of the Great Ones", 700)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Appeasing the Great Rain Stone", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] A Cleansing Song", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Song of Fecundity", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Song of Reflection", 500)
	FIZ_AddQuest("The Oracles", 6, 8, "[77] Song of Wind and Water", 500)
	-- The Sons of Hodir
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Hodir's Tribute", 650, {["Relic of Ulduar"] = 10})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Remember Everfrost", 455, {["Everfrost Chip"] = 1})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Polishing the Helm", 455, {["Viscous Oil"] = 5})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Hot and Cold", 455, {["Frozen Iron Scrap"] = 5})
	FIZ_AddQuest("The Sons of Hodir", 5, 8, "[80] Blowing Hodir's Horn", 455)
	FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Spy Hunter", 455)
	FIZ_AddQuest("The Sons of Hodir", 6, 8, "[80] Thrusting Hodir's Spear", 650)
	FIZ_AddQuest("The Sons of Hodir", 7, 8, "[80] Feeding Arngrim", 455)
	FIZ_AddItems("The Sons of Hodir", 4, 8, 520, {["Sons of Hodir Commendation Badge"] = 1})
	-- The Wyrmrest Accord
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[71] Drake Hunt", 325)
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[74] Defending Wyrmrest Temple", 325)
	FIZ_AddQuest("The Wyrmrest Accord", 4, 8, "[80] Aces High!", 325)
	FIZ_AddItems("The Wyrmrest Accord", 4, 8, 520, {["Wyrmrest Commendation Badge"] = 1})
	FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Championing (Tabard)", 800, false)
	FIZ_AddInstance("The Wyrmrest Accord", 4, 8, "Championing (Tabard)", 2000, true)
	-- The Ashen Verdict
	FIZ_AddInstance("The Ashen Verdict", 4, 8, "Icecrown Citadel 10 (full clear)", 2070, false)
end
