-- Russian factions init (Русские фракции)
function FIZ_InitRuFactions()
	FIZ_AddMapping("Darnassus", "Дарнас")
	FIZ_AddMapping("Gnomeregan Exiles", "Изгнанники Гномрегана")
	FIZ_AddMapping("Ironforge", "Стальгорн")
	FIZ_AddMapping("Stormwind", "Штормград")
	FIZ_AddMapping("Exodar", "Экзодар")
	-- Horde
	FIZ_AddMapping("Darkspear Trolls", "Тролли Черного Копья")
	FIZ_AddMapping("Orgrimmar", "Огриммар")
	FIZ_AddMapping("Thunder Bluff", "Громовой Утес")
	FIZ_AddMapping("Undercity", "Подгород")
	FIZ_AddMapping("Silvermoon City", "Луносвет")
	-- Alliance PvP
	FIZ_AddMapping("League of Arathor", "Лига Аратора")
	FIZ_AddMapping("Silverwing Sentinels", "Среброкрылые Часовые")
	FIZ_AddMapping("Stormpike Guard", "Стража Грозовой Вершины")
	-- Horde PvP
	FIZ_AddMapping("The Defilers", "Осквернители")
	FIZ_AddMapping("Frostwolf Clan", "Клан Северного Волка")
	FIZ_AddMapping("Warsong Outriders", "Всадники Песни Войны")
	-- Steamwheedle Cartel
	FIZ_AddMapping("Booty Bay", "Пиратская бухта")
	FIZ_AddMapping("Everlook", "Круговзор")
	FIZ_AddMapping("Gadgetzan", "Прибамбасск")
	FIZ_AddMapping("Ratchet", "Кабестан")
	-- Outland
	FIZ_AddMapping("Cenarion Expedition", "Кенарийская экспедиция")
	FIZ_AddMapping("Honor Hold", "Оплот Чести")
	FIZ_AddMapping("Kurenai", "Куренай")
	FIZ_AddMapping("The Mag'har", "Маг'хары")
	FIZ_AddMapping("Ogri'la", "Огри'ла")
	FIZ_AddMapping("Netherwing", "Крылья пустоты")
	FIZ_AddMapping("Sporeggar", "Спореггар")
	FIZ_AddMapping("The Consortium", "Консорциум")
	FIZ_AddMapping("Thrallmar", "Траллмар")
	FIZ_AddMapping("Tranquillien", "Транквиллион")
	-- Shattrath
	FIZ_AddMapping("Lower City", "Нижний город")
	FIZ_AddMapping("Sha'tari Skyguard", "Стражи Небес Ша'тар")
	FIZ_AddMapping("The Aldor", "Алдоры")
	FIZ_AddMapping("The Scryers", "Провидцы")
	FIZ_AddMapping("The Sha'tar", "Ша'тар")
	FIZ_AddMapping("Shattered Sun Offensive", "Армия Расколотого Солнца")
	-- Raid
	FIZ_AddMapping("Ashtongue Deathsworn", "Пеплоусты-служители")
	FIZ_AddMapping("Brood of Nozdormu", "Род Ноздорму")
	FIZ_AddMapping("Cenarion Circle", "Круг Кенария")
	FIZ_AddMapping("Hydraxian Waterlords", "Гидраксианские Повелители Вод")
	FIZ_AddMapping("The Scale of the Sands", "Песчаная Чешуя")
	FIZ_AddMapping("Zandalar Tribe", "Племя Зандалар")
	-- Others
	FIZ_AddMapping("Argent Dawn", "Серебряный Рассвет")
	FIZ_AddMapping("Bloodsail Buccaneers", "Пираты Кровавого Паруса")
	FIZ_AddMapping("Darkmoon Faire", "Ярмарка Новолуния")
	FIZ_AddMapping("Gelkis Clan Centaur", "Кентавры из племени Гелкис")
	FIZ_AddMapping("Keepers of Time", "Хранители Времени")
	FIZ_AddMapping("Magram Clan Centaur", "Кентавры из племени Маграм")
	FIZ_AddMapping("Ravenholdt", "Черный ворон")
	FIZ_AddMapping("Shen'dralar", "Шен'дралар")
	FIZ_AddMapping("Syndicate", "Синдикат")
	FIZ_AddMapping("Thorium Brotherhood", "Братство Тория")
	FIZ_AddMapping("Timbermaw Hold", "Древобрюхи")
	FIZ_AddMapping("The Violet Eye", "Аметистовое Око")
	FIZ_AddMapping("Wintersaber Trainers", "Укротители ледопардов")

	-- Wrath of the Lich King (WotLK)
	FIZ_AddMapping("Argent Crusade", "Серебряный Авангард")
	FIZ_AddMapping("Frenzyheart Tribe", "Племя Бешеного Сердца")
	FIZ_AddMapping("The Kalu'ak", "Калу'ак")
	FIZ_AddMapping("Kirin Tor", "Кирин-Тор")
	FIZ_AddMapping("Knights of the Ebon Blade", "Рыцари Черного Клинка")
	FIZ_AddMapping("The Oracles", "Оракулы")
	FIZ_AddMapping("The Sons of Hodir", "Сыны Ходира")
	FIZ_AddMapping("The Wyrmrest Accord", "Драконий союз")
	FIZ_AddMapping("Explorers' League", "Лига Исследователей")
	FIZ_AddMapping("The Frostborn", "Зиморожденные")
	FIZ_AddMapping("The Silver Covenant", "Серебряный Союз")
	FIZ_AddMapping("Valiance Expedition", "Экспедиция Отважных")
	FIZ_AddMapping("The Hand of Vengeance", "Карающая Длань")
	FIZ_AddMapping("The Sunreavers", "Похитители Солнца")
	FIZ_AddMapping("The Taunka", "Таунка")
	FIZ_AddMapping("Warsong Offensive", "Армия Песни Войны")
	FIZ_AddMapping("Alliance Vanguard", "Авангард Альянса")
	FIZ_AddMapping("Horde Expedition", "Экспедиция Орды")
	FIZ_AddMapping("The Ashen Verdict", "The Ashen Verdict")	-- todo: localise
end