-- French factions init (French)
function FIZ_InitFrFactions()
	-- Alliance
	FIZ_AddMapping("Darnassus", "Darnassus")
	FIZ_AddMapping("Gnomeregan Exiles", "Exilé©s de Gonmeragan")
	FIZ_AddMapping("Ironforge", "Forgefer")
	FIZ_AddMapping("Stormwind", "Hurlevent")
	FIZ_AddMapping("Exodar", "Exodar")
	-- Horde
	FIZ_AddMapping("Darkspear Trolls", "Trolls Sombrelance")
	FIZ_AddMapping("Orgrimmar", "Orgrimmar")
	FIZ_AddMapping("Thunder Bluff", "Les Pitons du Tonnerre")
	FIZ_AddMapping("Undercity", "Fossoyeuse")
	FIZ_AddMapping("Silvermoon City", "Lune-d'argent")
	-- Alliance PvP
	FIZ_AddMapping("League of Arathor", "La Ligue d'Arathor")
	FIZ_AddMapping("Silverwing Sentinels", "Sentinelles d'Aile-argent")
	FIZ_AddMapping("Stormpike Guard", "Guarde Foudrepique")
	-- Horde PvP
	FIZ_AddMapping("The Defilers", "Les Profanateurs")
	FIZ_AddMapping("Frostwolf Clan", "Clan Loup-de-givre")
	FIZ_AddMapping("Warsong Outriders", "Voltigeurs Chanteguerre")
	-- Steamwheedle Cartel
	FIZ_AddMapping("Booty Bay", "Baie-du-Butin")
	FIZ_AddMapping("Everlook", "Long-guet")
	FIZ_AddMapping("Gadgetzan", "Gadgetzan")
	FIZ_AddMapping("Ratchet", "Cabestan ")
	-- Outland
	FIZ_AddMapping("Cenarion Expedition", "Expédition cénarienne")
	FIZ_AddMapping("Honor Hold", "Bastion de l'Honneur")
	FIZ_AddMapping("Kurenai", "Kurenaé")
	FIZ_AddMapping("The Mag'har", "The Mag'har")
	FIZ_AddMapping("Ogri'la", "Ogri'la")
	FIZ_AddMapping("Netherwing", "Aile-du-Néant")
	FIZ_AddMapping("Sporeggar", "Sporeggar")
	FIZ_AddMapping("The Consortium", "Le Consortium")
	FIZ_AddMapping("Thrallmar", "Thrallmar")
	FIZ_AddMapping("Tranquillien", "Tranquillien")
	-- Shattrath
	FIZ_AddMapping("Lower City", "Ville basse")
	FIZ_AddMapping("Sha'tari Skyguard", "Garde-ciel sha'tari")
	FIZ_AddMapping("The Aldor", "L'Aldor")
	FIZ_AddMapping("The Scryers", "Les Clairvoyants")
	FIZ_AddMapping("The Sha'tar", "Les Sha'tar")
	FIZ_AddMapping("Shattered Sun Offensive", "Opération Soleil brisé")
	-- Raid
	FIZ_AddMapping("Ashtongue Deathsworn", "Ligemort cendrelangue")
	FIZ_AddMapping("Brood of Nozdormu", "Progéniture de Nozdormu")
	FIZ_AddMapping("Cenarion Circle", "Cercle cénarien")
	FIZ_AddMapping("Hydraxian Waterlords", "Les Hydraxiens")
	FIZ_AddMapping("The Scale of the Sands", "La Balance des sables")
	FIZ_AddMapping("Zandalar Tribe", "Tribu Zandalar")
	-- Others
	FIZ_AddMapping("Argent Dawn", "Aube d'argent")
	FIZ_AddMapping("Bloodsail Buccaneers", "La Voile sanglante")
	FIZ_AddMapping("Darkmoon Faire", "Foire de Sombrelune")
	FIZ_AddMapping("Gelkis Clan Centaur", "Centaures (Gelkis)")
	FIZ_AddMapping("Keepers of Time", "Gardiens du Temps")
	FIZ_AddMapping("Magram Clan Centaur", "Centaures (Magram)")
	FIZ_AddMapping("Ravenholdt", "Ravenholdt")
	FIZ_AddMapping("Shen'dralar", "Shen'dralar")
	FIZ_AddMapping("Syndicate", "Syndicat")
	FIZ_AddMapping("Thorium Brotherhood", "Confrérie du Thorium")
	FIZ_AddMapping("Timbermaw Hold", "Les Grumegueules")
	FIZ_AddMapping("The Violet Eye", "L'Œil pourpre")
	FIZ_AddMapping("Wintersaber Trainers", "Éleveurs de sabres-d'hiver")
	-- Wrath of the Lich King (WotLK)
	FIZ_AddMapping("Argent Crusade", "La Croisade d'argent")
	FIZ_AddMapping("Frenzyheart Tribe", "Tribu Frénécœur")
	FIZ_AddMapping("The Kalu'ak", "Les Kalu'aks")
	FIZ_AddMapping("Kirin Tor", "Kirin Tor")
	FIZ_AddMapping("Knights of the Ebon Blade", "Chevaliers de la Lame d'ébène")
	FIZ_AddMapping("The Oracles", "Les Oracles")
	FIZ_AddMapping("The Sons of Hodir", "Les Fils de Hodir")
	FIZ_AddMapping("The Wyrmrest Accord", "L'Accord de Repos du ver")
	FIZ_AddMapping("Explorers' League", "Ligue des explorateurs")
	FIZ_AddMapping("The Frostborn", "Les Givre-nés")
	FIZ_AddMapping("The Silver Covenant", "Le Concordat argenté")
	FIZ_AddMapping("Valiance Expedition", "Expédition de la Bravoure")
	FIZ_AddMapping("The Hand of Vengeance", "La Main de la vengeance")
	FIZ_AddMapping("The Sunreavers", "Les Saccage-soleil")
	FIZ_AddMapping("The Taunka", "Les Taunkas")
	FIZ_AddMapping("Warsong Offensive", "Offensive chanteguerre")
	FIZ_AddMapping("Alliance Vanguard", "Avant-garde de l'Alliance")
	FIZ_AddMapping("Horde Expedition", "Expédition de la Horde")
	FIZ_AddMapping("The Ashen Verdict", "The Ashen Verdict") -- todo: localise
end