-- English factions init (English)
function FIZ_InitEnFactions()
	-- Alliance
	FIZ_AddMapping("Darnassus", "Darnassus")
	FIZ_AddMapping("Gnomeregan Exiles", "Gnomeregan Exiles")
	FIZ_AddMapping("Ironforge", "Ironforge")
	FIZ_AddMapping("Stormwind", "Stormwind")
	FIZ_AddMapping("Exodar", "Exodar")
	-- Horde
	FIZ_AddMapping("Darkspear Trolls", "Darkspear Trolls")
	FIZ_AddMapping("Orgrimmar", "Orgrimmar")
	FIZ_AddMapping("Thunder Bluff", "Thunder Bluff")
	FIZ_AddMapping("Undercity", "Undercity")
	FIZ_AddMapping("Silvermoon City", "Silvermoon City")
	-- Alliance PvP
	FIZ_AddMapping("League of Arathor", "League of Arathor")
	FIZ_AddMapping("Silverwing Sentinels", "Silverwing Sentinels")
	FIZ_AddMapping("Stormpike Guard", "Stormpike Guard")
	-- Horde PvP
	FIZ_AddMapping("The Defilers", "The Defilers")
	FIZ_AddMapping("Frostwolf Clan", "Frostwolf Clan")
	FIZ_AddMapping("Warsong Outriders", "Warsong Outriders")
	-- Steamwheedle Cartel
	FIZ_AddMapping("Booty Bay", "Booty Bay")
	FIZ_AddMapping("Everlook", "Everlook")
	FIZ_AddMapping("Gadgetzan", "Gadgetzan")
	FIZ_AddMapping("Ratchet", "Ratchet")
	-- Outland
	FIZ_AddMapping("Cenarion Expedition", "Cenarion Expedition")
	FIZ_AddMapping("Honor Hold", "Honor Hold")
	FIZ_AddMapping("Kurenai", "Kurenai")
	FIZ_AddMapping("The Mag'har", "The Mag'har")
	FIZ_AddMapping("Ogri'la", "Ogri'la")
	FIZ_AddMapping("Netherwing", "Netherwing")
	FIZ_AddMapping("Sporeggar", "Sporeggar")
	FIZ_AddMapping("The Consortium", "The Consortium")
	FIZ_AddMapping("Thrallmar", "Thrallmar")
	FIZ_AddMapping("Tranquillien", "Tranquillien")
	-- Shattrath
	FIZ_AddMapping("Lower City", "Lower City")
	FIZ_AddMapping("Sha'tari Skyguard", "Sha'tari Skyguard")
	FIZ_AddMapping("The Aldor", "The Aldor")
	FIZ_AddMapping("The Scryers", "The Scryers")
	FIZ_AddMapping("The Sha'tar", "The Sha'tar")
	FIZ_AddMapping("Shattered Sun Offensive", "Shattered Sun Offensive")
	-- Raid
	FIZ_AddMapping("Ashtongue Deathsworn", "Ashtongue Deathsworn")
	FIZ_AddMapping("Brood of Nozdormu", "Brood of Nozdormu")
	FIZ_AddMapping("Cenarion Circle", "Cenarion Circle")
	FIZ_AddMapping("Hydraxian Waterlords", "Hydraxian Waterlords")
	FIZ_AddMapping("The Scale of the Sands", "The Scale of the Sands")
	FIZ_AddMapping("Zandalar Tribe", "Zandalar Tribe")
	-- Others
	FIZ_AddMapping("Argent Dawn", "Argent Dawn")
	FIZ_AddMapping("Bloodsail Buccaneers", "Bloodsail Buccaneers")
	FIZ_AddMapping("Darkmoon Faire", "Darkmoon Faire")
	FIZ_AddMapping("Gelkis Clan Centaur", "Gelkis Clan Centaur")
	FIZ_AddMapping("Keepers of Time", "Keepers of Time")
	FIZ_AddMapping("Magram Clan Centaur", "Magram Clan Centaur")
	FIZ_AddMapping("Ravenholdt", "Ravenholdt")
	FIZ_AddMapping("Shen'dralar", "Shen'dralar")
	FIZ_AddMapping("Syndicate", "Syndicate")
	FIZ_AddMapping("Thorium Brotherhood", "Thorium Brotherhood")
	FIZ_AddMapping("Timbermaw Hold", "Timbermaw Hold")
	FIZ_AddMapping("The Violet Eye", "The Violet Eye")
	FIZ_AddMapping("Wintersaber Trainers", "Wintersaber Trainers")
	-- Wrath of the Lich King (WotLK)
	FIZ_AddMapping("Argent Crusade", "Argent Crusade")
	FIZ_AddMapping("Frenzyheart Tribe", "Frenzyheart Tribe")
	FIZ_AddMapping("The Kalu'ak", "The Kalu'ak")
	FIZ_AddMapping("Kirin Tor", "Kirin Tor")
	FIZ_AddMapping("Knights of the Ebon Blade", "Knights of the Ebon Blade")
	FIZ_AddMapping("The Oracles", "The Oracles")
	FIZ_AddMapping("The Sons of Hodir", "The Sons of Hodir")
	FIZ_AddMapping("The Wyrmrest Accord", "The Wyrmrest Accord")
	FIZ_AddMapping("Explorers' League", "Explorers' League")
	FIZ_AddMapping("The Frostborn", "The Frostborn")
	FIZ_AddMapping("The Silver Covenant", "The Silver Covenant")
	FIZ_AddMapping("Valiance Expedition", "Valiance Expedition")
	FIZ_AddMapping("The Hand of Vengeance", "The Hand of Vengeance")
	FIZ_AddMapping("The Sunreavers", "The Sunreavers")
	FIZ_AddMapping("The Taunka", "The Taunka")
	FIZ_AddMapping("Warsong Offensive", "Warsong Offensive")
	FIZ_AddMapping("Alliance Vanguard", "Alliance Vanguard")
	FIZ_AddMapping("Horde Expedition", "Horde Expedition")
	FIZ_AddMapping("The Ashen Verdict", "The Ashen Verdict")
end