-- Deutsch factions init (German)
function FIZ_InitDeFactions()
	-- Alliance
	FIZ_AddMapping("Darnassus", "Darnassus")
	FIZ_AddMapping("Gnomeregan Exiles", "Gnomeregangnome")
	FIZ_AddMapping("Ironforge", "Eisenschmiede")
	FIZ_AddMapping("Stormwind", "Sturmwind")
	FIZ_AddMapping("Exodar", "Die Exodar")
	-- Horde
	FIZ_AddMapping("Darkspear Trolls", "Dunkelspeertrolle")
	FIZ_AddMapping("Orgrimmar", "Orgrimmar")
	FIZ_AddMapping("Thunder Bluff", "Donnerfels")
	FIZ_AddMapping("Undercity", "Unterstadt")
	FIZ_AddMapping("Silvermoon City", "Silbermond")
	-- Alliance PvP
	FIZ_AddMapping("League of Arathor", "Der Bund von Arathor")
	FIZ_AddMapping("Silverwing Sentinels", "Silberschwingen")
	FIZ_AddMapping("Stormpike Guard", "Sturmlanzengarde")
	-- Horde PvP
	FIZ_AddMapping("The Defilers", "Die Entweihten")
	FIZ_AddMapping("Frostwolf Clan", "Frostwolfklan ")
	FIZ_AddMapping("Warsong Outriders", "Kriegshymnenklan ")
	-- Steamwheedle Cartel
	FIZ_AddMapping("Booty Bay", "Beutebucht")
	FIZ_AddMapping("Everlook", "Ewige Warte")
	FIZ_AddMapping("Gadgetzan", "Gadgetzan")
	FIZ_AddMapping("Ratchet", "Ratschet")
	-- Outland
	FIZ_AddMapping("Cenarion Expedition", "Expedition des Cenarius")
	FIZ_AddMapping("Honor Hold", "Ehrenfeste")
	FIZ_AddMapping("Kurenai", "Kurenai")
	FIZ_AddMapping("The Mag'har", "Die The Mag'har")
	FIZ_AddMapping("Ogri'la", "Ogri'la")
	FIZ_AddMapping("Netherwing", "Netherschwingen")
	FIZ_AddMapping("Sporeggar", "Sporeggar")
	FIZ_AddMapping("The Consortium", "Das Konsortium")
	FIZ_AddMapping("Thrallmar", "Thrallmar")
	FIZ_AddMapping("Tranquillien", "Tristessa")
	-- Shattrath
	FIZ_AddMapping("Lower City", "Unteres Viertel")
	FIZ_AddMapping("Sha'tari Skyguard", "Himmelswache der Sha'tari")
	FIZ_AddMapping("The Aldor", "Die Aldor")
	FIZ_AddMapping("The Scryers", "Die Seher")
	FIZ_AddMapping("The Sha'tar", "Die Sha'tar")
	FIZ_AddMapping("Shattered Sun Offensive", "Zerschmetterte Sonne")
	-- Raid
	FIZ_AddMapping("Ashtongue Deathsworn", "Die Todesh\195\182rigen")
	FIZ_AddMapping("Brood of Nozdormu", "Brut Nozdormus")
	FIZ_AddMapping("Cenarion Circle", "Zirkel des Cenarius")
	FIZ_AddMapping("Hydraxian Waterlords", "Hydraxianer")
	FIZ_AddMapping("The Scale of the Sands", "Die W\195\164chter der Sande")
	FIZ_AddMapping("Zandalar Tribe", "Stamm der Zandalar")
	-- Others
	FIZ_AddMapping("Argent Dawn", "Argentumd\195\164mmerung")
	FIZ_AddMapping("Bloodsail Buccaneers", "Blutsegelbukaniere")
	FIZ_AddMapping("Darkmoon Faire", "Dunkelmond-Jahrmarkt")
	FIZ_AddMapping("Gelkis Clan Centaur", "Gelkisklan")
	FIZ_AddMapping("Keepers of Time", "H\195\188ter der Zeit")
	FIZ_AddMapping("Magram Clan Centaur", "Magramklan")
	FIZ_AddMapping("Ravenholdt", "Rabenholdt")
	FIZ_AddMapping("Shen'dralar", "Shen'dralar")
	FIZ_AddMapping("Syndicate", "Syndikat")
	FIZ_AddMapping("Thorium Brotherhood", "Thoriumbruderschaft")
	FIZ_AddMapping("Timbermaw Hold", "Holzschlundfeste")
	FIZ_AddMapping("The Violet Eye", "Das violette Auge")
	FIZ_AddMapping("Wintersaber Trainers", "Winters\195\164blerausbilder")
	-- Wrath of the Lich King (WotLK)
	FIZ_AddMapping("Argent Crusade", "Argentumkreuzzug ")
	FIZ_AddMapping("Frenzyheart Tribe", "Stamm der Wildherzen")
	FIZ_AddMapping("The Kalu'ak", "Die Kalu'ak")
	FIZ_AddMapping("Kirin Tor", "Kirin Tor")
	FIZ_AddMapping("Knights of the Ebon Blade", "Ritter der Schwarzen Klinge")
	FIZ_AddMapping("The Oracles", "Die Orakel")
	FIZ_AddMapping("The Sons of Hodir", "Die S\195\182hne Hodirs")
	FIZ_AddMapping("The Wyrmrest Accord", "Der Wyrmruhpakt")
	FIZ_AddMapping("Explorers' League", "Forscherliga ")
	FIZ_AddMapping("The Frostborn", "Die Frosterben")
	FIZ_AddMapping("The Silver Covenant", "Der Silberbund")
	FIZ_AddMapping("Valiance Expedition", "Expedition Valianz")
	FIZ_AddMapping("The Hand of Vengeance", "Die Hand der Rache")
	FIZ_AddMapping("The Sunreavers", "Die Sonnenh\195\164scher")
	FIZ_AddMapping("The Taunka", "Die Taunka")
	FIZ_AddMapping("Warsong Offensive", "Kriegshymnenoffensive")
	FIZ_AddMapping("Alliance Vanguard", "Vorposten der Allianz")
	FIZ_AddMapping("Horde Expedition", "Expedition der Horde")
	FIZ_AddMapping("The Ashen Verdict", "Das Äscherne Verdikt")
end