-- Spanish factions init (Spanish)
function FIZ_InitEsFactions()
	-- Alliance
	FIZ_AddMapping("Darnassus", "Darnassus")
	FIZ_AddMapping("Gnomeregan Exiles", "Exiliados de Gnomeregan")
	FIZ_AddMapping("Ironforge", "Forjaz")
	FIZ_AddMapping("Stormwind", "Ventormenta")
	FIZ_AddMapping("Exodar", "El Exodar")
	-- Horde
	FIZ_AddMapping("Darkspear Trolls", "Trols Lanza Negra")
	FIZ_AddMapping("Orgrimmar", "Orgrimmar")
	FIZ_AddMapping("Thunder Bluff", "Cima del Trueno")
	FIZ_AddMapping("Undercity", "Entrañas")
	FIZ_AddMapping("Silvermoon City", "Ciudad de Lunargenta")
	-- Alliance PvP
	FIZ_AddMapping("League of Arathor", "Liga de Arathor")
	FIZ_AddMapping("Silverwing Sentinels", "Centinelas Ala de Plata")
	FIZ_AddMapping("Stormpike Guard", "Guardia Pico Tormenta")
	-- Horde PvP
	FIZ_AddMapping("The Defilers", "Los Rapiñadores")
	FIZ_AddMapping("Frostwolf Clan", "Clan Lobo Gélido")
	FIZ_AddMapping("Warsong Outriders", "Escoltas Grito de Guerra")
	-- Steamwheedle Cartel
	FIZ_AddMapping("Booty Bay", "Bahía del Botín")
	FIZ_AddMapping("Everlook", "Vista Eterna")
	FIZ_AddMapping("Gadgetzan", "Gadgetzan")
	FIZ_AddMapping("Ratchet", "Trinquete")
	-- Outland
	FIZ_AddMapping("Cenarion Expedition", "Expedición Cenarion")
	FIZ_AddMapping("Honor Hold", "Bastión del Honor")
	FIZ_AddMapping("Kurenai", "Kurenai")
	FIZ_AddMapping("The Mag'har", "Los Mag'har")
	FIZ_AddMapping("Ogri'la", "Ogri'la")
	FIZ_AddMapping("Netherwing", "Ala Abisal")
	FIZ_AddMapping("Sporeggar", "Esporaggar")
	FIZ_AddMapping("The Consortium", "El Consorcio")
	FIZ_AddMapping("Thrallmar", "Thrallmar")
	FIZ_AddMapping("Tranquillien", "Tranquillien")
	-- Shattrath
	FIZ_AddMapping("Lower City", "Bajo Arrabal")
	FIZ_AddMapping("Sha'tari Skyguard", "Guardia del cielo Sha'tari")
	FIZ_AddMapping("The Aldor", "Los Aldor")
	FIZ_AddMapping("The Scryers", "Los Arúspices")
	FIZ_AddMapping("The Sha'tar", "Los Sha'tar")
	FIZ_AddMapping("Shattered Sun Offensive", "Ofensiva Sol Devastado")
	-- Raid
	FIZ_AddMapping("Ashtongue Deathsworn", "Juramorte Lengua de ceniza")
	FIZ_AddMapping("Brood of Nozdormu", "Linaje de Nozdormu")
	FIZ_AddMapping("Cenarion Circle", "Círculo Cenarion")
	FIZ_AddMapping("Hydraxian Waterlords", "Srs. del Agua de Hydraxis")
	FIZ_AddMapping("The Scale of the Sands", "La Escama de las Arenas")
	FIZ_AddMapping("Zandalar Tribe", "Tribu Zandalar")
	-- Others
	FIZ_AddMapping("Argent Dawn", "El Alba Argenta")
	FIZ_AddMapping("Bloodsail Buccaneers", "Bucaneros Velasangre")
	FIZ_AddMapping("Darkmoon Faire", "Feria de la Luna Negra")
	FIZ_AddMapping("Gelkis Clan Centaur", "Centauros del clan Gelkis")
	FIZ_AddMapping("Keepers of Time", "Vigilantes del Tiempo")
	FIZ_AddMapping("Magram Clan Centaur", "Centauros del clan Magram")
	FIZ_AddMapping("Ravenholdt", "Ravenholdt")
	FIZ_AddMapping("Shen'dralar", "Shen'dralar")
	FIZ_AddMapping("Syndicate", "La Hermandad")
	FIZ_AddMapping("Thorium Brotherhood", "Hermandad del Torio")
	FIZ_AddMapping("Timbermaw Hold", "Bastión Fauces de Madera")
	FIZ_AddMapping("The Violet Eye", "El Ojo Violeta")
	FIZ_AddMapping("Wintersaber Trainers", "Instructores de Sableinvernales")
	-- Wrath of the Lich King (WotLK)
	FIZ_AddMapping("Argent Crusade", "Cruzada Argenta")
	FIZ_AddMapping("Frenzyheart Tribe", "Tribu Corazón Frenético")
	FIZ_AddMapping("The Kalu'ak", "Los Kalu'ak")
	FIZ_AddMapping("Kirin Tor", "Kirin Tor")
	FIZ_AddMapping("Knights of the Ebon Blade", "Caballeros de la Espada de Ébano")
	FIZ_AddMapping("The Oracles", "Los Oráculos")
	FIZ_AddMapping("The Sons of Hodir", "Los Hijos de Hodir")
	FIZ_AddMapping("The Wyrmrest Accord", "El Acuerdo del Reposo del Dragón")
	FIZ_AddMapping("Explorers' League", "Liga de Expedicionarios")
	FIZ_AddMapping("The Frostborn", "Los Natoescarcha")
	FIZ_AddMapping("The Silver Covenant", "El Pacto de Plata")
	FIZ_AddMapping("Valiance Expedition", "Expedición de Denuedo")
	FIZ_AddMapping("The Hand of Vengeance", "La Mano de la Venganza")
	FIZ_AddMapping("The Sunreavers", "Los Atracasol")
	FIZ_AddMapping("The Taunka", "Los taunka")
	FIZ_AddMapping("Warsong Offensive", "Ofensiva Grito de Guerra")
	FIZ_AddMapping("Alliance Vanguard", "Vanguardia de la Alianza")
	FIZ_AddMapping("Horde Expedition", "Expedición de la Horda")
	FIZ_AddMapping("The Ashen Verdict", "The Ashen Verdict")	-- todo: localise
end