-- yleaf(yaroot@gmail.com)
if GetLocale() ~= "zhTW" then return end

DBM_BC_TARGET		= "<目標>"

DBM_GRUULS_LAIR		= "戈魯爾之巢"
DBM_MAGS_LAIR		= "瑪瑟里頓的巢穴"
DBM_HELLFIRE		= "地獄火半島"
DBM_SHADOWMOON		= "影月谷"

DBM_GENERIC_ENRAGE_WARN		= "%s%s后激怒"
DBM_GENERIC_PHASE_MSG		= "第%s階段"
DBM_GENERIC_PHASE_MSG2		= "第%s階段"
DBM_PHASE					= "第%s階段"
DBM_WAVE					= "第%s波"
DBM_SET_ICON				= "設置圖標"
DBM_SEND_WHISPER			= "發送密語"
DBM_HP_UNKNOWN				= "未知血量"
DBM_NO_TARGET				= "<沒有目標>"
DBM_UPGRADE					= "升級"
DBM_MISC					= "其他"
DBM_IS						= "是"
DBM_OR						= "或"
DBM_AND						= "和"
DBM_UNKNOWN			 		= "未知"
DBM_LOCAL					= "本地"
DBM_SEC						= "秒"
DBM_MIN						= "分"
DBM_SECOND					= "秒"
DBM_SECONDS					= "秒"
DBM_MINUTES					= "分鐘"
DBM_MINUTE					= "分鐘"
DBM_DEAD					= "死亡"
DBM_OFFLINE					= "離線"
