if GetLocale() ~= "esES" and GetLocale() ~= "esMX" then return end

DBM_BC_TARGET		= "<target>"

DBM_GRUULS_LAIR		= "Guarida de Gruul"
DBM_MAGS_LAIR		= "Guarida de Magtheridon"
DBM_HELLFIRE		= "Península del Fuego Infernal"
DBM_SHADOWMOON		= "Valle Sombraluna"

DBM_GENERIC_ENRAGE_WARN		= "Enrage en %s %s"
DBM_GENERIC_PHASE_MSG		= "Fase %s"
DBM_GENERIC_PHASE_MSG2		= "%s fase"
DBM_PHASE					= "Fase %s"
DBM_WAVE					= "Oleada %s"
DBM_SET_ICON				= "Poner icono"
DBM_SEND_WHISPER			= "Enviar susurro"
DBM_HP_UNKNOWN				= "HP Desconocida"
DBM_NO_TARGET				= "<no target>"
DBM_UPGRADE					= "actualizar"
DBM_MISC					= "miscelanea"
DBM_IS						= "es"
DBM_OR						= "o"
DBM_AND						= "y"
DBM_UNKNOWN			 		= "desconocido"
DBM_LOCAL					= "local"
DBM_SEC						= "seg"
DBM_MIN						= "min"
DBM_SECOND					= "segundo"
DBM_SECONDS					= "segundos"
DBM_MINUTES					= "minutos"
DBM_MINUTE					= "minuto"
DBM_DEAD					= "Muerto"
DBM_OFFLINE					= "Desconectado"