-- This file is automagically generated.
-- Please visit http://www.wowace.com/projects/range-display/localization/
-- if you wish to help with the translation.

local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay_Options", "ruRU")
if not L then return end

L["A free-form suffix to append to the range display when you are further than range limit"] = "Суффикс, отображаемый на экране в то время, пока цель находится вне зоны досягаемости. (По умолчанию - +)"
L["A free-form suffix to append to the range display when you are in range"] = "Суффикс, отображаемый на экране в то время, пока цель находится в пределах досягаемости"
L["Anchor to Mouse"] = "Привязать к мышке"
L["Auto adjust"] = "Авто регулировка"
L["Auto hide"] = "Авто скрытие"
L["Background Color"] = "Цвет фона"
L["Background Options"] = "Настройки фона"
L["Background Texture"] = "Текстура фона"
L["Background Tile Size"] = "Размер мозаики фона"
L["Border Color"] = "Цвет краев"
L["Border Texture"] = "Текстура краев"
L["Border Thickness"] = "Толщина краев"
L["Close range section"] = "В близи"
L["Color"] = "Цвет"
L["Default section"] = "По умолчанию"
L["Enabled"] = "Включен"
L["Enable this color section"] = "Включить окраску"
L["Enemy only"] = "Только враг"
L["Font"] = "Црифт"
L["Font outline"] = "Контур шрифта"
L["Font size"] = "Размер шрифта"
L["Frame's background color"] = "Цвет фона фрейма"
L["Frame's border color"] = "Цвет края фрейма"
L["Frame strata"] = "Слои фрейма"
L["Height"] = "Высота"
L["Hide the background if the range display is not active"] = "Скрыть фон если индикатор досягаемости не активен"
L["High"] = "Высокий"
L["Locked"] = "Фиксировать"
L["Lock/Unlock display frame"] = "Фиксировать/освободить фреймы на экране"
L["Low"] = "Низкий"
L["Max range only"] = "Только макс дистанция"
L["Medium"] = "Средний"
L["Medium range section"] = "Средняя дистанция"
L["None"] = "Нету"
L["Normal"] = "Обычный"
L["Out of range section"] = "Вне досягаемости"
L["Over limit display"] = "Предел отображения"
L["Over limit suffix"] = "Суффикс \"Вне досягаемости\""
L["Range limit"] = "Предел дистанции"
L["Ranges above this are not reported"] = "Дистанция выше указанной не будет выдаватся"
L["Short range section"] = "Не долеко"
L["Show/Hide display if the target is further than range limit"] = "Показать/Скрыть если цель дальше чем заданный предел дистанции"
L["Show range for enemy targets only"] = "Показывать дистанцию только до вражеских целей"
L["Show the maximum range only"] = "Показывать только максимальную дистанцию"
L["Strata"] = "Слои"
L["Suffix"] = "Суффикс"
L["Text"] = "Текст"
L["Texture to use for the frame's background"] = "Текстура для использования в качестве фона фрейма"
L["Texture to use for the frame's border"] = "Текстура для использования в качестве края фрейма"
L["The size used to tile the background texture"] = "Размер мазайки используемой в фоновой текстуре"
L["The thickness of the border"] = "Толщина края"
L["Thick"] = "Толстый"
L["Tile Background"] = "Фон - мозаика"
L["Tile the background texture"] = "Мозаичное изображения фоновой текстуры"
L["Use Section Colors"] = "Использовать Выбраный Цвет"
L["Use Text"] = "Использовать Выбраный Шрифт"
L["Width"] = "Ширина"

