-- This file is automagically generated.
-- Please visit http://www.wowace.com/projects/range-display/localization/
-- if you wish to help with the translation.

local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay_Options", "zhTW")
if not L then return end

L["A free-form suffix to append to the range display when you are further than range limit"] = "當目標在你的射程外時顯示一個尾碼"
L["A free-form suffix to append to the range display when you are in range"] = "當目標在你的射程內時顯示一個尾碼"
L["Auto adjust"] = "自動調整"
L["Auto hide"] = "自動隱藏"
L["Background Color"] = "背景顏色"
L["Background Options"] = "背景選項"
L["Background Texture"] = "背景材質"
L["Background Tile Size"] = "背景網格尺寸"
L["Border Color"] = "邊框顏色"
L["Border Texture"] = "邊框材質"
L["Border Thickness"] = "邊框厚度"
L["Close range section"] = "近距離項"
L["Color"] = "顏色"
L["Default section"] = "默認項"
L["Enabled"] = "開啟"
L["Enable this color section"] = "開啟此色彩項目"
L["Enemy only"] = "僅敵對"
L["Font"] = "字體"
L["Font outline"] = "字體描邊"
L["Font size"] = "字型大小"
L["Frame's background color"] = "框架背景顏色"
L["Frame's border color"] = "框架邊框顏色"
L["Frame strata"] = "框架顯示層面"
L["Height"] = "高度"
L["Hide the background if the range display is not active"] = "如果距離檢測沒有使用自動隱藏背景"
L["High"] = "最高層"
L["Locked"] = "鎖定"
L["Lock/Unlock display frame"] = "鎖定或解鎖顯示框"
L["Low"] = "最低層"
L["Max range only"] = "只顯示最大射程"
L["Medium"] = "中間層"
L["Medium range section"] = "中距離項"
L["None"] = "無"
L["Normal"] = "正常"
L["Out of range section"] = "超出距離項"
L["Over limit display"] = "超出距離顯示"
L["Over limit suffix"] = "超出距離尾碼"
L["Range limit"] = "距離限制"
L["Ranges above this are not reported"] = "不提醒超出此數值的距離"
L["Short range section"] = "短距離項"
L["Show/Hide display if the target is further than range limit"] = "在目標超出距離時顯示/隱藏距離框體"
L["Show range for enemy targets only"] = "僅顯示敵對目標的距離"
L["Show the maximum range only"] = "只顯示最大射程"
L["Strata"] = "層級"
L["Suffix"] = "尾碼"
L["Texture to use for the frame's background"] = "框架背景的材質"
L["Texture to use for the frame's border"] = "框架邊框的材質"
L["The size used to tile the background texture"] = "網格背景尺寸"
L["The thickness of the border"] = "設置邊框厚度"
L["Thick"] = "加粗"
L["Tile Background"] = "網格背景"
L["Tile the background texture"] = "網格背景材質"
L["Width"] = "寬度"

