-- Local stuff

XPERL_RAID_MONITOR_TITLE		= "Casting Monitor |c00A04040(BETA)|r"
XPERL_RAID_MONITOR_TOTALS		= "Toggle display of Totals and Statistics"

XPERL_RAID_MONITOR_STATS_RAID_MANA	= "Raid Mana"
XPERL_RAID_MONITOR_STATS_HIGH_MANA	= "High Mana"
XPERL_RAID_MONITOR_STATS_LOW_MANA	= "Low Mana"
XPERL_RAID_MONITOR_STATS_RAID_HEALTH	= "Raid Health"

XPERL_MONITOR_LEFTCLICK			= "|c00FFFFFFLeft Click|r to %s"
XPERL_MONITOR_RIGHTCLICK		= "|c00FFFFFFRight Click|r to %s"
XPERL_MONITOR_CLICKCAST			= "cast |c0000FF00%s|r"
XPERL_MONITOR_CLICKTARGET		= "|c00FFFF80target|r"

XPERL_MONITOR_INNERVATE			= "Innervate"
XPERL_MONITOR_MANATIDE			= "Mana Tide Totem"

XPERL_LOC_OOR				= "n/a"
