-- Local stuff

if (GetLocale() == "koKR") then
	XPERL_RAID_MONITOR_TITLE		= "시전 현황 |c00A04040(BETA)|r"
	XPERL_RAID_MONITOR_TOTALS		= "총계와 현황의 표시를 켜고 끕니다."

	XPERL_RAID_MONITOR_STATS_RAID_MANA	= "공격대 마나"
	XPERL_RAID_MONITOR_STATS_HIGH_MANA	= "마나 높음"
	XPERL_RAID_MONITOR_STATS_LOW_MANA	= "마나 낮음"
	XPERL_RAID_MONITOR_STATS_RAID_HEALTH	= "공격대 생명력"

	XPERL_MONITOR_LEFTCLICK			= "|c00FFFFFF좌클릭|r - %s"
	XPERL_MONITOR_RIGHTCLICK		= "|c00FFFFFF우클릭|r - %s"
	XPERL_MONITOR_CLICKCAST			= "|c0000FF00%s|r 시전"
	XPERL_MONITOR_CLICKTARGET		= "|c00FFFF80대상|r"

	XPERL_MONITOR_INNERVATE		= "정신 자극"
	XPERL_MONITOR_MANATIDE		= "마나 해일 토템"
end
