--[[

************************************************************************

deDE.lua

deDE localization strings for Querier

File date: 2009-06-16T21:39:38Z 
Project version: v1.82

Please update http://www.wowace.com/projects/querier/localization/deDE/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.

************************************************************************

Please see http://www.wowace.com/projects/querier/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************

]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Querier", "deDE", false);

if not L then return end

