
function Skinner:BattleCry()

-->>--	Help Frame
	BC_MainFrame_HelpFrame:SetHeight(BC_MainFrame:GetHeight())
	self:keepFontStrings(BC_MainFrame_HelpFrame)
	self:moveObject(BC_MainFrame_HelpFrame, "-", 13, "-", 5)
	self:applySkin(BC_MainFrame_HelpFrame, nil)

-->>--	EditConditions Frame
	self:keepFontStrings(BC_EditConditionsFrame_ConditionFrame_ListScroll)
	self:skinScrollBar(BC_EditConditionsFrame_ConditionFrame_ListScroll)
	self:keepFontStrings(BC_EditConditionsFrame_ConditionFrame)
	self:applySkin(BC_EditConditionsFrame_ConditionFrame, nil)
	self:skinEditBox(BC_EditConditionsFrame_TarEditBox, {9})
	self:skinEditBox(BC_EditConditionsFrame_VarEditBox, {9})
	self:moveObject(BC_EditConditionsFrame_VarEditBox, nil, nil, "-", 8)
	self:skinEditBox(BC_EditConditionsFrame_TesEditBox, {9})
	self:moveObject(BC_EditConditionsFrame_TesEditBox, nil, nil, "-", 8)
	self:skinEditBox(BC_EditConditionsFrame_ValEditBox, {9})
	self:moveObject(BC_EditConditionsFrame_ValEditBox, nil, nil, "-", 6)
	self:moveObject(BC_EditConditionsFrame_TestButton, nil, nil, "-", 4)
	self:moveObject(BC_EditConditionsFrame_SaveButton, nil, nil, "-", 4)
	self:keepFontStrings(BC_EditConditionsFrame)
	self:applySkin(BC_EditConditionsFrame, nil)

-->>--	EventWatch Frame
	self:keepFontStrings(BC_EventWatchFrame_WatchFrame_ListScroll)
	self:skinScrollBar(BC_EventWatchFrame_WatchFrame_ListScroll)
	self:keepFontStrings(BC_EventWatchFrame_WatchFrame)
	self:applySkin(BC_EventWatchFrame_WatchFrame, nil)
	self:keepFontStrings(BC_EventWatchFrame_Arg2Frame)
	self:applySkin(BC_EventWatchFrame_Arg2Frame, nil)
	self:keepFontStrings(BC_EventWatchFrame_Arg1Frame_ListScroll)
	self:skinScrollBar(BC_EventWatchFrame_Arg1Frame_ListScroll)
	self:keepFontStrings(BC_EventWatchFrame_Arg1Frame)
	self:applySkin(BC_EventWatchFrame_Arg1Frame, nil)
	self:keepFontStrings(BC_EventWatchFrame_EventsFrame_ListScroll)
	self:skinScrollBar(BC_EventWatchFrame_EventsFrame_ListScroll)
	self:keepFontStrings(BC_EventWatchFrame_EventsFrame)
	self:applySkin(BC_EventWatchFrame_EventsFrame, nil)
	self:skinEditBox(BC_EventWatchFrame_EventsFrame_TextEditBox, {9})
	self:skinEditBox(BC_EventWatchFrame_Arg1Frame_TextEditBox, {9})
	self:skinEditBox(BC_EventWatchFrame_Arg2Frame_TextEditBox, {9})
	self:skinEditBox(BC_EventWatchFrame_WatchFrame_NameEditBox, {9})

-->>--	EditCries Frame
	self:keepFontStrings(CryEditCategoryFrame_ListScroll)
	self:skinScrollBar(CryEditCategoryFrame_ListScroll)
	self:keepFontStrings(CryEditCategoryFrame)
	self:applySkin(CryEditCategoryFrame, nil)
	self:keepFontStrings(CryInputFrame_CastDropDown)
	self:keepFontStrings(CryInputFrame_LanguagesDropDown)
	self:keepFontStrings(CryInputFrame_ModesDropDown)
	self:keepFontStrings(CryInputFrame)
	self:applySkin(CryInputFrame, nil)
	self:keepFontStrings(CryEditCryListFrame_ListScroll)
	self:skinScrollBar(CryEditCryListFrame_ListScroll)
	self:keepFontStrings(CryEditCryListFrame)
	self:applySkin(CryEditCryListFrame, nil)
	self:keepFontStrings(CryEditCustomCryEditActionFrame_DeleteString)
	self:applySkin(CryEditCustomCryEditActionFrame_DeleteString, nil)
	self:keepFontStrings(CryEditCustomCryEditActionFrame)
	self:applySkin(CryEditCustomCryEditActionFrame, nil)
	self:keepFontStrings(CryEditActionFrame_ListScroll)
	self:skinScrollBar(CryEditActionFrame_ListScroll)
	self:keepFontStrings(CryEditActionFrame)
	self:applySkin(CryEditActionFrame, nil)
	self:skinEditBox(CryEditCustomCryEditActionFrame_EditBox, {9})
	self:skinEditBox(CryEditActionFrame_CooldownEditBox, {9})
	self:skinEditBox(CryInputFrame_NameEditBox, {9})

-->>--	SavedChains Frame
	self:keepFontStrings(SavedChainsFrame_ListScroll)
	self:skinScrollBar(SavedChainsFrame_ListScroll)
	self:keepFontStrings(SavedChainsFrame)
	self:applySkin(SavedChainsFrame, nil)

-->>--	ChainSelectTail
	self:keepFontStrings(ChainSelectTail_CryListFrame_ListScroll)
	self:skinScrollBar(ChainSelectTail_CryListFrame_ListScroll)
	self:keepFontStrings(ChainSelectTail_CryListFrame)
	self:applySkin(ChainSelectTail_CryListFrame, nil)
	self:keepFontStrings(ChainSelectTail_CategoryFrame_ListScroll)
	self:skinScrollBar(ChainSelectTail_CategoryFrame_ListScroll)
	self:keepFontStrings(ChainSelectTail_CategoryFrame)
	self:applySkin(ChainSelectTail_CategoryFrame, nil)
	self:keepFontStrings(ChainSelectTail_ActionFrame_ListScroll)
	self:skinScrollBar(ChainSelectTail_ActionFrame_ListScroll)
	self:keepFontStrings(ChainSelectTail_ActionFrame)
	self:applySkin(ChainSelectTail_ActionFrame, nil)
	self:keepFontStrings(ChainSelectTail)
	self:applySkin(ChainSelectTail, nil)

-->>--	ChainSelectHead
	self:keepFontStrings(ChainSelectHead_CategoryFrame_ListScroll)
	self:skinScrollBar(ChainSelectHead_CategoryFrame_ListScroll)
	self:keepFontStrings(ChainSelectHead_CategoryFrame)
	self:applySkin(ChainSelectHead_CategoryFrame, nil)
	self:keepFontStrings(ChainSelectHead_CryListFrame_ListScroll)
	self:skinScrollBar(ChainSelectHead_CryListFrame_ListScroll)
	self:keepFontStrings(ChainSelectHead_CryListFrame)
	self:applySkin(ChainSelectHead_CryListFrame, nil)
	self:keepFontStrings(ChainSelectHead_ActionFrame_ListScroll)
	self:skinScrollBar(ChainSelectHead_ActionFrame_ListScroll)
	self:keepFontStrings(ChainSelectHead_ActionFrame)
	self:applySkin(ChainSelectHead_ActionFrame, nil)
	self:keepFontStrings(ChainSelectHead)
	self:applySkin(ChainSelectHead, nil)

-->>--	Tabs
	self:keepFontStrings(BC_TabFrameTab2)
	self:keepFontStrings(BC_TabFrameTab3)
	self:keepFontStrings(BC_TabFrameTab1)
	if self.db.profile.TexturedTab then self:applySkin(BC_TabFrameTab1, nil, 0)
	else self:applySkin(BC_TabFrameTab1) end
	if self.db.profile.TexturedTab then self:applySkin(BC_TabFrameTab2, nil, 0)
	else self:applySkin(BC_TabFrameTab2) end
	self:moveObject(BC_TabFrameTab2, "-", 6, nil, nil)
	if self.db.profile.TexturedTab then self:applySkin(BC_TabFrameTab3, nil, 0)
	else self:applySkin(BC_TabFrameTab3) end
	self:moveObject(BC_TabFrameTab3, "-", 6, nil, nil)

	self:skinEditBox(BC_MainFrame_ExecBox, {9})
	self:keepRegions(BC_MainFrame, {8, 9, 10}) -- N.B. region 8 is text, 9 & 10 are icons
	self:applySkin(BC_MainFrame, nil)

-->>--	EventFinder Frame
	self:keepFontStrings(BC_EventFinderFrame_ListScroll)
	self:skinScrollBar(BC_EventFinderFrame_ListScroll)
	self:skinEditBox(BC_EventFinderFrame_Arg1EditBox, {9})
	self:skinEditBox(BC_EventFinderFrame_Arg2EditBox, {9})
	self:skinEditBox(BC_EventFinderFrame_Arg3EditBox, {9})
	self:skinEditBox(BC_EventFinderFrame_Arg4EditBox, {9})
	self:skinEditBox(BC_EventFinderFrame_Arg5EditBox, {9})
	self:keepFontStrings(BC_EventFinderFrame)
	self:applySkin(BC_EventFinderFrame, nil)

end
