-- Chinese localization file for zhTW.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local zhTW = AceLocale:NewLocale("GoblinVendorFilter", "zhTW")
if not zhTW then return end

-- zhTW["Affordable"] = "Affordable"
-- zhTW["Affordable Filter"] = "Affordable Filter"
-- zhTW["Affordable Filter Default"] = "Affordable Filter Default"
zhTW["Already Known Filter"] = "已學配方過濾"
zhTW["Already Known Filter Default"] = "已學配方過濾（默認）"
-- zhTW["|cFFFF0000<<WARNING>>|r|nIf you change these from the default grey checkmark you may missout on items with no stats.|nOnly item stats you have previously seen can be filtered by default"] = "|cFFFF0000<<WARNING>>|r|nIf you change these from the default grey checkmark you may missout on items with no stats.|nOnly item stats you have previously seen can be filtered by default"
-- zhTW["Don't Want:"] = "Don't Want:"
zhTW["Equip Location Filter"] = "物品位置過濾"
zhTW["Filter All"] = "過濾所有"
zhTW["Filter All desc"] = "由於過濾重疊你必須禁用兩個或多個過濾條件使用後該過濾按鈕。"
-- zhTW["Hides this sub type from being displayed"] = "Hides this sub type from being displayed"
zhTW["Item Quality Filter"] = "物品品质过滤"
-- zhTW["Item Stat Filter"] = "Item Stat Filter"
zhTW["Item Type Filter"] = "物品類型过滤"
-- zhTW["Only equip location you have previously seen can be filtered by default"] = "Only equip location you have previously seen can be filtered by default"
-- zhTW["Only item stats you have previously seen can be filtered by default"] = "Only item stats you have previously seen can be filtered by default"
-- zhTW["Only Type/SubType combinations you have previously seen can be filtered by default"] = "Only Type/SubType combinations you have previously seen can be filtered by default"
zhTW["Show All"] = "顯示全部"
-- zhTW["Show this sub type"] = "Show this sub type"
zhTW["Usable Items Filter"] = "可用的物品過濾"
zhTW["Usable Items Filter Default"] = "可用的物品過濾（過濾）"
-- zhTW["Want:"] = "Want:"
-- zhTW["When selected only items you can afford will be displayed initially!"] = "When selected only items you can afford will be displayed initially!"
zhTW["When selected only unknown or not learnable items will be shown initially!"] = "只選擇未知或不可以學習的物品時將顯示初步！"
zhTW["When selected only usable items will be displayed initially!"] = "只選擇可用的物品時會最先顯示！"
-- zhTW["When selected this item equip location will be filtered out"] = "When selected this item equip location will be filtered out"
-- zhTW["When selected this item equip location will be shown"] = "When selected this item equip location will be shown"
zhTW["When selected this item quality will be filtered out"] = "當選定這個項目質量將被過濾掉"
-- zhTW["When selected this item quality will be shown"] = "When selected this item quality will be shown"
-- zhTW["When selected this item stat will be filtered out"] = "When selected this item stat will be filtered out"
-- zhTW["When selected this item type will be hidden unless multible subtypes are found"] = "When selected this item type will be hidden unless multible subtypes are found"
-- zhTW["When selected this item type will be shown unless multible subtypes are found"] = "When selected this item type will be shown unless multible subtypes are found"
-- zhTW["Yellow Checkmark:|nWe want this stat.|n|nGrey Checkmark:|nWe do not care if we have this stat or not.|n|nNo Checkmark:|nWe do not want this stat."] = "Yellow Checkmark:|nWe want this stat.|n|nGrey Checkmark:|nWe do not care if we have this stat or not.|n|nNo Checkmark:|nWe do not want this stat."

