-- X-Perl UnitFrames
-- Author: Zek <Boodhoof-EU>
-- License: GNU GPL v3, 29 June 2007 (see LICENSE.txt)

XPERL_RAID_GROUP		= "Group %d"
XPERL_RAID_TOOLTIP_NOCTRA	= "No CTRA Found"
XPERL_RAID_TOOLTIP_OFFLINE	= "Offline for %s"
XPERL_RAID_TOOLTIP_AFK		= "AFK for %s"
XPERL_RAID_TOOLTIP_DND		= "DND for %s"
XPERL_RAID_TOOLTIP_DYING	= "Dying in %s"
XPERL_RAID_TOOLTIP_REBIRTH	= "Rebirth up in: %s"
XPERL_RAID_TOOLTIP_ANKH		= "Ankh up in: %s"
XPERL_RAID_TOOLTIP_SOULSTONE	= "Soulstone up in: %s"

XPERL_RAID_TOOLTIP_REMAINING	= " remaining"

XPERL_RAID_DROPDOWN_SHOWPET	= "Show Pets"
XPERL_RAID_DROPDOWN_SHOWOWNER	= "Show Owners"

XPERL_RAID_DROPDOWN_MAINTANKS	= "Main Tanks"
XPERL_RAID_DROPDOWN_SETMT	= "Set MT #%d"
XPERL_RAID_DROPDOWN_REMOVEMT	= "Remove MT #%d"

XPERL_RAID_RESSING		= " ressing"
XPERL_RAID_AFK			= "AFK"
XPERL_RAID_DND			= "DND"
XPERL_RAID_AUTOPROMOTE		= "Auto-Promote"
XPERL_RAID_RESSER_AVAIL		= "Rezzers Available: "
