-- X-Perl UnitFrames
-- Author: Zek <Boodhoof-EU>
-- License: GNU GPL v3, 29 June 2007 (see LICENSE.txt)

-- Localizations

if (GetLocale() == "zhTW") then

XPERL_RAID_GROUP		= "隊伍 %d"
XPERL_RAID_TOOLTIP_NOCTRA	= "沒有發現 CTRA"
XPERL_RAID_TOOLTIP_OFFLINE	= "%s 已離線"
XPERL_RAID_TOOLTIP_AFK		= "%s 已暫離"
XPERL_RAID_TOOLTIP_DND		= "%s 已勿擾"
XPERL_RAID_TOOLTIP_DYING	= "%s 已死亡"
XPERL_RAID_TOOLTIP_REBIRTH	= "%s 已戰復"
XPERL_RAID_TOOLTIP_ANKH		= "%s 已死者復生"
XPERL_RAID_TOOLTIP_SOULSTONE	= "%s 已綁定靈魂石"

XPERL_RAID_TOOLTIP_REMAINING	= " 剩餘"

XPERL_RAID_DROPDOWN_SHOWPET	= "顯示寵物"
XPERL_RAID_DROPDOWN_SHOWOWNER	= "顯示擁有者"

XPERL_RAID_DROPDOWN_MAINTANKS	= "主坦"
XPERL_RAID_DROPDOWN_SETMT	= "設為主坦 #%d"
XPERL_RAID_DROPDOWN_REMOVEMT	= "移除主坦 #%d"

XPERL_RAID_RESSING		= " 復活中"
XPERL_RAID_AFK			= "暫離"
XPERL_RAID_DND			= "勿擾"
XPERL_RAID_AUTOPROMOTE		= "自動晉級"
XPERL_RAID_RESSER_AVAIL		= "可施展復活技能者仍有："

end
