-- X-Perl UnitFrames
-- Author: Zek <Boodhoof-EU>
-- License: GNU GPL v3, 29 June 2007 (see LICENSE.txt)

if (GetLocale() == "zhCN") then

	XPERL_RAID_GROUP		= "小队 %d"
	XPERL_RAID_TOOLTIP_NOCTRA	= "没有发现CTRA"
	XPERL_RAID_TOOLTIP_OFFLINE	= "离线计时： %s"
	XPERL_RAID_TOOLTIP_AFK		= "暂离计时： %s"
	XPERL_RAID_TOOLTIP_DND		= "勿扰计时： %s"
	XPERL_RAID_TOOLTIP_DYING	= "死亡倒计时： %s"
	XPERL_RAID_TOOLTIP_REBIRTH	= "重生倒计时： %s"
	XPERL_RAID_TOOLTIP_ANKH		= "十字章失效： %s"
	XPERL_RAID_TOOLTIP_SOULSTONE	= "灵魂石失效： %s"

	XPERL_RAID_TOOLTIP_REMAINING	= "后消失"

	XPERL_RAID_DROPDOWN_SHOWPET	= "显示宠物"
	XPERL_RAID_DROPDOWN_SHOWOWNER	= "显示主人"

	XPERL_RAID_DROPDOWN_MAINTANKS	= "主坦克"
	XPERL_RAID_DROPDOWN_SETMT	= "设置 MT #%d"
	XPERL_RAID_DROPDOWN_REMOVEMT	= "移除 MT #%d"

	XPERL_RAID_RESSING		= "正在复活"
	XPERL_RAID_AFK			= "暂离"
	XPERL_RAID_DND			= "勿扰"
	XPERL_RAID_AUTOPROMOTE		= "自动提升"
	XPERL_RAID_RESSER_AVAIL		= "可以复活者: "	
end
