local L = LibStub("AceLocale-3.0"):NewLocale("Magnet","enUS",true,true)
if not L then return end

L["Adds a new item to the attracted items list"] = true
L["Adds a new item to the repel list"] = true
L["Atract fishing loot"] = true
L["Attract by item quality"] = true
L["Attracting"] = true
L["Attracting disenchanted item"] = true
L["Attracting fishingloot"] = true
L["Attracting gathered item"] = true
L["Attracting item by quality"] = true
L["Attracting item in battlefield"] = true
L["Attracting milled item"] = true
L["Attracting mined item"] = true
L["Attracting money"] = true
L["Attracting pick pocketed item"] = true
L["Attracting prospected item"] = true
L["Attracting quest item for quest"] = true
L["Attracting quest item %s"] = true
L["Attracting salvaged item %s"] = true
L["Attracting %s because it is a ingredient for %s"] = true
L["Attracting skinned item"] = true
L["Attract item"] = true
L["Attract items by their quality"] = true
L["Attract list"] = true
L["Attract money"] = true
L["Attract quest items"] = true
L["Attracts items if you are on a quest that requires it."] = true
L["Auto clear list"] = true
L["Auto close loot window"] = true
L["Automatically attract fishing loot. Overrides any repel settings!"] = true
L["Automatically closes the loot window when there are no more worthy loots"] = true
L["Automatically removes an item from the attract/repel list if that item is attracted/repelled by quality."] = true
L["Auto removing from attract list"] = true
L["Auto removing from repel list"] = true
L["Clear item list"] = true
L["Constructing ingredients cache..."] = true
L["Creature %s can be mined, adding to the list"] = true
L["Creature %s can be salvaged, adding to the list"] = true
L["Creature %s can be skinned, adding to the list"] = true
L["Disabled"] = true
L["Disenchant"] = true
L["Done constructing ingredients cache!"] = true
L["Enable"] = true
L["Enable Magnet"] = true
L["Engineering"] = true
L["Farm mode: Destroying %s"] = true
L["Farm mode: Looting %s"] = true
L["General"] = true
L["Handling loot window"] = true
L["Herb Gathering"] = true
L["Inverting polarity on"] = true
L["Item is locked. Can't loot."] = true
L["Item is locked. Repelling..."] = true
L["Item %s is Bind on Pickup"] = true
L["Magnet disabled"] = true
L["Magnet enabled"] = true
L["Magnetize"] = true
L["Magnetized"] = true
L["Magnetized as a reagent for \\n    %s"] = true
L["Magnetized by quality (party)"] = true
L["Magnetized by quality (raid)"] = true
L["Magnetized by quality (solo)"] = true
L["Magnetizing"] = true
L["Magnet list cleared. It's empty now."] = true
L["Magnet options"] = true
L["Milling"] = true
L["Mining"] = true
L["No items in lootwindow. Closing loot window."] = true
L["Not skilled-up or %s is not divisible by 5"] = true
L["No worthy items remaining. Closing loot window."] = true
L["Open GUI"] = true
L["Opens the configuration panel"] = true
L["party"] = true
L["Party options"] = true
L["Pick Pocket"] = true
L["Prints detailed messages in the chat frame if, what, when and why it loots"] = true
L["Prospecting"] = true
L["raid"] = true
L["Raid options"] = true
L["reature %s can be gathered from, adding to the list"] = true
L["Remove item"] = true
L["Removes an item from the attract or repel list"] = true
L["Repel"] = true
L["Repel by item quality"] = true
L["Repel item"] = true
L["Repel items"] = true
L["Repel items by their quality"] = true
L["Repelled"] = true
L["Repelled by quality (party)"] = true
L["Repelled by quality (raid)"] = true
L["Repelled by quality (solo)"] = true
L["Repelling "] = true
L["Repelling item by quality"] = true
L["Repelling %s"] = true
L["Repel list"] = true
L["Show attract list"] = true
L["Show repel list"] = true
L["Shows the list of current items to attract"] = true
L["Shows the list of current items to repel"] = true
L["Show verbose messages in the chat frame"] = true
L["Skillmode: looting %s"] = true
L["Skinning"] = true
L["solo"] = true
L["Solo options"] = true
L["Will clear the list of current items to search and autoloot for. THIS IS NOT UNDOABLE."] = true
L["You have autoloot enabled and not used the autoloot modifer key. This will bypass Magnet."] = true
L["You have chosen to autoloot using the modifier key. This will bypass Magnet."] = true

