if not(GetLocale() == "koKR") then
    return;
end

local L = WeakAuras.L

-- Options translation
L["Actions and Animations: 1/7"] = "액션 & 애니메이션: 1/7"
L["Actions and Animations: 2/7"] = "액션 & 애니메이션: 2/7"
L["Actions and Animations: 3/7"] = "액션 & 애니메이션: 3/7"
L["Actions and Animations: 4/7"] = "액션 & 애니메이션: 4/7"
L["Actions and Animations: 5/7"] = "액션 & 애니메이션: 5/7"
L["Actions and Animations: 6/7"] = "액션 & 애니메이션: 6/7"
L["Actions and Animations: 7/7"] = "액션 & 애니메이션: 7/7"
L["Actions and Animations Text"] = [=[To test your animation, you'll have to hide your display and make it appear again. This can be done using the display's View button on the sidebar.

Click it a few times to see your Start animation.]=]
L["Activation Settings: 1/5"] = "활성화 설정: 1/5"
L["Activation Settings: 2/5"] = "활성화 설정: 2/5"
L["Activation Settings: 3/5"] = "활성화 설정: 3/5"
L["Activation Settings: 4/5"] = "활성화 설정: 4/5"
L["Activation Settings: 5/5"] = "활성화 설정: 5/5"
L["Activation Settings Text"] = "활성화 설정 텍스트"
-- L["Auto-cloning: 1/10"] = ""
-- L["Auto-cloning 1/10 Text"] = ""
-- L["Beginners Finished Text"] = ""
L["Beginners Guide Desc"] = "초보자 가이드"
L["Beginners Guide Desc Text"] = "WeakAuras 기본적인 옵션 설정에 대하여 안내합니다"
L["Create a Display: 1/5"] = "디스플레이 생성: 1/5"
L["Create a Display: 2/5"] = "디스플레이 생성: 2/5"
L["Create a Display: 3/5"] = "디스플레이 생성: 3/5"
L["Create a Display: 4/5"] = "디스플레이 생성: 4/5"
L["Create a Display: 5/5"] = "디스플레이 생성: 5/5"
-- L["Create a Display Text"] = ""
L["Display Options: 1/4"] = "디스플레이 옵션: 1/4"
-- L["Display Options 1/4 Text"] = ""
L["Display Options: 2/4"] = "디스플레이 옵션: 2/4"
-- L["Display Options 2/4 Text"] = ""
L["Display Options: 4/4"] = "디스플레이 옵션: 4/4"
-- L["Display Options 4/4 Text"] = ""
L["Dynamic Group Options: 2/4"] = "유동적 그룹 옵션: 2/4"
-- L["Dynamic Group Options 2/4 Text"] = ""
L["Dynamic Group Options: 3/4"] = "유동적 그룹 옵션: 3/4"
-- L["Dynamic Group Options 3/4 Text"] = ""
L["Dynamic Group Options: 4/4"] = "유동적 그룹 옵션: 4/4"
-- L["Dynamic Group Options 4/4 Text"] = ""
L["Finished"] = "마침"
L["Full-scan Auras: 2/10"] = "오라 전체 스캔: 2/10"
L["Full-scan Auras 2/10 Text"] = "첫번째, 모두 스캔 옵션을 활성화"
L["Full-scan Auras: 3/10"] = "오라 전체 스캔: 3/10"
-- L["Full-scan Auras 3/10 Text"] = ""
L["Full-scan Auras: 4/10"] = "오라 전체 스캔: 4/10"
-- L["Full-scan Auras 4/10 Text"] = ""
L["Full-scan Auras: 5/10"] = "오라 전체 스캔: 5/10"
-- L["Full-scan Auras 5/10 Text"] = ""
L["Group Auras 6/10"] = "그룹 오라: 6/10"
-- L["Group Auras 6/10 Text"] = ""
L["Group Auras: 7/10"] = "그룹 오라: 7/10"
-- L["Group Auras 7/10 Text"] = ""
L["Group Auras: 8/10"] = "그룹 오라: 8/10"
-- L["Group Auras 8/10 Text"] = ""
L["Home"] = "처음으로"
L["Multi-target Auras: 10/10"] = "다중 대상 오라: 10/10"
-- L["Multi-target Auras 10/10 Text"] = ""
L["Multi-target Auras: 9/10"] = "다중 대상 오라: 9/10"
-- L["Multi-target Auras 9/10 Text"] = ""
L["New in 1.4:"] = "1.4의 새 기능:"
L["New in 1.4 Desc:"] = "1.4의 새 기능"
L["New in 1.4 Desc Text"] = "WeakAuras 1.4의 새로운 기능을 봅니다"
-- L["New in 1.4 Finnished Text"] = ""
-- L["New in 1.4 Text1"] = ""
-- L["New in 1.4 Text2"] = ""
L["Previous"] = "이전"
L["Trigger Options: 1/4"] = "조건 옵션: 1/4"
-- L["Trigger Options 1/4 Text"] = ""
L["Trigger Options: 2/4"] = "조건 옵션: 2/4"
-- L["Trigger Options 2/4 Text"] = ""
L["Trigger Options: 3/4"] = "조건 옵션: 3/4"
-- L["Trigger Options 3/4 Text"] = ""
L["Trigger Options: 4/4"] = "조건 옵션: 4/4"
-- L["Trigger Options 4/4 Text"] = ""
L["WeakAuras Tutorials"] = "WeakAuras 설명서"
L["Welcome"] = "환영합니다"
L["Welcome Text"] = [=[|cFF8800FFWeakAuras|r 초보자 가이드에 오신 것을 환영합니다.

이 가이드는 WeakAuras를 어떻게 사용하는지 보여주며. 
옵션을 설정하는 기본적인 방법에 대해 알려줍니다.]=]



