if not(GetLocale() == "esMX") then
    return;
end

local L = WeakAuras.L

-- Options translation
-- L["Actions and Animations: 1/7"] = ""
-- L["Actions and Animations: 2/7"] = ""
-- L["Actions and Animations: 3/7"] = ""
-- L["Actions and Animations: 4/7"] = ""
-- L["Actions and Animations: 5/7"] = ""
-- L["Actions and Animations: 6/7"] = ""
-- L["Actions and Animations: 7/7"] = ""
-- L["Actions and Animations Text"] = ""
L["Activation Settings: 1/5"] = "Activation Settings: 1/5"
-- L["Activation Settings: 2/5"] = ""
-- L["Activation Settings: 3/5"] = ""
-- L["Activation Settings: 4/5"] = ""
-- L["Activation Settings: 5/5"] = ""
-- L["Activation Settings Text"] = ""
-- L["Auto-cloning: 1/10"] = ""
-- L["Auto-cloning 1/10 Text"] = ""
-- L["Beginners Finished Text"] = ""
-- L["Beginners Guide Desc"] = ""
-- L["Beginners Guide Desc Text"] = ""
L["Create a Display: 1/5"] = "Create a Display: 1/5"
L["Create a Display: 2/5"] = "Create a Display: 2/5"
L["Create a Display: 3/5"] = "Create a Display: 3/5"
L["Create a Display: 4/5"] = "Create a Display: 4/5"
L["Create a Display: 5/5"] = "Create a Display: 5/5"
L["Create a Display Text"] = [=[Although the Display tab has sliders to control Width, Height, and X and Y positioning, there is an easier way to move and size your display.

You can simply click and drag your display to anywhere on your screen, and click and drag the corners to change the size.

You can also press Shift to hide the mover/sizer frame, for more accurate placement.]=]
L["Display Options: 1/4"] = "Display Options: 1/4"
-- L["Display Options 1/4 Text"] = ""
L["Display Options: 2/4"] = "Display Options: 2/4"
-- L["Display Options 2/4 Text"] = ""
L["Display Options: 4/4"] = "Display Options: 4/4"
-- L["Display Options 4/4 Text"] = ""
-- L["Dynamic Group Options: 2/4"] = ""
-- L["Dynamic Group Options 2/4 Text"] = ""
-- L["Dynamic Group Options: 3/4"] = ""
-- L["Dynamic Group Options 3/4 Text"] = ""
-- L["Dynamic Group Options: 4/4"] = ""
-- L["Dynamic Group Options 4/4 Text"] = ""
-- L["Finished"] = ""
-- L["Full-scan Auras: 2/10"] = ""
-- L["Full-scan Auras 2/10 Text"] = ""
-- L["Full-scan Auras: 3/10"] = ""
-- L["Full-scan Auras 3/10 Text"] = ""
-- L["Full-scan Auras: 4/10"] = ""
-- L["Full-scan Auras 4/10 Text"] = ""
-- L["Full-scan Auras: 5/10"] = ""
-- L["Full-scan Auras 5/10 Text"] = ""
-- L["Group Auras 6/10"] = ""
-- L["Group Auras 6/10 Text"] = ""
-- L["Group Auras: 7/10"] = ""
-- L["Group Auras 7/10 Text"] = ""
-- L["Group Auras: 8/10"] = ""
-- L["Group Auras 8/10 Text"] = ""
-- L["Home"] = ""
-- L["Multi-target Auras: 10/10"] = ""
-- L["Multi-target Auras 10/10 Text"] = ""
L["Multi-target Auras: 9/10"] = "Multi-target Auras: 9/10"
L["Multi-target Auras 9/10 Text"] = "Finally, select \"Multi-target\" for the Unit option."
-- L["New in 1.4:"] = ""
-- L["New in 1.4 Desc:"] = ""
-- L["New in 1.4 Desc Text"] = ""
-- L["New in 1.4 Finnished Text"] = ""
-- L["New in 1.4 Text1"] = ""
-- L["New in 1.4 Text2"] = ""
-- L["Previous"] = ""
-- L["Trigger Options: 1/4"] = ""
-- L["Trigger Options 1/4 Text"] = ""
-- L["Trigger Options: 2/4"] = ""
-- L["Trigger Options 2/4 Text"] = ""
-- L["Trigger Options: 3/4"] = ""
-- L["Trigger Options 3/4 Text"] = ""
-- L["Trigger Options: 4/4"] = ""
-- L["Trigger Options 4/4 Text"] = ""
L["WeakAuras Tutorials"] = "WeakAuras Tutorials"
-- L["Welcome"] = ""
-- L["Welcome Text"] = ""



