local L = LibStub("AceLocale-3.0"):NewLocale("SkullMe", "enUS", true)

L["AutoMark"] = true
L["Star"] = true
L["Circle"] = true
L["Diamond"] = true
L["Triangle"] = true
L["Moon"] = true
L["Square"] = true
L["Cross"] = true
L["Skull"] = true
L["Unknown Mark"] = true
L["SkullMe"] = true
L["SkullMe was designed for tanks or dps to automaticly mark mobs"] = true
L["You can also option these options with /sm"] = true
L["Sets all options to the defaults."] = true
L["Default Options"] = true
L["Core"] = true
L["Enabled"] = true
L["SkullMe is on when checked."] = true
L["Enable"] = true
L["Instance Only"] = true
L["Disable"] = true
L["Sensitivity"] = true
L["Time in seconds till the target becomes marked, after changing marks"] = true
L["Mark"] = true
L["The mark to automaticly mark with"] = true
L["Deadly Boss Mods Timer"] = true
L["Shows time till change in target."] = true
L["Advanced"] = true
L["Extra Slash Handler"] = true
L["WARNING: This section is for beta or advanced functions. Wrong inputs may result in unexpected results."] = true
L["This will change your slash command handlers to the desired handle. Usefull if another addon interfers, or if SkullMe interfers with another. Requires a reload of UI to take effect."] = true
L["FPS"] = true
L["The number of times SkullMe updates each second in a percent"] = true