if (GetLocale() == "zhCN") then

XPERL_MSG_PREFIX	= "|c00C05050X-Perl|r "
XPERL_COMMS_PREFIX	= "X-Perl"

XPERL_TOOLTIP_ASSISTING	= "正在协助的玩家："
XPERL_TOOLTIP_HEALERS	= "以我为目标的治疗者："
XPERL_TOOLTIP_ALLONME	= "以我为目标的所有人："
XPERL_TOOLTIP_ENEMYONME	= "以我为目标的敌对者："
XPERL_TOOLTIP_HELP	= "点击打开实时观察"
XPERL_TOOLTIP_PET	= "%s的宠物"

XPERL_LOC_DEAD		= "死亡"

XPERL_BUTTON_TOGGLE_LABELS	= "显示坦克标签"
XPERL_BUTTON_TOGGLE_MTTARGETS	= "显示MT目标的目标"
XPERL_BUTTON_TOGGLE_SHOWMT	= "显示主坦克"
XPERL_BUTTON_HELPER_PIN		= "固定窗口"

XPERL_XS_TARGET			= "%s的目标"
XPERL_NO_TARGET			= "没有目标"

XPERL_TITLE_MT_LONG		= "MT 目标"
XPERL_TITLE_MT_SHORT		= "MT"
XPERL_TITLE_WARRIOR_LONG	= "战士目标"
XPERL_TITLE_WARRIOR_SHORT	= "坦克"

XPERL_HELPER_NEEDPROMOTE	= "你必须获得提升后才能设定主要协助对象"
XPERL_HELPER_MASET		= "主要协助对象设为 %s"
XPERL_HELPER_MACLEAR		= "主要协助对象 |c00FF0000已清除!"
XPERL_HELPER_MAREMOVED		= "坦克列表中没有找到主要协助 %s - 移除!"
XPERL_HELPER_MAREMOTESET	= "%s 分配主要协助对象是 %s"

XPERL_HELPER_FINDFOUND		= "使用 FIND 来搜寻适合的目标. ('|c00007F00/xp find|r' 可清除)."
XPERL_HELPER_FINDCLEARED	= "Find |c00FF0000已清除!|r"
XPERL_HELPER_FINDSET		= "Find 设置为 %s. ('|c00007F00/xp find|r' 可清除)."

XPERL_AGGRO_PLAYER		= "- 获得仇恨 -"
XPERL_AGGRO_PET			= "- 宠物获得仇恨 -"
XPERL_AGGRO_DRAGTIP		= "移动仇恨警告位置"

end
