--[[
mwayne@cox.net for translations, thanks! 

cwow-BG1-安威玛尔-萌萌兽: zhCN/zhTW
Juido: deDE
Nya: frFR
usy820127: koKR
]]
   

DFILTER_BACKDROP_TOOLTIP = "Shift+left click to move.\nCtrl+right click to change time orientation."

DFILTER_OPTIONS_TARGET = "Target:"
DFILTER_OPTIONS_GROW = "Grow:"
DFILTER_OPTIONS_ROW = "Buffs per row"
DFILTER_OPTIONS_SELFAPPLIED = "Self-applied only"
DFILTER_OPTIONS_DONTCOMBINE = "Don't Combine Stacks"
DFILTER_OPTIONS_NAME = "Buff/Debuff name:"
DFILTER_OPTIONS_TEXTURE = "Texture (optional):"
DFILTER_OPTIONS_ADD = "Add"
DFILTER_OPTIONS_DEL = "Del"
DFILTER_OPTIONS_DEBUFFS = "Debuffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "Settings"
DFILTER_OPTIONS_DEBUFF_FILTERING = "Debuff Filtering"
DFILTER_OPTIONS_BUFF_FILTERING = "Buff Filtering"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "Player Debuff Filtering"
DFILTER_OPTIONS_PBUFF_FILTERING = "Player Buff Filtering"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "Focus Debuff Filtering"
DFILTER_OPTIONS_FBUFF_FILTERING = "Focus Buff Filtering"
DFILTER_OPTIONS_COUNT = "Show Debuff/Buff Count"
DFILTER_OPTIONS_COOLDOWNCOUNT = "CooldownCount Timers"
DFILTER_OPTIONS_COMBAT = "Only Show During Combat"
DFILTER_OPTIONS_TOOLTIPS = "Show Tooltips"
DFILTER_OPTIONS_BACKDROP = "Show Backdrop"
DFILTER_OPTIONS_LOCK = "Lock Frames"
DFILTER_OPTIONS_SCALE = "Scale"

DFILTER_OPTIONS_TARGET_TOOLTIP = "The target you want to configure."
DFILTER_OPTIONS_GROW_TOOLTIP = "The direction buffs or debuffs will grow."
DFILTER_OPTIONS_ROW_TOOLTIP = "The number of buffs or debuffs to display per row."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "Only show buffs and debuffs that you have applied yourself."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Don't combine multiple stacks of a buff or debuff into one icon."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on your target."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on your target."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on yourself."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on yourself."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "Enables or disables debuff filtering on your focus target."
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "Enables or disables buff filtering on your focus target."
DFILTER_OPTIONS_COUNT_TOOLTIP = "Shows a counter next to each frame, displaying the total number of buffs or debuffs."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "Displays CooldownCount-style timers via OmniCC."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "Hides each filter frame until you enter combat."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "Show tooltips when mousing over buffs and debuffs."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "Shows a backdrop under each filter frame to assist in moving them."
DFILTER_OPTIONS_LOCK_TOOLTIP = "Locks the frames, allowing mouse click-thru.\n\nNote: buff/debuff tooltips will not show when the frames are locked."
DFILTER_OPTIONS_SCALE_TOOLTIP = "Scales the frames up or down in size.";

if (GetLocale() == "zhCN") then
DFILTER_BACKDROP_TOOLTIP = "Shift+左键移动.\nCtrl+右键改变时间大小."

DFILTER_OPTIONS_TARGET = "目标:"
DFILTER_OPTIONS_GROW = "图标位置"
DFILTER_OPTIONS_ROW = "每行BUFF数"
DFILTER_OPTIONS_SELFAPPLIED = "只显示自身造成的debuff"
DFILTER_OPTIONS_DONTCOMBINE = "Don't Combine Stacks"
DFILTER_OPTIONS_NAME = "Buff/Debuff名称:"
DFILTER_OPTIONS_TEXTURE = "材质(任选):"
DFILTER_OPTIONS_ADD = "增加"
DFILTER_OPTIONS_DEL = "删除"
DFILTER_OPTIONS_DEBUFFS = "Debuffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "设置"
DFILTER_OPTIONS_DEBUFF_FILTERING = "目标 Debuff 过滤"
DFILTER_OPTIONS_BUFF_FILTERING = "目标 Buff 过滤"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "玩家 Debuff 过滤"
DFILTER_OPTIONS_PBUFF_FILTERING = "玩家 Buff 过滤"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "焦点 Debuff 过滤"
DFILTER_OPTIONS_FBUFF_FILTERING = "焦点 Buff 过滤"
DFILTER_OPTIONS_COUNT = "显示 Debuff/Buff 数量"
DFILTER_OPTIONS_COOLDOWNCOUNT = "冷却计时"
DFILTER_OPTIONS_COMBAT = "只在战斗中显示"
DFILTER_OPTIONS_TOOLTIPS = "显示说明"
DFILTER_OPTIONS_BACKDROP = "显示背景"
DFILTER_OPTIONS_LOCK = "锁定图标"
DFILTER_OPTIONS_SCALE = "缩放"

DFILTER_OPTIONS_TARGET_TOOLTIP = "你想设置的目标."
DFILTER_OPTIONS_GROW_TOOLTIP = "BUFF/DEBUFF排列方向."
DFILTER_OPTIONS_ROW_TOOLTIP = "每行显示的BUFF/DEBUFF数量."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "只显示你所定义的BUFF/DEBUFF."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Don't combine multiple stacks of a buff or debuff into one icon."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "是否对你的目标debuff使用过滤器."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "是否对你的目标buff使用过滤器."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "是否对你自己的debuff使用过滤器."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "是否对你自己的buff使用过滤器."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "是否对你的焦点debuff使用过滤器."
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "是否对你的焦点buff使用过滤器."
DFILTER_OPTIONS_COUNT_TOOLTIP = "是否在图标旁边显示BUFF/DEBUFF的数量."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "是否通过OmniCC显示冷却计时."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "隐藏你所过滤的BUFF/DEBUFF直到进入战斗."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "当鼠标移到图标时显示技能说明."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "当移动图标时显示背景色."
DFILTER_OPTIONS_LOCK_TOOLTIP = "锁定图标, 允许鼠标拖动.\n\nNote: buff/debuff 在锁定时不显示说明."
DFILTER_OPTIONS_SCALE_TOOLTIP = "调整图标大小.";

elseif (GetLocale() == "zhTW") then
DFILTER_BACKDROP_TOOLTIP = "Shift+左鍵移動.\nCtrl+右键改變時間大小."

DFILTER_OPTIONS_TARGET = "目標:"
DFILTER_OPTIONS_GROW = "圖標位置"
DFILTER_OPTIONS_ROW = "每行BUFF位置"
DFILTER_OPTIONS_SELFAPPLIED = "只顯示自身造成的debuff"
DFILTER_OPTIONS_DONTCOMBINE = "Don't Combine Stacks"
DFILTER_OPTIONS_NAME = "Buff/Debuff名稱:"
DFILTER_OPTIONS_TEXTURE = "材質(任選):"
DFILTER_OPTIONS_ADD = "增加"
DFILTER_OPTIONS_DEL = "刪除"
DFILTER_OPTIONS_DEBUFFS = "Debuffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "設置"
DFILTER_OPTIONS_DEBUFF_FILTERING = "目標 Debuff 過濾"
DFILTER_OPTIONS_BUFF_FILTERING = "目標 Buff 過濾"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "玩家 Debuff 過濾"
DFILTER_OPTIONS_PBUFF_FILTERING = "玩家 Buff 过滤"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "焦點 Debuff 過濾"
DFILTER_OPTIONS_FBUFF_FILTERING = "焦點 Buff 過濾"
DFILTER_OPTIONS_COUNT = "顯示 Debuff/Buff 數量"
DFILTER_OPTIONS_COOLDOWNCOUNT = "冷卻計時"
DFILTER_OPTIONS_COMBAT = "只在戰鬥中顯示"
DFILTER_OPTIONS_TOOLTIPS = "顯示說明"
DFILTER_OPTIONS_BACKDROP = "顯示背景"
DFILTER_OPTIONS_LOCK = "鎖定圖標"
DFILTER_OPTIONS_SCALE = "綻放"

DFILTER_OPTIONS_TARGET_TOOLTIP = "你想設置的目標."
DFILTER_OPTIONS_GROW_TOOLTIP = "BUFF/DEBUFF排列方向."
DFILTER_OPTIONS_ROW_TOOLTIP = "每行顯示的BUFF/DEBUFF數量."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "只顯示你所定義的BUFF/DEBUFF."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Don't combine multiple stacks of a buff or debuff into one icon."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "是否對你的目標debuff使用過濾器."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "是否對你的目標buff使用過濾器."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "是否對你自己的debuff使用過濾器."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "是否对對自己的buff使用過濾器."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "是否對你的焦點debuff使用過濾器."
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "是否對你的焦点buff使用過濾器."
DFILTER_OPTIONS_COUNT_TOOLTIP = "是否在圖標旁邊顯示BUFF/DEBUFF的數量."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "是否通過OmniCC顯示冷卻計時."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "隱藏你所過濾的BUFF/DEBUFF直到進入戰鬥."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "當鼠標移到圖標顯示技能說明."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "當移動圖標時顯示背景色."
DFILTER_OPTIONS_LOCK_TOOLTIP = "鎖定圖標，允許鼠標拖動.\n\nNote: buff/debuff 在鎖定時不顯示說明."
DFILTER_OPTIONS_SCALE_TOOLTIP = "調整圖標大小.";

elseif (GetLocale() == "deDE") then

DFILTER_BACKDROP_TOOLTIP = "Shift+linksklick zum bewegen.\nCtrl+rechtsklick um timerausrichtung zu \195\164ndern."

DFILTER_OPTIONS_TARGET = "Ziel:"
DFILTER_OPTIONS_GROW = "Ansteigen:"
DFILTER_OPTIONS_ROW = "Buffs pro Reihe"
DFILTER_OPTIONS_SELFAPPLIED = "Nur Eigenbuffs"
DFILTER_OPTIONS_DONTCOMBINE = "Keine Stacks zusammenz\195\164hlen"
DFILTER_OPTIONS_NAME = "Buff/Debuff Name:"
DFILTER_OPTIONS_TEXTURE = "Texture (optional):"
DFILTER_OPTIONS_ADD = "Zuf\195\188gen"
DFILTER_OPTIONS_DEL = "L\195\181schen"
DFILTER_OPTIONS_DEBUFFS = "Debuffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "Einstellungen"
DFILTER_OPTIONS_DEBUFF_FILTERING = "Debuff Filter"
DFILTER_OPTIONS_BUFF_FILTERING = "Buff Filter"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "Spieler Debuff Filte"
DFILTER_OPTIONS_PBUFF_FILTERING = "Spieler Buff Filter"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "Focus Debuff Filter"
DFILTER_OPTIONS_FBUFF_FILTERING = "Focus Buff Filter"
DFILTER_OPTIONS_COUNT = "Zeige Debuff/Buff Anzahl"
DFILTER_OPTIONS_COOLDOWNCOUNT = "Zeige Cooldown Timers"
DFILTER_OPTIONS_COMBAT = "Nur beim Kampf anzeigen"
DFILTER_OPTIONS_TOOLTIPS = "Zeige Tooltips"
DFILTER_OPTIONS_BACKDROP = "Zeige Platzhalter"
DFILTER_OPTIONS_LOCK = "Anzeigen Sperre"
DFILTER_OPTIONS_SCALE = "Skalierung"

DFILTER_OPTIONS_TARGET_TOOLTIP = "Die Ziel Einstellungen."
DFILTER_OPTIONS_GROW_TOOLTIP = "Die Richtung in der die Buffs oder Debuffs angereiht werden."
DFILTER_OPTIONS_ROW_TOOLTIP = "Die Anzahl der angezeigten Buffs oderr Debuffs pro Reihe."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "Zeige nur die von Dir selber verursachten Buffs und Debuffs."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Keine Mehrfachanzeige von Buff oder Debuff Stacks auf einem Icon."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Debuff Filters auf Deinem Ziel."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Buff Filters auf Deinem Ziel."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Debuff Filters auf Dir selbst."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Buff Filters auf Dir selbst."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Debuff Filters auf dem Focus-Ziel"
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "Aktivieren oder Deaktivieren des Buff Filters auf dem Focus-Ziel"
DFILTER_OPTIONS_COUNT_TOOLTIP = "Zeigt einen Z\195\164hler der Gesamtzahl der Buffs und Debuffs zu jeder Einstellung."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "Zeigt graphischen Cooldown Z\195\164hler mit OmniCC."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "Versteckt jeden Filter Frame ausserhalb des Kampfes."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "Zeigt Tooltips beim Mouseover."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "Zeigt einen Platzhalter zu jedem Filter Frame um das verschieben zu erleichtern."
DFILTER_OPTIONS_LOCK_TOOLTIP = "Sperrt die Frames und erlaubt das hindurch Klicken.\n\nBeachte: Buff/Debuff Tooltips werden bei gesperrten Frames nicht angezeigt."
DFILTER_OPTIONS_SCALE_TOOLTIP = "Ver\195\164ndert die Gr\195\181sse der Frames.";

elseif (GetLocale() == "frFR") then
DFILTER_BACKDROP_TOOLTIP = "Maj+clic gauche pour d\195\169placer.\nCtrl+clic droit pour changer l'orientation du chrono."

DFILTER_OPTIONS_TARGET = "Cible:"
DFILTER_OPTIONS_GROW = "Orientation:"
DFILTER_OPTIONS_ROW = "Buffs par ligne"
DFILTER_OPTIONS_SELFAPPLIED = "Pos\195\169 soi-m\195\170me uniquement"
DFILTER_OPTIONS_DONTCOMBINE = "Ne pas combiner les piles"
DFILTER_OPTIONS_NAME = "Nom du Buff/D\195\169buff:"
DFILTER_OPTIONS_TEXTURE = "Texture (optionnel):"
DFILTER_OPTIONS_ADD = "Ajouter"
DFILTER_OPTIONS_DEL = "Effacer"
DFILTER_OPTIONS_DEBUFFS = "D\195\169buffs"
DFILTER_OPTIONS_BUFFS = "Buffs"
DFILTER_OPTIONS_SETTINGS = "Options"
DFILTER_OPTIONS_DEBUFF_FILTERING = "D\195\169buffs de la cible"
DFILTER_OPTIONS_BUFF_FILTERING = "Buffs de la cible"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "D\195\169buffs du joueur"
DFILTER_OPTIONS_PBUFF_FILTERING = "Buffs du joueur"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "D\195\169buffs de la focalisation"
DFILTER_OPTIONS_FBUFF_FILTERING = "Buffs de la focalisation"
DFILTER_OPTIONS_COUNT = "Afficher le total de Buffs"
DFILTER_OPTIONS_COOLDOWNCOUNT = "Affichage type \"cooldown\""
DFILTER_OPTIONS_COMBAT = "Afficher en combat"
DFILTER_OPTIONS_TOOLTIPS = "Afficher les infobulles"
DFILTER_OPTIONS_BACKDROP = "Afficher les ancres"
DFILTER_OPTIONS_LOCK = "Verrouiller les cadres"
DFILTER_OPTIONS_SCALE = "Echelle"

DFILTER_OPTIONS_TARGET_TOOLTIP = "Cible \195\160 configurer."
DFILTER_OPTIONS_GROW_TOOLTIP = "Direction de l'affichage des Buffs/D\195\169buffs."
DFILTER_OPTIONS_ROW_TOOLTIP = "Nombre de Buffs/D\195\169buffs affich\195\169s par ligne."
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "Afficher uniquement les Buffs/D\195\169buffs appliqu\195\169s soi-m\195\170me."
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "Ne pas combiner les piles d'un Buff/D\195\169buffs en une seule ic\195\180ne."
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des D\195\169buffs sur la cible."
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des Buffs sur la cible."
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des D\195\169buffs sur le joueur."
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des Buffs sur le joueur."
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des D\195\169buffs sur la focalisation."
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "Active ou d\195\169sactive le filtrage des Buffs sur la focalisation."
DFILTER_OPTIONS_COUNT_TOOLTIP = "Affiche un compteur \195\160 cot\195\169 de chaque cadre, indiquant le nombre total de Buffs/D\195\169buffs."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "Affiche le temps restant comme des \"Cooldowns\" via OmniCC."
DFILTER_OPTIONS_COMBAT_TOOLTIP = "Masque chaque cadre de filtrage en dehors du combat."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "Afficher les infobulles en passant le curseur sur les Buffs/D\195\169buffs."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "Afficher une ancre sous chaque cadre de filtrage afin de faciliter leur d\195\169placements."
DFILTER_OPTIONS_LOCK_TOOLTIP = "Verrouille les cadres de filtrage, permettant de cliquer \195\160 travers.\n\nNote: Les infobulles des Buffs/D\195\169buffs ne s'afficheront pas si les cadres sont verrouill\195\169s."
DFILTER_OPTIONS_SCALE_TOOLTIP = "Redimensionne les cadres de filtrage.";

elseif (GetLocale() == "koKR") then
DFILTER_BACKDROP_TOOLTIP = "Shift+left: 이동\nCtrl+right: 시간표시 위/아래 위치변경"

DFILTER_OPTIONS_TARGET = "대상:"
DFILTER_OPTIONS_GROW = "나열 방향:"
DFILTER_OPTIONS_ROW = "행당 버프갯수"
DFILTER_OPTIONS_SELFAPPLIED = "본인 시전한 주문만"
DFILTER_OPTIONS_DONTCOMBINE = "중첩 횟수 표시안함"
DFILTER_OPTIONS_NAME = "버프/디버프 이름:"
DFILTER_OPTIONS_TEXTURE = "텍스처 (선택적):"
DFILTER_OPTIONS_ADD = "추가"
DFILTER_OPTIONS_DEL = "삭제"
DFILTER_OPTIONS_DEBUFFS = "디버프"
DFILTER_OPTIONS_BUFFS = "버프"
DFILTER_OPTIONS_SETTINGS = "설정"
DFILTER_OPTIONS_DEBUFF_FILTERING = "디버프 필터링"
DFILTER_OPTIONS_BUFF_FILTERING = "버프 필터링"
DFILTER_OPTIONS_PDEBUFF_FILTERING = "본인 디버프 필터링"
DFILTER_OPTIONS_PBUFF_FILTERING = "본인 버프 필터링"
DFILTER_OPTIONS_FDEBUFF_FILTERING = "주시대상 디버프 필터링"
DFILTER_OPTIONS_FBUFF_FILTERING = "주시대상 버프 필터링"
DFILTER_OPTIONS_COUNT = "버프/디버프 총 갯수 표시"
DFILTER_OPTIONS_COOLDOWNCOUNT = "지속시간 표시방법 변경"
DFILTER_OPTIONS_COMBAT = "전투중에만 표시"
DFILTER_OPTIONS_TOOLTIPS = "툴팁 표시"
DFILTER_OPTIONS_BACKDROP = "뒷배경 표시"
DFILTER_OPTIONS_LOCK = "잠금"
DFILTER_OPTIONS_SCALE = "크기"

DFILTER_OPTIONS_TARGET_TOOLTIP = "설정할 대상"
DFILTER_OPTIONS_GROW_TOOLTIP = "버프/디버프가 나열될 방향"
DFILTER_OPTIONS_ROW_TOOLTIP = "가로 1줄당 표시할 버프갯수"
DFILTER_OPTIONS_SELFAPPLIED_TOOLTIP = "자신이 시전한 버프/디버프만 표시"
DFILTER_OPTIONS_DONTCOMBINE_TOOLTIP = "버프/디버프 아이콘에 중첩횟수 표시여부"
DFILTER_OPTIONS_DEBUFF_FILTERING_TOOLTIP = "대상의 디버프 표시/숨김 전환"
DFILTER_OPTIONS_BUFF_FILTERING_TOOLTIP = "대상의 버프 표시/숨김 전환"
DFILTER_OPTIONS_PDEBUFF_FILTERING_TOOLTIP = "본인의 디버프 표시/숨김 전환"
DFILTER_OPTIONS_PBUFF_FILTERING_TOOLTIP = "본인의 버프 표시/숨김 전환"
DFILTER_OPTIONS_FDEBUFF_FILTERING_TOOLTIP = "주시대상의 디버프 표시/숨김 전환"
DFILTER_OPTIONS_FBUFF_FILTERING_TOOLTIP = "주시대상의 버프 표시/숨김 전환"
DFILTER_OPTIONS_COUNT_TOOLTIP = "전체 버프 또는 전체 디버프의 총 갯수를 프레임 옆쪽에 별도로 표시합니다."
DFILTER_OPTIONS_COOLDOWNCOUNT_TOOLTIP = "OmniCC 형식의 지속시간 표시방식으로의 전환"
DFILTER_OPTIONS_COMBAT_TOOLTIP = "전투시작 전까지 모든 창을 숨깁니다."
DFILTER_OPTIONS_TOOLTIPS_TOOLTIP = "버프/디버프 아이콘에 마우스오버시 툴팁을 표시합니다."
DFILTER_OPTIONS_BACKDROP_TOOLTIP = "프레임 이동에 도움이 되는 아이콘의 뒷배경을 표시합니다."
DFILTER_OPTIONS_LOCK_TOOLTIP = "마우스에 반응하지 않도록 잠급니다.\n\nNote: 잠갔을 때 버프/디버프 툴팁은 표시되지 않습니다."
DFILTER_OPTIONS_SCALE_TOOLTIP = "아이콘 크기를 조절합니다."

end
