-- Generated Data, do not modify
local tabdata = {
	DEATHKNIGHT = {
		{ background = "DeathKnightBlood", },
		{ background = "DeathKnightFrost", },
		{ background = "DeathKnightUnholy", },
	},
	WARRIOR = {
		{ background = "WarriorArms", },
		{ background = "WarriorFury", },
		{ background = "WarriorProtection", },
	},
	ROGUE = {
		{ background = "RogueAssassination", },
		{ background = "RogueCombat", },
		{ background = "RogueSubtlety", },
	},
	MAGE = {
		{ background = "MageArcane", },
		{ background = "MageFire", },
		{ background = "MageFrost", },
	},
	PRIEST = {
		{ background = "PriestDiscipline", },
		{ background = "PriestHoly", },
		{ background = "PriestShadow", },
	},
	WARLOCK = {
		{ background = "WarlockCurses", },
		{ background = "WarlockSummoning", },
		{ background = "WarlockDestruction", },
	},
	HUNTER = {
		{ background = "HunterBeastMastery", },
		{ background = "HunterMarksmanship", },
		{ background = "HunterSurvival", },
	},
	DRUID = {
		{ background = "DruidBalance", },
		{ background = "DruidFeralCombat", },
		{ background = "DruidRestoration", },
	},
	SHAMAN = {
		{ background = "ShamanElementalCombat", },
		{ background = "ShamanEnhancement", },
		{ background = "ShamanRestoration", },
	},
	PALADIN = {
		{ background = "PaladinHoly", },
		{ background = "PaladinProtection", },
		{ background = "PaladinCombat", },
	},
	Cunning = { { background = "HunterPetCunning", }, },
	Tenacity = { { background = "HunterPetTenacity", }, },
	Ferocity = { { background = "HunterPetFerocity", }, },
}
local locale = GetLocale()
if locale == "esES" then
	tabdata.DEATHKNIGHT[1].name = "Sangre"
	tabdata.DEATHKNIGHT[2].name = "Escarcha"
	tabdata.DEATHKNIGHT[3].name = "Profana"
	tabdata.WARRIOR[1].name = "Armas"
	tabdata.WARRIOR[2].name = "Furia"
	tabdata.WARRIOR[3].name = "Protección"
	tabdata.ROGUE[1].name = "Asesinato"
	tabdata.ROGUE[2].name = "Combate"
	tabdata.ROGUE[3].name = "Sutileza"
	tabdata.MAGE[1].name = "Arcano"
	tabdata.MAGE[2].name = "Fuego"
	tabdata.MAGE[3].name = "Escarcha"
	tabdata.PRIEST[1].name = "Disciplina"
	tabdata.PRIEST[2].name = "Sagrado"
	tabdata.PRIEST[3].name = "Sombras"
	tabdata.WARLOCK[1].name = "Aflicción"
	tabdata.WARLOCK[2].name = "Demonología"
	tabdata.WARLOCK[3].name = "Destrucción"
	tabdata.HUNTER[1].name = "Dominio de bestias"
	tabdata.HUNTER[2].name = "Puntería"
	tabdata.HUNTER[3].name = "Supervivencia"
	tabdata.DRUID[1].name = "Equilibrio"
	tabdata.DRUID[2].name = "Combate feral"
	tabdata.DRUID[3].name = "Restauración"
	tabdata.SHAMAN[1].name = "Elemental"
	tabdata.SHAMAN[2].name = "Mejora"
	tabdata.SHAMAN[3].name = "Restauración"
	tabdata.PALADIN[1].name = "Sagrado"
	tabdata.PALADIN[2].name = "Protección"
	tabdata.PALADIN[3].name = "Reprensión"
	tabdata.Cunning[1].name = "Astucia"
	tabdata.Tenacity[1].name = "Tenacidad"
	tabdata.Ferocity[1].name = "Ferocidad"
elseif locale == "zhCN" then
	tabdata.DEATHKNIGHT[1].name = "鲜血"
	tabdata.DEATHKNIGHT[2].name = "冰霜"
	tabdata.DEATHKNIGHT[3].name = "邪恶"
	tabdata.WARRIOR[1].name = "武器"
	tabdata.WARRIOR[2].name = "狂怒"
	tabdata.WARRIOR[3].name = "防护"
	tabdata.ROGUE[1].name = "刺杀"
	tabdata.ROGUE[2].name = "战斗"
	tabdata.ROGUE[3].name = "敏锐"
	tabdata.MAGE[1].name = "奥术"
	tabdata.MAGE[2].name = "火焰"
	tabdata.MAGE[3].name = "冰霜"
	tabdata.PRIEST[1].name = "戒律"
	tabdata.PRIEST[2].name = "神圣"
	tabdata.PRIEST[3].name = "暗影"
	tabdata.WARLOCK[1].name = "痛苦"
	tabdata.WARLOCK[2].name = "恶魔学识"
	tabdata.WARLOCK[3].name = "毁灭"
	tabdata.HUNTER[1].name = "野兽掌握"
	tabdata.HUNTER[2].name = "射击"
	tabdata.HUNTER[3].name = "生存"
	tabdata.DRUID[1].name = "平衡"
	tabdata.DRUID[2].name = "野性战斗"
	tabdata.DRUID[3].name = "恢复"
	tabdata.SHAMAN[1].name = "元素战斗"
	tabdata.SHAMAN[2].name = "增强"
	tabdata.SHAMAN[3].name = "恢复"
	tabdata.PALADIN[1].name = "神圣"
	tabdata.PALADIN[2].name = "防护"
	tabdata.PALADIN[3].name = "惩戒"
	tabdata.Cunning[1].name = "灵巧"
	tabdata.Tenacity[1].name = "坚毅"
	tabdata.Ferocity[1].name = "凶暴"
elseif locale == "frFR" then
	tabdata.DEATHKNIGHT[1].name = "Sang"
	tabdata.DEATHKNIGHT[2].name = "Givre"
	tabdata.DEATHKNIGHT[3].name = "Impie"
	tabdata.WARRIOR[1].name = "Armes"
	tabdata.WARRIOR[2].name = "Fureur"
	tabdata.WARRIOR[3].name = "Protection"
	tabdata.ROGUE[1].name = "Assassinat"
	tabdata.ROGUE[2].name = "Combat"
	tabdata.ROGUE[3].name = "Finesse"
	tabdata.MAGE[1].name = "Arcanes"
	tabdata.MAGE[2].name = "Feu"
	tabdata.MAGE[3].name = "Givre"
	tabdata.PRIEST[1].name = "Discipline"
	tabdata.PRIEST[2].name = "Sacré"
	tabdata.PRIEST[3].name = "Ombre"
	tabdata.WARLOCK[1].name = "Affliction"
	tabdata.WARLOCK[2].name = "Démonologie"
	tabdata.WARLOCK[3].name = "Destruction"
	tabdata.HUNTER[1].name = "Maîtrise des bêtes"
	tabdata.HUNTER[2].name = "Précision"
	tabdata.HUNTER[3].name = "Survie"
	tabdata.DRUID[1].name = "Équilibre"
	tabdata.DRUID[2].name = "Combat farouche"
	tabdata.DRUID[3].name = "Restauration"
	tabdata.SHAMAN[1].name = "Élémentaire"
	tabdata.SHAMAN[2].name = "Amélioration"
	tabdata.SHAMAN[3].name = "Restauration"
	tabdata.PALADIN[1].name = "Sacré"
	tabdata.PALADIN[2].name = "Protection"
	tabdata.PALADIN[3].name = "Vindicte"
	tabdata.Cunning[1].name = "Ruse"
	tabdata.Tenacity[1].name = "Tenacité"
	tabdata.Ferocity[1].name = "Férocité"
elseif locale == "zhTW" then
	tabdata.DEATHKNIGHT[1].name = "血魄"
	tabdata.DEATHKNIGHT[2].name = "冰霜"
	tabdata.DEATHKNIGHT[3].name = "穢邪"
	tabdata.WARRIOR[1].name = "武器"
	tabdata.WARRIOR[2].name = "狂怒"
	tabdata.WARRIOR[3].name = "防護"
	tabdata.ROGUE[1].name = "刺殺"
	tabdata.ROGUE[2].name = "戰鬥"
	tabdata.ROGUE[3].name = "敏銳"
	tabdata.MAGE[1].name = "秘法"
	tabdata.MAGE[2].name = "火焰"
	tabdata.MAGE[3].name = "冰霜"
	tabdata.PRIEST[1].name = "戒律"
	tabdata.PRIEST[2].name = "神聖"
	tabdata.PRIEST[3].name = "暗影"
	tabdata.WARLOCK[1].name = "痛苦"
	tabdata.WARLOCK[2].name = "惡魔"
	tabdata.WARLOCK[3].name = "毀滅"
	tabdata.HUNTER[1].name = "野獸控制"
	tabdata.HUNTER[2].name = "射擊"
	tabdata.HUNTER[3].name = "生存"
	tabdata.DRUID[1].name = "平衡"
	tabdata.DRUID[2].name = "野性戰鬥"
	tabdata.DRUID[3].name = "恢復"
	tabdata.SHAMAN[1].name = "元素"
	tabdata.SHAMAN[2].name = "增強"
	tabdata.SHAMAN[3].name = "恢復"
	tabdata.PALADIN[1].name = "神聖"
	tabdata.PALADIN[2].name = "防護"
	tabdata.PALADIN[3].name = "懲戒"
	tabdata.Cunning[1].name = "靈巧"
	tabdata.Tenacity[1].name = "堅毅"
	tabdata.Ferocity[1].name = "兇暴"
elseif locale == "deDE" then
	tabdata.DEATHKNIGHT[1].name = "Blut"
	tabdata.DEATHKNIGHT[2].name = "Frost"
	tabdata.DEATHKNIGHT[3].name = "Unheilig"
	tabdata.WARRIOR[1].name = "Waffen"
	tabdata.WARRIOR[2].name = "Furor"
	tabdata.WARRIOR[3].name = "Schutz"
	tabdata.ROGUE[1].name = "Meucheln"
	tabdata.ROGUE[2].name = "Kampf"
	tabdata.ROGUE[3].name = "Täuschung"
	tabdata.MAGE[1].name = "Arkan"
	tabdata.MAGE[2].name = "Feuer"
	tabdata.MAGE[3].name = "Frost"
	tabdata.PRIEST[1].name = "Disziplin"
	tabdata.PRIEST[2].name = "Heilig"
	tabdata.PRIEST[3].name = "Schatten"
	tabdata.WARLOCK[1].name = "Gebrechen"
	tabdata.WARLOCK[2].name = "Dämonologie"
	tabdata.WARLOCK[3].name = "Zerstörung"
	tabdata.HUNTER[1].name = "Tierherrschaft"
	tabdata.HUNTER[2].name = "Treffsicherheit"
	tabdata.HUNTER[3].name = "Überleben"
	tabdata.DRUID[1].name = "Gleichgewicht"
	tabdata.DRUID[2].name = "Wilder Kampf"
	tabdata.DRUID[3].name = "Wiederherstellung"
	tabdata.SHAMAN[1].name = "Elementar"
	tabdata.SHAMAN[2].name = "Verstärkung"
	tabdata.SHAMAN[3].name = "Wiederherstellung"
	tabdata.PALADIN[1].name = "Heilig"
	tabdata.PALADIN[2].name = "Schutz"
	tabdata.PALADIN[3].name = "Vergeltung"
	tabdata.Cunning[1].name = "Gerissenheit"
	tabdata.Tenacity[1].name = "Hartnäckigkeit"
	tabdata.Ferocity[1].name = "Wildheit"
elseif locale == "ruRU" then
	tabdata.DEATHKNIGHT[1].name = "Кровь"
	tabdata.DEATHKNIGHT[2].name = "Холод"
	tabdata.DEATHKNIGHT[3].name = "Нечестивость"
	tabdata.WARRIOR[1].name = "Оружие"
	tabdata.WARRIOR[2].name = "Неистовство"
	tabdata.WARRIOR[3].name = "Защита"
	tabdata.ROGUE[1].name = "Ликвидация"
	tabdata.ROGUE[2].name = "Бой"
	tabdata.ROGUE[3].name = "Скрытность"
	tabdata.MAGE[1].name = "Тайная магия"
	tabdata.MAGE[2].name = "Огонь"
	tabdata.MAGE[3].name = "Лед"
	tabdata.PRIEST[1].name = "Послушание"
	tabdata.PRIEST[2].name = "Свет"
	tabdata.PRIEST[3].name = "Темная магия"
	tabdata.WARLOCK[1].name = "Колдовство"
	tabdata.WARLOCK[2].name = "Демонология"
	tabdata.WARLOCK[3].name = "Разрушение"
	tabdata.HUNTER[1].name = "Чувство зверя"
	tabdata.HUNTER[2].name = "Стрельба"
	tabdata.HUNTER[3].name = "Выживание"
	tabdata.DRUID[1].name = "Баланс"
	tabdata.DRUID[2].name = "Сила зверя"
	tabdata.DRUID[3].name = "Исцеление"
	tabdata.SHAMAN[1].name = "Стихии"
	tabdata.SHAMAN[2].name = "Совершенствование"
	tabdata.SHAMAN[3].name = "Исцеление"
	tabdata.PALADIN[1].name = "Свет"
	tabdata.PALADIN[2].name = "Защита"
	tabdata.PALADIN[3].name = "Возмездие"
	tabdata.Cunning[1].name = "Хитрость"
	tabdata.Tenacity[1].name = "Упорство"
	tabdata.Ferocity[1].name = "Свирепость"
elseif locale == "koKR" then
	tabdata.DEATHKNIGHT[1].name = "혈기"
	tabdata.DEATHKNIGHT[2].name = "냉기"
	tabdata.DEATHKNIGHT[3].name = "부정"
	tabdata.WARRIOR[1].name = "무기"
	tabdata.WARRIOR[2].name = "분노"
	tabdata.WARRIOR[3].name = "방어"
	tabdata.ROGUE[1].name = "암살"
	tabdata.ROGUE[2].name = "전투"
	tabdata.ROGUE[3].name = "잠행"
	tabdata.MAGE[1].name = "비전"
	tabdata.MAGE[2].name = "화염"
	tabdata.MAGE[3].name = "냉기"
	tabdata.PRIEST[1].name = "수양"
	tabdata.PRIEST[2].name = "신성"
	tabdata.PRIEST[3].name = "암흑"
	tabdata.WARLOCK[1].name = "고통"
	tabdata.WARLOCK[2].name = "악마"
	tabdata.WARLOCK[3].name = "파괴"
	tabdata.HUNTER[1].name = "야수"
	tabdata.HUNTER[2].name = "사격"
	tabdata.HUNTER[3].name = "생존"
	tabdata.DRUID[1].name = "조화"
	tabdata.DRUID[2].name = "야성"
	tabdata.DRUID[3].name = "회복"
	tabdata.SHAMAN[1].name = "정기"
	tabdata.SHAMAN[2].name = "고양"
	tabdata.SHAMAN[3].name = "복원"
	tabdata.PALADIN[1].name = "신성"
	tabdata.PALADIN[2].name = "보호"
	tabdata.PALADIN[3].name = "징벌"
	tabdata.Cunning[1].name = "교활"
	tabdata.Tenacity[1].name = "끈기"
	tabdata.Ferocity[1].name = "야성"
else
	tabdata.DEATHKNIGHT[1].name = "Blood"
	tabdata.DEATHKNIGHT[2].name = "Frost"
	tabdata.DEATHKNIGHT[3].name = "Unholy"
	tabdata.WARRIOR[1].name = "Arms"
	tabdata.WARRIOR[2].name = "Fury"
	tabdata.WARRIOR[3].name = "Protection"
	tabdata.ROGUE[1].name = "Assassination"
	tabdata.ROGUE[2].name = "Combat"
	tabdata.ROGUE[3].name = "Subtlety"
	tabdata.MAGE[1].name = "Arcane"
	tabdata.MAGE[2].name = "Fire"
	tabdata.MAGE[3].name = "Frost"
	tabdata.PRIEST[1].name = "Discipline"
	tabdata.PRIEST[2].name = "Holy"
	tabdata.PRIEST[3].name = "Shadow"
	tabdata.WARLOCK[1].name = "Affliction"
	tabdata.WARLOCK[2].name = "Demonology"
	tabdata.WARLOCK[3].name = "Destruction"
	tabdata.HUNTER[1].name = "Beast Mastery"
	tabdata.HUNTER[2].name = "Marksmanship"
	tabdata.HUNTER[3].name = "Survival"
	tabdata.DRUID[1].name = "Balance"
	tabdata.DRUID[2].name = "Feral Combat"
	tabdata.DRUID[3].name = "Restoration"
	tabdata.SHAMAN[1].name = "Elemental"
	tabdata.SHAMAN[2].name = "Enhancement"
	tabdata.SHAMAN[3].name = "Restoration"
	tabdata.PALADIN[1].name = "Holy"
	tabdata.PALADIN[2].name = "Protection"
	tabdata.PALADIN[3].name = "Retribution"
	tabdata.Cunning[1].name = "Cunning"
	tabdata.Tenacity[1].name = "Tenacity"
	tabdata.Ferocity[1].name = "Ferocity"
end
Talented.tabdata = tabdata
